// _curriculum_docker.mjs
// Currículum del curso de Docker.
// Exporta COURSES con todos los módulos y lecciones.
// Las lecciones existentes en disco se listan SIN body (no se regeneran);
// las nuevas (módulos 06 y 07) llevan body completo (11 secciones estándar + metadatos).

export const COURSES = [
  {
    slug: "docker",
    title: "Docker",
    modules: [
      {
        id: "modulo-01",
        n: 1,
        t: "Fundamentos de Contenedores",
        level: "intermedio",
        caption: "Qué es un contenedor, cómo instalarlo y los primeros comandos.",
        desc: "Comprende qué es un contenedor, en qué se diferencia de una máquina virtual, instala Docker y maneja su ciclo de vida con los comandos esenciales.",
        subtitle: "Empaqueta tu software para que corrija donde sea, igual que en tu máquina.",
        objectives: [
          "Entender qué es un contenedor y por qué existe",
          "Diferenciar contenedores de máquinas virtuales",
          "Instalar Docker en tu sistema",
          "Ejecutar los primeros comandos y conocer el ciclo de vida",
          "Aplicar buenas prácticas de limpieza",
        ],
        lessons: [
          {
            id: "contenedor-vs-maquina-virtual",
            title: "Contenedor vs máquina virtual",
            duration: "9 min",
            level: "intermedio",
            category: "fundamentos",
            cardText: "Comparten el kernel del host: por eso los contenedores son ligeros y arrancan en segundos.",
            desc: "Compara contenedores y máquinas virtuales para elegir bien en cada caso.",
          },
          {
            id: "el-ciclo-de-vida",
            title: "El ciclo de vida",
            duration: "11 min",
            level: "intermedio",
            category: "fundamentos",
            cardText: "De docker create a docker stop: los estados por los que pasa un contenedor.",
            desc: "Sigue los estados de un contenedor a lo largo de todo su ciclo de vida.",
          },
          {
            id: "instalando-docker",
            title: "Instalando Docker",
            duration: "10 min",
            level: "intermedio",
            category: "fundamentos",
            cardText: "Instala Docker Engine en Linux, Windows y macOS sin sorpresas.",
            desc: "Instala Docker Engine y configura tu entorno de trabajo.",
          },
          {
            id: "limpieza-y-buenas-practicas",
            title: "Limpieza y buenas prácticas",
            duration: "9 min",
            level: "intermedio",
            category: "fundamentos",
            cardText: "Contenedores huérfanos e imágenes intermedias: cómo mantener tu Docker limpio.",
            desc: "Aprende a limpiar recursos huérfanos y mantener tu host ordenado.",
          },
          {
            id: "primeros-comandos",
            title: "Primeros comandos",
            duration: "10 min",
            level: "intermedio",
            category: "fundamentos",
            cardText: "docker run, docker ps, docker exec y docker logs: tu primer día en la terminal.",
            desc: "Conoce los comandos esenciales para trabajar con contenedores.",
          },
          {
            id: "que-es-un-contenedor",
            title: "¿Qué es un contenedor?",
            duration: "10 min",
            level: "intermedio",
            category: "fundamentos",
            cardText: "Un proceso aislado con su propio sistema de archivos mediante namespaces y cgroups.",
            desc: "Descubre qué es exactamente un contenedor y qué lo hace diferente.",
          },
        ],
      },
      {
        id: "modulo-02",
        n: 2,
        t: "Imágenes y Dockerfile",
        level: "intermedio",
        caption: "Construye imágenes reproducibles y ligeras.",
        desc: "Escribe Dockerfiles profesionales, entiende el sistema de capas, optimiza el tamaño con multi-stage builds y publica tus imágenes en un registry.",
        subtitle: "Una imagen bien construida es la mitad del despliegue ganado.",
        objectives: [
          "Escribir un Dockerfile correcto y ordenado",
          "Entender el sistema de capas de las imágenes",
          "Manejar el build context y el .dockerignore",
          "Optimizar imágenes con multi-stage builds",
          "Publicar imágenes en un registry",
        ],
        lessons: [
          {
            id: "capas-de-imagen",
            title: "Las capas de la imagen",
            duration: "10 min",
            level: "intermedio",
            category: "imágenes",
            cardText: "Cada instrucción del Dockerfile crea una capa que se puede cachear y reutilizar.",
            desc: "Entiende cómo se apilan las capas y por qué importa el orden en el cache.",
          },
          {
            id: "dockerignore",
            title: "El build context y .dockerignore",
            duration: "9 min",
            level: "intermedio",
            category: "imágenes",
            cardText: "Haz que el build sea rápido y seguro excluyendo ficheros que no necesitas.",
            desc: "Controla el contexto de construcción con el fichero .dockerignore.",
          },
          {
            id: "multi-stage-builds",
            title: "Multi-stage builds",
            duration: "11 min",
            level: "intermedio",
            category: "imágenes",
            cardText: "Compila en una etapa y copia solo lo necesario a la imagen final.",
            desc: "Reduce el tamaño de tus imágenes con builds de varias etapas.",
          },
          {
            id: "optimizando-imagenes",
            title: "Optimizando imágenes",
            duration: "10 min",
            level: "intermedio",
            category: "imágenes",
            cardText: "Imágenes pequeñas, seguras y rápidas de descargar: técnicas de optimización.",
            desc: "Aplica técnicas para reducir el tamaño y mejorar la seguridad de tus imágenes.",
          },
          {
            id: "publicando-en-el-registry",
            title: "Publicando en el registry",
            duration: "9 min",
            level: "intermedio",
            category: "imágenes",
            cardText: "Sube tus imágenes a Docker Hub o a un registry privado y versiona los tags.",
            desc: "Publica tus imágenes y gestiona sus versiones con tags.",
          },
          {
            id: "que-es-un-dockerfile",
            title: "¿Qué es un Dockerfile?",
            duration: "10 min",
            level: "intermedio",
            category: "imágenes",
            cardText: "El recetario que define cómo se construye tu imagen: instrucciones y sintaxis.",
            desc: "Aprende qué es un Dockerfile y su sintaxis esencial.",
          },
        ],
      },
      {
        id: "modulo-03",
        n: 3,
        t: "Volúmenes y Redes",
        level: "intermedio",
        caption: "Datos persistentes y comunicación entre contenedores.",
        desc: "Persiste tus datos con volúmenes y bind mounts, y diseña redes para que tus contenedores se comuniquen entre sí de forma segura.",
        subtitle: "Los contenedores son efímeros; tus datos no deberían serlo.",
        objectives: [
          "Persistir datos con volúmenes nombrados y bind mounts",
          "Montar bases de datos con almacenamiento fiable",
          "Diseñar redes de Docker y conectar contenedores",
          "Comunicar servicios entre sí correctamente",
        ],
        lessons: [
          {
            id: "bases-de-datos-con-volumenes",
            title: "Bases de datos con volúmenes",
            duration: "11 min",
            level: "intermedio",
            category: "volúmenes",
            cardText: "Postgres y MySQL sin perder datos: el volumen como almacén persistente.",
            desc: "Monta bases de datos en contenedores con volúmenes persistentes.",
          },
          {
            id: "bind-mounts",
            title: "Bind mounts",
            duration: "10 min",
            level: "intermedio",
            category: "volúmenes",
            cardText: "Comparte carpetas del host con el contenedor para desarrollo y configuración.",
            desc: "Usa bind mounts para compartir archivos entre host y contenedor.",
          },
          {
            id: "comunicacion-entre-contenedores",
            title: "Comunicación entre contenedores",
            duration: "10 min",
            level: "intermedio",
            category: "redes",
            cardText: "App y base de datos hablando entre sí mediante la red interna.",
            desc: "Conecta contenedores para que se comuniquen por nombre de servicio.",
          },
          {
            id: "persistencia-de-datos",
            title: "La persistencia de datos",
            duration: "9 min",
            level: "intermedio",
            category: "volúmenes",
            cardText: "Por qué perder un contenedor no debe significar perder sus datos.",
            desc: "Entiende el problema de la persistencia y sus soluciones en Docker.",
          },
          {
            id: "redes-de-docker",
            title: "Redes de Docker",
            duration: "10 min",
            level: "intermedio",
            category: "redes",
            cardText: "bridge, host y overlay: elige la red adecuada para cada situación.",
            desc: "Conoce los tipos de red de Docker y cuándo usar cada una.",
          },
          {
            id: "volumenes-nombrados",
            title: "Volúmenes nombrados",
            duration: "9 min",
            level: "intermedio",
            category: "volúmenes",
            cardText: "Almacenamiento gestionado por Docker que sobrevive a los contenedores.",
            desc: "Crea y gestiona volúmenes nombrados para persistir datos.",
          },
        ],
      },
      {
        id: "modulo-04",
        n: 4,
        t: "Docker Compose",
        level: "intermedio",
        caption: "Orquesta varios contenedores con un solo fichero YAML.",
        desc: "Define servicios, dependencias, variables de entorno, volúmenes y redes en un docker-compose.yml y levanta tu stack completo con un comando.",
        subtitle: "Un fichero YAML puede levantar toda tu cartera de servicios.",
        objectives: [
          "Definir un stack con docker-compose.yml",
          "Organizar servicios y dependencias de arranque",
          "Configurar variables de entorno por servicio",
          "Conectar volúmenes y redes desde Compose",
          "Mantener entornos de desarrollo y debug",
        ],
        lessons: [
          {
            id: "entornos-de-desarrollo",
            title: "Entornos de desarrollo",
            duration: "11 min",
            level: "intermedio",
            category: "compose",
            cardText: "Levanta la base de datos, la cola y la API de desarrollo con un comando.",
            desc: "Usa Compose para replicar tu entorno de desarrollo entero.",
          },
          {
            id: "perfiles-y-debug",
            title: "Perfiles y debug",
            duration: "10 min",
            level: "intermedio",
            category: "compose",
            cardText: "Activa servicios opcionales y depura mientras el stack sigue corriendo.",
            desc: "Gestiona perfiles de Compose y estrategias de depuración.",
          },
          {
            id: "que-es-docker-compose",
            title: "¿Qué es Docker Compose?",
            duration: "10 min",
            level: "intermedio",
            category: "compose",
            cardText: "La herramienta que define y ejecuta aplicaciones multi-contenedor.",
            desc: "Descubre Docker Compose y para qué sirve.",
          },
          {
            id: "servicios-y-dependencias",
            title: "Servicios y dependencias",
            duration: "10 min",
            level: "intermedio",
            category: "compose",
            cardText: "Declara cada servicio y controla el orden en el que arranca.",
            desc: "Define servicios en Compose y sus dependencias.",
          },
          {
            id: "variables-de-entorno",
            title: "Variables de entorno",
            duration: "10 min",
            level: "intermedio",
            category: "compose",
            cardText: "Configuración por servicio sin recompilar: el poder de los environment.",
            desc: "Inyecta variables de entorno a tus servicios de Compose.",
          },
          {
            id: "volumenes-y-redes-en-compose",
            title: "Volúmenes y redes en Compose",
            duration: "10 min",
            level: "intermedio",
            category: "compose",
            cardText: "Declara la persistencia y la topología de red desde el mismo fichero.",
            desc: "Gestiona volúmenes y redes directamente desde Compose.",
          },
        ],
      },
      {
        id: "modulo-05",
        n: 5,
        t: "Docker en el Backend",
        level: "intermedio",
        caption: "Dockeriza una API real con bases de datos y caché.",
        desc: "Aplica todo lo aprendido: dockeriza una API Node, añade Postgres y Redis con Compose, y configura health checks para un arranque ordenado.",
        subtitle: "Tu API completa corriendo en contenedores, lista para producción.",
        objectives: [
          "Dockerizar una API Node de principio a fin",
          "Levantar Postgres como base de datos del stack",
          "Añadir Redis como caché",
          "Configurar health checks y el orden de arranque",
        ],
        lessons: [
          {
            id: "api-node-con-postgres",
            title: "API Node con Postgres",
            duration: "11 min",
            level: "intermedio",
            category: "backend",
            cardText: "Un solo docker-compose.yml para tu API y su base de datos PostgreSQL.",
            desc: "Compón una API Node con Postgres usando Docker Compose.",
          },
          {
            id: "dockerizando-una-api-node",
            title: "Dockerizando una API Node",
            duration: "11 min",
            level: "intermedio",
            category: "backend",
            cardText: "Del código fuente a una imagen lista para producción en unos minutos.",
            desc: "Crea la imagen Docker de una API Node paso a paso.",
          },
          {
            id: "healthchecks-y-arranque",
            title: "Healthchecks y arranque",
            duration: "10 min",
            level: "intermedio",
            category: "backend",
            cardText: "Healthchecks y depends_on: que cada servicio arranque cuando toca.",
            desc: "Usa health checks para controlar el arranque y el estado de los servicios.",
          },
          {
            id: "redis-como-cache",
            title: "Redis como caché",
            duration: "10 min",
            level: "intermedio",
            category: "backend",
            cardText: "Añade Redis al stack para reducir la carga de tu base de datos.",
            desc: "Integra Redis como caché dentro del stack de la API.",
          },
        ],
      },
      {
        id: "modulo-06",
        n: 6,
        t: "Seguridad en contenedores",
        level: "avanzado",
        caption: "Contenedores duros de romper: de la imagen al runtime.",
        desc: "Aplica el principio de menor privilegio, ejecuta sin root, gestiona secretos sin exponerlos, escanea vulnerabilidades y endurece el aislamiento del runtime.",
        subtitle: "Imágenes fiables, procesos humildes y secretos protegidos.",
        objectives: [
          "Aplicar el principio de menor privilegio a los contenedores",
          "Ejecutar procesos sin root y limitar capabilities",
          "Gestionar secretos sin quemarlos en las imágenes",
          "Escanearte vulnerabilidades en el CI",
          "Endurecer el aislamiento y el runtime del motor",
        ],
        lessons: [
          {
            id: "seguridad-principios-contenedores",
            title: "Principios de seguridad en contenedores",
            duration: "11 min",
            level: "avanzado",
            category: "seguridad",
            cardText: "Menor privilegio, superficie mínima y defender en profundidad.",
            desc: "Principios de seguridad que guían todo el trabajo con contenedores.",
            body: {
              intro: [
                "Un contenedor no es una máquina virtual aislada: comparte el kernel con el host y con el resto de contenedores. Si lo tratas como una caja impenetrable, te llevarás sorpresas cuando alguien escape del proceso.",
                "La seguridad en contenedores se construye en capas: imagen fiable, usuario sin privilegios, capabilities mínimas, secretos protegidos y un runtime endurecido. La regla de oro es el menor privilegio: dar a cada pieza solo lo que necesita.",
              ],
              def: {
                par: "La seguridad en contenedores consiste en reducir la superficie de ataque de la imagen y del proceso en ejecución aplicando menor privilegio, aislamiento y defensa en profundidad.",
                porQue: "Los contenedores se despliegan masivamente y suelen ejecutar código de terceros. Un único contenedor comprometido puede escalar al host si no lo limitamos desde el diseño.",
                cuando: "Aplica estas reglas siempre, pero son críticas en producción, multitenancy y cuando ejecutas imágenes de terceros.",
              },
              concepts: [
                "Superficie de ataque: todo lo que un atacante puede tocar; reduce imagen, puertos y paquetes.",
                "Menor privilegio: usuarios no root, capabilities mínimas y recursos limitados.",
                "Defensa en profundidad: varias capas para que una brecha no sea un juego terminado.",
                "Cadena de suministro: de dónde vienen tus imágenes y quién puede modificarlas.",
                "Runtime endurecido: seccomp, AppArmor y lectura en solo para el sistema de archivos.",
              ],
              basic: {
                p: "El punto de partida: correr el proceso con un usuario sin privilegios y con un sistema de archivos de solo lectura.",
                code: [
                  "docker run -it \\",
                  "  --user 10001:10001 \\",
                  "  --read-only \\",
                  "  --tmpfs /tmp \\",
                  "  nginx:1.27-alpine",
                ],
                out: "El contenedor ejecuta como usuario 10001 y no puede escribir fuera de /tmp.",
                lang: "bash",
              },
              intermediate: {
                p: "Definimos la seguridad directamente en el Dockerfile para que sea parte de la imagen, con usuario dedicado y sin herramientas de administración.",
                code: [
                  "FROM node:22-alpine",
                  "",
                  "COPY package*.json ./",
                  "RUN npm ci --omit=dev && \\",
                  "    rm -rf /usr/local/lib/node_modules/npm/docs",
                  "",
                  "WORKDIR /app",
                  "COPY src ./src",
                  "",
                  "RUN addgroup -S app && adduser -S app -G app",
                  "USER app",
                  "",
                  "EXPOSE 3000",
                  "CMD [\"node\", \"src/index.js\"]",
                ],
                caption: "Imagen segura: menos capas, usuario no root y sin sleep ni shell innecesarios",
              },
              real: {
                p: "Una startup sufrió un contenedor comprometido por una imagen con un backdoor. El contenedor corría como root y montaba el socket del host. Al endurecer la imagen y ejecutar sin privilegios, el incidente quedó contenido y no llegó a tocar el host.",
                ul: [
                  "Verifica la procedencia y la firma de las imágenes antes de usarlas.",
                  "Elimina del contenedor los binarios que no necesita para operar.",
                  "Expon la menor cantidad de puertos posible y usa networks aisladas.",
                  "Audita tus imágenes de forma periódica, no solo en el primer build.",
                ],
                code: [
                  "docker run \\",
                  "  --publish 127.0.0.1:3000:3000 \\",
                  "  --security-opt no-new-privileges \\",
                  "  --cap-drop ALL \\",
                  "  --user 10001:10001 \\",
                  "  mi-app:1.2.0",
                ],
                nota: "--cap-drop ALL y volver a añadir solo las capabilities necesarias es más seguro que el enfoque por defecto.",
              },
              expl: [
                "El kernel no distingue un contenedor del host: los namespaces y cgroups son la única barrera inicial.",
                "Un cambio de usuario sin privilegios limita el daño si alguien gana ejecución dentro del contenedor.",
                "El principio de menor privilegio se aplica a usuarios, capabilities, puertos, volúmenes y recursos.",
                "La imagen es la superficie de ataque base: cada paquete extra es una dependencia vulnerable nueva.",
                "La defensa en profundidad asume que una capa fallará y prepara la siguiente para contener el daño.",
              ],
              errors: [
                "Confiar en que un contenedor aislado es impermeable: el kernel compartido es la frontera real.",
                "Montar el socket de Docker dentro de un contenedor: es acceso root al host sin contraseña.",
                "Exponer servicios internos a redes públicas por puertos abiertos por defecto.",
              ],
              tips: [
                "Trata tus imágenes como código: versiona, audita y firma.",
                "Empieza por lo más barato: usuario no root, read-only y cap-drop ALL.",
                "Mantén las bases (alpine, node, postgres) actualizadas para recibir parches de seguridad.",
              ],
              exercise: [
                "Arranca un contenedor con --cap-drop ALL y comprueba que sigue funcionando.",
                "Ejecuta tu API con --read-only y ajusta los tmpfs necesarios.",
                "Identifica qué capabilities mínimas necesita tu proceso y configúralas.",
              ],
              summary: [
                "La seguridad en contenedores exige menor privilegio desde la imagen hasta el runtime.",
                "Imagen fiable, usuario no root y capabilities mínimas reducen la superficie de ataque.",
                "La defensa en profundidad convierte una brecha en un incidente contenido.",
              ],
              lang: "bash",
              exampleFile: "seguridad-principios",
              desc: "Principios de seguridad que guían todo el trabajo con contenedores.",
            },
          },
          {
            id: "usuarios-no-root",
            title: "Usuarios no root y capabilities",
            duration: "11 min",
            level: "avanzado",
            category: "seguridad",
            cardText: "Nunca correas como root: usuarios dedicados y capabilities mínimas.",
            desc: "Ejecuta procesos sin root con usuarios dedicados y capabilities acotadas.",
            body: {
              intro: [
                "La mayoría de imágenes por defecto ejecutan como root. Si un atacante explota tu aplicación dentro del contenedor, ese root solo está limitado por un puñado de namespaces: demasiado poco para dormir tranquilo.",
                "La solución es ejecutar como un usuario sin privilegios y recortar las capabilities, esos poderes especiales que el kernel concede a los procesos con permisos elevados.",
              ],
              def: {
                par: "Las capabilities son unidades de privilegio que el kernel otorga a procesos (CHOWN, NET_BIND_SERVICE, DAC_OVERRIDE...). Ejecutar sin root y descartar las que no necesitas limita lo que un proceso comprometido puede hacer.",
                porQue: "Un proceso no root no puede modificar ficheros sensibles del host ni escalar fácilmente. Reducir capabilities elimina vectores de ataque concretos sin perder funcionalidad.",
                cuando: "Siempre en producción, y especialmente cuando ejecutas imágenes de terceros cuyos scripts 'de instalación' hacen trucos como root.",
              },
              concepts: [
                "USER en el Dockerfile: el proceso arranca con ese usuario y grupo.",
                "Capabilities: poderes granulares del kernel (CHOWN, NET_ADMIN, SETUID...).",
                "cap-drop ALL: elimina todas las capabilities y añade solo las imprescindibles.",
                "no-new-privileges: impide escalar privilegios incluso si hay un binario setuid.",
                "host UID mapping: usar rangos de ids para evitar colisiones con el host.",
              ],
              basic: {
                p: "Ejecutar tu servicio con un usuario sin privilegios y sin capabilities peligrosas.",
                code: [
                  "docker run --rm \\",
                  "  --user 10001:10001 \\",
                  "  --cap-drop ALL \\",
                  "  --cap-add NET_BIND_SERVICE \\",
                  "  --security-opt no-new-privileges \\",
                  "  -p 8080:8080 mi-api",
                ],
                out: "El proceso arranca en el puerto 8080 pero no tiene casi ningún poder sobre el sistema.",
                lang: "bash",
              },
              intermediate: {
                p: "Lo mejor es dejarlo escrito en el Dockerfile para que la imagen ya sea segura por defecto.",
                code: [
                  "FROM node:22-alpine",
                  "",
                  "RUN adduser -S backend && mkdir -p /app",
                  "WORKDIR /app",
                  "COPY --chown=backend:backend . .",
                  "",
                  "USER backend",
                  "",
                  "EXPOSE 8080",
                  'CMD ["node", "server.js"]',
                ],
                caption: "Usuario dedicado en el Dockerfile",
              },
              real: {
                p: "Una pasarela de pagos detectaba escapes de contenedores en fase beta. El análisis mostró que la mayoría usaban procesos root y capabilities de red demasiado amplias. Con usuario dedicado y cap-drop ALL, el escape quedó neutralizado en la mayoría de escenarios.",
                ul: [
                  "Define un usuario y grupo con ids explícitos y estables.",
                  "Revisa las capabilities de un contenedor con docker inspect y capsh.",
                  "Añade no-new-privileges para reforzar la barrera del setuid.",
                  "Prueba la imagen en un entorno con capacidad de escritura ajustada.",
                ],
                code: [
                  "FROM node:22-alpine",
                  "RUN adduser -S backend",
                  "USER backend",
                  "COPY --chown=backend:backend . /app",
                  "WORKDIR /app",
                  'CMD ["node", "server.js"]',
                ],
                nota: "Combina el usuario no root con read-only y tmpfs para que ni /etc ni la raíz sean escribibles.",
              },
              expl: [
                "La directiva USER cambia el uid/gid efectivo del proceso, pero no ocurre mágicamente: los ficheros deben pertenecer a ese usuario.",
                "Docker Engine pone a disposición un conjunto de capabilities por defecto; --cap-drop ALL las quita todas y re-estableces las que necesites.",
                "Un proceso con todas las capabilities puede montar unidades, cambiar owners o manipular la red del host.",
                "no-new-privileges es una garantía adicional contra la escalada vía binarios setuid.",
                "Las imágenes base como alpine tienen menos herramientas, lo que complica la vida del atacante a la vez que reduce tu superficie.",
              ],
              errors: [
                "Crear el usuario no root pero olvidar darle permisos sobre los ficheros de la app.",
                "Aplicar cap-drop ALL y romper el arranque por necesitar un puerto privilegiado.",
                "Usar USER root para 'simplificar' la instalación de dependencias en el runtime.",
              ],
              tips: [
                "Comprueba tu imagen con: docker run --user 10001:10001 --entrypoint whoami imagen.",
                "Documenta las capabilities mínimas junto al Dockerfile para que el equipo sepa por qué están.",
                "En Kubernetes, define securityContext con runAsNonRoot y allowPrivilegeEscalation: false.",
              ],
              exercise: [
                "Crea un Dockerfile con usuario no root para tu API y verifica quién ejecuta el proceso.",
                "Intenta escribir en /etc dentro de un contenedor read-only y observa el error.",
                "Lista las capabilities de un contenedor tuya con y sin --cap-drop ALL.",
              ],
              summary: [
                "Ejecutar sin root y con capabilities mínimas reduce drásticamente el poder de un atacante.",
                "El Dockerfile debe declarar el usuario y la imagen debe ser segura por defecto.",
                "Combina USER, cap-drop ALL, no-new-privileges y read-only para una defensa real.",
              ],
              lang: "bash",
              exampleFile: "usuarios-no-root",
              desc: "Ejecuta procesos sin root con usuarios dedicados y capabilities acotadas.",
            },
          },
          {
            id: "imagenes-confiables-secretos",
            title: "Imágenes confiables y gestión de secretos",
            duration: "10 min",
            level: "avanzado",
            category: "seguridad",
            cardText: "De dónde vienen tus imágenes y dónde viven tus secretos.",
            desc: "Usa imágenes confiables y protege los secretos para que nunca entren en la capa.",
            body: {
              intro: [
                "Dos fugas de credenciales muy comunes tienen el mismo origen: una imagen que contiene un token o un fichero de configuración con la contraseña en claro. Las migas de tu .env se quedan grabadas en las capas y viajan a todos los despliegues.",
                "Aunar suministro y secretos evita el 90% de los problemas: verifica de dónde bajas las imágenes y haz que los secretos vivan fuera de ellas, inyectándose en el runtime.",
              ],
              def: {
                par: "Usar imágenes confiables significa basarse en imágenes oficiales y verificadas, y gestionar secretos significa inyectarlos en tiempo de ejecución (variables de entorno, mounted secrets) sin que formen parte de la imagen.",
                porQue: "Una imagen comprometida se propaga a cada contenedor que la use, y un secreto incrustado en una capa se envía con ella a cada registry y a cada clúster.",
                cuando: "En toda imagen que llegue a producción y con cualquier credencial que dé acceso a algo valioso, hoy o en el futuro.",
              },
              concepts: [
                "Imagen oficial: mantenida por el proyecto, firmada y con CVE conocidos.",
                "Digest: el hash de la imagen; anclar por digest garantiza exactamente lo que probaste.",
                "Secrets en runtime: variables de entorno o ficheros montados, nunca capas.",
                "BuildKit secrets: cuenta con secretos durante el build sin grabarlos en la imagen.",
                "Rotación: cambiar credenciales periódicamente; caducan y se renuevan sin redeploy de imagen.",
              ],
              basic: {
                p: "Montar un secreto como fichero en runtime en lugar de grabarlo en la imagen.",
                code: [
                  "echo $DATABASE_PASSWORD > /tmp/db_password.txt",
                  "docker run \\",
                  "  --env-file .env.production \\",
                  "  --mount type=bind,src=/tmp/db_password.txt,dst=/run/secrets/db_password,readonly \\",
                  "  mi-api",
                ],
                out: "La credencial vive fuera de la imagen y solo está disponible en el contenedor en ejecución.",
                lang: "bash",
              },
              intermediate: {
                p: "Con BuildKit y secrets durante la construcción, instalas dependencias privadas sin dejar rastro en las capas.",
                code: [
                  "# syntax=docker/dockerfile:1",
                  "FROM node:22-alpine",
                  "RUN --mount=type=secret,id=npm_token \\",
                  "    NPM_TOKEN=$(cat /run/secrets/npm_token) && \\",
                  "    npm ci --omit=dev",
                  "COPY . .",
                  'CMD ["node", "server.js"]',
                ],
                caption: "Dockerfile con BuildKit secrets en el build",
              },
              real: {
                p: "Un equipo entero se enteró de que su API pública mostraba la API key de producción incrustada en el bundle del frontend desde hacía un año. La rotación masiva fue dolorosa. Ahora los secretos viven en secretos de Kubernetes y las imágenes no contienen ni un token.",
                ul: [
                  "Usa siempre imágenes oficiales o firmadas y verifica el digest oficial.",
                  "Escanea el registry para localizar secretos incrustados en imágenes anteriores.",
                  "No uses .env dentro de la imagen: dispara variables desde el orquestador.",
                  "Rota secretos periódicamente y con procedimiento automatizado.",
                ],
                code: [
                  "apiVersion: v1",
                  "kind: Secret",
                  "metadata:",
                  "  name: db-credentials",
                  "type: Opaque",
                  "stringData:",
                  "  DATABASE_URL: postgres://app:pass@db:5432/app",
                ],
                nota: "El secreto de Kubernetes se monta como fichero en el pod; la imagen nunca lo conoce.",
              },
              expl: [
                "Cada RUN que copia un fichero con una credencial deja la credencial en esa capa para siempre.",
                "El digest de la imagen es un hash único: despliegas exactamente la versión que probaste, sin ambigüedades.",
                "Los secrets de docker swarm y Kubernetes se montan como volúmenes temporales y solo los ve el proceso.",
                "Las variables de entorno son menos seguras que los ficheros montados, porque son legibles desde cualquier proceso.",
                "La rotación con --env-file permite cambiar credenciales sin reconstruir la imagen.",
              ],
              errors: [
                "Copiar .env dentro de la imagen y publicarla en el registry.",
                "Usar las mismas credenciales de desarrollo en producción.",
                "Caché de docker con imágenes viejas que aún contienen los secretos.",
              ],
              tips: [
                "Añade .env y *.pem a .dockerignore en todos tus proyectos.",
                "Audita tus imágenes con un escáner de secretos antes de publicarlas.",
                "En CI, inyecta secretos como variables del pipeline, nunca literales en el repositorio.",
              ],
              exercise: [
                "Inspecciona una imagen tuya con dive o docker history y busca credenciales.",
                "Monta un fichero de secretos en runtime y compruébalo desde el proceso.",
                "Reescribe un Dockerfile para bajar dependencias privadas con BuildKit secrets.",
              ],
              summary: [
                "Las imágenes deben ser oficiales, firmadas y verificadas por digest.",
                "Los secretos viven en el runtime, nunca en las capas de la imagen.",
                "BuildKit secrets y secretos del orquestador resuelven el build y el despliegue.",
              ],
              lang: "bash",
              exampleFile: "imagenes-confiable-secretos",
              desc: "Usa imágenes confiables y protege los secretos para que nunca entren en la capa.",
            },
          },
          {
            id: "escaneo-y-vulnerabilidades",
            title: "Escaneo y auditoría de vulnerabilidades",
            duration: "10 min",
            level: "avanzado",
            category: "seguridad",
            cardText: "Descubre CVEs de tus imágenes antes de que lleguen a producción.",
            desc: "Escanea imágenes en busca de vulnerabilidades conocidas y automatízalo en CI.",
            body: {
              intro: [
                "Tu imagen hereda vulnerabilidades de cada paquete que instala: la base del sistema, el runtime de tu lenguaje y las dependencias de cada capa. El escaneo de imágenes convierte esa lista opaca de paquetes en un informe de riesgos accionable.",
                "Herramientas como Trivy, Grype o la integración de los registros comerciales hacen el trabajo contra bases de datos de CVE actualizadas. El truco no es escanear una vez, sino hacerlo de forma continua y en el punto correcto del pipeline.",
              ],
              def: {
                par: "El escaneo de imágenes compara los paquetes instalados y su versión con bases de datos de vulnerabilidades conocidas (CVEs) y devuelve un informe con severidad y las acciones a tomar.",
                porQue: "La mayoría de compromisos en contenedores vienen de dependencias vulnerables conocidas y sin parchear. Detectarlas antes del despliegue es barato y evita incidentes caros.",
                cuando: "En cada build del CI, en el registry de forma periódica y siempre antes de tocar desarrollo o producción.",
              },
              concepts: [
                "CVE: vulnerabilidad pública identificada con un descriptor estándar.",
                "Trivy/Grype: escáneres open source de paquetes y sistemas operativos.",
                "Severidad: critical, high, medium, low según el impacto potencial.",
                "SBOM: lista de materiales de la imagen; quién construye qué.",
                "Política de CI: fallar el build si aparece una vulnerabilidad por encima del umbral.",
              ],
              basic: {
                p: "Escanea una imagen local con Trivy y entiende el informe de severidad.",
                code: [
                  "docker build -t mi-api:1.0 .",
                  "trivy image mi-api:1.0",
                  "# Salida: tabla con CVE, severidad, paquete y versión afectada",
                ],
                out: "El informe muestra CVEs con severidad y el paquete vulnerable de cada imagen.",
                lang: "bash",
              },
              intermediate: {
                p: "Integrar el escaneo en GitHub Actions para que falle el build si hay críticos o altos.",
                code: [
                  "jobs:",
                  "  scan:",
                  "    runs-on: ubuntu-latest",
                  "    steps:",
                  "      - uses: actions/checkout@v4",
                  "      - name: Build imagen",
                  "        run: docker build -t mi-api:ci .",
                  "      - name: Escaneo con Trivy",
                  "        uses: aquasecurity/trivy-action@master",
                  "        with:",
                  "          image-ref: mi-api:ci",
                  "          exit-code: '1'",
                  "          ignore-unfixed: true",
                  "          severity: CRITICAL,HIGH",
                ],
                caption: "Política de escaneo en CI",
              },
              real: {
                p: "Un marketplace pasó de revisar dependencias manualmente a catalogar todos sus servicios con SBOM y escaneo en el CI. Detectaron un CVE crítico en una imagen base que llevaba meses en producción y lo desplegaron en horas.",
                ul: [
                  "Elegir la severidad mínima que bloquea el build y documentarla.",
                  "Priorizar vulnerabilidades explotables en el contexto real de la app.",
                  "Actualizar las bases y el escáner a diario: las bases de CVEs crecen rápido.",
                  "Generar y firmar el SBOM en cada release.",
                ],
                code: [
                  "trivy image --exit-code 1 --ignore-unfixed --severity HIGH,CRITICAL mi-api:1.0",
                  "trivy image --format cyclonedx --output sbom.json mi-api:1.0",
                ],
                nota: "ignore-unfixed descarta CVEs que aún no tienen parche, para no bloquear tu día con algo que no puedes resolver.",
              },
              expl: [
                "El escáner compara cada paquete instalado contra los boletines de seguridad publicados.",
                "Distorsional: un CVE en un paquete nunca usado por tu código es menos urgente que uno explotable.",
                "El SBOM permite saber exactamente qué versiones de qué componentes viajan en cada release.",
                "Escaneo en el CI solo cubre el momento del build; el registry y el runtime deben escanearse de forma continua.",
                "Basearse en actualizaciones diarias de la base del lenguaje reduce la deuda de CVEs acumulada.",
              ],
              errors: [
                "Escaneo manual y esporádico: la deuda de seguridad vuelve a crecer entre revisiones.",
                "Bloquear el build a cualquier CVE med, causando parálisis y que el equipo apague el escáner.",
                "Ignorar el SBOM y no saber qué hay realmente dentro de tus imágenes.",
              ],
              tips: [
                "Empieza con severidad HIGH y CRITICAL y afina según tu contexto.",
                "Combina escaneo de imagen con escaneo de dependencias del proyecto (npm audit, pip-audit).",
                "Mantén actualizadas las bases del contenedor (node:22-alpine, postgres:16-alpine) que despliegas.",
              ],
              exercise: [
                "Escanea una imagen tuya con Trivy y clasifica los hallazgos por severidad.",
                "Añade el paso de escaneo a un workflow de GitHub Actions y pruébalo.",
                "Genera el SBOM de una imagen y localiza la versión exacta de tu framework.",
              ],
              summary: [
                "El escaneo continuo descubre CVEs conocidas antes de que lleguen a producción.",
                "Trivy o Grype, integrados en CI y registry, convierten la seguridad en un proceso.",
                "El SBOM te da transparencia total sobre el contenido de tus imágenes.",
              ],
              lang: "bash",
              exampleFile: "escaneo-vulnerabilidades",
              desc: "Escanea imágenes en busca de vulnerabilidades conocidas y automatízalo en CI.",
            },
          },
          {
            id: "aislamiento-y-hardening",
            title: "Aislamiento y hardening del motor",
            duration: "11 min",
            level: "avanzado",
            category: "seguridad",
            cardText: "Endurece el aislamiento del contenedor en el runtime del host.",
            desc: "Endurece seccomp, AppArmor y las opciones de aislamiento del motor Docker.",
            body: {
              intro: [
                "Cuando endureces la imagen y el proceso, queda una última frontera: el propio motor y las syscalls que el kernel deja ejecutar. Un proceso que huye del namespace necesita syscalls específicas; tú puedes cerrar esa puerta.",
                "El runtime de Docker soporta filtros seccomp, perfiles AppArmor y SELinux, además de opciones como no-new-privileges o el bloqueo de automount. Este módulo une todas las piezas en un perfil de aislamiento.",
              ],
              def: {
                par: "El hardening del host restringe qué syscalls puede hacer un contenedor (seccomp), qué paths y capabilities concede AppArmor, y qué operativas adicionales como el montaje se bloquean, reduciendo el potencial de escalada al host.",
                porQue: "Aunque el proceso esté 'dentro' de un contenedor, las syscalls viajan al kernel del host. Filtrarlas limita la superficie para escapes y ataques de kernel.",
                cuando: "Siempre que el host corra código externo, y de forma obligatoria cuando proceses datos no confiables o ejecutes imágenes de terceros.",
              },
              concepts: [
                "Syscall: la llamada al kernel; el contenedor la ejecuta en el named kernel del host.",
                "seccomp: perfil que permite o niega syscalls concretas.",
                "AppArmor: perfil de acceso que restringe paths, networks y capabilities.",
                "no-new-privileges: impide ganar privilegios de binarios setuid.",
                "Read-only rootfs: el sistema de ficheros raíz no se puede modificar.",
              ],
              basic: {
                p: "Reforzar el runtime de arranque combinando read-only, no-new-privileges y capabilities mínimas.",
                code: [
                  "docker run \\",
                  "  --rm \\",
                  "  --read-only \\",
                  "  --tmpfs /tmp \\",
                  "  --cap-drop ALL \\",
                  "  --security-opt no-new-privileges \\",
                  "  --user 10001:10001 \\",
                  "  nginx:1.27-alpine",
                ],
                out: "nginx corre sin capacidad de escritura, sin privileges y sin capabilities de red salvo las del arranque.",
                lang: "bash",
              },
              intermediate: {
                p: "Aplicar un perfil seccomp que solo permite las syscalls necesarias (modo estricto) en una imagen propia.",
                code: [
                  "docker run \\",
                  "  --security-opt seccomp=./perfil-seccomp.json \\",
                  "  mi-api",
                  "",
                  "# perfil-seccomp.json (fragmento)",
                  "{",
                  '  "defaultAction": "SCMP_ACT_ERRNO",',
                  '  "syscalls": [{',
                  '    "names": ["read", "write", "exit", "execve", "openat", "close"],',
                  '    "action": "SCMP_ACT_ALLOW"',
                  "  }]",
                  "}",
                ],
                caption: "Perfil seccomp que solo habilita las syscalls básicas",
              },
              real: {
                p: "Un proveedor de SaaS ejecuta cientos de servicios multi-tenant del mismo pool. Cada uno corre con read-only, cap-drop ALL y un perfil AppArmor propio, más seccomp personalizado para las imágenes internas. Un escape probado en benchmarks no consiguió romper ninguno de los perfiles.",
                ul: [
                  "Empieza con no-new-privileges y read-only: el coste de aplicar es mínimo.",
                  "Perfiles AppArmor y seccomp por imagen, revisables y versionados.",
                  "No compartas imágenes con permisos privilegiados en tu registry.",
                  "Mide el impacto de los perfiles en las APIs SLO antes de estresar.",
                ],
                code: [
                  "docker run \\",
                  "  --security-opt apparmor=perfil-api \\",
                  "  --security-opt seccomp=perfil-seccomp-api.json \\",
                  "  --cap-drop ALL \\",
                  "  --read-only \\",
                  "  mi-api:3.0",
                ],
                nota: "El runtime de contenedores modernos (containerd, cri-o) permite aplicar los mismos conceptos en Kubernetes vía securityContext.",
              },
              expl: [
                "Las syscalls de un contenedor se ejecutan en el kernel del host: la frontera definitiva es ese kernel.",
                "seccomp audita o bloquea las syscalls antes de que toquen los subsistemas sensibles.",
                "AppArmor controla el acceso a rutas y operaciones más allá de las syscalls.",
                "Read-only rootfs no impide escribir en /tmp o en volúmenes montados: define esos destinos explícitamente.",
                "El conjunto mínimo de opciones robustas: USER, cap-drop ALL, no-new-privileges, read-only, tmpfs acotado.",
              ],
              errors: [
                "Depender de una única capa de aislamiento y del 'contenedor = seguro'.",
                "Montar sockets, /proc o /sys del host en el contenedor.",
                "Aplicar no-new-privileges a procesos que legítimamente necesitan setuid.",
              ],
              tips: [
                "Automatiza el perfil de hardening para que sea el default de tu plataforma.",
                "Valida los perfiles con pentest y benchmarks (CIS Docker Benchmark).",
                "Revisa versiones de kernels para parches de vulnerabilidades del kernel compartido.",
              ],
              exercise: [
                "Arranca tu API con read-only y resuelve los tmpfs que necesita.",
                "Escribe un perfil seccomp mínimo y ejecuta tu imagen con él.",
                "Comprueba un escape real: intenta montar el host desde un contenedor con todas las opciones por defecto.",
              ],
              summary: [
                "El aislamiento en runtime filtra syscalls, acceso y privilegios en el borde del kernel.",
                "seccomp, AppArmor, read-only y no-new-privileges son tu cinturón de seguridad.",
                "El hardening marca la diferencia entre una brecha contenida y un host comprometido.",
              ],
              lang: "bash",
              exampleFile: "aislamiento-hardening",
              desc: "Endurece seccomp, AppArmor y las opciones de aislamiento del motor Docker.",
            },
          },
        ],
      },
      {
        id: "modulo-07",
        n: 7,
        t: "Docker en producción a escala",
        level: "avanzado",
        caption: "Orquestación, observabilidad y CI/CD de contenedores.",
        desc: "Lleva Docker a producción: orquesta con Swarm y Kubernetes, centraliza logs y métricas, limita recursos, y automatiza el despliegue con pipelines de CI/CD.",
        subtitle: "De docker run en tu portátil a cientos de nodos coordinados.",
        objectives: [
          "Orquestar contenedores con Docker Swarm",
          "Centralizar logs y monitorizar contenedores",
          "Limitar recursos y gestionar la escala",
          "Automatizar builds y despliegues con CI/CD",
          "Entender Kubernetes como el siguiente nivel",
        ],
        lessons: [
          {
            id: "orquestacion-swarm-kubernetes",
            title: "Orquestación: Swarm y Kubernetes",
            duration: "12 min",
            level: "avanzado",
            category: "producción",
            cardText: "Varios nodos coordinados: servicios, réplicas y equilibrio de carga.",
            desc: "Orquesta servicios a escala con Docker Swarm y sus conceptos esenciales.",
            body: {
              intro: [
                "Una vez que tu stack cruza la frontera de un solo host, surgen las mismas preguntas: qué pasa si un nodo muere, cómo reparto carga y cómo mantengo N réplicas de un servicio. Ahí entran los orquestadores.",
                "Docker Swarm es el orquestador integrado en el propio Docker: con los mismos conceptos de Compose pero pensado para varios hosts, con equilibrio de carga, redes en overlay y actualizaciones sin downtime.",
              ],
              def: {
                par: "Docker Swarm convierte un grupo de hosts Docker en un clúster con un plano de control distribuido, donde defines servicios y réplicas que el orquestador distribuye entre nodos.",
                porQue: "Escalar un servicio en Swarm es declarar la réplica deseada y dejar que el orquestador la mantenga, por más que falle un nodo.",
                cuando: "Perfecto para plataformas medianas que ya viven en Docker y prefieren no introducir Kubernetes. Kubernetes aporta más ecosistema pero más complejidad operativa.",
              },
              concepts: [
                "Nodo manager: miembro del plano de control que acepta servicios y mantiene el estado.",
                "Nodo worker: ejecuta las tareas asignadas y vota en el consenso.",
                "Servicio: definición declarativa de tu app, como un compose pero distribuido.",
                "Réplica: copia del contenedor que el orquestador mantiene viva.",
                "Red overlay: red interna multi-host que conecta servicios entre nodos.",
              ],
              basic: {
                p: "Inicializar el swarm, crear un servicio con tres réplicas y ver su estado.",
                code: [
                  "docker swarm init --advertise-addr 10.0.0.5",
                  "docker service create \\",
                  "  --name api \\",
                  "  --replicas 3 \\",
                  "  --publish published=8080,target=3000 \\",
                  "  mi-api:1.0",
                  "docker service ps api",
                ],
                out: "El servicio api tiene 3 réplicas distribuidas y tolera la caída de un nodo.",
                lang: "bash",
              },
              intermediate: {
                p: "Actualizar un servicio sin downtime con actualización gradual y rollback automático.",
                code: [
                  "docker service update \\",
                  "  --image mi-api:1.1 \\",
                  "  --update-delay 5s \\",
                  "  --update-parallelism 1 \\",
                  "  --rollback-on-failure api",
                ],
                caption: "Actualización rolling con rollback automático",
              },
              real: {
                p: "Una plataforma de envíos corre su API, el worker de colas y Postgres en un clúster Swarm de seis nodos. El despliegue se hace con docker stack deploy, rollback por fallo de healthcheck y sin interrupción del servicio.",
                ul: [
                  "Define el stack en un docker-stack.yml versionado y desplieguéalo con un comando.",
                  "Usa pinned tags en producción y digests anclados para reproducibilidad.",
                  "Recurrente para los stateful como Postgres, gestiona su volumen con cuidado.",
                  "Monitoriza el estado del clúster y las réplicas en tiempo real.",
                ],
                code: [
                  "docker stack deploy -c docker-stack.yml mi_stack",
                  "docker service ls",
                  "docker service scale api=5",
                ],
                nota: "Swarm gestiona el equilibrado de carga interno con VIP: un único endpoint virtual sobre el que sirven todas las réplicas.",
              },
              expl: [
                "El plano de control Swarm mantiene el estado deseado declarado en cada servicio.",
                "El orquestador reconcilia continuamente: si muere una réplica, crea otra.",
                "La red overlay cifra y enruta el tráfico entre nodos mediante VXLAN.",
                "El stack deploy traduce tu compose distribuido a servicios del swarm.",
                "Swarm encaja cuando quieres orquestación sin la curva de Kubernetes.",
              ],
              errors: [
                "Tratar los servicios como contenedores sueltos y no como estado declarado.",
                "No fijar el número de managers (siempre impar) para no perder consenso.",
                "Poner servicios sin healthcheck: el orquestador no sabe cuándo reiniciar.",
              ],
              tips: [
                "Empieza con 3 managers y el resto workers.",
                "Define healthchecks en cada servicio para que el orquestador actúe.",
                "Prueba el fracaso: mata un nodo y observa cómo se reequilibran las réplicas.",
              ],
              exercise: [
                "Crea un clúster Swarm local con dos nodos (docker swarm + worker).",
                "Despliega un servicio con 4 réplicas y comprueba su distribución.",
                "Haz rolling update con rollback y simula una caída de nodo.",
              ],
              summary: [
                "Swarm orquesta servicios a escala con réplicas, overlay y consenso distribuido.",
                "Los servicios son estado deseado: el orquestador los mantiene vivos.",
                "Rolling updates y rollback convierten el despliegue en algo seguro y repetible.",
              ],
              lang: "bash",
              exampleFile: "orquestacion-swarm",
              desc: "Orquesta servicios a escala con Docker Swarm y sus conceptos esenciales.",
            },
          },
          {
            id: "logs-y-monitoreo",
            title: "Logs y monitoreo de contenedores",
            duration: "11 min",
            level: "avanzado",
            category: "producción",
            cardText: "Centraliza logs y mide la salud de cada contenedor.",
            desc: "Centraliza logs y monitoriza la salud y las métricas de tus contenedores.",
            body: {
              intro: [
                "Con decenas de contenedores reescalándose, los logs en la terminal se vuelven inmanejables. La historia de un fallo vive fragmentada entre servicios que arrancan y mueren: necesitas logs centralizados y métricas que te cuenten la salud global.",
                "Docker respeta la filosofía de que los contenedores escriban en stdout, y los drivers de logging trasladan ese flujo a ELK, Loki o las plataformas de la nube. En el otro frente, docker stats y el ecosistema de métricas te dan la visibilidad operativa.",
              ],
              def: {
                par: "La observabilidad de contenedores separa logs (eventos discretos) de métricas (medidas continuas): los primeros se centralizan y los segundos se recogen y grafican para conocer la salud del sistema.",
                porQue: "Es la diferencia entre 'algo falló' y saber qué contenedor, cuándo y por qué. Sin logs centralizados, cada acierto en producción es un paseo por mil terminales.",
                cuando: "Desde el primer servicio que despliegues en serio, y de forma obligatoria cuando hay más de un host o réplicas.",
              },
              concepts: [
                "Driver de logging: cómo el contenedor entrega sus logs (json-file, fluentd, loki, gelf).",
                "Centralización: un destino único con búsqueda, retención y alertas.",
                "docker stats: instantáneas de CPU, memoria y red por contenedor.",
                "Exporter: expone métricas para que un sistema las recoja, como cAdvisor.",
                "Healthcheck: test periódico que dice si el servicio responde de verdad.",
              ],
              basic: {
                p: "Leer logs en directo y etiquetarlos con compose para distinguirlos entre servicios.",
                code: [
                  "docker logs -f --tail 100 api",
                  "",
                  "docker compose logs -f api db worker",
                ],
                out: "El flujo de logs de varios servicios en la misma terminal, con prefijo por servicio.",
                lang: "bash",
              },
              intermediate: {
                p: "Configurar el driver de logging en Compose para enviar los logs a un destino centralizado.",
                code: [
                  "services:",
                  "  api:",
                  "    image: mi-api:1.2",
                  "    logging:",
                  "      driver: loki",
                  "      options:",
                  "        loki-url: http://loki:3100/loki/api/v1/push",
                  "        max-size: '10m'",
                  "        max-file: '5'",
                ],
                caption: "Logs hacia Grafana Loki con límite de tamaño",
              },
              real: {
                p: "Un incidente de facturación se resolvió en minutos porque todas las réplicas volcaban sus logs al mismo Loki y sus métricas a Prometheus. El grep entre servicios y la correlación temporal señalaron la réplica con deuda de cola.",
                ul: [
                  "Centraliza logs desde el inicio: luego migrar es mucho más caro.",
                  "Usa IDs de petición o trazabilidad única para correlacionar servicios.",
                  "Mantén retención y backups según el cumplimiento.",
                  "Combina logs con métricas: el log cuenta la historia, la métrica la tendencia.",
                ],
                code: [
                  "docker stats --format \"{{.Name}}: {{.CPUPerc}} cpu, {{.MemUsage}} mem\"",
                ],
                nota: "En Swarm o Kubernetes, la plataforma recolecta logs y métricas a nivel de orquestador.",
              },
              expl: [
                "Escribir logs a stdout permite que el motor decida el destino sin cambiar tu app.",
                "Los drivers con límite (max-size, max-file) evitan que /var/lib/docker crezca sin control.",
                "docker stats lee los cgroups del kernel, no son medidas exactas pero sí suficientemente fiables.",
                "Un healthcheck es la señal que usan los orquestadores para decidir reinicios y tráfico.",
                "Grafana + Loki + Prometheus es el stack de observabilidad por defecto del mundo open source.",
              ],
              errors: [
                "Enviar logs a tantos destinos como réplicas, duplicando el ruido.",
                "No fijar rotación y llenar el disco del host con logs.",
                "Usar docker logs en producción para diagnósticos: es efímero si el contenedor muere.",
              ],
              tips: [
                "Sé estricto con el formato de los logs: JSON estructurado con timestamp y nivel.",
                "Empieza con docker stats y pasa a un sistema real al crecer.",
                "Aterriza las alertas en el p95 de latencia y los healthchecks, no solo en CPU media.",
              ],
              exercise: [
                "Configura rotación de logs en un contenedor y verifica el límite de ficheros.",
                "Envía logs de dos servicios a un Loki local y busca por etiqueta.",
                "Consulta docker stats mientras cargas tu API para ver la relación demanda-recurso.",
              ],
              summary: [
                "Los logs se centralizan y las métricas se recogen para entender la salud a escala.",
                "Docker ofrece drivers de logging y docker stats para arrancar con poco.",
                "Logs, métricas y healthchecks juntos convierten un incidente en una historia resuelta.",
              ],
              lang: "bash",
              exampleFile: "logs-monitoreo",
              desc: "Centraliza logs y monitoriza la salud y las métricas de tus contenedores.",
            },
          },
          {
            id: "ci-cd-con-docker",
            title: "CI/CD con Docker",
            duration: "10 min",
            level: "avanzado",
            category: "producción",
            cardText: "Pipe de builds, escaneo y despliegue con la misma imagen que probaste.",
            desc: "Automatiza con CI/CD el build, escaneo y despliegue de imágenes Docker.",
            body: {
              intro: [
                "La promesa de Docker, 'funciona en mi máquina', solo se cumple cuando la imagen que se despliega es exactamente la que se probó. El CI/CD convierte cada cambio de código en una imagen construida, escaneada y desplegada de forma automática.",
                "El pipeline ideal construye una imagen con un tag reproducible, la somete a pruebas (unitarias, contrato y escaneo), la publica en un registry y la despliega solo si todo pasó. Ningún humano debería escribir docker build a mano en producción.",
              ],
              def: {
                par: "El CI/CD con Docker encadena la construcción de la imagen, el escaneo y las pruebas, la publicación en el registry y el despliegue en los entornos, todo en el mismo formato de imagen que se probó.",
                porQue: "Las imágenes inmutables y los pipelines automatizados eliminan la deriva entre entornos y permiten rollback instantáneo a un artefacto conocido.",
                cuando: "Desde el primer proyecto serio: un pipeline mínimo (build + test + push) ya paga su coste y se amplía luego.",
              },
              concepts: [
                "Artefacto único: una imagen es el mismo binario en dev, staging y producción.",
                "Tag reproducible: versión + commit (mi-api:1.2.0-abc123) para trazabilidad.",
                "Registry: repositorio central de imágenes (Docker Hub, ECR, GHCR).",
                "Cache del build: aprovecha capas en CI para acelerar el pipeline.",
                "Deploy con la misma imagen: lo que escaneaste y probaste es lo que corre.",
              ],
              basic: {
                p: "Construir, publicar y desplegar una imagen en GitHub Actions.",
                code: [
                  "jobs:",
                  "  build:",
                  "    runs-on: ubuntu-latest",
                  "    steps:",
                  "      - uses: actions/checkout@v4",
                  "      - name: Login en registry",
                  "        run: echo ${{ secrets.REGISTRY_TOKEN }} | docker login ghcr.io -u ${{ vars.USER }} --password-stdin",
                  "      - name: Build y push",
                  "        run: |",
                  "          docker build -t ghcr.io/${{ vars.ORG }}/mi-api:${GITHUB_SHA} .",
                  "          docker push ghcr.io/${{ vars.ORG }}/mi-api:${GITHUB_SHA}",
                ],
                out: "Cada commit genera una imagen etiquetada con su hash y la sube al registry.",
                lang: "yaml",
              },
              intermediate: {
                p: "Añadir escaneo y despliegue: la imagen pasa las pruebas y el escaneo antes de llegar al entorno.",
                code: [
                  "      - name: Escaneo",
                  "        uses: aquasecurity/trivy-action@master",
                  "        with:",
                  "          image-ref: ghcr.io/${{ vars.ORG }}/mi-api:${{ github.sha }}",
                  "          severity: CRITICAL,HIGH",
                  "          exit-code: '1'",
                  "      - name: Deploy en staging",
                  "        run: docker stack deploy -c docker-stack.yml mi_stack",
                ],
                caption: "Escaneo y despliegue en el mismo pipeline",
              },
              real: {
                p: "Un equipo de deliveries despacha cada dos horas gracias a: imagen con tag del commit, pruebas y escaneo en el pipeline, y despliegue automático en staging con aprobación manual para producción. El rollback es cambiar el tag del servicio en el stack.",
                ul: [
                  "Versiona los tags: usa un semver del commit no solo latest.",
                  "Caché del build multicapa (buildx) para pipelines rápidos y baratos.",
                  "Protege el registry con autenticación y firmado de imágenes.",
                  "Separa el pipeline de staging de la aprobación de producción.",
                ],
                code: [
                  "docker buildx build --cache-from=type=gha --cache-to=type=gha .",
                ],
                nota: "El artefacto desplazado es exactamente el mismo que el probado: cero deriva entre entornos.",
              },
              expl: [
                "El hash del commit como tag hace cada imagen trazable a su código fuente.",
                "El escaneo en el mismo pipeline evita que una imagen vulnerable llegue a registry.",
                "La publicación en registry central garantiza que los nodos bajen la imagen del lugar correcto.",
                "El despliegue declarativo por stack permite actualizar con la misma herramienta de orquestación.",
                "Los pipelines de la nube (GH Actions, GitLab CI, Jenkins) ofrecen auth integrada con los registry.",
              ],
              errors: [
                "Desplegar con imágenes construidas a mano y no versionadas.",
                "Usar el tag latest en producción: no sabes qué versión real corres.",
                "No cachear el build y multiplicar el tiempo del pipeline.",
              ],
              tips: [
                "Empieza con un pipeline mínimo y añade escaneo al día siguiente.",
                "Usa el contexto del CI para no sumar fricción: secrets desde el proveedor.",
                "Regístrate un SBOM en el release repo para cumplimiento y auditoría.",
              ],
              exercise: [
                "Crea un flujo de GitHub Actions que construya y publique tu imagen.",
                "Añade el paso de escaneo con severidad y pruébalo con una versión intencionalmente vieja.",
                "Haz un deploy y un rollback modificando solo el tag del stack.",
              ],
              summary: [
                "El CI/CD garantiza que la imagen probada sea la desplegada.",
                "Tags reproducibles, escaneo y registry central son el núcleo del pipeline.",
                "La misma imagen viaja de dev a producción; el rollback es cambiar un tag.",
              ],
              lang: "yaml",
              exampleFile: "ci-cd-docker",
              desc: "Automatiza con CI/CD el build, escaneo y despliegue de imágenes Docker.",
            },
          },
          {
            id: "limites-de-recursos",
            title: "Límites de recursos y autoescalado",
            duration: "10 min",
            level: "avanzado",
            category: "producción",
            cardText: "Acota CPU y memoria para que un contenedor no ahogue al vecino.",
            desc: "Configura límites de recursos y escala tus servicios bajo demanda.",
            body: {
              intro: [
                "Un contenedor avaricioso puede acaparar toda la memoria del nodo y tumbar a los compañeros de host. Sin límites, el aislamiento que promete Docker se convierte en una pelea por recursos compartidos.",
                "Los límites de CPU y memoria no solo protegen al vecino: dan previsibilidad. Con ellos sabes cuánto tráfico aguanta cada réplica y cuándo toca escalar.",
              ],
              def: {
                par: "Los límites de recursos restringen cuánta CPU y memoria puede consumir un contenedor (y su cuota al nodo), mientras el autoescalado ajusta el número de réplicas según métricas de uso.",
                porQue: "Protegen la estabilidad del host y de los servicios compartidos, y son la base de decisiones de escala basadas en datos.",
                cuando: "Siempre en entornos compartidos o en producción. Sin límites, basta una fuga de memoria para degradar a todos.",
              },
              concepts: [
                "Memory limit: tope de memoria; superarlo mate el contenedor con OOM.",
                "CPU limit: cuota de núcleos; por encima, la CPU se reprime",
                "Reserva (reservation): recurso garantizado que el orquestador considera al repartir.",
                "OOM killer: mecanismo del kernel que mata un proceso que supera la memoria.",
                "Autoescalado: subir el número de réplicas según CPU, latencia o cola.",
              ],
              basic: {
                p: "Correr un servicio con límites explícitos de memoria y CPU.",
                code: [
                  "docker run \\",
                  "  --memory 512m \\",
                  "  --memory-swap 512m \\",
                  "  --cpus 1.0 \\",
                  "  mi-api",
                ],
                out: "El contenedor no puede usar más de 512 MB ni más de 1 núcleo.",
                lang: "bash",
              },
              intermediate: {
                p: "Declarar límites y reservas en el stack de Swarm para que el orquestador reparta nodos respetando la capacidad.",
                code: [
                  "services:",
                  "  api:",
                  "    image: mi-api:1.3",
                  "    deploy:",
                  "      replicas: 3",
                  "      resources:",
                  "        limits:",
                  "          cpus: '0.50'",
                  "          memory: 512M",
                  "        reservations:",
                  "          cpus: '0.25'",
                  "          memory: 256M",
                ],
                caption: "Límites y reservas en docker-stack.yml",
              },
              real: {
                p: "Una API de reservas dispara su CPU a las 20h. En lugar de diseñar para el pico, el k8s HPA y la escala de Swarm ajustan réplicas: de 3 a 12 en el pico y de vuelta a 3 de noche. Cada réplica con sus límites evita sorpresas.",
                ul: [
                  "Define límites más altos que la reserva para permitir picos puntuales.",
                  "Ajusta el autoescalado por la métrica que de verdad implica tu SLO.",
                  "Prueba la OOM de un contenedor y valida que el orquestador lo reinicie.",
                  "Mide el uso real antes de fijar números: docker stats te da la primera pista.",
                ],
                code: [
                  "docker service scale api=12",
                ],
                nota: "La reserva es la que el orquestador 'reserva' en el nodo; el límite es el máximo real.",
              },
              expl: [
                "--memory 512m sin --memory-swap impide que el proceso haga swap y crezca sin control.",
                "La CPU se expresa en núcleos completos o fracciones: --cpus 1.0 usa un núcleo como máximo.",
                "Los límites informan al kernel mediante cgroups, la misma tecnología que soporta el aislamiento.",
                "El orquestador solo coloca la réplica si el nodo tiene reserva disponible.",
                "El autoescalado es la consecuencia lógica de tener límites: sin métricas claras no sabes cuándo escalar.",
              ],
              errors: [
                "Poner solo reserva y no límite: los picos pueden desbordar al vecino.",
                "Memoria sin swap y proceso con legítimo trabajo grande: OOM por diseño.",
                "Autoescalar por CPU cuando tu cuello de botella es la base de datos.",
              ],
              tips: [
                "Empieza por la memoria: es el recurso que más fácilmente tumba un nodo.",
                "Usa métricas de SLO (latencia, errores) para escalar, y CPU/memoria como contexto.",
                "Configura límites por entorno: la reservación de dev no tiene por qué ser la de prod.",
              ],
              exercise: [
                "Lanza un contenedor con --memory 128m y estrégalo con una carga grande.",
                "Declara límites y reservas en tu stack y observa la colocación en nodos.",
                "Mide el uso real de tu API y propón un autoescalado justificado.",
              ],
              summary: [
                "Los límites de recursos protegen al host y hacen tu sistema predecible.",
                "La reserva garantiza capacidad; el límite pone el tope real.",
                "El autoescalado ajusta réplicas con métricas de SLO y límites razonables.",
              ],
              lang: "bash",
              exampleFile: "limites-recursos",
              desc: "Configura límites de recursos y escala tus servicios bajo demanda.",
            },
          },
          {
            id: "kubernetes-siguiente-paso",
            title: "Kubernetes: el siguiente paso",
            duration: "12 min",
            level: "avanzado",
            category: "producción",
            cardText: "Del Swarm al estándar de la industria: los conceptos que te llevan a K8s.",
            desc: "Modela tu stack en Kubernetes: Pods, Deployments, Services e Ingress.",
            body: {
              intro: [
                "Cuando el clúster crece, aparecen más problemas: descubrimiento de servicios robusto, config volumes a escala, secretos, autoscaling fino, canary y el ecosistema de la nube. Kubernetes se convirtió en el estándar para responderlos.",
                "La buena noticia: los conceptos que ya conoces de Docker y Swarm se trasladan. El pod, el deployment y el service son parientes cercanos del contenedor, la réplica y la red overlay de Swarm.",
              ],
              def: {
                par: "Kubernetes es un orquestador de contenedores que automatiza despliegue, escala y operación, organizando los contenedores en pods agrupados por deployments y expuestos por services e ingress.",
                porQue: "Es el estándar de la industria, soportado por todas las nubes, y su modelo declarativo ofrece rollback, autoescalado y alta disponibilidad probadas a escala.",
                cuando: "Cuando necesitas capacidades más ricas que Swarm (storage abstracto, canary, RBAC, ecosistema) o tu propia nube ya lo ofrece como servicio.",
              },
              concepts: [
                "Pod: la unidad mínima; uno o unos pocos contenedores que comparten red y volúmenes.",
                "Deployment: declara el estado deseado de réplicas y gestiona actualizaciones.",
                "Service: expone un conjunto de pods detrás de un nombre y equilibrio estable.",
                "Ingress: puerta HTTP externa con enrutado por host y path.",
                "ConfigMap/Secret: configuración y credenciales separadas del pod.",
              ],
              basic: {
                p: "Declarar un Deployment de tu API y exponerla con un Service.",
                code: [
                  "kubectl create deployment api --image=mi-api:1.0 --replicas=3",
                  "kubectl expose deployment api --port=80 --target-port=3000 --type=ClusterIP",
                  "kubectl get pods,svc",
                ],
                out: "Tres pods de la API servidos por un Service llamado api.",
                lang: "bash",
              },
              intermediate: {
                p: "El mismo stack en un manifiesto declarativo y versionable con actualización y rollback.",
                code: [
                  "apiVersion: apps/v1",
                  "kind: Deployment",
                  "metadata:",
                  "  name: api",
                  "spec:",
                  "  replicas: 3",
                  "  selector:",
                  "    matchLabels:",
                  "      app: api",
                  "  template:",
                  "    metadata:",
                  "      labels:",
                  "        app: api",
                  "    spec:",
                  "      containers:",
                  "        - name: api",
                  "          image: mi-api:1.4",
                  "          ports:",
                  "            - containerPort: 3000",
                  "          resources:",
                  "            limits:",
                  "              memory: 512M",
                ],
                caption: "Deployment de Kubernetes con límites de recursos",
              },
              real: {
                p: "La plataforma de logística migró su Swarm a Kubernetes para aprovechar el autoscaling horizontal, los ingresses gestionados y el storage de la nube. Las réplicas, redes y límites que configuraban en Swarm ahora se declaran en manifiestos y en el plan de control.",
                ul: [
                  "Empezar con los mismos límites y healthchecks que ya tenías en Swarm.",
                  "Usar Probes (liveness/readiness) para que K8s sepa cuándo enviar tráfico.",
                  "ConfigMap para config y Secret para credenciales, separados del pod.",
                  "Exponer solo con Ingress y limitar los ClusterIP internos.",
                ],
                code: [
                  "kubectl scale deployment api --replicas=5",
                  "kubectl rollout restart deployment api",
                  "kubectl get events --sort-by=.lastTimestamp",
                ],
                nota: "El paso natural: tu stack Compose existe casi 1:1 como stack de Helm de K8s.",
              },
              expl: [
                "El pod es la unidad mínima de programación: contiene un proceso y comparte red y almacenamiento con sus compañeros.",
                "El Deployment declara el número deseado de réplicas y el controlador reconcilia la realidad.",
                "El Service ofrece un nombre virtual y equilibrio entre pods, que pueden morir y nacer libremente.",
                "El Ingress es la puerta HTTP externa que enruta por host/path a tus servicios.",
                "ConfigMap y Secret separan la config de la imagen: tu imagen portable y tu config por entorno.",
              ],
              errors: [
                "Exponer pods directamente sin Service: el pod muere y la dirección cambia.",
                "No configurar readiness probe: K8s envía tráfico a cada pod aunque aún no responde.",
                "Copiar secretos en Config: ConfigMap no cifra nada.",
              ],
              tips: [
                "Convierte tu docker-stack.yml en Helm para gestión declarativa con plantillas.",
                "Usa helm upgrade --install y aprovecha el rollback automático ante fallos de despliegue.",
                "Empieza en un cluster gestionado por tu nube; la operación de K8s deja de ser tu problema inicial.",
              ],
              exercise: [
                "Crea un Deployment de 3 réplicas de tu API y expónlo con un Service.",
                "Añade liveness y readiness probes y observa el estado de los pods.",
                "Escala, reinicia y haz rollback con kubectl para ver la reconciliación.",
              ],
              summary: [
                "Kubernetes estandariza pods, deployments y servicios sobre los conceptos de Docker.",
                "Declarativo, escalable y con rollback: el estándar de la industria.",
                "Tu conocimiento de Docker/Compose/Swarm se traslada casi 1:1.",
              ],
              lang: "bash",
              exampleFile: "kubernetes-siguiente-paso",
              desc: "Modela tu stack en Kubernetes: Pods, Deployments, Services e Ingress.",
            },
          },
        ],
      },
    ],
  },
];