// _curriculum_testing.mjs
// Currículum del curso de Testing Backend.
// Exporta COURSES con todos los módulos y lecciones.
// Las lecciones existentes en disco se listan SIN body (no se regeneran);
// las nuevas (módulo 07) llevan body completo (12 secciones estándar).

export const COURSES = [
  {
    slug: "testing",
    title: "Testing Backend",
    modules: [
      {
        id: "modulo-01",
        n: 1,
        t: "Fundamentos del Testing",
        level: "avanzado",
        caption: "Por qué probar, qué tipos existen y cómo se organiza todo",
        desc: "Comprende qué es el testing, por qué importa en backend, la pirámide de testing, los tipos de pruebas, el ciclo de vida de un test y cómo organizar la suite para que crezca con el proyecto.",
        subtitle: "Probar no es opcional: es la red que sostiene el resto del desarrollo.",
        objectives: [
          "Explicar qué es el testing y por qué importa en backend",
          "Entender la pirámide de testing y su equilibrio",
          "Distinguir los tipos de pruebas y cuándo usarlos",
          "Conocer el ciclo de vida de un test",
          "Organizar los tests para un proyecto que crece",
        ],
        lessons: [
          {
            id: "ciclo-de-vida-de-un-test",
            title: "Ciclo de vida de un test",
            duration: "10 min",
            level: "avanzado",
            category: "fundamentos",
            cardText: "Setup, acción, aserción y teardown: el esqueleto de todo buen test.",
            desc: "Aprende las fases del ciclo de vida de un test y por qué cada una importa.",
          },
          {
            id: "organizando-tests",
            title: "Organizando los tests",
            duration: "9 min",
            level: "avanzado",
            category: "fundamentos",
            cardText: "Nombres claros, por test y paquetes: la estructura que escala.",
            desc: "Organiza tu suite de tests para que sea legible y mantenible.",
          },
          {
            id: "piramide-de-testing",
            title: "La pirámide de testing",
            duration: "9 min",
            level: "avanzado",
            category: "estrategia",
            cardText: "Muchos tests baratos arriba, pocos caros abajo: el equilibrio ideal.",
            desc: "Comprende la pirámide de testing y su distribución óptima de esfuerzo.",
          },
          {
            id: "que-es-testing",
            title: "¿Qué es el testing?",
            duration: "9 min",
            level: "avanzado",
            category: "fundamentos",
            cardText: "Probar software es gestionar el riesgo con evidencia y confianza.",
            desc: "Introducción al testing de software y su papel en el backend.",
          },
          {
            id: "tipos-de-pruebas",
            title: "Tipos de pruebas",
            duration: "11 min",
            level: "avanzado",
            category: "estrategia",
            cardText: "Unitarias, integración, E2E, regresión, humo: el mapa completo.",
            desc: "Recorre los tipos de pruebas y cuándo usar cada uno en backend.",
          },
        ],
      },
      {
        id: "modulo-02",
        n: 2,
        t: "Unit Testing",
        level: "avanzado",
        caption: "Prueba cada pieza en aislamiento con PHPUnit",
        desc: "Escribe tu primer test con PHPUnit, domina assertions y expectativas, aisla dependencias con mocks, stubs y spies, y cubre el testing de excepciones.",
        subtitle: "Aislar la lógica es poder probarla sin red, sin base de datos y sin miedo.",
        objectives: [
          "Escribir pruebas unitarias automatizadas con PHPUnit",
          "Usar assertions y expectativas con precisión",
          "Aislar dependencias con dobles de test",
          "Testear excepciones y flujos de error",
          "Aplicar los dobles en casos reales",
        ],
        lessons: [
          {
            id: "assertions-y-expectativas",
            title: "Assertions y expectativas",
            duration: "12 min",
            level: "avanzado",
            category: "unit testing",
            cardText: "assertSame, assertEquals, assertTrue: el vocabulario de la verdad.",
            desc: "Domina las assertions y expectativas de PHPUnit.",
          },
          {
            id: "dobles-en-practica",
            title: "Dobles en práctica",
            duration: "13 min",
            level: "avanzado",
            category: "dobles",
            cardText: "Fakes, mocks y stubs bien aplicados a servicios y repositorios.",
            desc: "Aplica los dobles de test en escenarios reales de backend.",
          },
          {
            id: "mocks-stubs-y-spies",
            title: "Mocks, stubs y spies",
            duration: "15 min",
            level: "avanzado",
            category: "dobles",
            cardText: "Mocks configura comportamiento, stubs devuelve datos, spies observa.",
            desc: "Comprende mocks, stubs y spies y cuándo conviene cada uno.",
          },
          {
            id: "primer-test-phpunit",
            title: "Primer test con PHPUnit",
            duration: "14 min",
            level: "avanzado",
            category: "phpunit",
            cardText: "Instala, configura y escribe tu primer test unitario en PHPUnit.",
            desc: "Pon en marcha PHPUnit y escribe tu primera prueba unitaria.",
          },
          {
            id: "testeando-excepciones",
            title: "Testeando excepciones",
            duration: "12 min",
            level: "avanzado",
            category: "unit testing",
            cardText: "expectException: verifica que el código falla de la forma esperada.",
            desc: "Aprende a testear excepciones y flujos de error en PHPUnit.",
          },
        ],
      },
      {
        id: "modulo-03",
        n: 3,
        t: "Tests de Integración",
        level: "avanzado",
        caption: "Verifica la conexión entre capas: BD, HTTP y servicios",
        desc: "Prueba la integración real: bases de datos con contenedores, test data con fixtures y seeds, HTTP y servicios externos, y pruebas contractuales entre consumidor y proveedor.",
        subtitle: "Las piezas funcionan solas; la integración demuestra que funcionan juntas.",
        objectives: [
          "Probar la capa de base de datos de forma aislada pero real",
          "Levantar Postgres con contenedores para tests",
          "Preparar test data con fixtures y seeds",
          "Simular HTTP y servicios externos de forma controlada",
          "Aplicar pruebas contractuales",
        ],
        lessons: [
          {
            id: "banco-postgres-y-contenedores",
            title: "Postgres con contenedores",
            duration: "15 min",
            level: "avanzado",
            category: "integración",
            cardText: "Levanta y derriba una Postgres real en segundos con Docker.",
            desc: "Configura Postgres en contenedores para tests de integración.",
          },
          {
            id: "pruebas-contractuales",
            title: "Pruebas contractuales",
            duration: "13 min",
            level: "avanzado",
            category: "contratos",
            cardText: "El pacto entre consumidor y proveedor que evita romper la integración.",
            desc: "Aplica pruebas contractuales para proteger la compatibilidad entre servicios.",
          },
          {
            id: "test-data-fixtures-y-seeds",
            title: "Test data, fixtures y seeds",
            duration: "14 min",
            level: "avanzado",
            category: "fixtures",
            cardText: "Datos de prueba reproducibles con fixtures y seeds controladas.",
            desc: "Genera y gestiona datos de prueba con fixtures y seeds.",
          },
          {
            id: "testing-bases-de-datos",
            title: "Testing de bases de datos",
            duration: "16 min",
            level: "avanzado",
            category: "integración",
            cardText: "Transacciones, migraciones y consultas probadas contra el motor real.",
            desc: "Escribe tests de integración para la capa de base de datos.",
          },
          {
            id: "testing-http-y-servicios-externos",
            title: "Testing HTTP y servicios externos",
            duration: "15 min",
            level: "avanzado",
            category: "integración",
            cardText: "Simula clientes HTTP y terceros sin golpear servicios reales.",
            desc: "Prueba la integración HTTP y los servicios externos de forma controlada.",
          },
        ],
      },
      {
        id: "modulo-04",
        n: 4,
        t: "Pruebas End-to-End",
        level: "avanzado",
        caption: "Flujos completos de la API al resultado final",
        desc: "Cubre el sistema de cabo a rabo: Supertest sobre la API, flujos completos, E2E con Playwright y ejecución de pruebas E2E dentro del CI.",
        subtitle: "Del clic del usuario al commit en la base de datos: todo junto por una vez.",
        objectives: [
          "Lanzar tu API y probarla end-to-end con Supertest",
          "Escribir flujos completos de API",
          "Usar Playwright para E2E realistas",
          "Integrar las pruebas E2E en el pipeline de CI",
        ],
        lessons: [
          {
            id: "e2e-con-playwright-api",
            title: "E2E con Playwright sobre la API",
            duration: "13 min",
            level: "avanzado",
            category: "e2e",
            cardText: "Playwright también prueba la API: peticiones, respuestas y flujos.",
            desc: "Usa Playwright para pruebas end-to-end sobre tu API.",
          },
          {
            id: "flujos-completos-api",
            title: "Flujos completos de API",
            duration: "14 min",
            level: "avanzado",
            category: "e2e",
            cardText: "Registro, login, CRUD y cierre: un viaje real por toda tu API.",
            desc: "Escribe flujos end-to-end completos de tu API.",
          },
          {
            id: "pruebas-e2e-en-ci",
            title: "Pruebas E2E en CI",
            duration: "14 min",
            level: "avanzado",
            category: "ci/cd",
            cardText: "Lanza las E2E en cada push sin romper la velocidad del pipeline.",
            desc: "Integra y mantiene las pruebas E2E dentro del CI.",
          },
          {
            id: "supertest-api",
            title: "Supertest para tu API",
            duration: "14 min",
            level: "avanzado",
            category: "e2e",
            cardText: "Peticiones HTTP reales a tu app Express para probar el flujo completo.",
            desc: "Prueba tu API end-to-end con Supertest sobre Express.",
          },
        ],
      },
      {
        id: "modulo-05",
        n: 5,
        t: "TDD y Buenas Prácticas",
        level: "avanzado",
        caption: "Escribe el test primero y deja que guíe el diseño",
        desc: "Desarrolla con Test-Driven Development: su filosofía, el ciclo Red, Green, Refactor, su aplicación a una API REST y al arreglo de bugs, con casos borde y errores bien cubiertos.",
        subtitle: "Primero la prueba, después el código: diseño guiado por especificación.",
        objectives: [
          "Entender la filosofía de TDD y por qué funciona",
          "Dominar el ciclo Red, Green, Refactor",
          "Aplicar TDD a una API REST completa",
          "Cubrir casos borde y errores en los tests",
          "Usar TDD para corregir bugs de forma segura",
        ],
        lessons: [
          {
            id: "casos-borde-y-errores",
            title: "Casos borde y errores",
            duration: "13 min",
            level: "avanzado",
            category: "buenas prácticas",
            cardText: "Nulos, vacíos, límites y errores: donde viven los bugs reales.",
            desc: "Cubre los casos borde y los flujos de error en tus pruebas.",
          },
          {
            id: "que-es-tdd",
            title: "¿Qué es TDD?",
            duration: "13 min",
            level: "avanzado",
            category: "tdd",
            cardText: "Test-Driven Development: la disciplina que escribe el test primero.",
            desc: "Introducción a TDD y a sus beneficios en el desarrollo de backend.",
          },
          {
            id: "red-green-refactor",
            title: "Red, Green, Refactor",
            duration: "15 min",
            level: "avanzado",
            category: "tdd",
            cardText: "Verlo fallar, verlo pasar, limpiarlo: el ritmo del TDD.",
            desc: "Domina el ciclo Red, Green, Refactor de TDD.",
          },
          {
            id: "tdd-en-api-rest",
            title: "TDD aplicado a una API REST",
            duration: "16 min",
            level: "avanzado",
            category: "tdd",
            cardText: "Endpoints creados desde la prueba: una API construida con TDD.",
            desc: "Construye una API REST paso a paso aplicando TDD.",
          },
          {
            id: "tdd-para-corregir-bugs",
            title: "TDD para corregir bugs",
            duration: "14 min",
            level: "avanzado",
            category: "tdd",
            cardText: "El bug como test que falla primero y código que lo arregla.",
            desc: "Usa TDD para corregir bugs sin reintroducir regresiones.",
          },
        ],
      },
      {
        id: "modulo-06",
        n: 6,
        t: "Métricas y CI/CD",
        level: "avanzado",
        caption: "Mide, integra y despliega con la calidad garantizada",
        desc: "Mide la cobertura de código, detecta regresiones, limpia los tests inestables y ejecuta el pipeline en GitHub Actions y GitLab CI.",
        subtitle: "Sin métricas y sin pipeline, el testing es solo una buena intención.",
        objectives: [
          "Medir y analizar la cobertura de código",
          "Detectar regresiones automáticamente",
          "Estabilizar los tests inestables",
          "Ejecutar los tests en GitHub Actions y GitLab CI",
        ],
        lessons: [
          {
            id: "cobertura-de-codigo",
            title: "Cobertura de código",
            duration: "13 min",
            level: "avanzado",
            category: "métricas",
            cardText: "Qué mide el %, sus límites y cómo usarlo sin autoengañarse.",
            desc: "Mide la cobertura de código y entiende sus limitaciones.",
          },
          {
            id: "detectando-regresiones",
            title: "Detectando regresiones",
            duration: "13 min",
            level: "avanzado",
            category: "métricas",
            cardText: "El cambio que rompe lo que ya funcionaba: cazado al vuelo.",
            desc: "Detecta regresiones de forma temprana en tu flujo de trabajo.",
          },
          {
            id: "integracion-con-github-actions",
            title: "Tests en GitHub Actions",
            duration: "14 min",
            level: "avanzado",
            category: "ci/cd",
            cardText: "Pipeline de GitHub Actions que ejecuta tu suite en cada push.",
            desc: "Configura y ejecuta tus tests en GitHub Actions.",
          },
          {
            id: "integracion-con-gitlab-ci",
            title: "Tests en GitLab CI",
            duration: "13 min",
            level: "avanzado",
            category: "ci/cd",
            cardText: "Etapas, runners y artefactos para correr tus tests en GitLab.",
            desc: "Configura y ejecuta tus tests en GitLab CI.",
          },
          {
            id: "limpiando-tests-inestables",
            title: "Limpiando tests inestables",
            duration: "13 min",
            level: "avanzado",
            category: "calidad",
            cardText: "Flaky tests que pasan a veces: cómo encontrarlos y destruirlos.",
            desc: "Identifica y elimina los tests inestables que minan la confianza.",
          },
        ],
      },
      {
        id: "modulo-07",
        n: 7,
        t: "Testing en CI/CD y calidad continua",
        level: "avanzado",
        caption: "Convierte la calidad en un proceso continuo dentro del pipeline",
        desc: "Lleva el testing al siguiente nivel: quality gates y umbrales de calidad, análisis estático y secretos, mutation testing, tests en paralelo y una estrategia integral de testing para el equipo.",
        subtitle: "No basta con tener tests: hay que gobernarlos, medirlos y acelerarlos.",
        objectives: [
          "Definir quality gates y umbrales de calidad en el pipeline",
          "Añadir análisis estático y detección de secretos al CI",
          "Aplicar mutation testing para medir la fortaleza de la suite",
          "Acelerar la ejecución con tests en paralelo",
          "Diseñar una estrategia de testing integral",
        ],
        lessons: [
          {
            id: "quality-gates-y-umbrales",
            title: "Quality gates y umbrales de calidad",
            duration: "12 min",
            level: "avanzado",
            category: "ci/cd",
            cardText: "Cobertura mínima, complejidad y fallos: si no cumples, no se despliega.",
            desc: "Define quality gates que bloqueen la entrega cuando la calidad no alcanza el umbral.",
            body: {
              intro: [
                "Un pipeline verde no significa calidad: basta con tener pocas pruebas. Los quality gates convierten la calidad en una condición objetiva del pipeline: si la suite no llega al umbral de cobertura o introduce regresiones, el despliegue se detiene ahí mismo.",
                "Esta lección cierra el curso con el salto de escribir tests a gobernar la calidad como proceso: gates, métricas de fortaleza, secretos, velocidad y estrategia integral.",
              ],
              def: {
                par: "Un quality gate es una condición automatizable que el pipeline evalúa para decidir si una entrega pasa: porcentaje de cobertura mínimo, límite de complejidad, tolerancia a fallos o violaciones de estilo.",
                porQue: "Las promesas manuales no protegen nada. El gate convierte la calidad en una puerta real que exige evidencia antes de desplegar.",
                cuando: "Usa gates en commits a ramas protegidas, en pull requests y antes de cada despliegue a staging o producción.",
              },
              concepts: [
                "Cobertura mínima: % de líneas o ramas que la suite debe cubrir para aprobar.",
                "Umbral de complejidad: evitar que la lógica inmanejable se cuele en el código.",
                "Zero policy en críticos: ningún test roto en la rama principal o el deploy se bloquea.",
                "El gate siempre tiene salida de emergencia auditable, nunca silenciosa.",
                "Los gates se definen en el pipeline, no en el buen ánimo del equipo.",
              ],
              basic: {
                p: "En GitHub Actions puedes bloquear el merge si la cobertura no llega al umbral. Usamos el reporte Cobertura para comparar el total de líneas cubiertas contra el objetivo.",
                code: [
                  "name: quality-gate",
                  "on: pull_request",
                  "jobs:",
                  "  gate:",
                  "    runs-on: ubuntu-latest",
                  "    steps:",
                  "      - uses: actions/checkout@v4",
                  "      - run: npm ci",
                  "      - run: npm test -- --coverage",
                  "      - name: Comprobar cobertura mínima del 80%",
                  "        run: |",
                  "          C=$(awk -F[:,] '/<coverage/{c+=$3} END{print c}' coverage-final.json)",
                  "          if (( C < 80 )); then",
                  "            echo \"Cobertura $C% por debajo del 80%\"; exit 1",
                  "          fi",
                ],
                out: "El job falla y bloquea el merge si la cobertura de la suite baja del 80 %.",
                lang: "bash",
              },
              intermediate: {
                p: "Los umbrales también controlan la complejidad del código: con PHPStan, SonarQube o Nx puedes fallar el build cuando la complejidad ciclomática supera el límite.",
                caption: "Gate de complejidad en el pipeline",
                code: [
                  "composer require --dev phpstan/phpstan",
                  "vendor/bin/phpstan analyse src --level=9 \\",
                  "  --rule='PhpStan\\Rules\\Complexity\\CyclomaticComplexityRule:5'",
                  "# El análisis fallará si una función supera complejidad 5,",
                  "# forzando a extraer métodos y a mantener la lectura clara.",
                ],
              },
              real: {
                p: "Un equipo maduro define gates por entorno: en staging la cobertura mínima es del 70 %, en producción del 85 %, y la rama principal no tolera ni un test inestable marcado. Cada rollback se anota como lección de calidad y se ajusta el gate.",
                ul: [
                  "Gates graduados por entorno: la exigencia crece donde el riesgo es mayor.",
                  "La cobertura es una métrica de humo: combínala con mutation testing y análisis estático.",
                  "Cada incumplimiento debe terminar en una incidencia con su remediación, no en un override silencioso.",
                ],
                code: [
                  "# Umbrales de calidad por entorno (dummied).",
                  "staging:   { coverage_min: 75, complejidad_max: 6, flaky_tolerancia: 1 }",
                  "produccion:{ coverage_min: 85, complejidad_max: 5, flaky_tolerancia: 0 }",
                  "# El pipeline elige el gate según la rama de destino.",
                ],
                nota: "El gate se evalúa con la misma suite que corre cada día: si el umbral no se cumple ni en local, mejor ajustarlo antes que liar el pipeline.",
              },
              expl: [
                "Un gate sin salida documentada genera odio: las excepciones deben aprobarse con un ticket y un plazo.",
                "La cobertura sola miente: combinar con mutantes y complejidad describe mejor la salud de la suite.",
                "Los gates por entorno evitan que la exigencia de producción ralentice el desarrollo en staging.",
                "El pipeline es el auditor silencioso: nota cada desvío sin intervención humana.",
                "Los umbrales se revisan periódicamente: no pueden quedar congelados para siempre.",
              ],
              errors: [
                "Fijar un umbral imposible y llenar el pipeline de overrides: el gate deja de proteger.",
                "Medir cobertura global en lugar de la de las zonas críticas.",
                "Permitir push directo a la rama protegida para esquivar el gate.",
              ],
              tips: [
                "Empieza por tener un informe de cobertura fiel y reutilizable en CI.",
                "Añade el gate en el pull request, no en el último paso de producción.",
                "Documenta cada umbral con su justificación y fecha de revisión.",
              ],
              exercise: [
                "Añade un quality gate de cobertura del 80 % a tu pipeline en GitHub Actions.",
                "Configura un límite de complejidad en tu analizador estático y corrige una función.",
                "Define los umbrales de tu entorno y documéntalos junto al pipeline.",
              ],
              summary: [
                "Los quality gates convierten la calidad en una condición objetiva del pipeline.",
                "Cobertura, complejidad y tolerancia a fallos se combinan como umbrales por entorno.",
                "Un gate con salida auditable protege más que diez promesas manuales.",
              ],
              lang: "bash",
              exampleFile: "quality-gates-y-umbrales",
              desc: "Define quality gates que bloqueen la entrega cuando la calidad no alcanza el umbral.",
            },
          },
          {
            id: "sast-y-deteccion-de-secretos",
            title: "SAST y detección de secretos",
            duration: "13 min",
            level: "avanzado",
            category: "seguridad",
            cardText: "Scanea tu código antes de desplegar: fallos estáticos y secretos colados.",
            desc: "Integra análisis estático (SAST) y detección de secretos en tu pipeline de CI.",
            body: {
              intro: [
                "La cobertura y los tests funcionales verifican el comportamiento esperado, pero no encuentran un fallo de validación en una función de búsqueda ni una API key de Stripe commitada. Para ese trabajo existe el análisis estático (SAST) y la detección de secretos.",
                "Estas herramientas se ejecutan en segundos sobre el diff, antes de que el código llegue a producción, y son la primera barrera contra clases enteras de vulnerabilidades y fugas de credenciales.",
              ],
              def: {
                par: "SAST (Static Application Security Testing) analiza el código fuente sin ejecutarlo para encontrar vulnerabilidades de patrón conocido: SQL injection, XSS, uso inseguro de criptografía y más. La detección de secretos busca claves y tokens accidentalmente versionados.",
                porQue: "Encontrar una vulnerabilidad al revisar el diff cuesta segundos; encontrarla en producción cuesta una brecha, una auditoría y una llamada de 3 de la mañana.",
                cuando: "Siempre en CI sobre cada push y pull request, e idealmente también en el código heredado que migra a la rama principal.",
              },
              concepts: [
                "SAST es análisis en reposo: lee patrones sin ejecutar el programa.",
                "DAST y SAST se complementan: el dinámico golpea la app en ejecución, el estático lee el código.",
                "La detección de secretos bloquea el commit si encuentra una credencial con formato conocido.",
                "Los falso-positivos minan la confianza: configura excepciones con justificación y verificación.",
                "Las herramientas líderes: Semgrep, SonarQube, Bandit (Python), gitleaks.",
              ],
              basic: {
                p: "Un escaneo de secretos en el pre-commit evita que la credencial llegue al repositorio. Con gitleaks y GitHub Actions puedes bloquear el merge si hay una fuga.",
                code: [
                  "name: detect-secrets",
                  "on: [pull_request]",
                  "jobs:",
                  "  scan:",
                  "    runs-on: ubuntu-latest",
                  "    steps:",
                  "      - uses: actions/checkout@v4",
                  "      - uses: gitleaks/gitleaks-action@v2",
                  "        env:",
                  "          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}",
                  "      - run: semgrep scan --config auto",
                ],
                out: "El pipeline se detiene si gitleaks detecta un secreto o semgrep encuentra una vulnerabilidad.",
                lang: "bash",
              },
              intermediate: {
                p: "Semgrep le permite escribir reglas propias. Un ejemplo pedagógico: prohibir la concatenación de SQL sin parámetros.",
                caption: "Regla SAST con Semgrep",
                code: [
                  "rules:",
                  "  - id: sql-injection-por-concat",
                  "    languages: [python]",
                  "    message: No concatenes SQL; usa consultas parametrizadas.",
                  "    severity: ERROR",
                  "    patterns:",
                  "      - pattern: execute(query + $USER)",
                  "    metadata:",
                  "      category: security",
                ],
              },
              real: {
                p: "Un equipo despliega con `git push` directo? Ningún gate le protege. Con SAST + secretos en el pull request, el fallo aparece antes de mergear y nunca sale de la rama de trabajo.",
                ul: [
                  "Ejecuta SAST en cada PR, no solo en la rama principal.",
                  "Configura excepciones con revisión y fecha de expiración.",
                  "Guarda los secretos en un gestor y rota cualquier credencial que toque git.",
                ],
                code: [
                  "# pipeline.yml - etapa de seguridad antes de los tests",
                  "stages: [security, test, deploy]",
                  "security:",
                  "  script:",
                  "    - gitleaks detect --verbose",
                  "    - semgrep scan --config auto --fail-on-rule",
                  "  except: ['tags']",
                ],
                nota: "Un secreto que se filtra se rota, siempre: borrar el commit no borra la copia de quien ya lo tiene.",
              },
              expl: [
                "SAST encuentra vulnerabilidades de patrón, pero no razona sobre la lógica de negocio: eso lo cubren los tests.",
                "La detección de secretos es la única barrera que evita que una credencial salga del repositorio.",
                "Los falso-positivos se gestionan con `--baseline` o anotaciones, pero siempre con revisión humana.",
                "SAST corre además de la suite, en la fase más barata del pipeline.",
                "La combinación SAST + cobertura + mutation testing describe mucho mejor la calidad real del código.",
              ],
              errors: [
                "Ejecutar SAST solo en el despliegue: para entonces la vulnerabilidad ya está integrada.",
                "Silenciar los avisos de secretos 'porque es un repo privado'.",
                "Ignorar los falso-positivos acumulados en vez de revisarlos periodِicamente.",
              ],
              tips: [
                "Empieza por la regla de SQL injection y XSS; después expande el catálogo.",
                "Conecta gitleaks al pre-commit y al pipeline: doble protección.",
                "Revisa los hallazgos SAST con etiquetas de severidad y prioriza los ERROR.",
              ],
              exercise: [
                "Configura gitleaks en tu pipeline y verifica que bloquea una clave de prueba.",
                "Escribe una regla de Semgrep que prohíba concatenar SQL en tu proyecto.",
                "Revisa los hallazgos de una pasada SAST y corrige el de mayor severidad.",
              ],
              summary: [
                "SAST encuentra vulnerabilidades de patrón sin ejecutar el código.",
                "La detección de secretos evita que la credencial salga del repositorio.",
                "SAST y secretos forman la primera barrera del pipeline, antes de los tests.",
              ],
              lang: "bash",
              exampleFile: "sast-y-deteccion-de-secretos",
              desc: "Integra análisis estático (SAST) y detección de secretos en tu pipeline de CI.",
            },
          },
          {
            id: "mutation-testing",
            title: "Mutation testing: midiendo la fortaleza",
            duration: "14 min",
            level: "avanzado",
            category: "testing",
            cardText: "Si mutando el código no se rompe ningún test, tu suite no vigila nada.",
            desc: "Aplica mutation testing para medir y mejorar la calidad real de tu suite.",
            body: {
              intro: [
                "La cobertura responde a una pregunta engañosa: ¿qué porcentaje de código se ejecuta? Pero ejecutar no es evaluar. Una suite puede cubrir el 100 % de las líneas y no darse cuenta de que una condición se ha invertido.",
                "El mutation testing resuelve ese hueco: introduce pequeños cambios en el código (mutantes), corre los tests, y mide cuántos de esos mutantes tus pruebas detectan. Cada mutante que sobrevive es un hueco en tu seguridad.",
              ],
              def: {
                par: "El mutation testing modifica el programa (cambia `>=` por `>`, invierte un booleano, borra una comprobación) y ejecuta la suite. Si los tests no detectan el cambio, el comportamiento mutado pasa de largo: hay un hueco de protección.",
                porQue: "Mientras la cobertura mide alcance, el mutation testing mide fuerza: te dice si tus asserts detectarían un cambio de comportamiento real.",
                cuando: "Úsalo periódicamente en módulos críticos (pagos, auth, reglas de negocio), no en cada PR, porque duplica o triplica el coste computacional.",
              },
              concepts: [
                "El ratio de mutación: porcentaje de mutantes que tus tests detectan.",
                "Los operadores de mutación: comparaciones, booleanos, valores, llamadas.",
                "Los mutantes equivalentes: el código cambiado que tiene el mismo comportamiento que el original.",
                "Infection (PHP) y Stryker (JS) son los frameworks de referencia.",
                "Cada mutante superviviente señala una aserción débil o un camino sin probar.",
              ],
              basic: {
                p: "Con Infection (PHP) corres la suite de mutación en una sola orden que te devuelve el MSI (Mutation Score Indicator).",
                code: [
                  "composer require --dev infection/infection",
                  "vendor/bin/infection --min-msi=70 --min-covered-msi=80",
                  "# Mutation Score Indicator (MSI) para el proyecto: 0-100%",
                  "# min-msi: si baja de 70, el comando sale con error.",
                ],
                out: "Mantaining a cierto umbral el comando termina con éxito; por debajo, falla y señala los supervivientes.",
                lang: "bash",
              },
              intermediate: {
                p: "El informe de Infection muestra cada mutante que sobrevivió. Vamos a escribir el test que lo captura en el ejemplo clásico de una validación de edad.",
                caption: "Reproduciendo y matando un mutante superviviente",
                code: [
                  "function mayor_de_edad(int $edad): bool",
                  "{",
                  "    return $edad >= 18;",
                  "}",
                  "// Mutante generado: return $edad > 18;",
                  "",
                  "public function test_edad_limite_es_mayor(): void",
                  "{",
                  "    $this->assertTrue(mayor_de_edad(18));",
                  "}",
                  "// El caso límite (18) elimina al mutante.",
                ],
              },
              real: {
                p: "En un equipo con una suite 'al 100 % de cobertura', el mutation testing reveló el problema real: el método de cálculo de descuento sobrevivía a la mutación porque los asserts comprobaban solo el resultado 'feliz'. Cada superviviente se convirtió en un test nuevo hasta alcanzar MSI 90 %.",
                ul: [
                  "Prioriza los módulos críticos: la fortaleza se gana donde el error es más caro.",
                  "Mata los supervivientes con casos límite y asserts más específicos.",
                  "Registra el MSI en el tiempo, como la cobertura, para ver la tendencia.",
                ],
                code: [
                  "# CI: etapa de mutation-testing solo en el módulo crítico",
                  "mutation:",
                  "  script:",
                  "    - vendor/bin/infection --filter=src/Domain/Precios",
                  "              --min-covered-msi=90 --threads=4",
                  "  allow_failure: false",
                ],
                nota: "Empieza con min-covered-msi (mutantes en código cubierto): el objetivo no es cubrir todo, es proteger lo que ya tocas.",
              },
              expl: [
                "Un mutante superviviente indica exactamente dónde tu suite no detectaría un error de comportamiento.",
                "Los operadores de mutación cubren comparaciones, booleanos, valores por defecto y condiciones de guarda.",
                "Los mutantes equivalentes generan falsos supervivientes: se marcan con anotación o excepción.",
                "El coste es alto: por eso el mutation testing se reserva para módulos críticos y ejecuciones periódicas.",
                "La combinación cobertura + MSI describe lo amplia y lo fuerte que es tu suite, no solo una métrica.",
              ],
              errors: [
                "Confundir MSI con cobertura: el primero mide fuerza, el segundo alcance.",
                "Ejecutar mutation testing sobre toda la base de código en cada push.",
                "Navegar los mutantes equivalentes manualmente sin herramienta de exclusión.",
              ],
              tips: [
                "Empieza por un solo módulo y una sola categoría de operador.",
                "Marka los equivalentes con `@codeCoverageIgnore` o la anotación de Infection.",
                "Corre la mutación en la rama antes de su release, no durante el desarrollo.",
              ],
              exercise: [
                "Instala Infection y calcula el MSI de tu módulo de pagos.",
                "Convierte dos mutantes supervivientes en tests nuevos con casos límite.",
                "Añade el job de mutation testing al pipeline solo para el módulo crítico.",
              ],
              summary: [
                "El mutation testing mide lo fuerte que es tu suite, no solo cuánto código toca.",
                "Cada mutante superviviente es un hueco real en la protección de tu lógica.",
                "Correlo periódicamente en los módulos críticos: es donde más rinde.",
              ],
              lang: "bash",
              exampleFile: "mutation-testing",
              desc: "Aplica mutation testing para medir y mejorar la calidad real de tu suite.",
            },
          },
          {
            id: "tests-en-paralelo-y-optimizacion",
            title: "Tests en paralelo y optimización del pipeline",
            duration: "12 min",
            level: "avanzado",
            category: "ci/cd",
            cardText: "Reparte la suite entre runners y baja de 20 minutos a 4.",
            desc: "Acelera tu pipeline repartiendo los tests en paralelo y optimizando la ejecución.",
            body: {
              intro: [
                "Cuando el proyecto crece, la suite pasa de minutos a decenas de minutos y el CI se convierte en el cuello de botella del equipo: cada push espera en la cola y el feedback llega tarde. La solución no es un runner más potente, sino repartir el trabajo.",
                "En esta lección vas a aprender a dividir los tests en shards paralelos, a usar la caché de dependencias y a mantener el pipeline estable pese a la concurrencia.",
              ],
              def: {
                par: "La paralelización del CI divide la suite en trozos (shards) que se ejecutan en runners simultáneos, reduciendo el tiempo total. La optimización suma caché de dependencias, orden de etapas y límites de tiempo.",
                porQue: "Un pipeline de 20 minutos desincentiva el push frecuente y retrasa el feedback: el tiempo de espera es coste real del desarrollo.",
                cuando: "Paraleliza cuando la suite supere los 5-10 minutos y el proyecto tenga runners disponibles o un presupuesto para ellos.",
              },
              concepts: [
                "Sharding: repartir la suite en N fragmentos ejecutados de forma independiente.",
                "Matriz de GitHub Actions: define la combinación de runner × shard.",
                "Caché de dependencias y de compilación: no reinstalar ni recompilar en cada shard.",
                "Los tests deben ser idempotentes y aislados para correr en paralelo.",
                "La lógica del fallo agrega: cuando un shard falla, el pipeline falla.",
              ],
              basic: {
                p: "Con GitHub Actions, una matriz reparte la suite en cuatro shards usando el atributo `--shard`. PHPUnit no lo trae nativo; aquí usamos pytest con su soporte, o un enumerador propio.",
                code: [
                  "jobs:",
                  "  test:",
                  "    runs-on: ubuntu-latest",
                  "    strategy:",
                  "      matrix:",
                  "        shard: [1, 2, 3, 4]",
                  "    steps:",
                  "      - uses: actions/checkout@v4",
                  "      - uses: actions/setup-python@v4",
                  "      - run: pip install pytest-xdist",
                  "      - run: pytest -n 4 --dist loadgroup",
                  "      - run: pytest -q",
                  "        if: matrix.shard == 1  # smoke en un solo shard",
                ],
                out: "Cuatro runners ejecutan porciones simultáneas y el informe agrega el resultado global.",
                lang: "bash",
              },
              intermediate: {
                p: "Para suite PHPUnit sin soporte nativo de sharding, repartimos por grupos: definimos grupos de test y cada job ejecuta uno.",
                caption: "Sharding por grupos en PHPUnit",
                code: [
                  "jobs:",
                  "  test:",
                  "    strategy:",
                  "      matrix:",
                  "        group: [domain, infra, api]",
                  "    steps:",
                  "      - uses: actions/checkout@v4",
                  "      - run: composer install --no-dev --prefer-dist",
                  "      - run: vendor/bin/phpunit --group \${{ matrix.group }}",
                  "      - uses: actions/upload-artifact@v4",
                  "        with:",
                  "          name: result-\${{ matrix.group }}",
                  "          path: build/junit.xml",
                ],
              },
              real: {
                p: "Un pipeline de 22 minutos terminó en 6 con 4 shards + caché. La clave fue hacer los tests independientes entre sí: fixture por shard, base de datos poblada aislada y almacenamiento temporal único.",
                ul: [
                  "Garantiza aislamiento: ningún test debe depender del orden de ejecución.",
                  "Usa caché de dependencias para que cada shard arranque con vendor instalado.",
                  "Mide los tiempos por test y equilibra los shards según duración, no según número de casos.",
                ],
                code: [
                  "# Plan de reparto por duración (se aprende ejecutando la suite)",
                  "tests/domain/*.php      -> shard 1  (~20% duración)",
                  "tests/infra/*.php       -> shard 2  (~30%)",
                  "tests/api/*.php         -> shard 3  (~25%)",
                  "tests/e2e/*.php         -> shard 4  (~25%)",
                ],
                nota: "La caché sigue con el proyecto: cuando cachead, asegúrate de invalidar por hash del lockfile.",
              },
              expl: [
                "El sharding reduce el tiempo de forma casi lineal hasta toparte con la inicialización de cada runner.",
                "El aislamiento es el requisito incómodo: los tests acoplados rompen en paralelo y revelan mal diseño.",
                "La caché de dependencias ahorra los 2-3 minutos de instalación en cada shard.",
                "Los resultados de cada shard se unifican en un solo artefacto para el informe.",
                "Equilibrar los shards por tiempo evita que un shard lento domine el total.",
              ],
              errors: [
                "Paralelizar tests que comparten el mismo estado global o la misma base de datos.",
                "Olvidar cachear las dependencias: cada shard paga la instalación completa.",
                "Creer que más shards siempre es mejor: la inicialización del runner es coste fijo.",
              ],
              tips: [
                "Mide primero: reparte por la duración real de cada archivo de test.",
                "Haz los fixtures por shard o por test, nunca compartidos.",
                "Deja un smoke test minimal que corra primero y avise antes de lanzar todo.",
              ],
              exercise: [
                "Reparte tu suite PHPUnit en tres grupos y crea la matriz en GitHub Actions.",
                "Añade caché tipo `actions/cache/setup-php` a tus jobs de test.",
                "Mide el tiempo antes y después: busca el punto donde añadir shards deja de ayudar.",
              ],
              summary: [
                "La paralelización real exige tests aislados e idempotentes.",
                "El sharding por duración y la caché de dependencias son las palancas más efectivas.",
                "El resultado se agrega: el pipeline falla si cualquier fragmento falla.",
              ],
              lang: "bash",
              exampleFile: "tests-en-paralelo",
              desc: "Acelera tu pipeline repartiendo los tests en paralelo y optimizando la ejecución.",
            },
          },
          {
            id: "estrategia-de-testing-integral",
            title: "Estrategia de testing integral",
            duration: "13 min",
            level: "avanzado",
            category: "estrategia",
            cardText: "Unitarias, integración, E2E, contratos y smoke: cómo encaja todo junto.",
            desc: "Diseña una estrategia de testing que reparta el esfuerzo y proteja al proyecto entero.",
            body: {
              intro: [
                "No basta con saber escribir tests: hay que decidir cuáles, en qué nivel, con qué prioridad y en qué orden. Una estrategia de testing dice qué capa protege el código crítico, qué se automatiza en CI y qué se deja para el humano.",
                "Esta lección final conecta lo aprendido en un mapa: la pirámide, los niveles, los entornos de ejecución y una estrategia sostenible para el día a día del equipo.",
              ],
              def: {
                par: "Una estrategia de testing es el plan que decide cómo se reparte el esfuerzo de prueba entre niveles (unitario, integración, E2E, contratos, humo), cómo se ejecuta en cada entorno y qué criterios abren la puerta al despliegue.",
                porQue: "Sin estrategia, el equipo testea por intuición: demasiado unitario en lo trivial, E2E lentos en lo esencial y huecos en el código crítico.",
                cuando: "Se define al inicio del proyecto, se revisa en cada hito grande y se ajusta cuando cambia la arquitectura o el riesgo.",
              },
              concepts: [
                "La pirámide ordena el esfuerzo: base ancha de unitarios baratos y cima pequeña de E2E caros.",
                "Test-driven de integración: cada nivel cubre las dudas que el anterior no puede responder.",
                "E2E para los flujos de dinero, login y datos sensibles: pocos pero no negociables.",
                "Los contratos prueban la compatibilidad sin lanzar el sistema completo.",
                "La estrategia se concreta en el pipeline: cada nivel tiene su etapa y su gate.",
              ],
              basic: {
                p: "El documento de estrategia mínimo que cualquier equipo puede escribir: un mapa de niveles con su objetivo, su frecuencia y su responsable.",
                code: [
                  "NIVEL             | OBJETIVO                   | FRECUENCIA       | HERAMIENTA",
                  "Unitario          | Lógica pura y dogmas       | cada commit      | PHPUnit",
                  "Integración      | BD, HTTP y servicios       | cada PR          | PHPUnit + Docker",
                  "Contratos        | Compatibilidad API        | cada merge       | Pact",
                  "E2E              | Flujos críticos           | cada release     | Playwright",
                  "Smoke            | Arranque y salud          | cada deploy      | curl + script",
                ],
                out: "Una tabla de una sola página que decide cuál es la prioridad de testing de tu equipo.",
                lang: "bash",
              },
              intermediate: {
                p: "Conviertes esa tabla en un pipeline por etapas: los niveles baratos corren antes y los caros solo cuando es imprescindible.",
                caption: "Pipeline por niveles en GitLab CI",
                code: [
                  "stages: [unit, integration, contracts, e2e, deploy]",
                  "unit:      { script: [\"phpunit --testsuite unit\"] }",
                  "integration: { script: [\"docker compose up -d db\",",
                  "                       \"phpunit --testsuite integration\"] }",
                  "contracts: { script: [\"pact-verifier\"] }",
                  "e2e:       { script: [\"playwright test e2e\"],",
                  "             when: manual }   # release manual",
                  "deploy:    { script: [\"deploy.sh\"], needs: [e2e] }",
                ],
              },
              real: {
                p: "Una plataforma de pagos reparte así su esfuerzo: unitarios para las tarifas, integración con la pasarela real en staging, contratos para no romper a los clientes de la API y E2E solo los flujos de checkout. El resultado: menos E2E frágiles y más bugs atrapados a nivel unitario.",
                ul: [
                  "Lo que falla caro se prueba antes: las reglas de negocio viven en los unitarios, no en la cima E2E.",
                  "Los contratos sustituyen a montones de E2E cuando hay terceros consumiendo tu API.",
                  "El nivel de cada test se decide por qué pregunta responde, no por dónde está el archivo.",
                ],
                code: [
                  "# Regla práctica de la estrategia:",
                  "# - si cambia el contrato  -> test de contrato",
                  "# - si cambia la lógica   -> test unitario",
                  "# - si cambia la integración -> test de integración",
                  "# - si cambia el flujo de negocio -> E2E",
                  "# - si cambia el deploy -> smoke test",
                ],
                nota: "La estrategia es dinámica: cuando un bug real prueba que faltaba un nivel, ese nivel entra en la estrategia.",
              },
              expl: [
                "Cada nivel cubre una pregunta distinta; sobredimensionar un nivel solo desplaza el esfuerzo, no lo elimina.",
                "La pirámide recomienda proporciones, no prohibiciones: pocos E2E, pero los críticos deben existir.",
                "Los entornos aíslan el objetivo: staging prueba integración, producción solo humo.",
                "La estrategia se convierte en pipeline: sin el nivel apropiado, el código no avanza a la siguiente etapa.",
                "Medir el tiempo por nivel ayuda a recalcular la asignación de esfuerzo con datos.",
              ],
              errors: [
                "Convertir toda la cobertura en E2E lentos que se prueban solo a fin de iteración.",
                "Dejar la lógica crítica sin unitarios y enterrarla en una cima E2E frágil.",
                "Olvidar el smoke test: un despliegue que no arranca no necesita 3000 asserts.",
              ],
              tips: [
                "Redacta la estrategia en una página y ponla en el repositorio.",
                "Revisa la proporción unitario/integración/E2E una vez al trimestre.",
                "Automatiza el smoke test en cada despliegue: es el primer aviso de un fallo total.",
              ],
              exercise: [
                "Escribe la tabla de niveles de tu proyecto con objetivo y herramienta.",
                "Mapea tu pipeline actual a esos niveles y detecta qué etapa falta.",
                "Define el flujo de bug: cuando falle en producción, ¿qué nivel se refuerza?",
              ],
              summary: [
                "Una estrategia de testing reparte el esfuerzo por nivel según la pregunta que responde.",
                "La pirámide y los contratos evitan el abuso de E2E lentos y frágiles.",
                "El pipeline convierte la estrategia en etapas obligatorias con sus gates.",
              ],
              lang: "bash",
              exampleFile: "estrategia-de-testing",
              desc: "Diseña una estrategia de testing que reparta el esfuerzo y proteja al proyecto entero.",
            },
          },
        ],
      },
    ],
  },
];