// _curriculum_fundamentos-backend.mjs
// Currículum del curso de Fundamentos de Backend.
// Exporta COURSES con todos los módulos y lecciones.
// Las lecciones existentes en disco se listan SIN body (no se regeneran);
// las nuevas (módulos 06 y 07) llevan body completo (11 secciones estándar + metadatos).

export const COURSES = [
  {
    slug: "fundamentos-backend",
    title: "Fundamentos de Backend",
    modules: [
      {
        id: "modulo-01",
        n: 1,
        t: "Introducción al Backend",
        level: "basico",
        caption: "Las primeras piezas: qué es el backend y cómo conversan cliente y servidor.",
        desc: "Descubre qué es el backend, qué hacen quienes lo construyen, la diferencia con el frontend y el ciclo de petición y respuesta que sostiene cualquier aplicación web.",
        subtitle: "Empieza por lo esencial: entender qué es el backend y de qué piezas se compone.",
        objectives: [
          "Definir qué es el backend y por qué existe",
          "Conocer el trabajo diario del desarrollador backend",
          "Diferenciar backend, frontend y full stack",
          "Explicar la arquitectura cliente-servidor",
          "Entender el ciclo de request y response",
        ],
        lessons: [
          {
            id: "que-es-backend",
            title: "¿Qué es Backend?",
            duration: "8 min",
            level: "basico",
            category: "fundamentos",
            cardText: "Descubre qué es el backend, qué pieza ocupa en un producto y por qué existe.",
            desc: "Aprende qué es el backend y qué papel juega en las aplicaciones.",
          },
          {
            id: "que-hace-un-desarrollador-backend",
            title: "¿Qué hace un desarrollador Backend?",
            duration: "8 min",
            level: "basico",
            category: "fundamentos",
            cardText: "Las responsabilidades diarias de quien construye y mantiene el lado servidor.",
            desc: "El día a día de un desarrollador backend y sus responsabilidades.",
          },
          {
            id: "backend-vs-frontend",
            title: "Backend vs Frontend",
            duration: "10 min",
            level: "basico",
            category: "fundamentos",
            cardText: "Dos caras del mismo producto: qué presenta el frontend y qué sostiene el backend.",
            desc: "Compara frontend y backend y entiende cómo se complementan.",
          },
          {
            id: "fullstack",
            title: "Full Stack",
            duration: "8 min",
            level: "basico",
            category: "fundamentos",
            cardText: "Ser Full Stack: dominar las dos orillas y cuándo merece la pena.",
            desc: "Qué significa ser Full Stack y qué supone dominar las dos partes.",
          },
          {
            id: "que-es-cliente",
            title: "Cliente",
            duration: "7 min",
            level: "basico",
            category: "arquitectura",
            cardText: "Quién pide: el cliente como origen de cada petición.",
            desc: "Aprende qué es el cliente en la arquitectura de una aplicación.",
          },
          {
            id: "que-es-servidor",
            title: "Servidor",
            duration: "7 min",
            level: "basico",
            category: "arquitectura",
            cardText: "Quién responde: el servidor procesa peticiones y entrega respuestas.",
            desc: "Qué es un servidor y cómo atiende las peticiones de los clientes.",
          },
          {
            id: "cliente-servidor",
            title: "Cliente-Servidor",
            duration: "12 min",
            level: "basico",
            category: "arquitectura",
            cardText: "El modelo que organiza toda la web: cómo conversan cliente y servidor.",
            desc: "El modelo cliente-servidor y cómo organiza la comunicación web.",
          },
          {
            id: "que-es-request",
            title: "Request",
            duration: "8 min",
            level: "basico",
            category: "http",
            cardText: "Anatomía de una petición: qué viaja del cliente al servidor.",
            desc: "Define qué es un request y qué contiene cada petición.",
          },
          {
            id: "que-es-response",
            title: "Response",
            duration: "8 min",
            level: "basico",
            category: "http",
            cardText: "Anatomía de una respuesta: estado, cabeceras y cuerpo.",
            desc: "Define qué es un response y qué partes lo componen.",
          },
          {
            id: "request-response",
            title: "Request y Response",
            duration: "10 min",
            level: "basico",
            category: "http",
            cardText: "El ciclo completo de petición y respuesta en una transacción web.",
            desc: "El ciclo completo de request y response en la web.",
          },
          {
            id: "aplicaciones-web",
            title: "Aplicaciones Web",
            duration: "8 min",
            level: "basico",
            category: "fundamentos",
            cardText: "Cómo se construyen y sirven las aplicaciones web modernas.",
            desc: "Qué son las aplicaciones web y cómo funcionan por dentro.",
          },
          {
            id: "aplicaciones-moviles-backend",
            title: "Aplicaciones Móviles y Backend",
            duration: "8 min",
            level: "basico",
            category: "fundamentos",
            cardText: "Lo que une a las apps móviles con el backend que las alimenta.",
            desc: "Cómo se relaciona una app móvil con su backend.",
          },
          {
            id: "arquitectura-basica",
            title: "Arquitectura Básica",
            duration: "10 min",
            level: "basico",
            category: "arquitectura",
            cardText: "Las piezas esenciales de una arquitectura backend por lo sano.",
            desc: "Las piezas básicas de la arquitectura de un backend.",
          },
        ],
      },
      {
        id: "modulo-02",
        n: 2,
        t: "Internet y la Web",
        level: "basico",
        caption: "Del cable a tu navegador: cómo viaja cada byte de Internet.",
        desc: "Internet, la web, el navegador, direcciones IP, puertos, DNS, dominios, hosting y CDN: el mapa completo de la infraestructura que sostiene cualquier backend.",
        subtitle: "Internet no es magia: es protocolos, direcciones y servidores conectados.",
        objectives: [
          "Comprender cómo funciona Internet y qué es la Web",
          "Entender el papel del navegador y del ISP",
          "Distinguir direcciones IP, puertos y DNS",
          "Conocer dominios, hosting, VPS y CDN",
          "Relacionar cada pieza con la vida de una petición",
        ],
        lessons: [
          {
            id: "como-funciona-internet",
            title: "¿Cómo funciona Internet?",
            duration: "12 min",
            level: "basico",
            category: "internet",
            cardText: "El viaje de tus datos: redes, routers y paquetes que forman Internet.",
            desc: "Cómo funciona Internet a nivel de redes y paquetes.",
          },
          {
            id: "que-es-la-web",
            title: "La Web",
            duration: "8 min",
            level: "basico",
            category: "internet",
            cardText: "La Web frente a Internet: el servicio que usas cada día sobre la red.",
            desc: "Diferencia entre Internet y la Web.",
          },
          {
            id: "que-es-un-navegador",
            title: "El Navegador",
            duration: "8 min",
            level: "basico",
            category: "internet",
            cardText: "Cómo pide y muestra el navegador las páginas que pides.",
            desc: "El papel del navegador dentro del ecosistema de la web.",
          },
          {
            id: "servidores",
            title: "Servidores",
            duration: "9 min",
            level: "basico",
            category: "internet",
            cardText: "Máquinas que atienden peticiones 24/7: el corazón técnico de la web.",
            desc: "Qué son los servidores y cómo sostienen la web.",
          },
          {
            id: "que-es-un-isp",
            title: "ISP",
            duration: "7 min",
            level: "basico",
            category: "internet",
            cardText: "El proveedor de Internet: tu puerta de entrada a la red.",
            desc: "Qué es un ISP y qué papel juega en tu conexión.",
          },
          {
            id: "que-es-una-ip",
            title: "Direcciones IP",
            duration: "9 min",
            level: "basico",
            category: "internet",
            cardText: "El identificador de cada dispositivo en la red.",
            desc: "Qué es una dirección IP y para qué sirve.",
          },
          {
            id: "ipv4",
            title: "IPv4",
            duration: "7 min",
            level: "basico",
            category: "internet",
            cardText: "El formato clásico de direcciones y por qué se quedó corto.",
            desc: "El protocolo IPv4 y sus limitaciones.",
          },
          {
            id: "ipv6",
            title: "IPv6",
            duration: "7 min",
            level: "basico",
            category: "internet",
            cardText: "La generación de direcciones que reemplaza a IPv4.",
            desc: "Qué es IPv6 y por qué sustituye a IPv4.",
          },
          {
            id: "puertos",
            title: "Puertos",
            duration: "8 min",
            level: "basico",
            category: "internet",
            cardText: "Cómo llega cada petición al servicio correcto de la máquina.",
            desc: "Qué son los puertos y cómo dirigen el tráfico.",
          },
          {
            id: "dns",
            title: "DNS",
            duration: "9 min",
            level: "basico",
            category: "internet",
            cardText: "La agenda global que traduce dominios a direcciones IP.",
            desc: "Cómo funciona el DNS y por qué es imprescindible.",
          },
          {
            id: "dominio",
            title: "Dominios",
            duration: "8 min",
            level: "basico",
            category: "internet",
            cardText: "Nombres legibles para las máquinas: registros y extensiones.",
            desc: "Qué son los dominios y cómo se registran.",
          },
          {
            id: "hosting",
            title: "Hosting",
            duration: "8 min",
            level: "basico",
            category: "internet",
            cardText: "Dónde viven los sitios web y qué se contrata realmente.",
            desc: "Qué es el hosting y qué contratas cuando alojas un sitio.",
          },
          {
            id: "vps",
            title: "VPS",
            duration: "8 min",
            level: "basico",
            category: "internet",
            cardText: "Un servidor dedicado virtual: el salto a tener control total.",
            desc: "Qué es un VPS y cuándo te conviene.",
          },
          {
            id: "cdn",
            title: "CDN",
            duration: "8 min",
            level: "basico",
            category: "internet",
            cardText: "Redes de distribución que acercan tu contenido a los usuarios.",
            desc: "Qué es un CDN y cómo acelera tu web.",
          },
        ],
      },
      {
        id: "modulo-03",
        n: 3,
        t: "HTTP",
        level: "basico",
        caption: "El idioma de la web: peticiones, respuestas y códigos HTTP.",
        desc: "HTTP y HTTPS, la anatomía de peticiones y respuestas, cabeceras, body, parámetros, cookies, caché y códigos de estado: el protocolo que todo backend debe dominar.",
        subtitle: "Cada intercambio entre cliente y servidor habla HTTP; aprende a leerlo.",
        objectives: [
          "Explicar qué es HTTP y qué aporta HTTPS",
          "Desglosar peticiones y respuestas HTTP",
          "Dominar headers, body y parámetros",
          "Entender cookies, caché y Content-Type",
          "Leer los códigos de estado del 1xx al 5xx",
        ],
        lessons: [
          {
            id: "que-es-http",
            title: "HTTP",
            duration: "10 min",
            level: "basico",
            category: "http",
            cardText: "El protocolo que habla la web: qué es y por qué importa.",
            desc: "Introducción al protocolo HTTP y su importancia.",
          },
          {
            id: "http-vs-https",
            title: "HTTPS",
            duration: "9 min",
            level: "basico",
            category: "http",
            cardText: "La capa de cifrado que protege todo lo que viaja con HTTP.",
            desc: "Qué es HTTPS y qué le aporta al protocolo HTTP.",
          },
          {
            id: "peticion-http",
            title: "Request HTTP",
            duration: "8 min",
            level: "basico",
            category: "http",
            cardText: "Línea inicial, cabeceras y cuerpo: las partes de una petición.",
            desc: "La anatomía de una petición HTTP.",
          },
          {
            id: "respuesta-http",
            title: "Response HTTP",
            duration: "8 min",
            level: "basico",
            category: "http",
            cardText: "Versión, status y cabeceras: cómo responde el servidor.",
            desc: "La anatomía de una respuesta HTTP.",
          },
          {
            id: "headers-http",
            title: "Headers HTTP",
            duration: "9 min",
            level: "basico",
            category: "http",
            cardText: "Los metadatos que negocian cada intercambio del protocolo.",
            desc: "Qué son los headers HTTP y cómo funcionan.",
          },
          {
            id: "body-http",
            title: "Body HTTP",
            duration: "8 min",
            level: "basico",
            category: "http",
            cardText: "El contenido que viaja en la petición: datos, JSON y formularios.",
            desc: "Qué es el body de una petición HTTP.",
          },
          {
            id: "query-parameters",
            title: "Query Parameters",
            duration: "9 min",
            level: "basico",
            category: "http",
            cardText: "Opciones de búsqueda y filtrado dentro de la propia URL.",
            desc: "Usa los query parameters para filtrar y parametrizar.",
          },
          {
            id: "path-parameters",
            title: "Path Parameters",
            duration: "9 min",
            level: "basico",
            category: "http",
            cardText: "Valores incrustados en la ruta para identificar recursos.",
            desc: "Identifica recursos con los path parameters.",
          },
          {
            id: "cookies",
            title: "Cookies",
            duration: "9 min",
            level: "basico",
            category: "http",
            cardText: "Pequeñas huellas que el servidor deja en el cliente.",
            desc: "Qué son las cookies y cómo se usan en HTTP.",
          },
          {
            id: "cache-control",
            title: "Cache-Control",
            duration: "9 min",
            level: "basico",
            category: "http",
            cardText: "Quién cachea, cuánto y qué reglas gobiernan la caché.",
            desc: "Controla la caché con el header Cache-Control.",
          },
          {
            id: "content-type",
            title: "Content-Type",
            duration: "9 min",
            level: "basico",
            category: "http",
            cardText: "El formato del contenido: cómo se anuncia y negocia.",
            desc: "El header Content-Type y la negociación de formato.",
          },
          {
            id: "status-codes",
            title: "Códigos de Estado HTTP",
            duration: "12 min",
            level: "basico",
            category: "http",
            cardText: "Del 1xx al 5xx: el idioma de los códigos de respuesta.",
            desc: "Domina los códigos de estado HTTP del 1xx al 5xx.",
          },
        ],
      },
      {
        id: "modulo-04",
        n: 4,
        t: "Arquitectura Web",
        level: "basico",
        caption: "Cómo se organiza un backend por dentro: capas, API y datos.",
        desc: "Del monolito al cliente-servidor, pasando por MVC, APIs, bases de datos, caché, reverse proxy y load balancer: el vocabulario de la arquitectura web.",
        subtitle: "El backend bien construido se sostiene sobre arquitecturas claras y decididas.",
        objectives: [
          "Comparar monolitos y arquitectura en capas",
          "Entender el patrón MVC",
          "Saber qué es una API y el papel del backend",
          "Conocer datos, caché, reverse proxy y load balancer",
          "Relacionar las piezas en un sistema real",
        ],
        lessons: [
          {
            id: "monolito",
            title: "Monolito",
            duration: "8 min",
            level: "basico",
            category: "arquitectura",
            cardText: "La aplicación de una sola pieza: simple al inicio, difícil de escalar.",
            desc: "Qué es una arquitectura monolítica y sus pros y contras.",
          },
          {
            id: "arquitectura-cliente-servidor",
            title: "Arquitectura Cliente-Servidor",
            duration: "10 min",
            level: "basico",
            category: "arquitectura",
            cardText: "El patrón estructural que domina el desarrollo backend.",
            desc: "El patrón de la arquitectura cliente-servidor.",
          },
          {
            id: "arquitectura-en-capas",
            title: "Arquitectura en Capas",
            duration: "9 min",
            level: "basico",
            category: "arquitectura",
            cardText: "Dividir la lógica en capas para mantener el orden.",
            desc: "Organiza el backend con una arquitectura en capas.",
          },
          {
            id: "mvc",
            title: "MVC",
            duration: "11 min",
            level: "basico",
            category: "arquitectura",
            cardText: "Modelo, Vista y Controlador: el patrón tradicional de las apps web.",
            desc: "El patrón MVC explicado para backend.",
          },
          {
            id: "que-es-una-api",
            title: "API",
            duration: "9 min",
            level: "basico",
            category: "api",
            cardText: "La interfaz que permite que programas hablen con programas.",
            desc: "Qué es una API y por qué estructura el backend.",
          },
          {
            id: "que-es-el-backend",
            title: "El Backend",
            duration: "8 min",
            level: "basico",
            category: "arquitectura",
            cardText: "La parte invisible del producto que procesa y guarda todo.",
            desc: "El backend como centro del procesamiento de datos.",
          },
          {
            id: "base-de-datos",
            title: "Base de Datos",
            duration: "9 min",
            level: "basico",
            category: "datos",
            cardText: "El almacén estructurado del backend: dónde vive la información.",
            desc: "El papel de la base de datos en el backend.",
          },
          {
            id: "cache",
            title: "Cache",
            duration: "9 min",
            level: "basico",
            category: "arquitectura",
            cardText: "Guardar lo ya calculado para responder sin repetir trabajo.",
            desc: "Qué es la caché y por qué acelera tu backend.",
          },
          {
            id: "reverse-proxy",
            title: "Reverse Proxy",
            duration: "9 min",
            level: "basico",
            category: "arquitectura",
            cardText: "El portero que recibe y reparte las peticiones hacia tus servicios.",
            desc: "Qué es un reverse proxy y qué aporta al sistema.",
          },
          {
            id: "load-balancer",
            title: "Load Balancer",
            duration: "10 min",
            level: "basico",
            category: "arquitectura",
            cardText: "Repartir la carga entre varios servidores para no caer nunca.",
            desc: "Cómo reparte el trabajo un load balancer.",
          },
        ],
      },
      {
        id: "modulo-05",
        n: 5,
        t: "Formatos y Comunicación",
        level: "basico",
        caption: "El contenido de cada petición: formatos y comunicación en tiempo real.",
        desc: "JSON, XML, form data, multipart, WebSockets y Server-Sent Events: cómo se codifica y se comunica la información entre cliente y servidor.",
        subtitle: "Los datos viajan en formatos concretos; saber cuál elegir es medio backend.",
        objectives: [
          "Diferenciar JSON y XML y cuándo usar cada uno",
          "Entender form data y multipart para formularios y archivos",
          "Conocer las comunicaciones en tiempo real",
          "Comparar WebSockets y Server-Sent Events",
          "Elegir el formato según el caso real",
        ],
        lessons: [
          {
            id: "json",
            title: "JSON",
            duration: "10 min",
            level: "basico",
            category: "formatos",
            cardText: "El formato de datos que habla toda la web moderna.",
            desc: "Domina JSON, el formato de datos estándar de la web.",
          },
          {
            id: "xml",
            title: "XML",
            duration: "9 min",
            level: "basico",
            category: "formatos",
            cardText: "El formato robusto que aún manda en muchos legados.",
            desc: "Qué es XML y cuándo sigue teniendo sentido.",
          },
          {
            id: "form-data",
            title: "Form Data",
            duration: "8 min",
            level: "basico",
            category: "formatos",
            cardText: "Los formularios clásicos codificados para viajar por HTTP.",
            desc: "Cómo viajan los datos de formulario por HTTP.",
          },
          {
            id: "multipart",
            title: "Multipart",
            duration: "9 min",
            level: "basico",
            category: "formatos",
            cardText: "Subir archivos y mezclarlos con datos en una misma petición.",
            desc: "Envía archivos y datos con el multipart/form-data.",
          },
          {
            id: "websockets",
            title: "WebSockets",
            duration: "10 min",
            level: "basico",
            category: "formatos",
            cardText: "Canal bidireccional y persistente: la comunicación en tiempo real.",
            desc: "Comunicación bidireccional en tiempo real con WebSockets.",
          },
          {
            id: "sse",
            title: "Server-Sent Events",
            duration: "9 min",
            level: "basico",
            category: "formatos",
            cardText: "El servidor empuja eventos a un cliente que solo escucha.",
            desc: "Empuja eventos del servidor al cliente con SSE.",
          },
        ],
      },
      {
        id: "modulo-06",
        n: 6,
        t: "APIs y HTTP en la práctica",
        level: "intermedio",
        caption: "De la teoría al teclado: diseña, prueba y consume APIs reales.",
        desc: "Diseña recursos con rutas coherentes, aplica los métodos HTTP con intención, prueba endpoint a endpoint con curl y aprende a consumir APIs de terceros con criterio.",
        subtitle: "Ya entiendes HTTP: ahora úsalo como un profesional.",
        objectives: [
          "Diseñar APIs de recursos con rutas consistentes",
          "Aplicar los métodos HTTP con su semántica correcta",
          "Probar endpoints reales con curl",
          "Consumir APIs externas con timeout, reintentos y paginación",
          "Situar REST frente a GraphQL y gRPC",
        ],
        lessons: [
          {
            id: "disenando-una-api-de-recursos",
            title: "Diseñando una API de recursos",
            duration: "12 min",
            level: "intermedio",
            category: "api",
            cardText: "Modela recursos, nombrarlos en plural y planifica las rutas de tu API antes de escribir código.",
            desc: "Diseña una API de recursos con nombres claros, plurales y rutas consistentes.",
            body: {
              intro: [
                "Detrás de cada API bien mantenida hay una decisión de diseño: qué recursos existen, cómo se llaman y cómo se relacionan. Antes de escribir una sola línea de servidor, el contrato debe estar claro.",
                "En este módulo vas a diseñar la API de una tienda: recursos, colecciones, identificadores y rutas anidadas, siguiendo las convenciones que usan los equipos de backend profesional.",
              ],
              def: {
                par: "Un recurso es una entidad (usuarios, pedidos, productos) que tu API expone mediante URLs consistentes y métodos HTTP estándar: la colección en plural y cada elemento con su identificador.",
                porQue: "Un buen diseño hace la API predecible: quien la consume sabe encontrar cualquier dato sin leer documentación a oscuras. Mal diseñada, cada endpoint es un mundo y el mantenimiento se dispara.",
                cuando: "Usa recursos cuando hay entidades con CRUD; evítalo cuando solo expones operaciones o cálculos, que piden otra aproximación.",
              },
              concepts: [
                "Los sustantivos en plural nombran colecciones: /usuarios, /pedidos.",
                "Cada elemento se alcanza con su id: /usuarios/42.",
                "Relaciones anidadas con sentido: /usuarios/42/pedidos.",
                "snake_case en el payload JSON y kebab-case en las URLs.",
                "Versiona en la URL: /v1/usuarios.",
              ],
              basic: {
                p: "Un mapa de rutas real para la colección de usuarios, expresado como estructura de datos.",
                code: [
                  "RUTAS = [",
                  '    ("GET", "/v1/usuarios", "listar_usuarios"),',
                  '    ("POST", "/v1/usuarios", "crear_usuario"),',
                  '    ("GET", "/v1/usuarios/{id}", "obtener_usuario"),',
                  '    ("PUT", "/v1/usuarios/{id}", "actualizar_usuario"),',
                  '    ("DELETE", "/v1/usuarios/{id}", "eliminar_usuario"),',
                  "]",
                  "",
                  "for metodo, ruta, handler in RUTAS:",
                  '    print(f"{metodo:6} {ruta:24} -> {handler}")',
                ],
                out: "GET    /v1/usuarios              -> listar_usuarios\nPOST   /v1/usuarios              -> crear_usuario\nGET    /v1/usuarios/{id}         -> obtener_usuario\nPUT    /v1/usuarios/{id}         -> actualizar_usuario\nDELETE /v1/usuarios/{id}         -> eliminar_usuario",
                lang: "python",
              },
              intermediate: {
                p: "Rutas anidadas con cabeza: usa solo las que aportan y evita enterrar demasiados niveles.",
                caption: "Anidación de recursos con criterio",
                code: [
                  "# Bien: pocos niveles y con sentido",
                  "GET /v1/tiendas/9/productos        # productos de la tienda 9",
                  "POST /v1/tiendas/9/productos       # alta de producto en tienda",
                  "",
                  "# Mal: anidacion infinita e innecesaria",
                  "GET /v1/tiendas/9/productos/7/stock/movimientos/historial",
                ],
              },
              real: {
                p: "En un ecommerce real, el equipo define primero el contrato (una tabla de rutas o un OpenAPI sencillo) y solo después escribe el código del servidor.",
                ul: [
                  "Nombra recursos desde el dominio del negocio, no desde la base de datos.",
                  "Mantén el mismo estilo en todos los endpoints: la consistencia vale más que la creatividad.",
                  "Documenta ejemplos reales de respuesta junto a cada ruta.",
                ],
                code: [
                  'def construir_url(entidad, id_entidad, subentidad=None, id_sub=None):',
                  '    base = f"/v1/{entidad}"',
                  "    if id_entidad:",
                  '        base += f"/{id_entidad}"',
                  "    if subentidad:",
                  '        base += f"/{subentidad}"',
                  "        if id_sub:",
                  '            base += f"/{id_sub}"',
                  "    return base",
                  "",
                  'print(construir_url("clientes", 42, "pedidos"))',
                  'print(construir_url("clientes", 42, "pedidos", 7))',
                ],
                nota: "Muchos frameworks generan las rutas a partir de estos nombres; un buen diseño inicial evita renombrar URLs (y romper clientes) más adelante.",
              },
              expl: [
                "La URL identifica el recurso; el método HTTP expresa la acción sobre él.",
                "Las colecciones en plural son el estándar de REST y de casi toda API pública.",
                "Anida solo cuando la relación se lee con naturalidad: cliente a pedidos sí; pedidos a cliente suele ir como campo.",
                "Versionar la API en la URL evita romper a los consumidores al evolucionar.",
                "Un recurso no es una tabla: agrupa bajo él lo que tenga sentido de negocio.",
              ],
              errors: [
                "Mezclar singular y plural entre endpoints (a veces /usuario, a veces /users).",
                "Anidar demasiado: /a/{id}/b/{id}/c/{id} en vez de aplanar con query params.",
                "Cambiar la forma de una URL sin versionar: rompe a los clientes de golpe.",
                "Nombrar recursos desde la base de datos en lugar del dominio.",
              ],
              tips: [
                "Define el contrato delante de todos antes de programar.",
                "Usa siempre el mismo formato de error en todas las rutas.",
                "Piensa primero en quien consumirá la API, no en tu base de datos.",
                "Revisa APIs famosas (GitHub, Stripe) para aprender convenciones.",
              ],
              exercise: [
                "Diseña las rutas de una API de biblioteca (libros, autores, préstamos).",
                "Extiende construir_url para aceptar filtros como query con ?categoria=tech.",
                "Escribe la tabla de rutas de una API de música y critica dos rutas anidadas.",
              ],
              summary: [
                "Los recursos se nombran en plural y se identifican por su id en la URL.",
                "La URL identifica recursos; los métodos HTTP definen la acción.",
                "Un contrato claro y consistente ahorra mantenimiento y rompe menos clientes.",
              ],
              lang: "python",
              exampleFile: "disenando-api-recursos",
              desc: "Diseña una API de recursos con nombres claros, plurales y rutas consistentes.",
            },
          },
          {
            id: "metodos-http-en-la-practica",
            title: "Métodos HTTP en la práctica",
            duration: "13 min",
            level: "intermedio",
            category: "http",
            cardText: "GET, POST, PUT, PATCH y DELETE: qué hace cada uno, cuándo usarlo y cómo se traducen a una API real.",
            desc: "Aplica los métodos HTTP GET, POST, PUT, PATCH y DELETE en una API real.",
            body: {
              intro: [
                "Ya sabes qué es HTTP; ahora toca lo que importa: usar cada método con intención. GET para leer, POST para crear, PUT y PATCH para modificar y DELETE para borrar.",
                "Un mismo recurso cambia de comportamiento según el método que reciba, y saber distinguirlos es lo que separa una API coherente de un caos.",
              ],
              def: {
                par: "Los métodos HTTP expresan la intención de una petición sobre un recurso: GET lee, POST crea, PUT reemplaza, PATCH modifica parcialmente y DELETE elimina.",
                porQue: "Los clientes (frontends, apps, otros servicios) confían en el significado de cada método para construir sus flujos; usarlos mal genera efectos inesperados y bugs difíciles de rastrear.",
                cuando: "GET para operaciones que no alteran estado; POST para crear y disparar acciones; el resto según la semántica exacta de la operación.",
              },
              concepts: [
                "GET es seguro: no debe cambiar el estado del servidor.",
                "POST no es idempotente: dos llamadas crean dos recursos.",
                "PUT reemplaza el recurso completo; PATCH modifica solo lo indicado.",
                "DELETE elimina el recurso y normalmente responde 200 o 204.",
                "OPTIONS y HEAD también existen: negocian capacidades y cabeceras.",
              ],
              basic: {
                p: "Un mini cliente que mapea cada método con su uso sobre una API.",
                code: [
                  'def llamar(metodo, url, datos=None):',
                  '    acciones = {',
                  '        "GET": f"leer {url}",',
                  '        "POST": f"crear en {url} con {datos}",',
                  '        "PUT": f"reemplazar {url} con {datos}",',
                  '        "PATCH": f"actualizar parcialmente {url} con {datos}",',
                  '        "DELETE": f"eliminar {url}",',
                  "    }",
                  '    return acciones.get(metodo, "Metodo no soportado")',
                  "",
                  'print(llamar("POST", "/v1/usuarios", {"nombre": "Ana"}))',
                  'print(llamar("GET", "/v1/usuarios/1"))',
                  'print(llamar("PATCH", "/v1/usuarios/1", {"rol": "admin"}))',
                ],
                out: "crear en /v1/usuarios con {'nombre': 'Ana'}\nleer /v1/usuarios/1\nactualizar parcialmente /v1/usuarios/1 con {'rol': 'admin'}",
                lang: "python",
              },
              intermediate: {
                p: "En el servidor, cada método responde de forma distinta al mismo recurso. Veamos el patrón con Express (Node).",
                caption: "Un recurso que responde según el método HTTP",
                code: [
                  'const estado = { nombre: "Ana", rol: "editor" };',
                  "",
                  "app.get('/v1/usuarios/:id', (req, res) => res.json(estado));",
                  "",
                  "app.put('/v1/usuarios/:id', (req, res) => {",
                  "  // reemplazo completo",
                  "  estado.nombre = req.body.nombre;",
                  "  estado.rol = req.body.rol;",
                  "  res.json(estado);",
                  "});",
                  "",
                  "app.patch('/v1/usuarios/:id', (req, res) => {",
                  "  // solo lo que llegue",
                  "  Object.assign(estado, req.body);",
                  "  res.json(estado);",
                  "});",
                ],
              },
              real: {
                p: "Un error clásico: usar PUT para cambiar solo el email puede borrar el resto de los campos. La semántica de cada método protege tus datos.",
                ul: [
                  "GET nunca debe disparar efectos secundarios: los crawlers y arañas lo usan masivamente.",
                  "En POST responde 201 Created; en DELETE, 204 No Content.",
                  "Rechaza métodos no soportados con 405 Method Not Allowed.",
                ],
                code: [
                  "import requests",
                  "",
                  "r = requests.patch(",
                  '    "https://api.ejemplo.com/v1/usuarios/1",',
                  '    json={"email": "ana@mail.com"},',
                  ")",
                  'print("PATCH ->", r.status_code, r.json())',
                  "",
                  'r = requests.delete("https://api.ejemplo.com/v1/usuarios/1")',
                  'print("DELETE ->", r.status_code)',
                ],
                nota: "La idempotencia de PUT y DELETE permite reintentar sin corromper el estado; POST, al no ser idempotente, requiere cuidado con los reintentos automáticos.",
              },
              expl: [
                "Cada método comunica intención: legibilidad para humanos y semántica para máquinas.",
                "PUT reemplaza todo el recurso; PATCH solo los campos enviados.",
                "DELETE es idempotente: borrar un recurso ya borrado responde 404 en lugar de duplicar el efecto.",
                "Los proxies y los cachés tratan los métodos según su definición: GET se cachea, POST no.",
                "El anti-patrón de usar POST para todo pierde toda la semántica de HTTP.",
              ],
              errors: [
                "Usar GET para eliminar o crear recursos (rompe caché y seguridad).",
                "Emplear POST donde corresponde PUT o PATCH y crear duplicados.",
                "Responder 200 en vez de 201 o 204: los clientes no distinguen la acción realizada.",
                "Mezclar PUT con PATCH y sobrescribir campos que no evolucionaron.",
              ],
              tips: [
                "Elige el status code que describa mejor la acción: 201 al crear, 204 al borrar.",
                "Si dudas entre PUT y PATCH, pregúntate: ¿reemplazo el recurso o solo una parte?",
                "Documenta la idempotencia de cada endpoint para que los clientes reintenten con seguridad.",
                "Usa constantes para los métodos en tu código, nunca strings sueltos.",
              ],
              exercise: [
                "Implementa un contador con GET para leer, POST para sumar y explica por qué se duplican los incrementos.",
                "Traduce cinco operaciones de una tienda al método HTTP correcto.",
                "Comprueba con curl qué status devuelve tu API al repetir un mismo DELETE dos veces.",
              ],
              summary: [
                "GET lee, POST crea, PUT reemplaza, PATCH modifica y DELETE elimina.",
                "La semántica correcta protege cachés, clientes y la integridad de los datos.",
                "Los status codes completan la historia: 201, 204, 404 o 405.",
              ],
              lang: "python",
              exampleFile: "metodos-http-practica",
              desc: "Aplica los métodos HTTP GET, POST, PUT, PATCH y DELETE en una API real.",
            },
          },
          {
            id: "probando-apis-con-curl",
            title: "Probando APIs con curl",
            duration: "11 min",
            level: "basico",
            category: "http",
            cardText: "Usa curl para hacer peticiones reales a una API: headers, body, status codes y autenticación básica.",
            desc: "Aprende a probar APIs desde la terminal con curl.",
            body: {
              intro: [
                "Tu mejor amigo para comprobar que una API funciona es curl: hace peticiones HTTP reales desde la terminal y muestra cada respuesta tal cual.",
                "Dominar curl te permite depurar endpoints, inspeccionar headers y automatizar comprobaciones sin abrir un navegador.",
              ],
              def: {
                par: "curl es una herramienta de línea de comandos que transfiere datos con protocolos de red, entre ellos HTTP, permitiéndote enviar peticiones completas y ver la respuesta en crudo.",
                porQue: "Antes de escribir tests automatizados necesitas ver qué devuelve tu API de verdad: curl te muestra status real, headers y cuerpo sin capas de abstracción.",
                cuando: "Úsalo en desarrollo para probar endpoints, depurar errores, reproducir un bug reportado o enviar peticiones con autenticación.",
              },
              concepts: [
                "curl URL hace una petición GET y muestra el cuerpo.",
                "-i muestra también las cabeceras de respuesta.",
                "-X METHOD fuerza un método concreto.",
                "-H agrega cabeceras; -d envía datos en el body.",
                "-o /dev/null -w nos deja ver solo el status code.",
              ],
              basic: {
                p: "La primera petición: un GET a una API pública y luego el mismo GET con cabeceras visibles.",
                code: [
                  "curl https://jsonplaceholder.typicode.com/users/1",
                  "",
                  "curl -i https://jsonplaceholder.typicode.com/users/1",
                ],
                out: "HTTP/2 200\ncontent-type: application/json; charset=utf-8\n{\n  \"id\": 1,\n  \"name\": \"Leanne Graham\",\n  ...\n}",
                lang: "bash",
              },
              intermediate: {
                p: "Enviar datos en el body y comprobar solo el status code de la respuesta.",
                caption: "POST con JSON y chequeo de estado",
                code: [
                  "curl -X POST https://jsonplaceholder.typicode.com/posts \\",
                  "  -H \"Content-Type: application/json\" \\",
                  "  -d '{\"title\": \"Mi primera API\", \"userId\": 1}'",
                  "",
                  "curl -o /dev/null -s -w \"%{http_code}\" https://jsonplaceholder.typicode.com/users/2",
                ],
              },
              real: {
                p: "Al consumir APIs protegidas suele haber un paso previo: obtener un token y reutilizarlo en cada petición mediante un header de autorización.",
                ul: [
                  "Empieza con -i o -v para ver todo lo que viaja por la red.",
                  "Respeta el endpoint según el entorno: usa la URL correcta en cada entorno.",
                  "Guarda las respuestas a archivo con -o para inspeccionarlas después.",
                ],
                code: [
                  "TOKEN=$(curl -s -X POST https://api.ejemplo.com/v1/auth/login \\",
                  "  -H \"Content-Type: application/json\" \\",
                  "  -d '{\"usuario\": \"ana\", \"password\": \"clave\"}' \\",
                  "  | jq -r .token)",
                  "",
                  "curl -s https://api.ejemplo.com/v1/usuarios/1 \\",
                  "  -H \"Authorization: Bearer $TOKEN\" | jq",
                ],
                nota: "jq formatea el JSON y hace legible la salida; en Windows puedes instalarlo o usar PowerShell.",
              },
              expl: [
                "Sin -X, curl usa GET o POST según haya datos con -d.",
                "-d envía application/x-www-form-urlencoded por defecto; usa -H para indicar JSON.",
                "-s silencia la barra de progreso y -w permite formatos de salida personalizados.",
                "-v muestra el diálogo completo TLS/HTTP, oro puro para depurar.",
                "En Windows, el escapado de comillas cambia; usa archivos con --data @archivo.json.",
              ],
              errors: [
                "Olvidar -H Content-Type: application/json y hacer que el servidor reciba texto plano.",
                "Usar comillas simples dentro de comillas simples en PowerShell.",
                "No escribir el JSON del -d como cadena válida y romper el body.",
                "Pedir en producción datos que solo existen en local y recibir 404.",
              ],
              tips: [
                "Crea scripts .curl en tu repo para las peticiones recurrentes.",
                "Empieza con GET y -i para ver el status real antes de debuggear el body.",
                "Usa --silent --show-error para no perder errores entre el ruido.",
                "Pasa credenciales por variables de entorno, nunca en el historial de la terminal.",
              ],
              exercise: [
                "Haz un GET a cualquier API pública y localiza el status en la respuesta.",
                "Crea un POST con JSON a jsonplaceholder y comprueba que responde 201.",
                "Repite una petición con -v y compara lo que ves con la versión sin -v.",
              ],
              summary: [
                "curl lanza peticiones HTTP reales y muestra la respuesta cruda.",
                "Métodos, cabeceras y body se controlan con -X, -H y -d.",
                "Ver el status code y las cabeceras acelera cualquier depuración.",
              ],
              lang: "bash",
              exampleFile: "probando-apis-curl",
              desc: "Aprende a probar APIs desde la terminal con curl.",
            },
          },
          {
            id: "consumir-apis-externas",
            title: "Consumiendo APIs externas",
            duration: "12 min",
            level: "intermedio",
            category: "api",
            cardText: "Integra servicios de terceros: paginación, rate limits, claves de acceso y manejo de errores.",
            desc: "Consume APIs de terceros con buenas prácticas: paginación, límites y errores.",
            body: {
              intro: [
                "Tu backend rara vez trabaja solo: cobra a través de una pasarela, envía correos por un proveedor y geolocaliza usuarios mediante una API externa.",
                "Consumir una API de terceros bien es tan importante como diseñar la tuya: respetar límites, paginar y tratar cada error.",
              ],
              def: {
                par: "Consumir una API externa es enviar peticiones a un servicio de otro equipo y transformar su respuesta en datos útiles para tu aplicación, respetando su contrato y sus límites.",
                porQue: "Casi todo producto de backend usa servicios externos, y hacerlo mal deriva en bloqueos por rate limit, datos inconsistentes y costes imprevistos.",
                cuando: "Úsalo cuando necesites una capacidad que no debes construir (pagos, emails, mapas); evita depender de APIs frágiles para tareas que controlas mejor internamente.",
              },
              concepts: [
                "Cada API externa tiene su propio contrato: lee la documentación primero.",
                "El rate limit limita peticiones por ventana; superarlo bloquea temporalmente.",
                "La paginación pide resultados en páginas; recórrelas todas para datasets completos.",
                "Las API keys viajan en headers como Authorization o X-API-Key.",
                "Los timeouts evitan que tu backend se quede colgado si el externo falla.",
              ],
              basic: {
                p: "Consumir una API con la librería requests de Python y manejar la posible falta de datos.",
                code: [
                  "import requests",
                  "",
                  "CLAVE_API = 'sk_demo_1234'",
                  "url = 'https://api.ejemplo.com/v1/productos'",
                  "",
                  "resp = requests.get(",
                  "    url,",
                  '    headers={"Authorization": f"Bearer {CLAVE_API}"},',
                  "    timeout=10,",
                  ")",
                  "",
                  "if resp.status_code == 200:",
                  "    productos = resp.json()",
                  '    print(f"Recibidos {len(productos)} productos")',
                  "else:",
                  '    print(f"Error {resp.status_code}: {resp.text}")',
                ],
                out: "Recibidos 25 productos",
                lang: "python",
              },
              intermediate: {
                p: "Recorrer todas las páginas con paginación respetando el contrato del proveedor.",
                caption: "Iterar por páginas hasta agotar los datos",
                code: [
                  "import requests",
                  "",
                  'def obtener_todo(url, headers):',
                  "    pagina = 1",
                  "    datos = []",
                  "    while True:",
                  "        resp = requests.get(url, headers=headers, params={\"page\": pagina}, timeout=10)",
                  '        if resp.status_code != 200:',
                  '            raise RuntimeError(f"Error en pagina {pagina}: {resp.status_code}")',
                  '        items = resp.json().get("items", [])',
                  "        datos.extend(items)",
                  '        if not resp.json().get("has_more", False):',
                  "            break",
                  "        pagina += 1",
                  "    return datos",
                  "",
                  'headers = {"Authorization": "Bearer sk_demo_1234"}',
                  'todos = obtener_todo("https://api.ejemplo.com/v1/pedidos", headers)',
                  'print(f"Total pedidos: {len(todos)}")',
                ],
              },
              real: {
                p: "Patrón robusto para producción: timeout, reintentos con backoff exponencial y respuesta degradada si el externo cae.",
                ul: [
                  "Define timeout siempre; sin él tu proceso puede colgarse para siempre.",
                  "Reintenta solo errores transitorios (5xx y timeouts), nunca los 4xx.",
                  "Cachea respuestas estables para no llamar dos veces seguidas al externo.",
                ],
                code: [
                  "import time, requests",
                  "",
                  "def pedir_con_reintentos(url, headers, intentos=3):",
                  "    for intento in range(intentos):",
                  "        try:",
                  "            r = requests.get(url, headers=headers, timeout=5)",
                  "            if r.status_code < 500:",
                  "                return r",
                  "        except requests.exceptions.Timeout:",
                  "            pass",
                  "        time.sleep(2 ** intento)  # backoff exponencial",
                  "    return None",
                  "",
                  'r = pedir_con_reintentos("https://api.ejemplo.com/v1/cotizaciones")',
                  'print("Servicio degradado" if r is None else r.json())',
                ],
                nota: "Los reintentos con backoff exponencial son el estándar en integraciones: espera 1s, 2s, 4s antes de desistir.",
              },
              expl: [
                "El contrato de una API externa (formato, límites, errores) es sagrado: documéntalo en tu código.",
                "Los 429 (rate limit) y 5xx son transitorios; 404 y 400 suelen ser bugs de tu integración.",
                "Paginación: sigue el mecanismo del propio servicio (page, offset o cursor).",
                "Nunca loguees las API keys ni las pongas en el código: ve a variables de entorno.",
                "Un API externa caída no debe tumbar tu servicio: aísla el fallo y responde de forma degradada.",
              ],
              errors: [
                "Olvidar el timeout y quedarse colgado ante un proveedor lento.",
                "Loggear la API key en los registros de error.",
                "No comprobar resp.status_code y parsear un cuerpo que llegó con error.",
                "Hacer llamadas en bucle sin respetar el rate limit (429).",
              ],
              tips: [
                "Empieza en sandbox si existe: mismo contrato, cero costes y datos reales.",
                "Guarda las credenciales en variables de entorno del servidor.",
                "Mide la latencia: si el externo tarda 800ms, tu endpoint también.",
                "Escribe un wrapper: si cambia la API externa, solo tocas un archivo.",
              ],
              exercise: [
                "Consume una API pública (por ejemplo de clima) y muestra el JSON formateado.",
                "Añade paginación manual a obtener_todo si el servicio no trae has_more.",
                "Escribe la versión con reintentos para un POST que devuelva 429.",
              ],
              summary: [
                "Consumir APIs externas exige respetar su contrato, sus límites y sus errores.",
                "Timeout y reintentos con backoff protegen tu backend de los fallos ajenos.",
                "Las claves se gestionan en el entorno y nunca en el código.",
              ],
              lang: "python",
              exampleFile: "consumir-apis-externas",
              desc: "Consume APIs de terceros con buenas prácticas: paginación, límites y errores.",
            },
          },
          {
            id: "rest-y-alternativas",
            title: "REST y sus alternativas: GraphQL y gRPC",
            duration: "12 min",
            level: "intermedio",
            category: "api",
            cardText: "Comprende cuándo REST no es suficiente y qué aportan GraphQL y gRPC.",
            desc: "Compara REST, GraphQL y gRPC y elige el estilo de API adecuado.",
            body: {
              intro: [
                "REST domina el ecosistema, pero no es la única respuesta. Cuando los clientes piden datos muy variados o el volumen interno es enorme, aparecen GraphQL y gRPC.",
                "Elegir bien el estilo de API depende del contexto: aquí verás qué resuelve cada uno y cuándo aplicarlo.",
              ],
              def: {
                par: "REST organiza recursos con URLs y métodos HTTP; GraphQL deja que el cliente pida exactamente los campos que necesita mediante un solo endpoint; gRPC llama a métodos remotos con contratos binarios muy eficientes.",
                porQue: "El transporte define la experiencia de tus clientes: elegir el protocolo adecuado reduce tiempo de carga, tráfico de red y complejidad de mantenimiento.",
                cuando: "REST para APIs públicas e integraciones simples; GraphQL cuando hay muchos clientes con necesidades distintas; gRPC para comunicación interna entre microservicios con alto rendimiento.",
              },
              concepts: [
                "REST: recursos, verbos HTTP y JSON; simple y universal.",
                "GraphQL: un único endpoint /graphql y el cliente elige su esquema.",
                "gRPC: define métodos en un .proto y usa HTTP/2 con mensajes binarios.",
                "El overfetching de REST frente al control fino de GraphQL.",
                "gRPC sobresale en latencia baja y streaming entre servicios.",
              ],
              basic: {
                p: "Un resumen ejecutable para comparar los tres estilos de una vez.",
                code: [
                  "estilos = {",
                  '    "REST": "recursos + metodos HTTP + JSON (API publica)",',
                  '    "GraphQL": "un endpoint, el cliente elige campos",',
                  '    "gRPC": "metodos remotos binarios sobre HTTP/2 (interno)",',
                  "}",
                  "",
                  "for estilo, desc in estilos.items():",
                  '    print(f"{estilo:9} -> {desc}")',
                ],
                out: "REST      -> recursos + metodos HTTP + JSON (API publica)\nGraphQL   -> un endpoint, el cliente elige campos\ngRPC      -> metodos remotos binarios sobre HTTP/2 (interno)",
                lang: "python",
              },
              intermediate: {
                p: "GraphQL resuelve el overfetching: cada cliente pide solo lo que necesita en una sola petición.",
                caption: "Consulta GraphQL con selección de campos",
                code: [
                  "query PedidoCompleto($id: ID!) {",
                  "  pedido(id: $id) {",
                  "    id",
                  "    total",
                  "    cliente { nombre email }",
                  "    articulos { nombre cantidad }",
                  "  }",
                  "}",
                  "",
                  "# responde solo los campos pedidos, en una sola peticion",
                ],
              },
              real: {
                p: "En un sistema de microservicios, el equipo suele hablar internamente con gRPC y exponer al exterior una API REST (o GraphQL) que traduce las llamadas.",
                ul: [
                  "REST para el borde público y gRPC para la red interna.",
                  "GraphQL brilla en apps móviles con pantallas que necesitan datos muy distintos.",
                  "Empieza simple: REST hasta que duela; llega a GraphQL o gRPC cuando haya razón.",
                ],
                code: [
                  "# contrato .proto de un microservicio de catalogo",
                  "syntax = \"proto3\";",
                  "",
                  "service Catalogo {",
                  "  rpc ListarProductos(Query) returns (stream Producto);",
                  "}",
                  "",
                  "message Producto {",
                  "  string id = 1;",
                  "  string nombre = 2;",
                  "  double precio = 3;",
                  "}",
                ],
                nota: "Los protocol buffers serializan de forma binaria: hasta diez veces más rápido que JSON en tráfico interno, ideal para streaming.",
              },
              expl: [
                "REST triunfa por simplicidad: cualquier cliente con HTTP lo entiende.",
                "GraphQL centraliza el esquema y evita versionar un endpoint por cada campo nuevo.",
                "gRPC mejora rendimiento y tipado fuerte, pero es menos amigable para navegadores.",
                "La complejidad se paga: GraphQL añade consultas peligrosas (recursión, N+1) y gRPC herramientas de depuración menos directas.",
                "La decisión correcta depende del contexto, no de la moda: empieza por REST.",
              ],
              errors: [
                "Elegir GraphQL por moda sin necesidad real de su flexibilidad.",
                "Usar gRPC en el borde público y complicar la vida a tus clientes.",
                "No proteger GraphQL con límites de profundidad y abrirte a consultas abusivas.",
                "Cambiar de estilo de API sin medir primero el coste de la migración.",
              ],
              tips: [
                "Mide primero: ¿hay overfetching real? ¿importa de verdad la latencia?",
                "Mantén el contrato documentado en cualquier estilo (OpenAPI o schema de GraphQL).",
                "Los microservicios internos se benefician de gRPC; las APIs públicas, de REST.",
                "No mezcles estilos en la misma familia de endpoints sin una razón clara.",
              ],
              exercise: [
                "Escribe la consulta GraphQL para los cinco últimos pedidos con su cliente.",
                "Define un .proto con dos métodos para un chat.",
                "Enlista tres señales de que un proyecto debería adoptar GraphQL.",
              ],
              summary: [
                "REST es simple y universal; GraphQL da control fino de campos; gRPC da rendimiento.",
                "El estilo se elige por contexto, no por moda.",
                "Es habitual combinar: gRPC interno con REST o GraphQL público.",
              ],
              lang: "python",
              exampleFile: "rest-y-alternativas",
              desc: "Compara REST, GraphQL y gRPC y elige el estilo de API adecuado.",
            },
          },
        ],
      },
      {
        id: "modulo-07",
        n: 7,
        t: "De cero a producción",
        level: "intermedio",
        caption: "El viaje completo: entorno, configuración, logs, seguridad y primer despliegue.",
        desc: "Prepara un entorno reproducible, configura el backend con variables de entorno, registra actividad con criterio, aplica seguridad básica y lleva tu primera API a producción.",
        subtitle: "Todo lo anterior suena bien sobre el papel: ahora toca que funcione de verdad.",
        objectives: [
          "Montar un entorno de desarrollo reproducible",
          "Configurar el backend con variables de entorno",
          "Registrar errores y actividad con logging estructurado",
          "Aplicar la seguridad básica mínima",
          "Desplegar tu primera API en producción",
        ],
        lessons: [
          {
            id: "entorno-de-desarrollo-backend",
            title: "Configurando tu entorno de desarrollo",
            duration: "10 min",
            level: "basico",
            category: "entorno",
            cardText: "Editor, terminal, gestor de paquetes y runtime: monta un entorno de backend cómodo y reproducible.",
            desc: "Prepara un entorno de desarrollo de backend completo y reproducible.",
            body: {
              intro: [
                "Antes de programar el backend necesitas un lugar donde probar: editor, terminal, runtime y una forma de ejecutar tu API localmente.",
                "Un entorno bien montado te ahorra horas: menos fricción para empezar y la misma experiencia en cualquier máquina.",
              ],
              def: {
                par: "El entorno de desarrollo es el conjunto de herramientas (editor, terminal, runtime, gestor de dependencias) con el que escribes, ejecutas y depuras tu código de backend en local.",
                porQue: "Una configuración reproducible garantiza que tu código funcione igual en tu portátil, en el de un compañero y en producción, sin sorpresas.",
                cuando: "Configúralo al empezar cada proyecto (versiones declaradas y dependencias fijadas) y arréglalo cuando el resto del equipo no consiga reproducir tu entorno.",
              },
              concepts: [
                "El runtime (Node, Python, PHP) debe quedar fijado a una versión.",
                "El gestor de dependencias (npm, pip, composer) genera un lockfile.",
                "El editor con terminal integrada y atajos: VS Code es el estándar.",
                "El servidor de desarrollo con recarga en caliente acelera las pruebas.",
                ".editorconfig y linters unifican el estilo del equipo.",
              ],
              basic: {
                p: "Fijar la versión del runtime y declarar los comandos de arranque.",
                code: [
                  "# node -v   (o python --version / php -v)",
                  "node -v",
                  "",
                  "# crear package.json e instalar dependencias",
                  "npm init -y",
                  "npm install express",
                  "",
                  "# arranque del servidor de desarrollo definido en package.json",
                  "npm run dev",
                ],
                out: "v20.11.0\nadded 70 packages in 3s\n> servidor de desarrollo escuchando en :3000",
                lang: "bash",
              },
              intermediate: {
                p: "Declarar la versión del engine y fijar las dependencias con lockfile.",
                caption: "Versiones en package.json y lockfile",
                code: [
                  "{",
                  '  "name": "api-tienda",',
                  '  "engines": { "node": ">=20" },',
                  '  "scripts": {',
                  '    "dev": "node --watch src/index.js",',
                  '    "start": "node src/index.js"',
                  "  }",
                  "}",
                  "",
                  "# el package-lock.json fija las versiones exactas",
                  "npm ci",
                ],
              },
              real: {
                p: "En un equipo real se usa .nvmrc, dependencias fijadas y, a menudo, contenedores para que todo el mundo (y el CI) reproduzca el mismo entorno.",
                ul: [
                  "Versiona el lockfile siempre: garantiza dependencias idénticas.",
                  "Usa contenedores si tu servicio depende de Redis o de una base de datos local.",
                  "Define claramente el comando de arranque en la documentación del repo.",
                ],
                code: [
                  "# .nvmrc: versión de Node que debe usar el equipo",
                  "20",
                  "",
                  "# ENV básico en local para arrancar sin configurar nada más",
                  'echo "PORT=3000" > .env',
                  'echo "DATABASE_URL=postgres://local:local@localhost:5432/tienda" >> .env',
                ],
                nota: "El .env no se versiona; en su lugar se sube un .env.example con las claves vacías.",
              },
              expl: [
                "Un entorno reproducible es el primer paso hacia despliegues predecibles.",
                "El lockfile elimina la coordenada depende de la máquina.",
                "Declarar engines del runtime avisa antes de que un cambio de versión rompa todo.",
                "El servidor con recarga en caliente (watch) acorta el ciclo de pruebas.",
                "Los contenedores resuelven el síndrome en mi máquina funciona.",
              ],
              errors: [
                "Olvidar subir el lockfile y que cada uno instale versiones distintas.",
                "Versionar el .env y exponer credenciales en el repositorio.",
                "Ejecutar todo como superusuario en local.",
                "Instalar dependencias globales cuando deberían ser del proyecto.",
              ],
              tips: [
                "Fija versiones de runtime y dependencias desde el primer día.",
                "Nunca pongas credenciales reales en archivos del repo.",
                "Arranca el servidor con watch para iterar rápido.",
                "Documenta: requisitos, instalación y comando de arranque.",
              ],
              exercise: [
                "Crea un proyecto nuevo con npm init y añade el script dev con watch.",
                "Escribe un .nvmrc y comprueba qué versión usarías con nvm use.",
                "Añade un paso de CI que instale con npm ci y arranque con npm start.",
              ],
              summary: [
                "Un entorno reproducible fija runtime, dependencias y arranque.",
                "El lockfile y las versiones declaradas evitan el en mi máquina funciona.",
                "Documenta el mínimo comando para que cualquiera levante el proyecto.",
              ],
              lang: "bash",
              exampleFile: "entorno-desarrollo-backend",
              desc: "Prepara un entorno de desarrollo de backend completo y reproducible.",
            },
          },
          {
            id: "variables-de-entorno-y-configuracion",
            title: "Variables de entorno y configuración",
            duration: "11 min",
            level: "basico",
            category: "configuracion",
            cardText: "Mantén credenciales y ajustes fuera del código con variables de entorno y archivos .env.",
            desc: "Gestiona la configuración del backend con variables de entorno.",
            body: {
              intro: [
                "Un API bien diseñada se configura sin tocar código: puerto, URL de base de datos, claves de API externas. Todo eso son variables de entorno.",
                "Separar configuración del código hace el proyecto portable: el mismo binario corre en local, staging y producción con distintas variables.",
              ],
              def: {
                par: "Una variable de entorno es un valor que el sistema operativo ofrece al proceso (puerto, URLs, claves) y que el backend lee en tiempo de ejecución, sin estar en el código fuente.",
                porQue: "Mantiene los secretos fuera del repositorio, permite configurar cada entorno sin recompilar y evita que una clave se filtre por un commit descuidado.",
                cuando: "Usa variables de entorno para todo lo que cambia entre entornos: credenciales, URLs, flags y niveles de log; evita usarlas para valores que siempre son iguales.",
              },
              concepts: [
                ".env es un archivo local no versionado con valores de desarrollo.",
                ".env.example es la versión versionada con claves y valores vacíos.",
                "process.env (Node) o os.environ (Python) leen cada variable.",
                "Las variables reales del sistema tienen precedencia sobre el .env.",
                "Valida la configuración al arrancar: falla rápido si falta una clave crítica.",
              ],
              basic: {
                p: "Leer configuración sin codificar ningún valor en el código.",
                code: [
                  "// Node.js",
                  'import "dotenv/config";',
                  "",
                  "const puerto = process.env.PORT ?? 3000;",
                  "const dbUrl = process.env.DATABASE_URL;",
                  "",
                  "if (!dbUrl) {",
                  '  console.error("Falta DATABASE_URL: revisa tu .env");',
                  "  process.exit(1);",
                  "}",
                  "",
                  'console.log(`API en :${puerto} conectada a la base de datos`);',
                ],
                out: "API en :3000 conectada a la base de datos",
                lang: "js",
              },
              intermediate: {
                p: "Los archivos .env de desarrollo y la versión de referencia que sí se versiona.",
                caption: "Archivos .env y .env.example de referencia",
                code: [
                  "# .env (NO versionar)",
                  "PORT=3000",
                  "DATABASE_URL=postgres://usuario:pass@localhost:5432/tienda",
                  "API_CLIMA_KEY=sk_live_xxxx",
                  "",
                  "# .env.example (versionar con claves vacías)",
                  "PORT=",
                  "DATABASE_URL=",
                  "API_CLIMA_KEY=",
                ],
              },
              real: {
                p: "En producción las variables las inyecta la plataforma (cloud, CI, contenedor), no un archivo .env: la misma imagen configura entornos distintos.",
                ul: [
                  "Nunca subas .env; usa .env.example y descríbelo en el README.",
                  "Rota de inmediato cualquier clave comprometida; no basta con borrarla.",
                  "Prefiere variables nativas o secrets del proveedor a archivos de configuración.",
                ],
                code: [
                  "# Comando de arranque del contenedor con variables inyectadas",
                  "docker run -p 3000:3000 \\",
                  "  -e PORT=8080 \\",
                  "  -e DATABASE_URL=postgres://prod:xxxx@db.interno:5432/tienda \\",
                  "  mi-api:1.0.0",
                ],
                nota: "En GitHub Actions los secrets se referencian como ${{ secrets.DATABASE_URL }} y nunca aparecen en el log.",
              },
              expl: [
                "La regla de los Doce-Factor: la configuración vive fuera del código.",
                ".env es solo para desarrollo; producción usa el entorno del sistema.",
                "Valida al arranque: si falta una variable crítica, termina con un error claro.",
                "Prefija las variables por dominio: API_*, DB_*, LOG_*.",
                "Los defaults solo sirven para valores inocuos (puerto); nunca para secretos.",
              ],
              errors: [
                "Versionar .env y exponer la clave de producción.",
                "Poner secretos en el código ante la falta de variables de entorno.",
                "No validar la configuración y arrancar medio roto.",
                "Confiar en defaults para credenciales de producción.",
              ],
              tips: [
                "Añade .env a .gitignore desde el primer commit del proyecto.",
                "Agrupa variables por dominio y documenta cada una en .env.example.",
                "Falla rápido y con un mensaje claro si falta configuración imprescindible.",
                "En producción usa los secrets del proveedor, no archivos en el repo.",
              ],
              exercise: [
                "Crea tu .env con tres variables y haz que tu API las lea.",
                "Escribe el .env.example del proyecto y complétalo en el README.",
                "Simula la falta de DATABASE_URL y comprueba que tu API termina con un error claro.",
              ],
              summary: [
                "La configuración vive en variables de entorno, no en el código.",
                ".env para desarrollo; secrets del sistema para producción.",
                "Valida al arranque y rota cualquier clave comprometida.",
              ],
              lang: "js",
              exampleFile: "variables-de-entorno",
              desc: "Gestiona la configuración del backend con variables de entorno.",
            },
          },
          {
            id: "errores-y-logging-backend",
            title: "Errores y registro de actividad: logging",
            duration: "12 min",
            level: "intermedio",
            category: "observabilidad",
            cardText: "Registra lo que importa y aprende a leer tus logs para depurar cualquier fallo.",
            desc: "Aplica buenas prácticas de logging y manejo de errores en el backend.",
            body: {
              intro: [
                "Cuando tu API falla en producción no puedes abrirla con el depurador: lees logs. Por eso registrar la actividad correcta es una habilidad imprescindible del backend.",
                "Logging no es escribir prints por todas partes: es emitir eventos estructurados y con nivel, en su punto justo.",
              ],
              def: {
                par: "El logging registra eventos del sistema (peticiones, errores, advertencias) en un formato estructurado y con nivel, para diagnosticar el comportamiento del backend en cualquier entorno.",
                porQue: "Sin logs, un fallo en producción solo se ve cuando el usuario lo reporta; con logs estructurados encuentras la causa en minutos.",
                cuando: "Loguea entradas y salidas de operaciones críticas, errores y flujos de dinero o datos sensibles; no loguees contraseñas, tokens ni datos personales innecesarios.",
              },
              concepts: [
                "Niveles: debug < info < warn < error < fatal; filtra según entorno.",
                "Un log estructurado es JSON: parseable, buscable y con contexto.",
                "El request_id conecta todas las líneas de una misma petición.",
                "info documenta el flujo normal; error documenta lo anormal.",
                "Los secretos jamás van en los logs.",
              ],
              basic: {
                p: "Logging estructurado con un helper sencillo en Python.",
                code: [
                  "import datetime, json",
                  "",
                  "def log(nivel, mensaje, **ctx):",
                  "    entrada = {",
                  '        "ts": datetime.datetime.now().isoformat(),',
                  '        "nivel": nivel,',
                  '        "mensaje": mensaje,',
                  "        **ctx,",
                  "    }",
                  "    print(json.dumps(entrada))",
                  "",
                  'log("info", "pedido creado", pedido_id=42, total=199.99)',
                  'log("error", "fallo al cobrar", pedido_id=42, proveedor="stripe")',
                ],
                out: '{"ts": "2026-09-24T10:15:00", "nivel": "info", "mensaje": "pedido creado", "pedido_id": 42, "total": 199.99}\n{"ts": "2026-09-24T10:15:00", "nivel": "error", "mensaje": "fallo al cobrar", "pedido_id": 42, "proveedor": "stripe"}',
                lang: "python",
              },
              intermediate: {
                p: "Incluir un request_id en cada log para reconstruir el camino completo de una petición.",
                caption: "Contexto de correlación en cada entrada",
                code: [
                  'def log(nivel, mensaje, request_id=None, **ctx):',
                  '    entrada = {"nivel": nivel, "mensaje": mensaje}',
                  "    if request_id:",
                  '        entrada["request_id"] = request_id',
                  "    entrada.update(ctx)",
                  "    print(json.dumps(entrada))",
                  "",
                  'rid = "req_a1b2c3"',
                  'log("info", "inicio de peticion", request_id=rid)',
                  'log("debug", "consulta a BBDD", request_id=rid, query_ms=12)',
                  'log("info", "peticion completada", request_id=rid, status=200)',
                ],
              },
              real: {
                p: "En producción los frameworks ya emiten logs por petición (middlewares); tu trabajo es añadir los que aporten valor de negocio sin ensuciar.",
                ul: [
                  "Usa librerías serias (pino, winston, structlog) con niveles y rotación.",
                  "En desarrollo quieres debug; en producción, info hacia arriba.",
                  "Los errores se registran con stack trace y el estado relevante, no solo el mensaje.",
                ],
                code: [
                  "// Configuración típica en Node con pino",
                  'import pino from "pino";',
                  "",
                  "const logger = pino({",
                  '  level: process.env.LOG_LEVEL ?? "info",',
                  "});",
                  "",
                  'logger.info({ pedidoId: 42 }, "pedido creado correctamente");',
                  'logger.error({ pedidoId: 42, err }, "fallo al cobrar el pedido");',
                ],
                nota: "El nivel de log debe ser configurable por variable de entorno (LOG_LEVEL).",
              },
              expl: [
                "Un log sin contexto es inútil: incluye ids, tiempos y el estado implicado.",
                "Los niveles permiten afinar el ruido de cada entorno sin tocar código.",
                "El request_id es la pieza de oro para reconstruir una petición completa.",
                "Loguea errores con stack trace y contexto, nunca prints sueltos.",
                "Los logs estructurados alimentan herramientas de agregación (Loki, CloudWatch, Elastic).",
              ],
              errors: [
                "Loguear contraseñas, tokens o datos de tarjetas.",
                "Imprimir tres prints de depuración por línea en producción.",
                "Mezclar niveles y usar error para tonterías informativas: invalida el filtro.",
                "Registrar un Error sin contexto: no ayuda a nadie.",
              ],
              tips: [
                "Empieza con nivel info y sube a debug solo cuando lo necesites.",
                "Define un formato único y estructurado en todo el proyecto.",
                "Añade siempre el request_id y la operación que falla.",
                "Revisa los logs de un fallo real como ejercicio semanal.",
              ],
              exercise: [
                "Añade request_id a los logs de una API pequeña y correlaciónalos.",
                "Escribe un middleware que loguee método, ruta y status de cada petición.",
                "Filtra en tu consola los logs de nivel error durante diez minutos.",
              ],
              summary: [
                "Loguea eventos estructurados, con nivel y contexto.",
                "El request_id correlaciona toda la vida de una petición.",
                "Los secretos nunca van en los logs.",
              ],
              lang: "python",
              exampleFile: "logging-errors-backend",
              desc: "Aplica buenas prácticas de logging y manejo de errores en el backend.",
            },
          },
          {
            id: "seguridad-basica-del-backend",
            title: "Seguridad básica del backend",
            duration: "12 min",
            level: "basico",
            category: "seguridad",
            cardText: "Autenticación, inputs, HTTPS y secretos: el checklist mínimo para no ser la puerta abierta.",
            desc: "Aplica las medidas de seguridad básicas en cualquier backend.",
            body: {
              intro: [
                "El backend concentra los datos valiosos: usuarios, pagos, secretos. Por eso es el objetivo preferido de los ataques automatizados que barren Internet las 24 horas.",
                "No necesitas ser experto en ciberseguridad para escribir código seguro: sí necesitas aplicar de forma sistemática un puñado de medidas básicas.",
              ],
              def: {
                par: "La seguridad básica del backend es el conjunto mínimo de prácticas: validar y sanitizar entradas, usar HTTPS, proteger contraseñas con hashing, gestionar secretos y aplicar control de acceso.",
                porQue: "Los fallos más explotados (inyección SQL, XSS, fugas de secretos) provienen de descuidos pequeños y repetidos en el código diario.",
                cuando: "Aplícala desde el primer endpoint, no esperes al final: endurecer después es caro y arriesgado.",
              },
              concepts: [
                "Nunca confíes en la entrada: valida y sanitiza todo lo que llega.",
                "Las contraseñas se guardan con hash y salt (bcrypt, argon2), nunca en claro.",
                "HTTPS cifra todo lo que viaja; sin él, tokens y claves van a la vista.",
                "Los secretos viven en el entorno, no en el código ni el repo.",
                "Autenticación es quién eres; autorización, qué puedes hacer.",
              ],
              basic: {
                p: "Validar entradas y nunca concatenar SQL con datos del usuario.",
                code: [
                  "import bcrypt",
                  "",
                  'password = "clave_muy_segura"',
                  'hashed = bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt())',
                  'print("Hash generado:", hashed.decode())',
                  "",
                  "# SQL parametrizado: la entrada nunca entra en el texto de la consulta",
                  'query = "SELECT * FROM usuarios WHERE email = ?"',
                  "resultado = db.execute(query, (email,)).fetchone()",
                ],
                out: "Hash generado: $2b$12$mPZ8mVvySa88JOv4B.1sM.edRi6JlFhoGsrp8//dLmyP2kYU0MmXu",
                lang: "python",
              },
              intermediate: {
                p: "Control de acceso a nivel de fila: nunca expongas datos ajenos sin comprobar quién pregunta.",
                caption: "Autorización básica en un endpoint",
                code: [
                  'def obtener_pedido(id_pedido, usuario_actual):',
                  "    pedido = db.execute(",
                  '        "SELECT * FROM pedidos WHERE id = ?",',
                  "        (id_pedido,),",
                  "    ).fetchone()",
                  "",
                  "    if pedido is None:",
                  '        return {"error": "No encontrado"}, 404',
                  "",
                  '    if pedido["usuario_id"] != usuario_actual["id"]:',
                  '        return {"error": "Acceso denegado"}, 403',
                  "",
                  "    return pedido, 200",
                ],
              },
              real: {
                p: "El checklist del día a día en producción: HTTPS forzado, rate limiting en el login, cabeceras de seguridad y secretos rotados.",
                ul: [
                  "Fuerza HTTPS: redirige el tráfico HTTP y bloquea peticiones inseguras.",
                  "Limita los intentos de login contra fuerza bruta.",
                  "Aplica cabeceras de seguridad como Content-Security-Policy.",
                ],
                code: [
                  "// Cabeceras seguras en un middleware",
                  'res.set("X-Content-Type-Options", "nosniff")',
                  'res.set("X-Frame-Options", "DENY")',
                  'res.set("Strict-Transport-Security", "max-age=31536000; includeSubDomains")',
                  "",
                  "// no devuelvas nunca el hash ni el salt en respuestas JSON",
                ],
                nota: "Empieza poco a poco: primero validación y hashing; después HTTPS, rate limiting y cabeceras.",
              },
              expl: [
                "La inyección SQL se evita con parámetros preparados, punto.",
                "Las contraseñas hasheadas con bcrypt o argon2 tardan tiempo por diseño, penalizando los ataques.",
                "HTTPS evita que un intermediario lea contraseñas y tokens en tránsito.",
                "Valida tipos, longitudes y dominios: lo que no llega no existe.",
                "Autoriza a nivel de fila: el pedido debe pertenecer al usuario que pregunta.",
              ],
              errors: [
                "Concatenar valores del usuario en consultas SQL o HTML.",
                "Guardar contraseñas en claro o con hashes rotos como md5.",
                "Exponer secretos en logs, respuestas JSON o el repositorio.",
                "Confiar en el id recibido sin comprobar la propiedad del recurso.",
              ],
              tips: [
                "Usa librerías maduras para hashing y validación, no reinventes la rueda.",
                "Escanea tu proyecto con herramientas básicas (OWASP ZAP).",
                "Nunca respondas con el objeto de la base de datos entero: mapea a campos.",
                "Rota credenciales comprometidas de inmediato.",
              ],
              exercise: [
                "Reescribe una consulta SQL concatenada en versión parametrizada.",
                "Cierra un endpoint para que solo su dueño lo vea (403 si no).",
                "Busca secretos en el repo con git grep y conviértelos en variables de entorno.",
              ],
              summary: [
                "Valida y parametriza las entradas; nunca confíes en el usuario.",
                "Contraseñas con hash moderno y secretos fuera del código.",
                "HTTPS, rate limiting y autorización por fila ciegan los ataques comunes.",
              ],
              lang: "python",
              exampleFile: "seguridad-basica-backend",
              desc: "Aplica las medidas de seguridad básicas en cualquier backend.",
            },
          },
          {
            id: "desplegar-tu-api-en-produccion",
            title: "Poner tu API en producción",
            duration: "12 min",
            level: "intermedio",
            category: "despliegue",
            cardText: "Del repositorio a un servidor: migraciones, build, variables, HTTPS y primer deploy.",
            desc: "Despliega tu primera API al mundo: build, servidor, HTTPS y mínimos operativos.",
            body: {
              intro: [
                "Tener la API funcionando en local está bien, pero el trabajo termina cuando corre en producción, accesible las 24 horas, con HTTPS y migraciones aplicadas.",
                "El primer despliegue asusta, pero es una lista corta y repetible: preparar el artefacto, copiarlo al servidor, configurar y servir con HTTPS.",
              ],
              def: {
                par: "Desplegar es llevar tu código en funcionamiento a un servidor accesible públicamente: preparar el artefacto y sus datos, ejecutarlo con las variables correctas y exponerlo con un servidor web.",
                porQue: "Un despliegue manual y bien documentado genera confianza operativa; hacerlo bien te permite automatizarlo después con CI/CD sin dolor.",
                cuando: "Despliega cuando el proyecto tenga sentido de negocio y esté estable; refina el proceso con cada release: más despliegues pequeños y controlados.",
              },
              concepts: [
                "Artefacto: compilado o imagen del servicio lista para ejecutarse.",
                "Entornos: dev, staging y producción; cada uno con sus variables.",
                "Migraciones: cambios de esquema aplicados en orden y con control.",
                "PM2 o systemd mantienen el proceso vivo y lo reinician si cae.",
                "Nginx o similar pone HTTPS y actúa de reverse proxy.",
              ],
              basic: {
                p: "Preparar el servicio para producción en Node: build, migraciones y arranque.",
                code: [
                  '"scripts": {',
                  '  "build": "npm run compile",',
                  '  "start": "node dist/index.js",',
                  '  "migrate": "node scripts/migrar.js"',
                  "},",
                  "",
                  "# pasos reales en el servidor",
                  "git pull",
                  "npm ci",
                  "npm run build",
                  "npm run migrate",
                  "npm start",
                ],
                out: "> npm run compile\n> node dist/index.js\nAPI de la tienda escuchando en :3000 (produccion)",
                lang: "bash",
              },
              intermediate: {
                p: "Mantener el proceso vivo con systemd (Linux) o PM2.",
                caption: "Unidad systemd para la API",
                code: [
                  "[Unit]",
                  "Description=API de la tienda",
                  "After=network.target postgresql.service",
                  "",
                  "[Service]",
                  "User=deploy",
                  "WorkingDirectory=/srv/tienda",
                  "EnvironmentFile=/etc/tienda/produccion.env",
                  "ExecStart=/usr/bin/node /srv/tienda/dist/index.js",
                  "Restart=always",
                  "RestartSec=3",
                  "",
                  "[Install]",
                  "WantedBy=multi-user.target",
                ],
              },
              real: {
                p: "Flujo real en un VPS: reverse proxy con HTTPS delante de la API y respaldo antes de migrar.",
                ul: [
                  "Prueba el artefacto en staging antes de tocar producción.",
                  "Haz copia de seguridad de la base de datos antes de migrar.",
                  "Mide un endpoint después del deploy para confirmar que responde bien.",
                ],
                code: [
                  "# Nginx: proxy inverso con HTTPS delante de la API",
                  "server {",
                  "  listen 443 ssl;",
                  "  server_name api.tienda.com;",
                  "  ssl_certificate /etc/letsencrypt/live/api.tienda.com/fullchain.pem;",
                  "  ssl_certificate_key /etc/letsencrypt/live/api.tienda.com/privkey.pem;",
                  "",
                  "  location / {",
                  "    proxy_pass http://127.0.0.1:3000;",
                  '    proxy_set_header Host $host;',
                  '    proxy_set_header X-Forwarded-Proto $scheme;',
                  "  }",
                  "}",
                  "",
                  "# Certificado gratis: certbot --nginx -d api.tienda.com",
                ],
                nota: "Con docker compose este flujo se reduce a subir la imagen y un docker compose up -d; de ahí que la contenerización sea el siguiente paso lógico.",
              },
              expl: [
                "Despliegue reproducible es el mismo artefacto en staging y producción: solo cambian las variables.",
                "Las migraciones se aplican con backup y control; romper datos no se arregla con un git revert.",
                "systemd o PM2 garantizan que el proceso vuelva a arrancar si cae.",
                "Nginx aporta HTTPS, compresión y tolerancia; hoy HTTPS ya no es opcional.",
                "Documenta el runbook: los pasos exactos de cada despliegue.",
              ],
              errors: [
                "Desplegar a ciegas sin haberlo probado en staging.",
                "Olvidar las variables de entorno de producción y arrancar con defaults.",
                "Aplicar migraciones sin backup y romper datos de forma irreversible.",
                "Exponer el puerto del servicio sin HTTPS ni reverse proxy.",
              ],
              tips: [
                "Empieza con un despliegue manual documentado; luego automatízalo.",
                "Fija el commit o tag que estás desplegando.",
                "Añade un GET /health que compruebe la base de datos para verificar el deploy.",
                "Copia de seguridad antes y plan de rollback de las migraciones.",
              ],
              exercise: [
                "Crea un /health que compruebe la conexión a la BD y verifícalo con curl al arrancar.",
                "Describe en un runbook los seis pasos del despliegue de tu API.",
                "Adapta el systemd unit de ejemplo a tu servicio y a sus rutas reales.",
              ],
              summary: [
                "Un despliegue reproducible: artefacto, variables, migraciones y proceso vivo.",
                "systemd o PM2 mantienen la API encendida y Nginx trae HTTPS.",
                "Copia de seguridad antes, healthcheck después y runbook siempre.",
              ],
              lang: "bash",
              exampleFile: "desplegar-api-produccion",
              desc: "Despliega tu primera API al mundo: build, servidor, HTTPS y mínimos operativos.",
            },
          },
        ],
      },
    ],
  },
];