// _curriculum_git-github.mjs
// Currículum del curso de Git y GitHub.
// Exporta COURSES con todos los módulos y lecciones.
// Las lecciones existentes en disco se listan SIN body (no se regeneran);
// las nuevas (módulos 06 y 07) llevan body completo (11 secciones estándar + metadatos).

export const COURSES = [
  {
    slug: "git-github",
    title: "Git y GitHub",
    modules: [
      {
        id: "modulo-01",
        n: 1,
        t: "Fundamentos de Git",
        level: "basico",
        caption: "Tu primer repositorio y el ciclo de vida de los archivos.",
        desc: "Aprende qué es Git y GitHub, configura tu entorno, da tus primeros commits y entiende el staging area y la visualización de cambios con git diff.",
        subtitle: "El control de versiones que todo desarrollador backend debe dominar al dedillo.",
        objectives: [
          "Entender qué es Git y por qué sirve el control de versiones",
          "Configurar Git por primera vez",
          "Iniciar un repositorio y hacer commits buenos",
          "Dominar el ciclo de vida de un archivo",
          "Usar el staging area y git diff para revisar cambios",
        ],
        lessons: [
          {
            id: "ciclo-de-vida-de-un-archivo",
            title: "Ciclo de vida de un archivo",
            duration: "10 min",
            level: "basico",
            category: "fundamentos",
            cardText: "Untracked, modified y staged: los estados por los que pasa cada archivo.",
            desc: "Entiende los estados de un archivo en Git y su ciclo de vida completo.",
          },
          {
            id: "commits-buenos-y-mensajes",
            title: "Commits buenos y mensajes",
            duration: "10 min",
            level: "basico",
            category: "fundamentos",
            cardText: "Un commit cuenta una historia: mensajes claros y cambios atómicos.",
            desc: "Escribe commits con mensajes claros y cambios atómicos y legibles.",
          },
          {
            id: "git-init-y-configuracion",
            title: "git init y configuración",
            duration: "10 min",
            level: "basico",
            category: "fundamentos",
            cardText: "Prepara tu identidad y tu primer repositorio local.",
            desc: "Configura tu identidad global y crea tu primer repositorio.",
          },
          {
            id: "que-es-git-github",
            title: "¿Qué es Git y GitHub?",
            duration: "9 min",
            level: "basico",
            category: "fundamentos",
            cardText: "La diferencia entre el sistema de control de versiones y la plataforma.",
            desc: "Distingue Git, el sistema local, de GitHub, la plataforma de colaboración.",
          },
          {
            id: "staging-area-y-git-diff",
            title: "Staging area y git diff",
            duration: "10 min",
            level: "basico",
            category: "fundamentos",
            cardText: "Prepara (add) y revisa exactamente qué vas a commitear.",
            desc: "Domina el staging area y revisa tus cambios con git diff.",
          },
        ],
      },
      {
        id: "modulo-02",
        n: 2,
        t: "Ramas y merges",
        level: "basico",
        caption: "Trabaja en paralelo sin pisarte el trabajo.",
        desc: "Crea y cambia de ramas, fusiona tu trabajo con git merge, resuelve conflictos y elige una estrategia de flujo como GitFlow.",
        subtitle: "Las ramas te dejan experimentar sin romper producción.",
        objectives: [
          "Crear y cambiar de rama con fluidez",
          "Entender por qué las ramas transforman el trabajo en equipo",
          "Fusionar trabajo con git merge",
          "Resolver conflictos sin miedo",
          "Elegir una estrategia de flujo como GitFlow",
        ],
        lessons: [
          {
            id: "conflictos-y-como-resolverlos",
            title: "Conflictos y cómo resolverlos",
            duration: "10 min",
            level: "basico",
            category: "ramas",
            cardText: "Dos ramas tocando lo mismo: identificar y resolver conflictos con calma.",
            desc: "Aprende a resolver conflictos de fusión paso a paso.",
          },
          {
            id: "crear-y-cambiar-ramas",
            title: "Crear y cambiar de rama",
            duration: "10 min",
            level: "basico",
            category: "ramas",
            cardText: "git branch y git checkout en acción para moverte entre líneas de trabajo.",
            desc: "Crea, listas y cambias entre ramas de forma segura.",
          },
          {
            id: "git-merge-fusionando",
            title: "git merge: fusionando trabajo",
            duration: "10 min",
            level: "basico",
            category: "ramas",
            cardText: "Integra una rama en otra y entiende los commits de fusión.",
            desc: "Fusiona ramas con git merge y comprende lo que sucede.",
          },
          {
            id: "gitflow-y-estrategias",
            title: "GitFlow y estrategias de flujo",
            duration: "10 min",
            level: "basico",
            category: "ramas",
            cardText: "GitFlow, trunk-based y otras estrategias para organizar el equipo.",
            desc: "Compara GitFlow con otras estrategias de ramas.",
          },
          {
            id: "ramas-por-que-y-para-que",
            title: "Ramas: por qué y para qué",
            duration: "10 min",
            level: "basico",
            category: "ramas",
            cardText: "El modelo mental que convierte a Git en una máquina de colaborar.",
            desc: "Descubre el modelo mental de las ramas y su propósito real.",
          },
        ],
      },
      {
        id: "modulo-03",
        n: 3,
        t: "GitHub y remotos",
        level: "basico",
        caption: "Conecta tu repositorio local con el mundo.",
        desc: "Clona, trae y envía cambios con git pull y git push, gestiona remotos, usa .gitignore para archivos molestos y entiende el tracking de ramas remotas.",
        subtitle: "Del repositorio local a la colaboración global.",
        objectives: [
          "Conectar repositorios locales con remotos",
          "Clonar y sincronizar con git pull y git push",
          "Gestionar varios remotos con git remote",
          "Usar .gitignore para no commitear basura",
          "Entender el tracking entre ramas locales y remotas",
        ],
        lessons: [
          {
            id: "git-clone-y-pull",
            title: "git clone y git pull",
            duration: "10 min",
            level: "basico",
            category: "remotos",
            cardText: "Trae un repositorio entero o los últimos cambios de la rama.",
            desc: "Clona repositorios y trae los últimos cambios con git pull.",
          },
          {
            id: "git-push-y-github",
            title: "git push y GitHub",
            duration: "10 min",
            level: "basico",
            category: "remotos",
            cardText: "Lanza tu trabajo al remoto y acompáñalo en GitHub.",
            desc: "Sube tus commits al remoto con git push y publícalos en GitHub.",
          },
          {
            id: "gitignore-y-archivos-grandes",
            title: ".gitignore y archivos grandes",
            duration: "10 min",
            level: "basico",
            category: "remotos",
            cardText: "Mantén tu historial limpio excluyendo binarios y secretos.",
            desc: "Usa .gitignore para excluir archivos y evitar binarios grandes.",
          },
          {
            id: "ramas-remotas-tracking",
            title: "Ramas remotas y tracking",
            duration: "10 min",
            level: "basico",
            category: "remotos",
            cardText: "The upstream: cómo sabe Git qué rama remota sigue cada local.",
            desc: "Entiende cómo las ramas locales siguen y rastrean a las remotas.",
          },
          {
            id: "remotos-y-git-remote",
            title: "Remotos y git remote",
            duration: "10 min",
            level: "basico",
            category: "remotos",
            cardText: "Añade, renombra y elimina remotos con git remote.",
            desc: "Gestiona los repositorios remotos conectados a tu proyecto.",
          },
        ],
      },
      {
        id: "modulo-04",
        n: 4,
        t: "Colaboración y PR",
        level: "basico",
        caption: "Forks, issues y pull requests en equipo.",
        desc: "Colabora como un equipo profesional: forks, issues, pull requests, revisión de código con comentarios y el flujo diario de trabajo en equipo.",
        subtitle: "GitHub es donde el código se convierte en conversación.",
        objectives: [
          "Colaborar con forks y colaboradores",
          "Gestionar el proyecto con issues",
          "Abrir, revisar y fusionar pull requests",
          "Dejar comentarios útiles en la revisión",
          "Integrar el flujo en el día a día del equipo",
        ],
        lessons: [
          {
            id: "forks-y-colaboradores",
            title: "Forks y colaboradores",
            duration: "10 min",
            level: "basico",
            category: "colaboración",
            cardText: "Trabaja sobre proyectos ajenos con forks o como colaborador.",
            desc: "Elige entre fork o colaborador directo según el proyecto.",
          },
          {
            id: "issues-y-project-management",
            title: "Issues y gestión de proyectos",
            duration: "10 min",
            level: "basico",
            category: "colaboración",
            cardText: "Convierte tareas, bugs y propuestas en issues accionables.",
            desc: "Gestiona el trabajo del equipo con issues y proyectos.",
          },
          {
            id: "pull-requests",
            title: "Pull requests",
            duration: "10 min",
            level: "basico",
            category: "colaboración",
            cardText: "El corazón de la colaboración: propuestas de cambio revisables.",
            desc: "Abre, describe y fusiona pull requests correctamente.",
          },
          {
            id: "revisar-codigo-comments",
            title: "Revisar código y comentarios",
            duration: "10 min",
            level: "basico",
            category: "colaboración",
            cardText: "Revisa el trabajo ajeno dejando comentarios constructivos.",
            desc: "Revisa código y deja comentarios que de verdad ayudan.",
          },
          {
            id: "trabajo-en-equipo-flujo",
            title: "Trabajo en equipo y flujo diario",
            duration: "10 min",
            level: "basico",
            category: "colaboración",
            cardText: "El día a día: pull, rama, commit, push y PR sin tropezos.",
            desc: "Domina el flujo diario de trabajo con Git y GitHub en equipo.",
          },
        ],
      },
      {
        id: "modulo-05",
        n: 5,
        t: "Git avanzado",
        level: "intermedio",
        caption: "Historia profunda, reescritura y recuperación.",
        desc: "Profundiza en git log, reescribe la historia con rebase, recupera el trabajo con reflog, y gestiona stash, worktrees, tags y releases.",
        subtitle: "Cuando el historial deja de ser un problema y se vuelve una herramienta.",
        objectives: [
          "Leer el historial con git log en profundidad",
          "Revertir con git revert y git reset sin miedo",
          "Reescribir la historia con rebase",
          "Guardar trabajo a medias con stash y usar worktrees",
          "Publicar versiones con tags y releases",
        ],
        lessons: [
          {
            id: "git-log-profundidad",
            title: "git log en profundidad",
            duration: "10 min",
            level: "intermedio",
            category: "avanzado",
            cardText: "Formatos, filtros y grafo del historial: git log sin límites.",
            desc: "Extrae todo el historial con opciones avanzadas de git log.",
          },
          {
            id: "git-revert-y-reset",
            title: "git revert y git reset",
            duration: "10 min",
            level: "intermedio",
            category: "avanzado",
            cardText: "Deshacer cambios conservando o reescribiendo la historia.",
            desc: "Deshaz cambios con git revert y git reset según el caso.",
          },
          {
            id: "rebase-y-rewriting",
            title: "Rebase y reescribir historia",
            duration: "10 min",
            level: "intermedio",
            category: "avanzado",
            cardText: "Reordena, combina y edita commits con rebase interactivo.",
            desc: "Reescribe la historia con rebase interactivo y enmiendas.",
          },
          {
            id: "stash-y-worktrees",
            title: "Stash y worktrees",
            duration: "10 min",
            level: "intermedio",
            category: "avanzado",
            cardText: "Guarda trabajo a medias y trabaja en varias ramas a la vez.",
            desc: "Guarda cambios a medias con stash y usa worktrees para multitarea.",
          },
          {
            id: "tags-y-releases",
            title: "Tags y releases",
            duration: "10 min",
            level: "intermedio",
            category: "avanzado",
            cardText: "Marca versiones en tu historial y publica releases.",
            desc: "Crea tags para marcar versiones y publícalas como releases.",
          },
        ],
      },
      {
        id: "modulo-06",
        n: 6,
        t: "Colaboración avanzada y code review",
        level: "intermedio",
        caption: "Reviews de calidad y reglas que protegen la rama principal.",
        desc: "Eleva el nivel del equipo: code reviews efectivos y constructivos, branch protection, convenciones de commits y hooks de Git para automatizar la calidad.",
        subtitle: "Un buen code review enseña más que cien commits.",
        objectives: [
          "Hacer code reviews efectivos y constructivos",
          "Proteger ramas con reglas del repositorio",
          "Aplicar convenciones de commits y changelogs",
          "Automatizar calidad con Git hooks",
        ],
        lessons: [
          {
            id: "code-review-efectivo",
            title: "Code review efectivo y comentarios constructivos",
            duration: "11 min",
            level: "intermedio",
            category: "code review",
            cardText: "Revisa el código ajeno buscando la mejor versión de una idea.",
            desc: "Haz code reviews que aporten sin juzgar a la persona.",
            body: {
              intro: [
                "Un code review no es una inspección policial: es una conversación técnica sobre cómo mejorar el código antes de que llegue a producción. Bien hecho, es la herramienta que más errores detecta por cada euro invertido y, de paso, la que forma al equipo.",
                "El objetivo no es aprobar o rechazar tu lista de cambios, sino que entre todos el código quede mejor: más claro, más seguro y más mantenible, con comentarios que explican el porqué y no solo el qué.",
              ],
              def: {
                par: "El code review es la revisión sistemática de un cambio de código por otra persona antes de fusionarlo, enfocada en encontrar defectos, mejorar el diseño y compartir conocimiento.",
                porQue: "Cada persona tiene puntos ciegos. Un par de ojos frescos detecta bugs, problemas de seguridad y malentendidos de negocio que el autor ya no ve.",
                cuando: "Todo cambio a la rama principal debería pasar por review cuando hay algo en juego: calidad, seguridad o el contrato de una API.",
              },
              concepts: [
                "Enfócate en el diff, no en el montón de archivos: cada línea que cambia tiene un motivo.",
                "Comentarios constructivos: sugieren y explican, no castigan ni juzgan.",
                "Alcance acotado: PRs pequeños se revisan mejor y más rápido.",
                "Petición de cambios: aprueba, solicita cambios o comenta; úsalo con criterio.",
                "Carácter asíncrono: el review es una herramienta de comunicación diferida.",
              ],
              basic: {
                p: "El patrón de oro de un comentario útil: señalar la línea, explicar por qué y proponer una alternativa concreta.",
                code: [
                  "# En lugar de: \"esto está feo\", escribe:",
                  "#",
                  "# ¿Podemos usar la misma estrategia de paginación",
                  "# que en el resto de la API? Aquí sería coherente",
                  "# reutilizar cursor + lastId para no mezclar estilos.",
                  "# Versión actual mezcla offset (lento en tablas grandes).",
                ],
                out: "Comentario accionable y con contexto detrás del código.",
                lang: "bash",
              },
              intermediate: {
                p: "GitHub permite comentar en línea dentro del pull request; ancla el comentario al diff exacto y referencia issues o documentación.",
                code: [
                  "git fetch origin main",
                  "git diff main...mi-rama",
                  "git push origin mi-rama",
                  "# Revisa en GitHub: Files changed > comentarios en línea",
                ],
                caption: "Flujo: trae main actualizado y compara la rama",
              },
              real: {
                p: "Un equipo de pagos detectó en review un token de acceso que filtraba en los logs por una línea de debug. El comentario '¿seguro que queremos loggear el token?' evitó una fuga de información en producción.",
                ul: [
                  "Revisa primero los puntos críticos: auth, dinero, datos personales y errores.",
                  "No apruebes una PR solo 'para darle salida': la prisa se paga luego.",
                  "Usa plantillas de PR para que el autor cuente qué hace y por qué.",
                  "Divide reviews largos: una lista de 20 comentarios abruma a cualquiera.",
                ],
                code: [
                  "git log --oneline origin/main..HEAD",
                  "# Revisa qué commits introduce tu PR antes de pedir review",
                ],
                nota: "El autor primero revisa su propio diff: la mitad de los comentarios del reviewers desaparecen solos.",
              },
              expl: [
                "Un review de calidad se centra en comportamiento, seguridad y diseño, no en gustos de formato (eso lo automatizan los linters).",
                "Los comentarios deben ofrecer una alternativa: criticar sin proponer solo crea fricción.",
                "El tamaño de la PR importa: hasta ~300 líneas la revisión es eficaz; por encima, la atención se dispersa.",
                "Las convenciones de equipo (título, ramas, tests) reducen la fricción de cada review.",
                "El asincronismo permite pensar con calma, a diferencia de una decisión en caliente en una reunión.",
              ],
              errors: [
                "Dejar comentarios estilo 'esto está mal' sin explicación ni alternativa.",
                "Aprobar 'hoy para no retrasar' y salvar el fallo en el siguiente deploy.",
                "Revisar sin mirar los tests: el código de pruebas cuenta tanto como el resto.",
              ],
              tips: [
                "Empieza el review por los tests: si ninguno falta, el cambio está bien defendido.",
                "Usa comandos cortos para reaccionar: LGTM invitando al autor para más contexto.",
                "Framea tus comentarios como preguntas: '¿Nos ayudaría reutilizar este helper?'",
              ],
              exercise: [
                "Revisa una PR real y clasifica tus comentarios: bug, diseño, nit o pregunta.",
                "Escribe un plan de review de 5 minutos para una PR de autenticación.",
                "Practica el feedback: responde con una alternativa concreta a un cambio.",
              ],
              summary: [
                "El code review busca la mejor versión del código, no la rendición del autor.",
                "Comentarios anclados, accionables y con contexto hacen avanzar al equipo.",
                "PRs pequeñas con template y convenciones convierten el review en un hábito ganador.",
              ],
              lang: "bash",
              exampleFile: "code-review-effectivo",
              desc: "Haz code reviews que aporten sin juzgar a la persona.",
            },
          },
          {
            id: "protected-branches-reglas",
            title: "Protected branches y reglas del repositorio",
            duration: "10 min",
            level: "intermedio",
            category: "code review",
            cardText: "Imposibilita el push directo a main con reglas del repositorio.",
            desc: "Protege las ramas clave con rulesets y checks obligatorios.",
            body: {
              intro: [
                "Un solo push descontrolado a la rama principal puede enviar un bug a producción sin que nadie se entere. Las branch protection rules existen para convertirlo en imposible: nadie 'edita main directamente' en un equipo profesional.",
                "GitHub permite exigir reviews, comprobaciones de estado (CI) y actualizaciones antes de fusionar, además de impedir que se borren ramas de protección por accidente.",
              ],
              def: {
                par: "Las protected branches son ramas configuradas con reglas que impiden el push directo, exigen reviews aprobadas y comprobaciones de estado preceptivas, y pueden limitar quién puede eliminar o modificar la historia.",
                porQue: "Garantizan que el código de producción pasa siempre por revisión y por los checks automáticos, y protegen a la rama principal de cambios accidentales o maliciosos.",
                cuando: "Aplica protección al menos a main y a las ramas de release desde el primer día; amplíalo según crezca el equipo.",
              },
              concepts: [
                "Require pull request reviews: ningún merge sin una revisión aprobada.",
                "Require status checks: el CI debe pasar antes de fusionar.",
                "Require up-to-date branches: la rama está al día con main para no romperlo.",
                "Restricciones de push: quién puede escribir directamente en la rama.",
                "Rulesets: agrupación moderna de reglas por patrón de rama.",
              ],
              basic: {
                p: "Proteger la rama main desde la configuración de reglas de GitHub.",
                code: [
                  "Settings > Branches > Add classic branch protection rule",
                  "Branch name pattern: main",
                  "✓ Require a pull request before merging",
                  "✓ Require reviews (mínimo 1 aprobador)",
                  "✓ Require status checks to pass (build & tests)",
                ],
                out: "Nadie pushea a main sin pasar por una PR con reviews y CI verde.",
                lang: "bash",
              },
              intermediate: {
                p: "Gestionar la protección también desde CLI o vía archivo de configuración en el repo (settings/quality).",
                code: [
                  "gh api -X PUT repos/:owner/:repo/branches/main/protection \\",
                  "  -f 'required_status_checks[strict]=true' \\",
                  "  -f 'required_pull_request_reviews[required_approving_review_count]=1' \\",
                  "  -f 'enforce_admins=false'",
                ],
                caption: "Proteger main con gh api",
              },
              real: {
                p: "Un incidente de producción se originó en un push directo de un cambio 'urgente'. Tras aplicar branch protection con CI obligatorio, la excusa de la urgencia se resuelve con una hotfix branch, no con un bypass de la protección.",
                ul: [
                  "Exigir también los checks de escaneo y los tests de conflictos en el merge.",
                  "Proteger no solo main, sino release y cualquier rama con nombre de patrón catch-all.",
                  "Aplicar a las ramas de protección el 'require signed commits' si tu compliance lo pide.",
                  "Revisar quién puede modificar las reglas de protección.",
                ],
                code: [
                  "gh repo edit --enable-issues --enable-wiki=false",
                  "gh secret set CI_TOKEN",
                ],
                nota: "Los rulesets modernos permiten además restricciones de no-rebase y de merges de squash/only.",
              },
              expl: [
                "La protección se materializa en el plan de control de GitHub: la operación se bloquea antes de escribir.",
                "Require status checks enlaza el merge con tu pipeline: si el CI falla, el botón de merge se bloquea.",
                "Require up-to-date evita la 'ventana': fusionar sobre una base desactualizada rompe el historial.",
                "Los rulesets aplican reglas a todos los branches que cuadren con un patrón, no solo a main.",
                "La protección no impide la revisión: la hace obligatoria y la nota en el historial.",
              ],
              errors: [
                "Proteger main pero permitir push directo a release.",
                "Exigir checks pero no 'require branches to be up to date'.",
                "Dar permisos de admin a más personas de las necesarias.",
              ],
              tips: [
                "Empieza con revisión obligatoria y CI; añade 'up-to-date' al mes siguiente.",
                "Utiliza rulesets nuevos: son el estándar y más legibles.",
                "Documenta el flujo de hotfix para que nadie intente saltarse la protección 'por urgencia'.",
              ],
              exercise: [
                "Protege main con una revisión obligatoria y comprúebalo con un push directo.",
                "Configura un status check con tu CI y valida que el merge se bloquea al fallar.",
                "Define un ruleset para las ramas v*.*.* de releases.",
              ],
              summary: [
                "Las protected branches impiden el push directo y exigen fuerza bruta en forma de reviews y CI.",
                "Los rulesets aplican reglas por patrón y protegen todo el historial.",
                "La protección bien configurada previene accidentes sin frenar al equipo.",
              ],
              lang: "bash",
              exampleFile: "protected-branches",
              desc: "Protege las ramas clave con rulesets y checks obligatorios.",
            },
          },
          {
            id: "semantic-commits-convenciones",
            title: "Semantic commits, convenciones y changelogs",
            duration: "10 min",
            level: "intermedio",
            category: "code review",
            cardText: "Mensajes de commit con tipo y alcance que cuentan la historia del proyecto.",
            desc: "Aplica commits semánticos y genera changelogs automáticos.",
            body: {
              intro: [
                "Un historial de commits bien escrito es la mejor documentación que tiene un proyecto: en cada commit puedes leer qué cambió, por qué y en qué parte del sistema. Un historial caótico convierte cada 'git blame' en una investigación policial.",
                "Los conventional commits estandarizan ese mensaje: tipo (feat, fix, docs), alcance opcional y descripción. Y de paso, son el combustible de los changelogs y del versionado semántico automatizado.",
              ],
              def: {
                par: "Los conventional commits siguen el formato 'tipo(alcance): descripción' (feat, fix, BREAKING CHANGE...) y permiten deducir la versión semántica y generar changelogs de forma automática.",
                porQue: "Estandarizan la historia, alimentan la generación de releases y hacen que git log y git blame hablen el mismo idioma.",
                cuando: "En equipos medianos y grandes, y en cualquier proyecto open source donde la comunicación por commits es la vía principal.",
              },
              concepts: [
                "feat: añade una funcionalidad nueva visible para el usuario.",
                "fix: corrige un bug sin cambiar comportamiento externo.",
                "BREAKING CHANGE: rompe compatibilidad y dispara major version.",
                "Alcance: la zona que toca el cambio (feat(api): ...).",
                "Changelog: listado de cambios por versión, generable con conventional-commits.",
              ],
              basic: {
                p: "Mensajes de commit siguiendo la convención y sus variantes más usadas.",
                code: [
                  "git commit -m \"feat(api): añade endpoint de listado paginado\"",
                  "git commit -m \"fix(db): corrige índice del campo email\"",
                  "git commit -m \"docs: documenta la firma del equipo\"",
                  "git commit -m \"style: ajusta formato del linter\"",
                ],
                out: "Cada commit es clasificable y legible en un vistazo.",
                lang: "bash",
              },
              intermediate: {
                p: "Generar un changelog automático con commitlint y conventional-changelog.",
                code: [
                  "npx commitlint --from v1.0.0 --to v1.1.0",
                  "conventional-changelog -p angular -i CHANGELOG.md -s",
                  "# npm install --save-dev commitlint conventional-changelog-cli",
                ],
                caption: "Changelog generado desde los commits semánticos",
              },
              real: {
                p: "Un servicio con estándar semántico releasea cada semana: al fusionar PRs con conventional commits, el pipeline calcula el siguiente número de versión y escribe el changelog, dejando a los ojos humanos solo la revisión final.",
                ul: [
                  "Aplica commitlint en el pre-commit o en el CI para que el formato nunca se rompa.",
                  "Asocia la convención con tu sistema de issues: 'fix(cliente): [42] corrige redirect'.",
                  "Usa BREAKING CHANGE para decisiones relevantes de contrato de API.",
                  "Mantén el changelog generado y, si quieres, añade notas manuales en la release.",
                ],
                code: [
                  "git tag v1.0.0",
                  "git push origin v1.0.0",
                  "# El pipeline calcula v1.1.0 si hay feat, v1.0.1 si solo .",
                ],
                nota: "La mayor parte de los repositorios de hoy mainstream usan esta convención; el paso de adoptarla es mínimo.",
              },
              expl: [
                "El tipo define el impacto semántico; el alcance da contexto espacial a cada cambio.",
                "fix y feat disparan patch y minor; BREAKING CHANGE dispara major.",
                "commitlint valida el formato en el hook o en CI, no depender solo de la voluntad.",
                "Los changelogs generados mantienen la historia del proyecto fresca sin trabajo manual.",
                "El versionado semántico aplicado sobre el historial hace que la release sea reproducible.",
              ],
              errors: [
                "Mezclar varios tipos en un mismo commit: mejor uno por cambio.",
                "Mensajes vagos como 'arreglos varios' que no permiten volver a contexto.",
                "Romper el formato y que el changelog automático falle en silencio.",
              ],
              tips: [
                "Usa commitzen como asistente interactivo en vez de memorizar la sintaxis.",
                "Incluye el número de issue para trazabilidad automática.",
                "Roja línea: si un mensaje necesita 3 líneas de explicación, acompaña el porqué en el cuerpo del commit.",
              ],
              exercise: [
                "Reescribe el propio mensaje de este commit con conventional commits.",
                "Instala commitlint y haz que falle un commit con formato inválido.",
                "Genera tu primer changelog a partir de los últimos 10 commits.",
              ],
              summary: [
                "Los conventional commits estandarizan el formato y el impacto de cada cambio.",
                "Alimentan versionado semántico y changelogs generados.",
                "Automatízalo con hooks y CI para que sea un hábito, no un debate.",
              ],
              lang: "bash",
              exampleFile: "semantic-commits",
              desc: "Aplica commits semánticos y genera changelogs automáticos.",
            },
          },
          {
            id: "git-hooks-automatizacion",
            title: "Git hooks y automatización local",
            duration: "11 min",
            level: "intermedio",
            category: "code review",
            cardText: "Ejecuta linters y tests automáticamente con los hooks de Git.",
            desc: "Automatiza la calidad local con Git hooks y pre-commit.",
            body: {
              intro: [
                "¿Cuántas veces se te escapó un error de lint, un secreto accidental o un test roto hasta el CI? Los Git hooks ejecutan tu automatización en el momento justo, en tu máquina, antes de que el problema salga de tu rama.",
                "pre-commit, pre-push y commit-msg son los hooks estrella: formatean, lintan, testean y validan tus mensajes en cada movimiento. Compartidos con el equipo, la calidad no depende de la disciplina de nadie.",
              ],
              def: {
                par: "Los Git hooks son scripts que Git ejecuta automáticamente en momentos concretos de su ciclo (pre-commit, post-commit, pre-push, pre-rebase). Herramientas como pre-commit o husky los comparten con el equipo.",
                porQue: "Mueven la corrección al momento más barato posible: localmente, antes de que un fallo viaje al repo compartido y moleste a todos.",
                cuando: "En cualquier repositorio con reglas de estilo, secretos o tests; son el primer escalón de la calidad por default.",
              },
              concepts: [
                "Hook: script que se dispara en un momento del ciclo de Git.",
                "pre-commit: se ejecuta antes de crear el commit; ideal para lint y format.",
                "pre-push: se ejecuta antes de enviar a remoto; ideal para tests y builds.",
                "commit-msg: valida el formato del mensaje de commit.",
                "pre-commit (la herramienta): framework que gestiona hooks declarativos por archivo.",
              ],
              basic: {
                p: "Configurar pre-commit con un hook de linter de Python y de Secret skip.",
                code: [
                  "cat > .pre-commit-config.yaml <<'EOF'",
                  "repos:",
                  "  - repo: https://github.com/pre-commit/pre-commit-hooks",
                  "    rev: v5.0.0",
                  "    hooks:",
                  "      - id: trailing-whitespace",
                  "      - id: end-of-file-fixer",
                  "      - id: check-added-large-files",
                  "EOF",
                  "pre-commit install",
                ],
                out: "Cada commit limpia espacios, líneas y valida el diff antes de dejar pasar.",
                lang: "bash",
              },
              intermediate: {
                p: "Hooks más potentes con husky y una herramienta de lint de mensajes (commitlint) para el primer commit.",
                code: [
                  "npx husky init",
                  "echo \"npx --no -- commitlint --edit \\$1\" > .husky/commit-msg",
                  'echo "npm run lint && npm test" > .husky/pre-commit',
                  "",
                  "cat > commitlint.config.js <<'EOF'",
                  "module.exports = { extends: ['@commitlint/config-conventional'] };",
                  "EOF",
                ],
                caption: "Husky: pre-commit con lint + tests y validación del mensaje",
              },
              real: {
                p: "Un incidente de fuga de credenciales se evitó porque el hook detectaba el patrón de API key (gitleaks) en pre-commit. El desarrollador que lo cometió recibió el aviso antes de hacer push; el equipo añadió el hook a su config compartida.",
                ul: [
                  "Comparte hooks en el repositorio para que todo el mundo los tenga en un clone.",
                  "Usa linters y secretes (gitleaks) dentro de pre-commit.",
                  "Permite escape rápido (SKIP=id) para casos justificados.",
                  "Mantén hooks rápidos: un hook de 10 segundos se ejecuta; uno de 2 minutos se saltea.",
                ],
                code: [
                  "SKIP=<hook_id> git commit -m \"fix: configuración local sin regla\"",
                ],
                nota: "Los hooks son locales por naturaleza; los puedes versionar pero no forzar en otros si no los instalan.",
              },
              expl: [
                "cada hook tiene props distintos: pre-commit ve el staging, pre-push ve el estado ya commitado listo para enviar.",
                "pre-commit (la herramienta) gestiona entornos por repositorio sin interferencia global.",
                "commit-msg valida el mensaje antes de que quede registrado.",
                "Los hooks pueden acceder al árbol de trabajo; por eso suelen terminar modificando archivos (format).",
                "Con SKIP o --no-verify puedes saltar los hooks: es deliberadamente fácil, porque a veces es legítimo.",
              ],
              errors: [
                "Construir hooks gigantes que tarden minutos: nadie quiere revisar antes de tu script.",
                "No versionar .pre-commit-config.yaml y perder la config al clonar.",
                "Ignorar el hook y hacer --no-verify por costumbre, saltando la protección.",
              ],
              tips: [
                "Empieza con el pre-commit estándar y añade linters de tu lenguaje.",
                "Añade la detección de secretos al primer día: es la más potente por el coste.",
                "Prueba los hooks en una rama aislada para no fastidiar al equipo.",
              ],
              exercise: [
                "Configura pre-commit con lint de estilo en tu repositorio.",
                "Añade un hook que ejecute los tests de tu proyecto.",
                "Crea un commit-msg hook y valida un mensaje inválido.",
              ],
              summary: [
                "Los Git hooks ejecutan tu calidad local, en el momento más barato de corregir.",
                "pre-commit (la herramienta) y husky los comparten y mantener.",
                "Lint, formato, secretos y mensajes pasan a ser automáticos.",
              ],
              lang: "bash",
              exampleFile: "git-hooks",
              desc: "Automatiza la calidad local con Git hooks y pre-commit.",
            },
          },
        ],
      },
      {
        id: "modulo-07",
        n: 7,
        t: "Git en equipos grandes",
        level: "avanzado",
        caption: "CI/CD, monorepos y cirugía de historial para equipos serios.",
        desc: "Adopta GitHub Actions para CI/CD, gestiona monorepos y repositorios grandes, haz cirugía de historial con reflog y define estrategias de branching multiteam.",
        subtitle: "Cuando el repositorio vive con cientos de personas, Git se vuelve disciplina.",
        objectives: [
          "Automatizar pruebas y deploys con GitHub Actions",
          "Gestionar monorepos y repositorios de gran tamaño",
          "Recuperar historial y hacer cirugía segura con reflog",
          "Aplicar estrategias de branching multiteam",
        ],
        lessons: [
          {
            id: "github-actions-ci-cd",
            title: "GitHub Actions: CI/CD sobre tu historial",
            duration: "12 min",
            level: "avanzado",
            category: "automatización",
            cardText: "Workflows que prueban, escanean y despliegan cada push.",
            desc: "Crea pipelines con GitHub Actions ligados a tu repositorio.",
            body: {
              intro: [
                "Si tu CI corre fuera del repo, cada cambio necesita ser informado a un tercero. GitHub Actions integra los pipelines en el propio repositorio: los workflows viven versionados con el código y se disparan por eventos como push o pull_request.",
                "Un buen flujo corre tests, lint, escaneo y build en cada push, y despliega automáticamente en staging (o en prod con aprobación) cuando el PR se fusiona.",
              ],
              def: {
                par: "GitHub Actions es la plataforma de CI/CD de GitHub: workflows YAML que definen jobs y steps ejecutados en runners por eventos del repositorio.",
                porQue: "Conecta la automatización al mismo sitio donde está el código y el histórico, con contextos (github, secrets) listos para usar.",
                cuando: "Elige Actions cuando tu código vive en GitHub y quieres integración de la una al cero: queries, matrix de versiones y secrets integrados.",
              },
              concepts: [
                "Workflow: definición YAML de un pipeline con jobs y triggers.",
                "Job: conjunto de steps que se ejecutan en un runner aislado.",
                "Runner: máquina que ejecuta los jobs (hosted o self-hosted).",
                "Evento: lo que dispara el workflow (push, pull_request, schedule).",
                "Secrets: variables cifradas disponibles solo en runtime.",
              ],
              basic: {
                p: "El workflow mínimo: se ejecuta en cada push y PR, hace lint y test con la matriz de Node.",
                code: [
                  "name: CI",
                  "on: [push, pull_request]",
                  "jobs:",
                  "  test:",
                  "    runs-on: ubuntu-latest",
                  "    strategy:",
                  "      matrix:",
                  "        node: [20, 22]",
                  "    steps:",
                  "      - uses: actions/checkout@v4",
                  "      - uses: actions/setup-node@v4",
                  "        with:",
                  "          node-version: ${{ matrix.node }}",
                  "      - run: npm ci",
                  "      - run: npm run lint && npm test",
                ],
                out: "Cada push y PR ejecuta lint y tests en Node 20 y 22.",
                lang: "yaml",
              },
              intermediate: {
                p: "Workflows con despliegue condicional y artefactos: publicar un paquete solo cuando se fusiona a main.",
                code: [
                  "name: release",
                  "on:",
                  "  push:",
                  "    branches: [main]",
                  "",
                  "jobs:",
                  "  publish:",
                  "    runs-on: ubuntu-latest",
                  "    steps:",
                  "      - uses: actions/checkout@v4",
                  "      - run: npm ci && npm run build",
                  "      - run: npm publish --access public",
                  "        env:",
                  "          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}",
                ],
                caption: "Publicar en el registry al fusionar a main",
              },
              real: {
                p: "Un monorepo con API, worker y CLI usa un workflow por área con paths: tocar solo la API no corre los tests del worker. La matriz de versiones y el escaneo de dependencias corren en cada PR, y los despliegues a staging se hacen al merge.",
                ul: [
                  "Usa paths para que cada área solo dispare su pipeline.",
                  "Cachea las dependencias entre runs para que el pipeline sea rápido.",
                  "Protege la rama con status checks apuntando a tus workflows.",
                  "Aprovecha los artefactos y reports para el code review.",
                ],
                code: [
                  "jobs:",
                  "  api-tests:",
                  "    runs-on: ubuntu-latest",
                  "    if: contains(github.event.pull_request.changed_files, 'api/')",
                ],
                nota: "Actions escala con matrices y reutiliza workflows vía actions/reusable-workflows.",
              },
              expl: [
                "El contexto github.sha, github.ref te permite construir nombres y etiquetas dinámicas.",
                "Los secrets nunca se exponen en logs; las variables de entorno las inyectas con env:.",
                "Los artefactos permiten a los humanos revisar builds y los reports a los checks en PR.",
                "Los runners self-hosted dan control total pero los mantienes tú.",
                "Los concurrency grupos evitan que dos deploys del mismo flujo se pisen.",
              ],
              errors: [
                "Workflows sin cache: npm ci de 4 minutos en cada push ralentiza el feedback.",
                "Disparar deploy en cada push en lugar de solo en el merge a main.",
                "Guardar secretos en el workflow en lugar de en Settings > Secrets.",
              ],
              tips: [
                "Empieza con un workflow de test y añade despliegue cuando el repo esté maduro.",
                "Usa matrix de node/python para cubrir las versiones soportadas.",
                "Visualiza el estado en la pestaña Actions y protege la rama con status checks.",
              ],
              exercise: [
                "Crea un workflow CI que ejecute lint y tests de tu proyecto.",
                "Añade un job de build con cache de dependencias.",
                "Configura un status check que bloquee el merge si el pipeline falla.",
              ],
              summary: [
                "GitHub Actions integra CI/CD en el repo, versionado con el código.",
                "Workflows, jobs, matrix y secrets cubren test, build y deploy.",
                "Con actions y checks obligatorios, la calidad vive en la plataforma.",
              ],
              lang: "yaml",
              exampleFile: "github-actions",
              desc: "Crea pipelines con GitHub Actions ligados a tu repositorio.",
            },
          },
          {
            id: "monorepos-gestion-escala",
            title: "Monorepos y gestión a escala",
            duration: "11 min",
            level: "avanzado",
            category: "automatización",
            cardText: "Un solo repositorio para muchos proyectos: herramientas y trucos.",
            desc: "Adopta monorepos o trabaja con submodules y repos grandes a escala.",
            body: {
              intro: [
                "Un monorepo almacena toda la organización en un único repositorio: código, config, librerías internas y servicios. Tiene ventajas claras de consistencia y refactor entre paquetes, y retos reales de tamaño y velocidad.",
                "Git soporta repos grandes con sparse checkout, partial clone y submodules, y los monorepos se ayudan de hashes y nilos de CI que solo construyen lo que cambió.",
              ],
              def: {
                par: "Un monorepo es un repositorio único para varios proyectos y paquetes; técnicas como sparse checkout, partial clone y path filters lo mantienen ágil aunque crezca.",
                porQue: "Facilita el refactor transversal, garantiza una fuente de verdad común y simplifica el versionado de librerías internas.",
                cuando: "Ideal para equipos que comparten código entre servicios, publican paquetes internos o quieren un solo trigger de CI para toda la organización.",
              },
              concepts: [
                "Packages/workspaces: subdirectorios con su propio package.json y gestión de dependencias.",
                "Sparse checkout: solo descargas las carpetas que necesitas.",
                "Partial clone: evita bajar el historial completo al clonar.",
                "Path filters: workflows CI solo para el área tocada.",
                "Submodules: repositorios anidados con su propio control de versiones.",
              ],
              basic: {
                p: "Clonar de forma eficiente un monorepo grande descargando solo lo necesario.",
                code: [
                  "git clone --filter=blob:none --no-checkout <url>",
                  "git sparse-checkout init --cone",
                  "git sparse-checkout set api/ worker/ shared/",
                  "git checkout main",
                ],
                out: "Clonas solo lo necesario: miles de descargas evitadas en monorepos grandes.",
                lang: "bash",
              },
              intermediate: {
                p: "Versionar un directorio independiente dentro del monorepo como su propio origen con subtree.",
                code: [
                  "git subtree split --prefix=libs/auth -b auth-export",
                  "git push origin auth-export",
                ],
                caption: "Exportar un paquete del monorepo a su propio repo",
              },
              real: {
                p: "Una empresa con 60 microservicios decidió consolidar en un monorepo: los equipos comparten tipos de contrato comunes, los refactors de API se propagan de golpe y el CI con path filters solo prueba lo tocado. El ahorro de cabeceras fue del 40%.",
                ul: [
                  "Adopta una división de paquetes clara y una política de versionado de librerías internas.",
                  "Usa sparse checkout para developers que solo trabajan en su área.",
                  "Configura path filters en todos los pipelines para no construir lo innecesario.",
                  "Empaquetado como paquete: conserva la procedencia de quién modifica qué.",
                ],
                code: [
                  "on:",
                  "  push:",
                  "    paths:",
                  "      - 'api/**'",
                  "      - 'shared/**'",
                ],
                nota: "Los submodules por otra parte mantienen independencia de versiones, pero suman complejidad de sincronización.",
              },
              expl: [
                "El formato de objeto Git por blob permite clonar con filtros para no bajar el histórico gigante.",
                "Sparse checkout crea una vista parcial del árbol de trabajo.",
                "Las workspaces (npm/pnpm) resuelven dependencias entre paquetes con symlinks.",
                "Los path filters en CI con solo 2-3 directorios ahorran el 80% de los builds.",
                "Elegir entre monorepo y multirepo depende de la cultura de tu equipo, no solo de la técnica.",
              ],
              errors: [
                "Construir todo el monorepo en cada pipeline: el tiempo de espera exaspera al equipo.",
                "Un solo package.json para toda la base: rompe el aislamiento de versiones.",
                "Submodules sin documentación: cada dev tropieza con su sincronización.",
              ],
              tips: [
                "Empieza pequeño: agrupa 2-3 paquetes y mide la fricción antes de abrazar el monorepo total.",
                "Automatiza el mapa de dependencias para que el CI construya solo lo afectado.",
                "Prueba el flujo de contribución: clonar con sparse debe ser trivial.",
              ],
              exercise: [
                "Clona un monorepo público grande con sparse checkout y mide el ahorro.",
                "Configura path filters en un workflow para solo correr los tests del área tocada.",
                "Divide un servicio en dos paquetes de workspace y versiona su dependencia.",
              ],
              summary: [
                "El monorepo centraliza código y configuración en un único repositorio.",
                "Sparse checkout, partial clone y path filters lo mantienen ágil.",
                "Workspaces y CI selectivo convierten la escala en un problema resuelto.",
              ],
              lang: "bash",
              exampleFile: "monorepos-escala",
              desc: "Adopta monorepos o trabaja con submodules y repos grandes a escala.",
            },
          },
          {
            id: "troubleshooting-reflog",
            title: "Troubleshooting avanzado: reflog y cirugía segura",
            duration: "11 min",
            level: "avanzado",
            category: "automatización",
            cardText: "Recupera lo que creías perdido y deshaz desaguisados sin pánico.",
            desc: "Recupera trabajo perdido con reflog y haz cirugía de historial segura.",
            body: {
              intro: [
                "A todos nos ha pasado: un reset --hard en la rama equivocada, un rebase que salió mal o un commit que 'desapareció'. La buena noticia es que Git guarda un diario de todo lo que hiciste: el reflog.",
                "Con el reflog y unas cuantas operaciones de cirugía controlada (filter-repo, reset, rebase) se recupera o se repara cualquier historial. La clave es saber exactamente qué comando usar según el daño.",
              ],
              def: {
                par: "El reflog es un historial local de las referencias que apuntan a commits (HEAD, ramas) y registra cada movimiento que haces, lo que permite volver a un estado aunque lo hayas 'perdido' por un reset o rebase.",
                porQue: "Git no borra inmediatamente: los commits que dejas de referenciar permanecen apuntados por el reflog hasta que los recolecta garbage. Siempre hay camino de vuelta.",
                cuando: "Después de un reset --hard, un rebase roto o un merge caprichoso: antes de tocar nada, consulta el reflog.",
              },
              concepts: [
                "Reflog: registro de posiciones de HEAD y ramas con timestamps.",
                "reset --hard: mueve la rama y el árbol; peligroso pero recuperable vía reflog.",
                "restore/checkout: recupera ficheros individuales de un commit cualquiera.",
                "filter-repo: filtra o reescribe historial (borra secretos, cambia autor).",
                "GC (garbage collection): el momento en que Git borra definitivamente los huérfanos.",
              ],
              basic: {
                p: "El movimiento estrella: volver atrás después de un reset --hard usando el reflog.",
                code: [
                  "git reset --hard HEAD~2",
                  "git reflog",
                  "# 0a1b2c HEAD@{0}: reset: moving to HEAD~2",
                  "# 9f8e7d HEAD@{1}: commit: feat(api): añade paginación",
                  "# vuelve al punto previo al reset",
                  "git reset --hard 9f8e7d",
                ],
                out: "El commit 'perdido' vuelve: el reflog lo mantuvo accesible.",
                lang: "bash",
              },
              intermediate: {
                p: "Borrar un secreto que se coló en el historial con git filter-repo (reescribe los commits).",
                code: [
                  "git filter-repo --path .env --invert-paths",
                  "git push --force-with-lease origin main",
                  "",
                  "# elimina un autor del historial",
                  "git filter-repo --mailmap mailmap.txt",
                ],
                caption: "Cirugía de historial con filter-repo",
              },
              real: {
                p: "Un error de merge rompió la config de despliegue y el equipo confió en una rama ya resetada. Con el reflog identificaron el commit bueno en segundos, hicieron cherry-pick de los cambios y siguieron; el incidente duró 10 minutos.",
                ul: [
                  "Antes de cualquier reset destructivo, anota el SHA o consulta reflog.",
                  "Nunca fuerces push a ramas compartidas sin --force-with-lease.",
                  "Para borrar secretos del historial usa filter-repo y revoca la credencial ya filtrada.",
                  "Documenta los rescates del equipo para que nadie sufra lo mismo dos veces.",
                ],
                code: [
                  "git branch rescue main",
                  "git checkout rescue",
                  "git cherry-pick 9f8e7d^..9f8e7d",
                  "git push origin rescue",
                ],
                nota: "filter-repo reescribe los hash de todos los commits: todos los forks y clones deben sincronizarse después.",
              },
              expl: [
                "El reflog es local: solo tu máquina lo ve; los demás no tienen su copia.",
                "reset mueve la punta de la rama; el commit queda huérfano hasta que GC lo borra (30 días por defecto).",
                "restore y checkout extraen ficheros de cualquier commit sin mover la rama.",
                "filter-repo es la herramienta de cirugía ficil: filtra, mapea y reescribe histórico.",
                "--force-with-lease protege a tus compañeros: solo fuerza si su versión está intacta.",
              ],
              errors: [
                "Hacer push --force a una rama compartida sin avisar: rompes historial ajeno.",
                "Recurrir al GC por miedo: revisa primero el reflog; Git guarda lo suficiente.",
                "Borrar un secreto solo del HEAD: sigue viviendo en el historial profundo.",
              ],
              tips: [
                "Configura los hook de reflog lifetime o simplemente no borres el .git.",
                "Si un rescatista va por pronto, guarda un backup de la rama con git branch rescue.",
                "Revoca la credencial que se te escapó SIEMPRE, incluso en repos privados.",
              ],
              exercise: [
                "Haz un reset --hard y recupérate con el reflog.",
                "Recupera un fichero concreto de un commit viejo sin tocar la rama.",
                "Crea un repos de prueba, filtra un archivo con filter-repo y force-mueve una rama propia.",
              ],
              summary: [
                "El reflog es tu seguro de vida: recupera estados que creíste perdidos.",
                "reset, restore y cherry-pick permiten reparar daños con calma.",
                "filter-repo hace cirugía grande, y la revocación siempre acompaña a la fuga.",
              ],
              lang: "bash",
              exampleFile: "troubleshooting-reflog",
              desc: "Recupera trabajo perdido con reflog y haz cirugía de historial segura.",
            },
          },
          {
            id: "contribuir-open-source",
            title: "Contribuir a proyectos open source",
            duration: "10 min",
            level: "avanzado",
            category: "automatización",
            cardText: "Del primer issue a tu primer PR aprobado en proyectos ajenos.",
            desc: "Contribuye con calidad a proyectos open source de manera efectiva.",
            body: {
              intro: [
                "Contribuir a open source es de los mejores entrenamientos: código real, revisores reales y una comunidad donde tu trabajo queda visible. También es un primer encuentro con las convenciones y expectativas de proyectos mantenidos por cientos de personas.",
                "La clave está en la preparación: leer el CONTRIBUTING, empezar con issues marcados como good first issue y crear un PR pequeño y claro. Un PR atropellado puede cerrarse sin aviso; uno bien preparado se aprueba.",
              ],
              def: {
                par: "Contribuir a un proyecto open source implica clonar o hacer fork, trabajar en una rama, abrir un PR concordante con el CONTRIBUTING del proyecto y pasar su CI, en un flujo asíncrono con revisores voluntarios.",
                porQue: "Es una cartera pública de trabajo real, una forma de aprender del estilo de código de proyectos maduros y una red de referentes para tu carrera.",
                cuando: "Cuando domines las bases de Git y GitHub y quieras suma a proyectos que usas y admiras.",
              },
              concepts: [
                "Fork: copia del repo en tu cuenta para proponer cambios desde ahí.",
                "Upstream: el repositorio original del que mantienes sincronizado tu fork.",
                "CONTRIBUTING.md: las reglas de contribución de cada proyecto.",
                "Good first issue: issues etiquetados para quienes empiezan.",
                "PR de calidad: pequeño, testado, con descripción y conexión con issue.",
              ],
              basic: {
                p: "Flujo completo: fork, clona, rama, commit, push y PR contra upstream.",
                code: [
                  "gh repo fork autorepo/autorepo --clone",
                  "cd autorepo",
                  "git checkout -b feat/42-mejora-logging",
                  "git add . && git commit -m \"feat(log): añade nivel de trace\"",
                  "git push origin feat/42-mejora-logging",
                  "gh pr create --base main --helpful",
                ],
                out: "Un PR listo para revisión apuntando al repositorio original.",
                lang: "bash",
              },
              intermediate: {
                p: "Mantener tu fork sincronizado con el upstream para que el PR nunca se envejezca.",
                code: [
                  "git remote add upstream https://github.com/autorepo/autorepo.git",
                  "git fetch upstream",
                  "git checkout main && git merge upstream/main",
                  "git push origin main",
                  "",
                  "# revisa tu rama comparada con upstream actualizado",
                  "git fetch upstream",
                  "git rebase upstream/main feat/42-mejora-logging",
                ],
                caption: "Sincronizar fork y rebasar la rama del PR",
              },
              real: {
                p: "Una junior consiguió su primer PR aprobado en un proyecto de menciones de seguridad: leyó el CONTRIBUTING, tomó un good first issue sobre validar inputs, añadió tests y llegó con cambios pequeños al cabo de pocos días de iteración.",
                ul: [
                  "Busca issues etiquetados 'good first issue' o 'help wanted'.",
                  "Lee el CONTRIBUTING y respeta su estilo, tests y plantillas de PR.",
                  "Comenta en el issue tu intención antes de empezar a codificar.",
                  "Responde con humildad y rapidez a los comentarios del reviewer.",
                ],
                code: [
                  "gh issue list --label 'good first issue'",
                  "gh issue view 1234",
                ],
                nota: "La paciencia es el recurso escaso: revisores voluntarios llegan cuando llegan.",
              },
              expl: [
                "El fork crea un repo público bajo tu cuenta; el PR compara tu rama con la del proyecto original.",
                "Respetar el CONTRIBUTING reduce a la mitad el diálogo antes del primer push.",
                "Mantener el fork fresco con upstream evita que tu PR se quede obsoleto.",
                "Los proyectos usan interceptors de estilo (lint) que corren en su CI.",
                "Tu historial de PRs en GitHub habla de tu forma de trabajar: cuídalo.",
              ],
              errors: [
                "Soltar un PR enorme sin contexto: los revisores lo cierran por falta de foco.",
                "No hacer fork desde la copia del repo: complicas la actualización.",
                "Discutir el CI en lugar de correrlo localmente antes de abrir.",
              ],
              tips: [
                "Empieza por repos de medianos con issues bien etiquetados y CI rápido.",
                "Escucha los reviews como oportunidad, no como juicio.",
                "Remarca tu trabajo en el apartado de cartera de tu perfil profesional.",
              ],
              exercise: [
                "Forkea un repo que uses y resuleve un good first issue.",
                "Mantén tu fork sincronizado con upstream durante una semana.",
                "Revisa dos PRs de otros para aprender el flujo desde el lado del reviewer.",
              ],
              summary: [
                "Contribuir empieza por el CONTRIBUTING y los good first issue.",
                "Fork, rama, PR pequeño y sincronización constante con upstream.",
                "Tu trabajo queda público: la constancia en PRs de calidad construye reputación.",
              ],
              lang: "bash",
              exampleFile: "contribuir-open-source",
              desc: "Contribuye con calidad a proyectos open source de manera efectiva.",
            },
          },
          {
            id: "branching-multiteam",
            title: "Branching multiteam",
            duration: "10 min",
            level: "avanzado",
            category: "automatización",
            cardText: "Estrategias de ramas cuando varios equipos comparten el repositorio.",
            desc: "Diseña estrategias de branching para equipos grandes y releases coordinadas.",
            body: {
              intro: [
                "Cuando tres equipos viven en el mismo repositorio, las decisiones de ramas dejan de ser personales: qué se fusiona a main, cuándo se congela una release y cómo viaja una hotfix a producción son decisiones de plataforma.",
                "Las estrategias maduras combinan ramas de soporte (main, develop, release) con el principio de compatibilidad continua, y definen quién escribe en cada rama y qué protecciones la cubren.",
              ],
              def: {
                par: "El branching multiteam organiza ramas de desarrollo, integración y releases (a menudo main + release branches), con reglas de fusión, protección y soporte para que equipos paralelos no se pisen ni rompan la release.",
                porQue: "La integración continua funciona solo si hay una rama compartida estable y controles de calidad que la protejen.",
                cuando: "Cuando hay más de un equipo tocando el mismo código o releases coordinadas con clientes.",
              },
              concepts: [
                "main: la rama de integración continua y única con fuente de verdad.",
                "develop: (opcional) rama de integración de funcionalidades.",
                "release branch: rama congelada para cada versión entregada.",
                "hotfix branch: rama corta que sale de main o release y vuelve a las dos.",
                "Trunk-based vs GitFlow: integración diaria en main frente a ramas largas.",
              ],
              basic: {
                p: "El patrón trunk-based: todos integran a main a diario y los releases son etiquetas.",
                code: [
                  "git checkout main && git pull",
                  "git checkout -b feat/carrito-resumen",
                  "git commit -m \"feat(shop): resumen del carrito\"",
                  "git push origin feat/carrito-resumen",
                  "# PR → review → merge (squash) a main",
                  "# release = tag v1.4.0 + despliegue",
                ],
                out: "Integración continua en una sola rama estable, releases por tags.",
                lang: "bash",
              },
              intermediate: {
                p: "El flujo con release branches para soporte de versiones (modelo clásico feature/release).",
                code: [
                  "# al congelar v1.3",
                  "git checkout -b release/1.3 main",
                  "git push origin release/1.3",
                  "git tag v1.3.0",
                  "",
                  "# una hotfix sale de release ya desplegado",
                  "git checkout -b hotfix/1.3.1 release/1.3",
                  "git commit -m \"fix(pay): parsea moneda correctamente\"",
                ],
                caption: "Release branch con hotfix anclada",
              },
              real: {
                p: "Una plataforma con 4 equipos (api, web, mobile, data) definió main protegida, PRs obligatorios con CI, y release branches para las versiones de contrato con clientes. La hotfix a una release se aplica también a main: la disciplina evitó divergencias.",
                ul: [
                  "Que la PR incluya test, lint y veredicto del owner de la zona.",
                  "Usa squash merge para mantener main con commits limpios.",
                  "Define un dueño de la release: solo esa persona fusiona en la rama congelada.",
                  "Documenta qué rama sustenta cada entorno (dev/QA/prod).",
                ],
                code: [
                  "# tras validar la release",
                  "git checkout main && git merge --ff-only release/1.3",
                  "# o aplica la hotfix también a main",
                  "git cherry-pick <sha_hotfix>",
                ],
                nota: "La regla de oro: lo que no está en main no existe para los demás equipos.",
              },
              expl: [
                "Trunk-based acorta ciclo de retroalimentación: todo integra a diario y los PRs son pequeños.",
                "GitFlow añade ramas de soporte para releases coordinadas con mayor ceremonia.",
                "Las branch protection impiden que equipos remotos rompan la rama compartida.",
                "Las releases etiquetadas requieren del release branch congelado para el soporte.",
                "Cualquier estrategia vale si hay protecciones, owners y disciplina de fusiòn.",
              ],
              errors: [
                "Ramas que viven semanas sin integrar: conflictos y sprint al final.",
                "Nadie dueño de la release: todos escriben en rama congelada.",
                "Merge a main sin PR ni CI: una reconstrucción cara para el resto.",
              ],
              tips: [
                "Elige una estrategia simple y hazla cumplir con protección y plantillas de PR.",
                "Si empiezas, trunk-based + tags es la opción más baja en fricción.",
                "Celebra los merge limpios: la disciplina se enseña con ejemplo.",
              ],
              exercise: [
                "Define para tu repo un flujo trunk-based con main protegida.",
                "Crea una release branch ficticia y simula aplicación de hotfix.",
                "Revisa la estrategia de ramas de un proyecto real y propón mejoras.",
              ],
              summary: [
                "El branching multiteam exige una estrategia clara, descrita y protegida.",
                "Trunk-based integra a diario; GitFlow coordina releases con ramas de soporte.",
                "Con dueños, protecciones y squash merges, la rama principal nunca se rompe.",
              ],
              lang: "bash",
              exampleFile: "branching-multiteam",
              desc: "Diseña estrategias de branching para equipos grandes y releases coordinadas.",
            },
          },
        ],
      },
    ],
  },
];