// _curriculum_patrones.mjs
// Currículum del curso de Patrones de Diseño.
// Exporta COURSES con todos los módulos y lecciones.
// Las lecciones existentes en disco se listan SIN body (no se regeneran);
// las nuevas (módulo 07) llevan body completo (11 secciones estándar + metadatos).

export const COURSES = [
  {
    slug: "patrones",
    title: "Patrones de Diseño",
    modules: [
      {
        id: "modulo-01",
        n: 1,
        t: "Fundamentos de patrones",
        level: "avanzado",
        caption: "Qué es un patrón, su anatomía y el catálogo GOF.",
        desc: "Define qué es un patrón de diseño, recorre el catálogo GOF y aprende a estudiarlos por contexto, problema y solución antes que por su diagrama de clases.",
        subtitle: "Los patrones no se memorizan: se reconocen en contexto.",
        objectives: [
          "Entender qué es un patrón y cuál es su anatomía",
          "Recorrer el catálogo GOF y sus tres familias",
          "Relacionar patrones, principios SOLID y arquitectura",
          "Adoptar una estrategia real para aprender patrones",
        ],
        lessons: [
          {
            id: "catalogo-gof",
            title: "El catálogo GOF",
            duration: "10 min",
            level: "avanzado",
            category: "fundamentos",
            cardText: "Los 23 patrones del libro de la Gang of Four organizados en creacionales, estructurales y de comportamiento.",
            desc: "Recorre el catálogo GOF y clasifica sus 23 patrones por familia.",
          },
          {
            id: "patrones-con-cabeza",
            title: "Aprender patrones con cabeza",
            duration: "9 min",
            level: "avanzado",
            category: "fundamentos",
            cardText: "Estrategias para interiorizar patrones: contexto, problema y solución en vez de memorizar diagramas.",
            desc: "Aprende a asimilar patrones por contexto, problema y solución.",
          },
          {
            id: "patrones-principios-arquitectura",
            title: "Patrones, principios y arquitectura",
            duration: "8 min",
            level: "avanzado",
            category: "fundamentos",
            cardText: "Cómo se conectan los patrones GoF, los principios SOLID y las decisiones de arquitectura de un backend.",
            desc: "Conecta los patrones con SOLID y la arquitectura de tu backend.",
          },
          {
            id: "que-es-un-patron",
            title: "¿Qué es un patrón?",
            duration: "8 min",
            level: "avanzado",
            category: "fundamentos",
            cardText: "Definición de patrón de diseño, su anatomía y por qué reutilizamos soluciones probadas.",
            desc: "Qué es un patrón de diseño y cuándo tiene sentido aplicarlo.",
          },
        ],
      },
      {
        id: "modulo-02",
        n: 2,
        t: "Patrones creacionales",
        level: "avanzado",
        caption: "Cómo y quién construye tus objetos.",
        desc: "Singleton, Factory Method, Abstract Factory y Builder: los patrones que controlan la creación de objetos para que tu código quede desacoplado de las clases concretas.",
        subtitle: "Construir objetos bien es la mitad del diseño.",
        objectives: [
          "Aplicar Singleton cuando una única instancia es obligatoria",
          "Delegar la creación con Factory Method",
          "Componer familias de objetos con Abstract Factory",
          "Montar objetos complejos con Builder",
          "Elegir el patrón creacional adecuado a cada problema",
        ],
        lessons: [
          {
            id: "abstract-factory",
            title: "Abstract Factory",
            duration: "9 min",
            level: "avanzado",
            category: "creacional",
            cardText: "Familias de objetos relacionados sin acoplar el cliente a clases concretas.",
            desc: "Abstract Factory para crear familias de objetos relacionados sin acoplamiento.",
          },
          {
            id: "builder",
            title: "Builder",
            duration: "10 min",
            level: "avanzado",
            category: "creacional",
            cardText: "Construye objetos complejos paso a paso, separando el montaje de la representación.",
            desc: "El patrón Builder para construir objetos complejos paso a paso.",
          },
          {
            id: "eligiendo-patron-creacional",
            title: "Eligiendo el patrón creacional",
            duration: "9 min",
            level: "avanzado",
            category: "creacional",
            cardText: "Criterios prácticos para elegir entre Singleton, Factory, Abstract Factory y Builder.",
            desc: "Cómo decidir qué patrón creacional encaja en cada contexto.",
          },
          {
            id: "factory-method",
            title: "Factory Method",
            duration: "9 min",
            level: "avanzado",
            category: "creacional",
            cardText: "Un método fábrica que delega en las subclases la decisión de qué objeto crear.",
            desc: "Factory Method para delegar la instanciación a las subclases.",
          },
          {
            id: "singleton",
            title: "Singleton",
            duration: "8 min",
            level: "avanzado",
            category: "creacional",
            cardText: "Garantiza una única instancia de un recurso compartido y un punto global de acceso.",
            desc: "El patrón Singleton y sus alternativas modernas en backend.",
          },
        ],
      },
      {
        id: "modulo-03",
        n: 3,
        t: "Patrones estructurales",
        level: "avanzado",
        caption: "Componer clases y objetos para formar estructuras mayores.",
        desc: "Adapter, Facade, Proxy, Decorator y Composite: los patrones que organizan la relación entre clases para ampliar funcionalidad sin reescribir código.",
        subtitle: "La composición bien hecha evita la herencia forzada.",
        objectives: [
          "Adaptar interfaces incompatibles con Adapter",
          "Ocultar subsistemas complejos con Facade",
          "Controlar el acceso a objetos con Proxy",
          "Extender comportamiento en caliente con Decorator",
          "Tratar jerarquías de forma uniforme con Composite",
        ],
        lessons: [
          {
            id: "adapter",
            title: "Adapter",
            duration: "9 min",
            level: "avanzado",
            category: "estructural",
            cardText: "Traduce interfaces incompatibles para integrar librerías y servicios externos.",
            desc: "Adapter para conectar interfaces incompatibles en tu backend.",
          },
          {
            id: "composite",
            title: "Composite",
            duration: "9 min",
            level: "avanzado",
            category: "estructural",
            cardText: "Trata estructuras de árbol de forma uniforme: un objeto compuesto como si fuera simple.",
            desc: "Composite para trabajar con jerarquías de objetos de forma uniforme.",
          },
          {
            id: "decorator",
            title: "Decorator",
            duration: "9 min",
            level: "avanzado",
            category: "estructural",
            cardText: "Añade responsabilidades a un objeto dinámicamente sin tocar su clase.",
            desc: "Decorator para extender el comportamiento sin modificar la clase.",
          },
          {
            id: "facade",
            title: "Facade",
            duration: "8 min",
            level: "avanzado",
            category: "estructural",
            cardText: "Una fachada sencilla que oculta la complejidad de un subsistema.",
            desc: "Facade para simplificar el acceso a subsistemas complejos.",
          },
          {
            id: "proxy",
            title: "Proxy",
            duration: "9 min",
            level: "avanzado",
            category: "estructural",
            cardText: "Un sustituto que controla el acceso a otro objeto: caché, seguridad o carga diferida.",
            desc: "Proxy para controlar el acceso a un objeto real.",
          },
        ],
      },
      {
        id: "modulo-04",
        n: 4,
        t: "Patrones de comportamiento",
        level: "avanzado",
        caption: "Asignar responsabilidades y modelar la comunicación.",
        desc: "Strategy, Observer, Command, State y Template Method: los patrones que definen cómo colaboran los objetos y cómo se comunican entre sí.",
        subtitle: "El comportamiento vive en la colaboración entre objetos.",
        objectives: [
          "Intercambiar algoritmos en caliente con Strategy",
          "Reaccionar a eventos con Observer",
          "Encapsular acciones con Command",
          "Modelar cambios de estado con State",
          "Fijar el esqueleto de un flujo con Template Method",
        ],
        lessons: [
          {
            id: "command",
            title: "Command",
            duration: "9 min",
            level: "avanzado",
            category: "comportamiento",
            cardText: "Encapsula una acción como objeto: colas de tareas, deshacer e historial de operaciones.",
            desc: "Command para encapsular acciones y retrasarlas o deshacerlas.",
          },
          {
            id: "observer-y-eventos",
            title: "Observer y eventos",
            duration: "10 min",
            level: "avanzado",
            category: "comportamiento",
            cardText: "Notifica a múltiples interesados cuando cambia el estado de un sujeto.",
            desc: "Observer y eventos para reaccionar a cambios de estado.",
          },
          {
            id: "state",
            title: "State",
            duration: "9 min",
            level: "avanzado",
            category: "comportamiento",
            cardText: "Un objeto cambia su comportamiento según su estado interno.",
            desc: "State para que un objeto altere su comportamiento con su estado.",
          },
          {
            id: "strategy",
            title: "Strategy",
            duration: "9 min",
            level: "avanzado",
            category: "comportamiento",
            cardText: "Intercambia algoritmos en tiempo de ejecución manteniendo la misma interfaz.",
            desc: "Strategy para seleccionar el algoritmo en caliente.",
          },
          {
            id: "template-method",
            title: "Template Method",
            duration: "8 min",
            level: "avanzado",
            category: "comportamiento",
            cardText: "Define el esqueleto de un algoritmo y deja los pasos concretos a las subclases.",
            desc: "Template Method para fijar el flujo y variar los pasos.",
          },
        ],
      },
      {
        id: "modulo-05",
        n: 5,
        t: "Patrones de backend",
        level: "avanzado",
        caption: "Estructura limpia para la capa de negocio y datos.",
        desc: "Repository, Service Layer, DTO y Unit of Work: los patrones que organizan la lógica de negocio y la persistencia en aplicaciones backend reales.",
        subtitle: "El backend se mantiene vivo cuando sus capas están separadas.",
        objectives: [
          "Aislar la persistencia tras Repository",
          "Centralizar la lógica de negocio con Service Layer",
          "Controlar el contrato de red con DTOs",
          "Agrupar cambios con Unit of Work y transacciones",
        ],
        lessons: [
          {
            id: "dto-y-objetos-de-transferencia",
            title: "DTO y objetos de transferencia",
            duration: "8 min",
            level: "avanzado",
            category: "backend",
            cardText: "Desacopla el dominio de lo que viaja por la red con DTOs explícitos.",
            desc: "DTOs para controlar el contrato de tus APIs.",
          },
          {
            id: "repository-y-capa-de-datos",
            title: "Repository y la capa de datos",
            duration: "10 min",
            level: "avanzado",
            category: "backend",
            cardText: "Aísla el acceso a datos tras una interfaz centrada en tu dominio.",
            desc: "Repository para desacoplar la persistencia del resto de la aplicación.",
          },
          {
            id: "service-layer-en-accion",
            title: "Service Layer en acción",
            duration: "10 min",
            level: "avanzado",
            category: "backend",
            cardText: "Centraliza la lógica de negocio entre los controladores y los repositorios.",
            desc: "Service Layer para organizar la lógica de negocio.",
          },
          {
            id: "unit-of-work-y-transacciones",
            title: "Unit of Work y transacciones",
            duration: "10 min",
            level: "avanzado",
            category: "backend",
            cardText: "Agrupa varios cambios en una transacción atómica para garantizar consistencia.",
            desc: "Unit of Work para agrupar cambios y garantizar consistencia.",
          },
        ],
      },
      {
        id: "modulo-06",
        n: 6,
        t: "Patrones modernos",
        level: "avanzado",
        caption: "DI, eventos y CQRS para backend contemporáneo.",
        desc: "Dependency Injection, event-driven, CQRS y el reconocimiento de antipatrones: las herramientas con las que los backends modernos se mantienen desacoplados y testables.",
        subtitle: "Los patrones evolucionan con la arquitectura del software.",
        objectives: [
          "Aplicar Dependency Injection de forma consciente",
          "Desacoplar servicios con una arquitectura event-driven",
          "Separar lecturas y escrituras con CQRS",
          "Reconocer antipatrones clásicos para evitarlos",
        ],
        lessons: [
          {
            id: "antipatrones-clasicos",
            title: "Antipatrones clásicos",
            duration: "10 min",
            level: "avanzado",
            category: "moderno",
            cardText: "God class, spaghetti code y otros antipatrones que conviene reconocer a tiempo.",
            desc: "Antipatrones clásicos y cómo evitarlos en backend.",
          },
          {
            id: "cqrs-lectura-escritura",
            title: "CQRS: lectura y escritura",
            duration: "10 min",
            level: "avanzado",
            category: "moderno",
            cardText: "Separa los modelos de lectura y escritura para escalar cada lado por separado.",
            desc: "CQRS para optimizar lecturas y escrituras de forma independiente.",
          },
          {
            id: "dependency-injection",
            title: "Dependency Injection",
            duration: "10 min",
            level: "avanzado",
            category: "moderno",
            cardText: "Invierte el control: entrega las dependencias en lugar de crearlas dentro.",
            desc: "Dependency Injection para desacoplar componentes.",
          },
          {
            id: "event-driven-y-mensajeria",
            title: "Event-driven y mensajería",
            duration: "11 min",
            level: "avanzado",
            category: "moderno",
            cardText: "Publica eventos y deja que otros servicios reaccionen sin conocerse.",
            desc: "Arquitectura event-driven para desacoplar servicios.",
          },
        ],
      },
      {
        id: "modulo-07",
        n: 7,
        t: "Patrones emergentes y arquitectura moderna",
        level: "avanzado",
        caption: "Hexagonal, resiliencia y flujos distribuidos fiables.",
        desc: "Arquitectura hexagonal, outbox pattern, circuit breaker y API Gateway frente a microservicios: los patrones que necesitas para sistemas modernos y resilientes.",
        subtitle: "El patrón correcto hoy es el que mantiene tu sistema vivo mañana.",
        objectives: [
          "Diseñar con arquitectura hexagonal y puertos y adaptadores",
          "Garantizar mensajería fiable con el outbox pattern",
          "Aislar fallos de terceros con circuit breaker",
          "Unificar el acceso externo con API Gateway y BFF",
        ],
        lessons: [
          {
            id: "arquitectura-hexagonal",
            title: "Arquitectura hexagonal",
            duration: "12 min",
            level: "avanzado",
            category: "emergente",
            cardText: "Aísla tu dominio del mundo exterior con puertos y adaptadores.",
            desc: "Arquitectura hexagonal para mantener el dominio independiente de la infraestructura.",
            body: {
              intro: [
                "Los backends que sobreviven años no son los que tienen mejor tecnología, sino los que pueden cambiar de base de datos, de cola de mensajes o de pasarela de pago sin reescribir la lógica de negocio. La arquitectura hexagonal, también llamada puertos y adaptadores, existe para eso.",
                "La idea es sencilla: el dominio, el corazón de tu aplicación, no sabe nada del mundo exterior. Todo lo que entra y sale (HTTP, base de datos, mensajería) viaja a través de interfaces llamadas puertos, y las implementaciones concretas son los adaptadores.",
              ],
              def: {
                par: "La arquitectura hexagonal organiza la aplicación en un núcleo (dominio y casos de uso) aislado del exterior mediante puertos (interfaces) que cada adaptador externo implementa, de modo que la infraestructura es intercambiable.",
                porQue: "En backend, la base de datos, la cola y el framework cambian más rápido de lo que te gustaría. Si el dominio solo depende de interfaces, esos cambios se convierten en reemplazar un adaptador, no en una reescritura.",
                cuando: "Úsala cuando el proyecto va a vivir varios años, hay varias fuentes de datos o quieres probar el núcleo sin levantar infraestructura. No la forces en scripts simples o prototipos desechables.",
              },
              concepts: [
                "Dominio: entidades y reglas de negocio sin importar HTTP ni SQL.",
                "Puerto (port): interfaz que el dominio declara y necesita.",
                "Adaptador (adapter): implementación concreta de ese puerto.",
                "Infraestructura: controladores HTTP, repositorios SQL, clientes de colas.",
                "Testeabilidad: se prueba el núcleo con dobles en lugar de servicios reales.",
              ],
              basic: {
                p: "Definimos un puerto para la persistencia de pedidos y una implementación en memoria. El caso de uso solo conoce la interfaz.",
                code: [
                  "class PedidoRepositorio:",
                  "    def guardar(self, pedido): ...",
                  "    def buscar(self, id_pedido): ...",
                  "",
                  "class PedidoRepositorioEnMemoria(PedidoRepositorio):",
                  "    def __init__(self):",
                  "        self.pedidos = {}",
                  "    def guardar(self, pedido):",
                  "        self.pedidos[pedido.id] = pedido",
                  "    def buscar(self, id_pedido):",
                  '        return self.pedidos.get(id_pedido)',
                  "",
                  "class CrearPedido:",
                  "    def __init__(self, repo: PedidoRepositorio):",
                  "        self.repo = repo",
                  "    def ejecutar(self, pedido):",
                  "        self.repo.guardar(pedido)",
                  "        return pedido",
                ],
                out: "CrearPedido usa cualquier implementación de PedidoRepositorio.",
                lang: "python",
              },
              intermediate: {
                p: "Añadir un adaptador PostgreSQL solo requiere implementar el mismo puerto. El dominio no cambia una línea.",
                code: [
                  "import psycopg",
                  "",
                  "class PedidoRepositorioPostgres(PedidoRepositorio):",
                  "    def __init__(self, dsn):",
                  "        self.conn = psycopg.connect(dsn)",
"    def guardar(self, pedido):",
                  "        with self.conn.cursor() as cur:",
                  "            cur.execute(",
                  '                "INSERT INTO pedidos (id, total) VALUES (%s, %s)",',
                  "                (pedido.id, pedido.total)",
                  "            )",
                  "        self.conn.commit()",
                  "    def buscar(self, id_pedido):",
                  "        with self.conn.cursor() as cur:",
                  '            cur.execute("SELECT id, total FROM pedidos WHERE id = %s", (id_pedido,))',
                  "            fila = cur.fetchone()",
                  "            return {'id': fila[0], 'total': fila[1]}",
                ],
                caption: "Adaptador PostgreSQL del mismo puerto",
              },
              real: {
                p: "Una plataforma de e-commerce cambió su API de pagos y su base de datos en el mismo año. Como el dominio dependía de puertos, el cambio fue añadir dos adaptadores nuevos y arrancar la app con otras configuraciones.",
                ul: [
                  "Coloca las interfaces (puertos) en el mismo paquete que el dominio.",
                  "Inyecta los adaptadores desde el punto de arranque, no desde el dominio.",
                  "Mantén el dominio libre de imports de frameworks y drivers.",
                  "Aprovecha la hexagonal para testear sin levantar Postgres ni Redis.",
                ],
                code: [
                  "def main():",
                  "    repo = PedidoRepositorioPostgres(dsn=config.dsn)",
                  "    caso = CrearPedido(repo)",
                  "    app = WebApp()",
                  "    app.casos_de_uso[\"crear_pedido\"] = caso",
                  "    app.run()",
                ],
                nota: "El framework web es otro adaptador: el caso de uso se invoca igual desde FastAPI que desde una CLI.",
              },
              expl: [
                "Los puertos se dibujan como hexágonos porque la estructura no impone una dirección de entrada única: entra y sale por cualquier lado.",
                "La regla de dependencia apunta siempre hacia dentro: el dominio nunca importa infraestructura.",
                "Separar puertos de su implementación hace los tests unitarios triviales.",
                "No confundas hexagonal con microservicios: es una organización interna que funciona también en monolitos.",
                "El coste es más indirección; recompénsalo solo cuando el proyecto se beneficie de la flexibilidad.",
              ],
              errors: [
                "Convertir el dominio en un CRUD sin reglas: la persistencia manda y el patrón pierde sentido.",
                "Importar el driver de base de datos dentro de un caso de uso.",
                "Crear interfaces para absolutamente todo, incluso llamadas internas que nunca cambian.",
              ],
              tips: [
                "Empieza por los puertos de salida (base de datos, colas) que son los que más varían.",
                "Prueba el núcleo con implementaciones falsas en memoria.",
                "Si el proyecto es pequeño, aplica la idea de forma pragmática sin 30 carpetas vacías.",
              ],
              exercise: [
                "Extrae una interfaz para tu cliente de pagos y crea un adaptador Sandbox.",
                "Convierte tu repositorio Framework en un puerto con dos implementaciones del mismo.",
                "Escribe un test del caso de uso CrearPedido sin tocar infraestructura real.",
              ],
              summary: [
                "El dominio depende de puertos, y los adaptadores implementan esas interfaces.",
                "La infraestructura se vuelve intercambiable y el núcleo testable sin servicios reales.",
                "Es una inversión que vale la pena cuando el backend va a evolucionar durante años.",
              ],
              lang: "python",
              exampleFile: "arquitectura-hexagonal",
              desc: "Arquitectura hexagonal para mantener el dominio independiente de la infraestructura.",
            },
          },
          {
            id: "patron-outbox-mensajeria-fiable",
            title: "Outbox pattern y mensajería fiable",
            duration: "11 min",
            level: "avanzado",
            category: "emergente",
            cardText: "Publica eventos sin perder ninguno: de la base de datos al broker con garantías.",
            desc: "Outbox pattern para publicar eventos de forma fiable sin perder mensajes.",
            body: {
              intro: [
                "Cuando un pedido se confirma, quieres notificar a facturación, stock y email. Si publicas el evento en la cola dentro de la misma transacción que guarda el pedido, cualquier sistema de mensajería reparte esa actualización en dos sistemas que pueden fallar por separado.",
                "El resultado clásico de ese enfoque son eventos perdidos o duplicados que generan pedidos sin factura y stock desincronizado. El outbox pattern resuelve el problema con una tabla sencilla y un proceso que nunca olvida un mensaje.",
              ],
              def: {
                par: "El outbox pattern guarda en una tabla de la misma base de datos (outbox) tanto el estado de negocio como los eventos a publicar, dentro de la misma transacción. Un relayer publica después los eventos pendientes en el broker.",
                porQue: "Garantiza exactly-once en la creación y te permite mantener base de datos y broker eventualmente consistentes sin transacciones distribuidas.",
                cuando: "Úsalo cuando la publicación de eventos debe ser tan fiable como el commit de la base de datos. No lo necesitas en flujos donde perder un evento puntual es aceptable.",
              },
              concepts: [
                "Outbox: tabla que guarda los eventos pendientes de publicación.",
                "Transacción atómica: pedido y evento se guardan juntos o no se guarda nada.",
                "Relayer o publicador: lee la tabla y publica en el broker.",
                "Idempotencia: el consumidor procesa el mismo evento una sola vez.",
                "Deduplicación: un id único de evento permite descartar duplicados.",
              ],
              basic: {
                p: "Guardamos el pedido y su evento de confirmación en la misma transacción con SQL.",
                code: [
                  "BEGIN;",
                  '',
                  "INSERT INTO pedidos (id, estado) VALUES (101, 'confirmado');",
                  '',
                  "INSERT INTO outbox (id, agregado, tipo, payload, publicado)",
                  "VALUES (",
                  "   '9f3c...', 'pedido', 'pedido_confirmado',",
                  "   '{\"pedido_id\": 101}', false",
                  ");",
                  "",
                  "COMMIT;",
                ],
                out: "El pedido y su evento quedan a la vez: o los dos, o ninguno.",
                lang: "sql",
              },
              intermediate: {
                p: "El relayer consulta los eventos no publicados y los envía al broker, marcándolos después. Con un límite y orden por id garantizamos publicación en orden.",
                code: [
                  "def publicar_pendientes(broker, db):",
                  "    eventos = db.ejecutar(",
                  '        "SELECT * FROM outbox WHERE publicado = false "',
                  '        "ORDER BY id LIMIT 100 FOR UPDATE SKIP LOCKED"',
                  "    )",
                  "    for evento in eventos:",
                  "        broker.publicar(evento.tipo, evento.payload)",
                  "        db.ejecutar(",
                  '            "UPDATE outbox SET publicado = true WHERE id = %s",',
                  "            (evento.id,)",
                  "        )",
                  "        db.confirmar()",
                  "    return len(eventos)",
                ],
                caption: "Relayer que publica eventos pendientes",
              },
              real: {
                p: "Un marketplace marca millones de pedidos al día. Facturación, stock y notificaciones consumen pedido_confirmado desde la cola. El outbox garantiza que ningún pedido queda sin su evento, incluso si el broker cae en el peor momento.",
                ul: [
                  "Diseña los consumidores idempotentes: procesar dos veces un evento debe ser inocuo.",
                  "Reintenta con backoff y cola de mensajes muertos para eventos que fallan.",
                  "Monitorea el tamaño de la tabla outbox: un crecimiento indica un publicador caído.",
                  "Usa FOR UPDATE SKIP LOCKED para que varios publicadores no se pisen.",
                ],
                code: [
                  "class PedidoServicio:",
                  "    def confirmar(self, pedido_id):",
                  "        with self.db.transaccion():",
                  "            self.db.guardar_pedido(pedido_id, \"confirmado\")",
                  "            self.db.insertar_outbox(",
                  "                evento=\"pedido_confirmado\",",
                  '                payload=json.dumps({"pedido_id": pedido_id}),',
                  "            )",
                  "        # El event broker recibe el evento más tarde via relayer",
                ],
                nota: "Combinarlo con idempotencia en el consumidor convierte un sistema eventual en uno muy difícil de romper.",
              },
              expl: [
                "El punto clave es que la inserción del evento vive en la misma transacción que el cambio de negocio.",
                "El broker falla, pero el evento no se pierde: queda en la tabla hasta que el relayer lo publique.",
                "Si el relayer falla, la tabla crece y las métricas te avisan; el sistema no se corrompe.",
                "Los consumidores deben deduplicar por id de evento para tolerar reintentos.",
                "Es la alternativa pragmática a transacciones distribuidas de dos fases.",
              ],
              errors: [
                "Publicar el evento fuera de la transacción: se pierden eventos cuando el commit falla.",
                "Olvidar la idempotencia y duplicar facturas al reintentar.",
                "No limpiar la tabla: crece sin límite y degrada las consultas.",
              ],
              tips: [
                "Añade un índice eficiente sobre publicado y añade una marca de los eventos viejos.",
                "Elige ids de evento aleatorios (UUID) para detectar duplicados de forma fiable.",
                "Prueba el escenario exacto: apaga el broker, confirma un pedido y verifica que el evento aparece tarde.",
              ],
              exercise: [
                "Crea la tabla outbox y publica pedido_confirmado dentro de una transacción.",
                "Escribe un relayer con reintentos que no pierda orden para un agregado concreto.",
                "Simula la caída del broker y comprueba que el evento se publica al recuperarlo.",
              ],
              summary: [
                "El outbox guarda el evento con el cambio de negocio en la misma transacción.",
                "Un relayer publica los pendientes en el broker sin perder ninguno.",
                "Consumidores idempotentes convierten el diseño en un sistema robusto.",
              ],
              lang: "python",
              exampleFile: "patron-outbox",
              desc: "Outbox pattern para publicar eventos de forma fiable sin perder mensajes.",
            },
          },
          {
            id: "circuit-breaker-y-resiliencia",
            title: "Circuit breaker y resiliencia",
            duration: "10 min",
            level: "avanzado",
            category: "emergente",
            cardText: "Aísla fallos de servicios externos para que no tumben tu backend.",
            desc: "Circuit breaker para aislar fallos de dependencias y mantener tu backend vivo.",
            body: {
              intro: [
                "Cuando tu API depende de otra API lenta o caída, cada petición espera un tiempo hasta fallar. Con suficiente tráfico, esos tiempos muertos llenan los pools de conexiones y derriban también tu servicio.",
                "El circuit breaker actúa como un fusible: si una dependencia falla demasiado, dejas de llamarla durante un tiempo y devuelves una respuesta degradada, dando al sistema externo margen para recuperarse.",
              ],
              def: {
                par: "El circuit breaker monitoriza las llamadas a una dependencia y pasa por tres estados: cerrado (llama con normalidad), abierto (deja de llamar durante un tiempo de espera) y semicerrado (prueba una llamada de forma controlada).",
                porQue: "Evita que un fallo ajeno consuma tus recursos de forma indefinida y protege a la propia dependencia de un aluvión de peticiones cuando aún no se ha recuperado.",
                cuando: "Úsalo para cualquier llamada externa: APIs de pago, proveedores de envío, servicios de IA o bases de datos replicadas. No lo uses para fallos locales que no dependen de red.",
              },
              concepts: [
                "Fusible (breaker): decide si se llama a la dependencia o se degrada.",
                "Umbral de fallos: porcentaje o número de errores que abre el circuito.",
                "Tiempo de apertura: cuánto espera el circuito antes de reintentar.",
                "Semicerrado: permite un tráfico mínimo de prueba durante la recuperación.",
                "Fallback: respuesta alternativa cuando el circuito está abierto.",
              ],
              basic: {
                p: "Una implementación mínima: si superamos 5 fallos seguidos, abrimos el circuito durante 30 segundos.",
                code: [
                  "class CircuitBreaker:",
                  "    def __init__(self, umbral=5, tiempo_apertura=30):",
                  "        self.umbral = umbral",
                  "        self.tiempo_apertura = tiempo_apertura",
                  "        self.fallos = 0",
                  "        self.abierto_hasta = 0",
                  "",
                  "    def ejecutar(self, accion, fallback):",
                  "        if time.time() < self.abierto_hasta:",
                  '            return fallback("servicio no disponible")',
                  "        try:",
                  "            resultado = accion()",
                  "            self.fallos = 0",
                  "            return resultado",
                  "        except ExcepcionRemota:",
                  "            self.fallos += 1",
                  "            if self.fallos >= self.umbral:",
                  "                self.abierto_hasta = time.time() + self.tiempo_apertura",
                  "            return fallback(str(self.fallos))",
                ],
                out: "Tras 5 fallos, el circuito abre y responde con el fallback 30 segundos.",
                lang: "python",
              },
              intermediate: {
                p: "Usando una librería madura como pybreaker sobre un cliente HTTP, con estados observables.",
                code: [
                  "import pybreaker",
                  "from requests import Session",
                  "",
                  "breaker = pybreaker.CircuitBreaker(",
                  "    fail_max=5, reset_timeout=30",
                  ")",
                  "",
                  "def llamar_pasarela(session: Session, payload):",
                  "    try:",
                  "        with breaker:",
                  "            respuesta = session.post(PASARELA_URL, json=payload)",
                  "            respuesta.raise_for_status()",
                  "            return respuesta.json()",
                  "    except pybreaker.CircuitBreakerError:",
                  '        return {"estado": "degradado", "motivo": "pagos temporalmente no disponibles"}',
                  "    except requests.HTTPError:",
                  '        return {"estado": "error", "motivo": "la pasarela rechazó el pago"}',
                ],
                caption: "Circuit breaker con pybreaker sobre una pasarela de pago",
              },
              real: {
                p: "Durante un pico de black friday, una pasarela de pagos satura. Sin circuit breaker, cada compra bloqueaba un worker durante 45 segundos de timeout. Con el fusible, el sistema degrada tras el umbral y devuelve un mensaje de reintento en segundos.",
                ul: [
                  "Da siempre un fallback digno: caché, cola o mensaje de reintento.",
                  "Configura timeouts cortos: el circuit breaker complementa, no sustituye, el timeout.",
                  "Expón el estado del circuito en tus métricas para ver la degradación.",
                  "Prueba la apertura y la recuperación en staging con interrupciones simuladas.",
                ],
                code: [
                  "metrics.increment(\"circuit.pagos.estado\", breaker.estado)",
                  "if breaker.estado == \"abierto\":",
                  '    return Respuesta(503, "Inténtalo en unos segundos, estamos cuidando tus pagos")',
                ],
                nota: "El patrón brilla cuando cada componente externo tiene su propio fusible: uno caído no arrastra al resto.",
              },
              expl: [
                "En estado cerrado se mide la tasa de errores real de la dependencia.",
                "Al superar el umbral, el circuito abre y deja de hacer llamadas reales.",
                "El tiempo de espera (reset_timeout) da a la dependencia espacio para recuperarse.",
                "En semicerrado se deja pasar un tráfico mínimo de sondeo.",
                "El fallback es clave: más vale una respuesta degradada clara que un timeout ciego.",
              ],
              errors: [
                "Confundir el circuit breaker con un timeout: solo el fusible detiene la hemorragia de peticiones.",
                "Reintentar sin control durante la apertura, que reproduce el problema original.",
                "Olvidar resetear el contador tras un éxito y abrir el circuito por errores antiguos.",
              ],
              tips: [
                "Elige umbrales y tiempos según el SLO de la dependencia y los reintentos del cliente.",
                "Separa circuit breakers por proveedor y por operación crítica.",
                "Monitoriza aperturas: una apertura frecuente indica que necesitas un fallback mejor.",
              ],
              exercise: [
                "Implementa un circuit breaker manual y comprueba los tres estados.",
                "Añade un endpoint /health que reporte el estado del circuito de pagos.",
                "Configura pybreaker y simula un proveedor caído en pruebas de integración.",
              ],
              summary: [
                "El circuit breaker corta las llamadas a una dependencia fallida para protegerte.",
                "Requiere umbral, tiempo de espera y un semicerrado de prueba.",
                "Un buen fallback mantiene tu API útil aunque un tercero falle.",
              ],
              lang: "python",
              exampleFile: "circuit-breaker",
              desc: "Circuit breaker para aislar fallos de dependencias y mantener tu backend vivo.",
            },
          },
          {
            id: "api-gateway-y-bff",
            title: "API Gateway y Backend for Frontend",
            duration: "11 min",
            level: "avanzado",
            category: "emergente",
            cardText: "Un único punto de entrada que orquesta, autentica y agrega tus servicios.",
            desc: "API Gateway y Backend for Frontend para unificar el acceso a tus servicios.",
            body: {
              intro: [
                "Cuando un solo cliente tiene que hablar con usuarios, pedidos, pagos y búsqueda, las llamadas se multiplican, la seguridad se dispersa y cada refactor acopla a todos. El API Gateway concentra ese frente en un único punto de entrada.",
                "El Backend for Frontend (BFF) afina la idea: un backend adaptado a las necesidades de cada cliente concreto, de modo que la app móvil y la web reciben justo lo que necesitan, ni más ni menos.",
              ],
              def: {
                par: "Un API Gateway es un único punto de entrada que enruta, autentica, agrega y gestiona el tráfico hacia el resto de servicios internos. El BFF es una variante que crea una API específica para cada tipo de cliente.",
                porQue: "Reduce la complejidad del cliente, centraliza la seguridad y el rate limiting, y permite agregar varias llamadas internas en una sola respuesta de red.",
                cuando: "Úsalo al pasar de unos pocos microservicios a varios, o cuando distintos clientes necesitan contratos distintos. En monolitos pequeños añade latencia sin beneficio.",
              },
              concepts: [
                "Enrutado: reenvía cada petición al servicio responsable.",
                "Agregación: responde combinando llamadas a varios servicios.",
                "Autenticación central: valida tokens una sola vez en el borde.",
                "Rate limiting: protege los servicios de abuso desde fuera.",
                "BFF: una API adaptada por cliente (web, móvil, terceros).",
              ],
              basic: {
                p: "Una agregación sencilla: el gateway recibe /pedido/12 y encadena las llamadas a pedidos y cliente para devolver una sola respuesta.",
                code: [
                  "class PedidoGateway:",
                  "    def __init__(self, clientes, pedidos):",
                  "        self.clientes = clientes",
                  "        self.pedidos = pedidos",
                  "",
                  "    def pedido_completo(self, token, pedido_id):",
                  "        cliente = self.clientes.perfil(token)",
                  "        pedido = self.pedidos.obtener(pedido_id)",
                  "        return {",
                  '            "pedido": pedido,',
                  '            "cliente": cliente,',
                  "        }",
                ],
                out: "Dos llamadas internas se convierten en una respuesta para el cliente.",
                lang: "python",
              },
              intermediate: {
                p: "Configuración de un gateway con Express: enrutado con validación de token y límite de peticiones para clientes anónimos.",
                code: [
                  "const express = require('express');",
                  "const rateLimit = require('express-rate-limit');",
                  "",
                  "const app = express();",
                  "app.use(express.json());",
                  "",
                  "const limitador = rateLimit({ windowMs: 60000, max: 60 });",
                  "",
                  "app.post('/api/pagos', limitador, validarToken, async (req, res) => {",
                  "    const resultado = await pagosServicio.cobrar(req.body);",
                  "    res.status(201).json(resultado);",
                  "});",
                  "",
                  "app.listen(8080);",
                ],
                caption: "Gateway con Express: rate limiting y validación de token",
              },
              real: {
                p: "Una app de comercio necesita un perfil con pedidos e historial de pagos en la primera pantalla. El gateway agrega tres servicios y también oculta los detalles internos (URLs, formatos) al móvil.",
                ul: [
                  "Centraliza ahí la autenticación, el rate limiting y el logging de entrada.",
                  "Agrega solo lo necesario para ahorrar round-trips; evita ir sobrevuelos con timeout largo.",
                  "Mantén contratos estables por versión para no romper clientes publicados.",
                  "Diferencia un BFF por cliente cuando los contratos divergen de verdad.",
                ],
                code: [
                  "async function perfilCompleto(req, res) {",
                  "    const [usuario, pedidos, pagos] = await Promise.all([",
                  "        usuarios.perfil(req.usuarioId),",
                  "        pedidos.listar(req.usuarioId),",
                  "        pagos.listar(req.usuarioId),",
                  "    ]);",
                  "    res.json({ usuario, pedidos, pagos });",
                  "}",
                ],
                nota: "Un gateway que solo enruta sin agregar sigue siendo útil, pero el valor real aparece con la agregación y la seguridad centralizada.",
              },
              expl: [
                "El gateway se convierte en el contrato público que los equipos internos pueden mover libremente.",
                "La agregación con Promise.all reduce latencia: las llamadas internas van en paralelo.",
                "Centralizar el rate limiting evita que un cliente ruidoso sature un servicio crítico.",
                "El BFF permite que el equipo móvil cambie su API sin tocar la web.",
                "Su riesgo es convertirse en un monolito de integración: vigila su tamaño y split en dominios.",
              ],
              errors: [
                "Crear un gateway sin rate limiting y exponer directamente los servicios internos.",
                "Agregar llamadas en serie que multiplican la latencia total.",
                "Mantener el contrato del gateway rígido cuando los clientes evolucionan.",
              ],
              tips: [
                "Diseña el gateway en torno a casos de uso del cliente, no a tablas del servidor.",
                "Mide la latencia de cada ruta agregada para detectar cuellos de botella.",
                "Combínalo con circuit breakers hacia los servicios internos.",
              ],
              exercise: [
                "Crea una ruta /perfil/... que agregue usuario, pedidos y pagos en paralelo.",
                "Añade rate limiting por IP y un mensaje claro al superar el límite.",
                "Separa un BFF móvil con un contrato reducido y mide la diferencia de payload.",
              ],
              summary: [
                "Un API Gateway unifica entrada, seguridad y agregación de servicios.",
                "El BFF adapta la API a cada cliente concreto.",
                "Bien diseñado, reduce latencia y acoplamiento; mal diseñado, es otro monolito.",
              ],
              lang: "js",
              exampleFile: "api-gateway-bff",
              desc: "API Gateway y Backend for Frontend para unificar el acceso a tus servicios.",
            },
          },
        ],
      },
    ],
  },
];