// _curriculum_autenticacion.mjs
// Currículum del curso de Autenticación y Autorización.
// Exporta COURSES con todos los módulos y lecciones.
// Las lecciones existentes en disco se listan SIN body (no se regeneran);
// las nuevas (módulo 07) llevan body completo (12 secciones estándar).

export const COURSES = [
  {
    slug: "autenticacion",
    title: "Autenticación y Autorización",
    modules: [
      {
        id: "modulo-01",
        n: 1,
        t: "Fundamentos de la Autenticación",
        level: "intermedio",
        caption: "Claves, sesiones y decisiones de identidad",
        desc: "Comprende la diferencia entre autenticación y autorización, el papel de las cookies, las diferencias entre hashing y encriptación y el modelo de amenazas que todo sistema de login debe contemplar.",
        subtitle: "Antes de escribir un login, entiende qué significa ser tú en la web.",
        objectives: [
          "Distinguir autenticación de autorización con ejemplos reales",
          "Explicar el papel de las cookies en la web actual",
          "Diferenciar hashing, encriptación y codificación",
          "Entender identidad y estados de sesión",
          "Construir un modelo de amenazas del login",
        ],
        lessons: [
          {
            id: "autenticacion-vs-autorizacion",
            title: "Autenticación vs Autorización",
            duration: "10 min",
            level: "intermedio",
            category: "fundamentos",
            cardText: "Autenticación responde \"¿quién eres?\" y autorización \"¿qué puedes hacer?\".",
            desc: "Aprende a distinguir autenticación de autorización en un backend real.",
          },
          {
            id: "cookies-y-su-rol",
            title: "Cookies y su rol en la web",
            duration: "8 min",
            level: "intermedio",
            category: "cookies",
            cardText: "Las cookies transportan el estado entre peticiones: su rol, atributos y riesgos.",
            desc: "Descubre cómo las cookies mantienen el estado y qué atributos las protegen.",
          },
          {
            id: "hashing-vs-encriptacion",
            title: "Hashing vs encriptación",
            duration: "11 min",
            level: "intermedio",
            category: "contraseñas",
            cardText: "Hash para verificar sin revelar, encriptación para recuperar: usa cada uno donde toca.",
            desc: "Comprende las diferencias entre hashing, encriptación y codificación.",
          },
          {
            id: "identidad-y-estados-de-sesion",
            title: "Identidad y estados de sesión",
            duration: "9 min",
            level: "intermedio",
            category: "sesiones",
            cardText: "La identidad digital y cómo se materializa en cada petición HTTP.",
            desc: "Conoce cómo se construye la identidad digital y los estados de sesión.",
          },
          {
            id: "modelo-de-amenazas-login",
            title: "El modelo de amenazas del login",
            duration: "10 min",
            level: "intermedio",
            category: "seguridad",
            cardText: "Piensa como un atacante: robo de credenciales, fuerza bruta y secuestro de sesión.",
            desc: "Construye el modelo de amenazas que guía las decisiones de tu login.",
          },
        ],
      },
      {
        id: "modulo-02",
        n: 2,
        t: "Registro y Login",
        level: "intermedio",
        caption: "Del registro al primer acceso seguro",
        desc: "Implementa el ciclo completo de cuentas: hashing de contraseñas con bcrypt, registro validado, login con verificación de credenciales, modelo de usuario con rol y recuperación de contraseña.",
        subtitle: "Bienvenida al sistema: registra, valida y verifica sin filtrar información.",
        objectives: [
          "Almacenar contraseñas con bcrypt y password_hash",
          "Validar el registro de usuario de forma segura",
          "Implementar login y verificación de credenciales",
          "Modelar un usuario con su rol básico",
          "Diseñar un flujo de restablecimiento de contraseña",
        ],
        lessons: [
          {
            id: "hashing-con-bcrypt",
            title: "Hashing con bcrypt y password_hash",
            duration: "10 min",
            level: "intermedio",
            category: "contraseñas",
            cardText: "Hash lento y con sal: por qué bcrypt es el estándar para guardar contraseñas.",
            desc: "Almacena contraseñas de forma segura con bcrypt y password_hash.",
          },
          {
            id: "login-y-verificacion",
            title: "Login y verificación de credenciales",
            duration: "10 min",
            level: "intermedio",
            category: "login",
            cardText: "Compara hashes con tiempo constante y responde igual ante errores de usuario o de clave.",
            desc: "Implementa la verificación de credenciales en el login sin filtrar información.",
          },
          {
            id: "modelo-de-usuario-y-rol",
            title: "Modelo de usuario y rol básico",
            duration: "9 min",
            level: "intermedio",
            category: "modelo de datos",
            cardText: "El esquema de usuarios con rol, estado y sellos de tiempo para tu base de datos.",
            desc: "Diseña el modelo de datos de usuarios con su rol y estado.",
          },
          {
            id: "registro-y-validacion",
            title: "Registro y validación de datos",
            duration: "9 min",
            level: "intermedio",
            category: "validación",
            cardText: "Valida email, contraseña y campos de registro antes de tocar la base de datos.",
            desc: "Valida los datos de registro en el servidor antes de crear la cuenta.",
          },
          {
            id: "restablecimiento-de-contrasena",
            title: "Restablecimiento de contraseña",
            duration: "11 min",
            level: "intermedio",
            category: "contraseñas",
            cardText: "Tokens de un solo uso, expiración y confirmación por email para recuperar la cuenta.",
            desc: "Implementa la recuperación de contraseña con tokens temporales de un solo uso.",
          },
        ],
      },
      {
        id: "modulo-03",
        n: 3,
        t: "Sesiones del lado servidor",
        level: "intermedio",
        caption: "Estado que vive en tu servidor",
        desc: "Gestiona sesiones persistentes en el servidor: expiración, renovación, revocación, protección de la cookie de sesión y almacenamiento en bases de datos o Redis.",
        subtitle: "El control de la sesión en tus manos, no en las del cliente.",
        objectives: [
          "Explicar por qué el estado de sesión vive en el servidor",
          "Aplicar expiración y renovación de sesiones",
          "Proteger la cookie de sesión con atributos seguros",
          "Almacenar sesiones en bases de datos y Redis",
          "Diseñar cierre de sesión y revocación efectivos",
        ],
        lessons: [
          {
            id: "cierre-de-sesion-y-revocacion",
            title: "Cierre de sesión y revocación",
            duration: "8 min",
            level: "intermedio",
            category: "sesiones",
            cardText: "Cerrar sesión debe invalidar el estado de verdad, no solo limpiar la cookie.",
            desc: "Implementa cierre de sesión y revocación real del estado del servidor.",
          },
          {
            id: "expiracion-y-renovacion",
            title: "Expiración y renovación",
            duration: "8 min",
            level: "intermedio",
            category: "sesiones",
            cardText: "Tiempos de vida, ventanas de inactividad y renovación para sesiones seguras.",
            desc: "Configura expiración por tiempo de vida e inactividad en tus sesiones.",
          },
          {
            id: "proteccion-de-la-cookie-de-sesion",
            title: "Protección de la cookie de sesión",
            duration: "9 min",
            level: "intermedio",
            category: "cookies",
            cardText: "HttpOnly, Secure, SameSite y prefijos de cookie para blindar la sesión.",
            desc: "Protege la cookie de sesión con sus atributos de seguridad.",
          },
          {
            id: "sesiones-en-bd-y-redis",
            title: "Sesiones en Bases de Datos y Redis",
            duration: "10 min",
            level: "intermedio",
            category: "almacenamiento",
            cardText: "Comparte sesiones entre instancias guardándolas en la base de datos o Redis.",
            desc: "Almacena sesiones en bases de datos y Redis para escalar horizontalmente.",
          },
          {
            id: "sesiones-y-almacenamiento",
            title: "Sesiones y almacenamiento",
            duration: "9 min",
            level: "intermedio",
            category: "almacenamiento",
            cardText: "En memoria, archivo o externo: elige el almacén según tu arquitectura.",
            desc: "Compara las opciones de almacenamiento de sesiones y elige la adecuada.",
          },
        ],
      },
      {
        id: "modulo-04",
        n: 4,
        t: "JWT",
        level: "intermedio",
        caption: "Tokens firmados para un backend sin estado",
        desc: "Domina los JSON Web Tokens: sus partes, el acceso sin estado, tipos de firma HS256 y RS256, expiración, almacenamiento seguro en el cliente y estrategias con refresh tokens y rotación.",
        subtitle: "Lleva la identidad firma a la mano de cada petición.",
        objectives: [
          "Explicar la anatomía de un JWT: header, payload y firma",
          "Firmar con HS256 y RS256 según el contexto",
          "Aplicar expiración y validación de access tokens",
          "Almacenar tokens de forma segura en el cliente",
          "Diseñar refresh tokens con rotación",
        ],
        lessons: [
          {
            id: "access-tokens-y-expiracion",
            title: "Access tokens y expiración",
            duration: "9 min",
            level: "intermedio",
            category: "jwt",
            cardText: "Access tokens cortos: qué llevan dentro y cómo se rechazan al expirar.",
            desc: "Entiende los access tokens, su contenido y su ciclo de vida.",
          },
          {
            id: "almacenamiento-seguro-en-el-cliente",
            title: "Almacenamiento seguro en el cliente",
            duration: "9 min",
            level: "intermedio",
            category: "jwt",
            cardText: "localStorage no son huevos verdes: dónde guardar tokens y por qué.",
            desc: "Aprende dónde almacenar los tokens en el cliente sin exponerlos a XSS.",
          },
          {
            id: "firmando-tokens-hs256-rs256",
            title: "Firmando tokens: HS256 y RS256",
            duration: "11 min",
            level: "intermedio",
            category: "jwt",
            cardText: "Algoritmos simétricos y asimétricos: cuándo usar cada firma.",
            desc: "Compara la firma simétrica HS256 y la asimétrica RS256.",
          },
          {
            id: "que-es-un-jwt",
            title: "¿Qué es un JWT y sus partes?",
            duration: "10 min",
            level: "intermedio",
            category: "jwt",
            cardText: "Header, payload y firma: el formato de tres segmentos separados por puntos.",
            desc: "Descompón un JWT en su header, payload y firma.",
          },
          {
            id: "refresh-tokens-y-rotacion",
            title: "Refresh tokens y rotación",
            duration: "11 min",
            level: "intermedio",
            category: "jwt",
            cardText: "Renueva access tokens con refresh tokens de larga vida y rotación segura.",
            desc: "Implementa refresh tokens con rotación y detección de reutilización.",
          },
        ],
      },
      {
        id: "modulo-05",
        n: 5,
        t: "Autorización y RBAC",
        level: "intermedio",
        caption: "Qué puede hacer quién",
        desc: "Separa identidad de permisos: construye roles, claims y middlewares de autorización, y protege rutas y funciones para que cada usuario solo acceda a lo suyo.",
        subtitle: "La identidad abre la puerta; la autorización decide el pasillo.",
        objectives: [
          "Modelar roles de usuario y sus jerarquías",
          "Representar permisos con claims",
          "Construir middlewares de autorización",
          "Proteger rutas y funciones con políticas reutilizables",
          "Combinar RBAC con checks por recurso",
        ],
        lessons: [
          {
            id: "middleware-de-autorizacion",
            title: "Middleware de autorización",
            duration: "11 min",
            level: "intermedio",
            category: "autorización",
            cardText: "Intercepta cada petición y decide si el usuario puede seguir o recibe 403.",
            desc: "Construye middlewares que aplican política de acceso antes del controlador.",
          },
          {
            id: "permisos-y-claims",
            title: "Permisos y claims",
            duration: "10 min",
            level: "intermedio",
            category: "autorización",
            cardText: "Los claims declaran hechos del usuario: rol, permisos y ámbito de acción.",
            desc: "Representa permisos como claims dentro del token o de la sesión.",
          },
          {
            id: "protegiendo-rutas-y-funciones",
            title: "Protegiendo rutas y funciones",
            duration: "10 min",
            level: "intermedio",
            category: "autorización",
            cardText: "No basta con ocultar botones: la autorización debe vivir en el servidor.",
            desc: "Aplica controles de acceso en rutas y también dentro de la lógica de negocio.",
          },
          {
            id: "roles-de-usuario",
            title: "Roles de usuario",
            duration: "10 min",
            level: "intermedio",
            category: "rbac",
            cardText: "Admin, editor y visitante: jerarquías de roles que simplifican el permiso.",
            desc: "Diseña el modelo de roles y sus jerarquías para tu API.",
          },
        ],
      },
      {
        id: "modulo-06",
        n: 6,
        t: "OAuth 2.0 y OIDC",
        level: "intermedio",
        caption: "Deja que otros pidan acceso por ti",
        desc: "Integra autenticación delegada: actores y flujos de OAuth 2.0, authorization code flow, integración con proveedores externos, scopes, consentimiento y OpenID Connect con id tokens.",
        subtitle: "Los usuarios ya tienen identidad en otro sitio: úsala con seguridad.",
        objectives: [
          "Explicar actores y flujos de OAuth 2.0",
          "Implementar el authorization code flow",
          "Integrar un proveedor externo de identidad",
          "Gestionar scopes y consentimiento",
          "Validar id tokens de OpenID Connect",
        ],
        lessons: [
          {
            id: "authorization-code-flow",
            title: "Authorization code flow",
            duration: "12 min",
            level: "intermedio",
            category: "oauth",
            cardText: "El flujo más seguro para web: código de autorización que se canjea por tokens.",
            desc: "Implementa el flujo de authorization code de OAuth 2.0.",
          },
          {
            id: "integrando-un-proveedor-externo",
            title: "Integrando un proveedor externo",
            duration: "9 min",
            level: "intermedio",
            category: "oauth",
            cardText: "Google, GitHub o Auth0: pasos reales para conectar una identidad externa.",
            desc: "Integra un proveedor de identidad externo en tu backend.",
          },
          {
            id: "oauth-actores-y-flujos",
            title: "OAuth: actores y flujos",
            duration: "10 min",
            level: "intermedio",
            category: "oauth",
            cardText: "Resource owner, client, authorization server y resource server: el reparto de roles.",
            desc: "Comprende los actores de OAuth 2.0 y cuándo usar cada flujo.",
          },
          {
            id: "openid-connect-id-tokens",
            title: "OpenID Connect e id tokens",
            duration: "11 min",
            level: "intermedio",
            category: "oidc",
            cardText: "La capa de identidad sobre OAuth: id tokens para saber quién es el usuario.",
            desc: "Aprende OpenID Connect y la validación de id tokens.",
          },
          {
            id: "scopes-y-consentimiento",
            title: "Scopes y consentimiento",
            duration: "8 min",
            level: "intermedio",
            category: "oauth",
            cardText: "Límites de acceso que el usuario aprueba: de leer perfil a gestionar datos.",
            desc: "Gestiona scopes y pantallas de consentimiento en OAuth 2.0.",
          },
        ],
      },
      {
        id: "modulo-07",
        n: 7,
        t: "Seguridad, OWASP y cumplimiento",
        level: "avanzado",
        caption: "Blinda tu sistema frente a ataques reales",
        desc: "Aplica la seguridad de sesiones y autenticación de nivel producción: OWASP en auth, gestión de secretos, CSRF y secuestro de sesión, rate limiting contra fuerza bruta y cabeceras de seguridad HTTP.",
        subtitle: "Autenticar bien es también saber defender lo autenticado.",
        objectives: [
          "Aplicar las guías OWASP (Top 10 y ASVS) a la autenticación",
          "Gestionar secretos sin filtrarlos en el código",
          "Mitigar CSRF, session fixation y secuestro de sesión",
          "Proteger el login con rate limiting y bloqueo de cuenta",
          "Hardening HTTP con cabeceras de seguridad",
        ],
        lessons: [
          {
            id: "owasp-y-autenticacion",
            title: "OWASP y la autenticación",
            duration: "12 min",
            level: "avanzado",
            category: "owasp",
            cardText: "El Top 10 y el ASVS aplicados a login, sesiones y gestión de cuentas.",
            desc: "Usa las guías de OWASP para auditar y blindar tu sistema de autenticación.",
            body: {
              intro: [
                "La autenticación concentra la mayoría de los ataques contra un backend: contraseñas robadas, sesiones secuestradas o enums de usuarios. OWASP publica las referencias de facto para saber qué cubrir y en qué orden.",
                "Este módulo cierra el curso llevando tu login de \"funciona\" a \"defiende\". Aquí conectamos los conceptos de toda la ruta con las guías OWASP Top 10 y el Application Security Verification Standard (ASVS).",
              ],
              def: {
                par: "OWASP es una fundación que publica estándares abiertos de seguridad web. El Top 10 lista los riesgos más críticos y el ASVS define niveles verificables de requisitos de seguridad para aplicaciones, incluida la autenticación.",
                porQue: "Un login vulnerable compromete todo el sistema aunque el resto del código sea impecable: el atacante entra con la identidad de otro y cruza cualquier autorización.",
                cuando: "Úsalo siempre, pero especialmente en el diseño, en cada code review y cuando un pentest o auditoría te pida un estándar que citar.",
              },
              concepts: [
                "OWASP Top 10 agrupa los 10 riesgos más críticos: broken authentication, IDOR, injection y más.",
                "ASVS define niveles (1 básico, 2 estándar, 3 avanzado) con requisitos verificables por módulo.",
                "Broken authentication agrupa credenciales débiles, sesiones mal gestionadas y falta de rate limiting.",
                "Security misconfiguration acumula headers faltantes, errores con stack traces y puertos abiertos.",
                "La verificación de seguridad es reproducible: misma versión, misma checklist, mismo resultado.",
              ],
              basic: {
                p: "Empieza la auditoría con una checklist rápida sobre el login real. Simulamos la inspección de un endpoint con curl y revisamos qué responde ante fallos.",
                code: [
                  "curl -i -X POST https://api.example.com/login \\",
                  "  -H 'Content-Type: application/json' \\",
                  "  -d '{\"email\":\"nadie@example.com\",\"password\":\"incorrecta\"}'",
                  "# Respuestas de control:",
                  "# 1) 401 siempre que fallen las credenciales (nunca 404 ni 'usuario inexistente')",
                  "# 2) sin stack trace ni detalles internos en el cuerpo",
                  "# 3) Set-Cookie con HttpOnly, Secure y SameSite=Strict en cada login",
                ],
                out: "HTTP/1.1 401 Unauthorized\\nSet-Cookie: session=...; HttpOnly; Secure; SameSite=Strict",
                lang: "bash",
              },
              intermediate: {
                p: "Traducimos la checklist a código: un middleware de login que registra intentos, responde igual ante errores y aplica un pequeño 'cooldown' de incremento.",
                caption: "Middleware de login con checks de OWASP",
                code: [
                  'import bcrypt',
                  'from flask import request, jsonify',
                  "",
                  'def login(users, failed_attempts):',
                  '    data = request.get_json()',
                  '    email = (data.get("email") or "").strip().lower()',
                  '    password = data.get("password") or ""',
                  "    user = users.find_one({\"email\": email})",
                  "    if not user or not bcrypt.checkpw(password.encode(), user[\"hash\"].encode()):",
                  '        key = email or "anónimo"',
                  '        failed_attempts[key] = failed_attempts.get(key, 0) + 1',
                  '        return jsonify({"error": "Credenciales inválidas"}), 401',
                  '    if failed_attempts.get(email, 0) >= 5:',
                  '        return jsonify({"error": "Cuenta bloqueada"}), 423',
                  '    failed_attempts[email] = 0',
                  '    return jsonify({"ok": True, "token": create_jwt(user)}), 200',
                ],
              },
              real: {
                p: "En un informe de pentest real, los hallazgos de autenticación llegan casi siempre con una referencia ASVS. Antes de que eso pase, tu equipo puede correr el mismo chequeo de forma regular y dejar constancia.",
                ul: [
                  "Elige un nivel ASVS objetivo (2 como mínimo) y cúbrelo por partes en cada sprint.",
                  "Automatiza lo automatizable: headers, rate limiting y manejo de errores son verificables en CI.",
                  "Conserva los hallazgos y su remediación documentados para auditorías.",
                ],
                code: [
                  "# Check rápido del nivel ASVS 2 (V2-Authentication) en CI",
                  "asvs_checks = {",
                  '  "v2.1 passwords_stored_with_argon2_or_bcrypt": True,',
                  '  "v2.5 no_enumeration_on_login_errors": True,',
                  '  "v2.9 rate_limiting_on_login": True,',
                  '  "v2.20 session_rotation_on_login": False,  # PENDIENTE',
                  "}",
                  "failed = [k for k, ok in asvs_checks.items() if not ok]",
                  "if failed:",
                  '    raise SystemExit(f"ASVS pendiente: {failed}")',
                ],
                nota: "El ASVS no es una licencia de seguridad perfecta, pero convertir sus requisitos en tu checklist elimina la improvisación.",
              },
              expl: [
                "Broken authentication es el fallo transversal: cualquier eslabón débil del ciclo de la cuenta pone en riesgo las demás capas.",
                "El ASVS mide con requisitos accionables y niveles, lo que permite comparar dos sistemas de forma objetiva.",
                "Los errores de login idénticos evitan la enumeración de usuarios, uno de los vectores más rentables para el atacante.",
                "Un stack trace o un 500 con detalles convierte un fallo lógico en información: siempre respondes JSON plano.",
                "Las revisiones de seguridad pierden valor si no se hacen con una versión reproducible y una checklist fija.",
              ],
              errors: [
                "Revelar con el mensaje de error si el email existe o no (enumeración de usuarios).",
                "Entregar la forma de credenciales original en los logs por error de codificación.",
                "Copiar y pegar una 'checklist general' sin requisitos verificables adoptables por tu equipo.",
              ],
              tips: [
                "Fija un nivel ASVS objetivo y ticket con la referencia en cada incidencia.",
                "Revisa primero los requisitos de autenticación: suelen concentrar el mayor riesgo.",
                "Incluye una tarea de auditoría ligera en cada sprint, no un pentest anual de golpe.",
                "Documenta supuestos: si usas un servicio externo, el alcance de responsabilidades cambia.",
              ],
              exercise: [
                "Clasifica 3 hallazgos reales de tu login según los requisitos ASVS V2.",
                "Redacta la política de contraseñas y bloqueo que cumpliría V2.1 y V2.9.",
                "Eleva tu checklist actual a nivel ASVS 2 y marca los puntos pendientes.",
              ],
              summary: [
                "OWASP Top 10 y ASVS dan un marco verificable para asegurar la autenticación.",
                "La enumeración de usuarios, los errores ricos y la falta de rate limiting son los fallos más típicos.",
                "La seguridad de auth se revisa con checklist reproducible, no con intuición.",
              ],
              lang: "python",
              exampleFile: "owasp-y-autenticacion",
              desc: "Usa las guías de OWASP para auditar y blindar tu sistema de autenticación.",
            },
          },
          {
            id: "manejo-seguro-de-secretos",
            title: "Gestión segura de secretos",
            duration: "13 min",
            level: "avanzado",
            category: "seguridad",
            cardText: "Claves, tokens y credenciales fuera del código: entorno, .env y gestores de secretos.",
            desc: "Gestiona claves y credenciales sin filtrarlas en código, git ni logs.",
            body: {
              intro: [
                "Toda la seguridad construida hasta aquí cae si una API key aparece en un repositorio público o en un log. Los secretos (contraseñas de BD, claves de firma JWT, tokens de proveedores) son el objetivo preferido de los escaneos automáticos.",
                "La regla es simple: el secreto nunca vive en el código y nunca se replica por mensajería. Vive en variables de entorno o en un gestor de secretos, se inyecta en tiempo de ejecución y se rota con regularidad.",
              ],
              def: {
                par: "Un secreto es cualquier credencial que permite autenticarse o descifrar datos: claves de API, secret keys, contraseñas de infraestructura o tokens OAuth. Los gestores de secretos los guardan cifrados y controlan su acceso y rotación.",
                porQue: "Un secreto filtrado es una brecha en horas: permiten acceso completo a bases de datos, cuentas cloud o servicios de pago sin levantar sospecha.",
                cuando: "Usa variables de entorno para configurar el despliegue y un gestor (Vault, Secret Manager, SSM) cuando el secreto deba auditarse, rotarse o compartirse entre servicios.",
              },
              concepts: [
                "Variable de entorno: configuración inyectada en el proceso, nunca escrita en el código.",
                ".env local ignorado por git: cómodo para desarrollo, insuficiente para producción.",
                "Gestor de secretos: almacén cifrado con auditoría, rotación y permisos finos.",
                "Rotación: reemplazo periódico del secreto para limitar el daño de una fuga.",
                "Secret scanning: escaneo del código y del historial de git en busca de claves coladas.",
              ],
              basic: {
                p: "El mínimo de higiene: cargar configuración sensible desde variables de entorno en lugar de constantes en el código.",
                code: [
                  "# .env (local, ignorado por git)",
                  "DB_PASSWORD=s3cr3t0-local",
                  "JWT_SECRET=cambia-en-produccion",
                  "STRIPE_API_KEY=sk_test_xxx",
                  "",
                  "# app.py",
                  "import os",
                  "DB_PASSWORD = os.environ[\"DB_PASSWORD\"]",
                  "JWT_SECRET = os.environ[\"JWT_SECRET\"]",
                ],
                out: "DB_PASSWORD y JWT_SECRET leídos del entorno, no del código fuente.",
                lang: "python",
              },
              intermediate: {
                p: "Ya en un gestor de secretos, el backend los lee en cada arranque. Con la CLI de Secret Manager descargamos los valores en variables y lanzamos el proceso sin tocarlos.",
                caption: "Inyección de secretos desde un gestor",
                code: [
                  "# MySQL / Postgres: pide credenciales por servicio",
                  'aws secretsmanager get-secret-value --secret-id prod/db \\',
                  "  --query SecretString --output text \\",
                  "  | jq -r 'to_entries | map(\"\\(.key)=\\(.value)\") | .[]' > /tmp/creds.env",
                  "export $(cat /tmp/creds.env)",
                  "rm /tmp/creds.env",
                  "node server.js",
                ],
              },
              real: {
                p: "En producción, la rotación de un JWT signing key o de la contraseña de la BD debe poder hacerse sin recompilar ni detener el servicio: el secreto se lee del gestor al arrancar y cada proceso nuevo recibe la nueva versión.",
                ul: [
                  "Marca cada secreto con fecha de rotación y alerta cuando se aproxime.",
                  "Aplica mínimo privilegio: un servicio solo accede a los secretos que necesita.",
                  "Nunca registres secretos en logs; si llegan, redacta antes de emitir.",
                ],
                code: [
                  "# Ejemplo de rotación semiautomática del JWT_SECRET",
                  "old=$(aws secretsmanager get-secret-value --secret-id prod/jwt --query SecretString --output text)",
                  "new=$(openssl rand -base64 48)",
                  "aws secretsmanager update-secret --secret-id prod/jwt --secret-string \"$new\"",
                  "@/deploy/api.sh restart",
                  "# los procesos leen la nueva versión; se mantiene el valor antiguo",
                  "# en la ventana de tolerancia para tokens emitidos",
                ],
                nota: "Para JWT conviene mantener dos claves en curso durante una rotación: la nueva firma y la anterior valida.",
              },
              expl: [
                "Las variables de entorno separan la configuración del proceso y hacen el código portable entre entornos.",
                "Git nunca debe contener secretos: incluso los commits borrados viven en el historial.",
                "Los gestores de secretos cifran el valor en reposo y en tránsito y auditan quién lo pidió.",
                "La rotación reduce la ventana de exposición y es obligatoria tras cualquier sospecha de fuga.",
                "El secret scanning en CI corta la fuga antes de que el commit llegue al remoto.",
              ],
              errors: [
                "Commitear un .env real: usa .env.example con placeholders y añade *env a .gitignore.",
                "Filtrar el secreto en un error de configuración o en los logs de arranque.",
                "Reutilizar la misma clave para desarrollo, staging y producción.",
              ],
              tips: [
                "Da secretos mínimos por servicio: una app que solo lee no necesita claves de escritura.",
                "Prefiere secretos efímeros alojados en memoria frente a archivos planos en disco.",
                "Activa secret scanning en tu proveedor de repositorio y en los pipelines.",
                "Cuando un secreto se filtre por aquí, restablécelo sin piedad aunque creas que nadie lo vio.",
              ],
              exercise: [
                "Migra tres constantes secretas de tu app a variables de entorno y añade .env.example.",
                "Simula una rotación de la clave de firma JWT dejando ventana para tokens antiguos.",
                "Configura secret scanning en tu repositorio y corrige el hallazgo detectado.",
              ],
              summary: [
                "Los secretos no viven en el código: se inyectan por entorno o gestor en tiempo de ejecución.",
                "Los gestores añaden cifrado, auditoría, acceso mínimo y rotación.",
                "El secret scanning en CI y la rotación disciplinada contienen el daño de una fuga.",
              ],
              lang: "bash",
              exampleFile: "manejo-seguro-de-secretos",
              desc: "Gestiona claves y credenciales sin filtrarlas en código, git ni logs.",
            },
          },
          {
            id: "csrf-y-secuestro-de-sesion",
            title: "CSRF y secuestro de sesión",
            duration: "12 min",
            level: "avanzado",
            category: "seguridad",
            cardText: "Ataques que abusan de tu sesión viva: CSRF, session fixation y cómo neutralizarlos.",
            desc: "Mitiga CSRF, session fixation y el secuestro de sesión en tu backend.",
            body: {
              intro: [
                "Muchos ataques no roban el password: abusan de una sesión ya iniciada. CSRF consigue que tu navegador autenticado ejecute acciones sin que lo sepas, y la fijación de sesión fuerza a la víctima a usar un id que el atacante conoce.",
                "La defensa empieza por entender de qué herramientas dispone el navegador y qué datos controla de verdad el servidor. Aquí cerramos el círculo de las sesiones del módulo 3 con su vertiente ofensiva y las contramedidas.",
              ],
              def: {
                par: "CSRF (Cross-Site Request Forgery) fuerza al navegador autenticado de la víctima a enviar peticiones a tu API. La fijación de sesión obliga a la víctima a heredar un session id que el atacante ya conoce.",
                porQue: "Con sesiones basadas en cookies, el navegador adjunta las credenciales automáticamente: el atacante solo necesita que la víctima pida a la página maliciosa.",
                cuando: "Mide el riesgo: es crítico con cookies de sesión para acciones de estado; decrece con cookies SameSite y con tokens en memoria (JWT en headers).",
              },
              concepts: [
                "CSRF abusa de cookies que viajan solas: peticiones forzadas (img, form, fetch) ejecutan acciones de estado.",
                "Session fixation: el atacante entrega un session id antes del login y el servidor no lo regenera al autenticar.",
                "SameSite=Strict/Lax limita el envío de cookies en peticiones cross-site, cortando el CSRF más común.",
                "Tokens anti-CSRF (double submit o sincronizados) validan que el origen de la petición es legítimo.",
                "La renovación del session id tras el login neutraliza la fijación y reduce el secuestro.",
              ],
              basic: {
                p: "Un curl con cookie jar muestra la vulnerabilidad de fijación: el servidor acepta el session id impuesto en lugar de generar uno nuevo al autenticar.",
                code: [
                  "curl -c jar.txt http://api.example.com/set?sid=ATAQUE123",
                  "curl -b jar.txt -c jar.txt -X POST http://api.example.com/login \\",
                  "  -H 'Content-Type: application/json' \\",
                  "  -d '{\"user\":\"ana\",\"password\":\"correcta\"}'",
                  "grep session jar.txt  # si sigue siendo ATAQUE123, hay fijación",
                ],
                out: "session ATAQUE123  (el servidor NO regeneró el id tras el login)",
                lang: "bash",
              },
              intermediate: {
                p: "La corrección en el controlador: regenerar el session id al autenticar y emitir la cookie con SameSite=Strict.",
                caption: "Regeneración de sesión y cookie endurecida",
                code: [
                  "from flask import session, make_response",
                  "import uuid",
                  "",
                  "def login_exitoso(resp):",
                  "    session.clear()        # limpia datos de la antigua sesión",
                  "    session[\"session_id\"] = uuid.uuid4().hex  # nueva identidad",
                  "    session.permanent = True",
                  "    resp = make_response(resp)",
                  '    resp.set_cookie("session", session["session_id"],',
                  "        httponly=True, secure=True, samesite=\"Strict\")",
                  "    return resp",
                ],
              },
              real: {
                p: "Escenario típico: un usuario autenticado visita un foro que le hace publicar un POST a tu API de transferencias. Con SameSite=Strict y un token anti-CSRF doble, la petición cross-site no lleva cookie válida ni token que verificar.",
                ul: [
                  "Combina SameSite=Strict con un token anti-CSRF en mutaciones (POST/PUT/DELETE).",
                  "Verifica el header Origin en peticiones con estado como segunda barrera.",
                  "Regenera siempre el identificador de sesión en login y privilegio escalado.",
                ],
                code: [
                  'app.use((req, res, next) => {',
                  '  if (["POST", "PUT", "PATCH", "DELETE"].includes(req.method)) {',
                  '    const ok = req.headers.origin &&',
                  "      new URL(req.headers.origin).host === req.get('host') &&",
                  '      req.body._token === res.locals.session.token;',
                  "    if (!ok) return res.status(403).json({ error: 'Origen no permitido' });",
                  "  }",
                  "  next();",
                  "});",
                ],
                nota: "El token anti-CSRF no necesita estar en la BD: un par aleatorio por sesión con doble envío (cookie + body) basta en la mayoría de APIs.",
              },
              expl: [
                "Las cookies con SameSite=Strict no viajan en peticiones cross-site, neutralizando de raíz el CSRF clásico.",
                "La fijación se resuelve regenerando el session id en cada login, no confiando en el id de la cookie inicial.",
                "El token anti-CSRF añade una prueba que el atacante no puede leer porque no comparte origen.",
                "El problema empeora con métodos idempotentes mal implementados: GET que borra recursos es un regalo.",
                "Para APIs token-in-header el riesgo cae porque los headers no viajan solos entre orígenes.",
              ],
              errors: [
                "Confiar solo en la cookie HttpOnly para frenar CSRF: HttpOnly evita XSS, no la petición cross-site.",
                "Esperar a SameSite sin actualizar el valor: emitir la cookie sin atributo explota el valor por defecto de cada navegador.",
                "Regenerar la sesión pero conservar los mismos datos sensibles reutilizables.",
              ],
              tips: [
                "Aplica SameSite=Strict en cookies de sesión y Lax solo si incrustas el sitio en iframes de confianza.",
                "Valida el Origin del navegador en todos los cambios de estado, aunque uses anti-CSRF.",
                "Logea (con alertas) activaciones de sesión desde IP o User-Agent distintos.",
              ],
              exercise: [
                "Reproduce la fijación con curl y corrige el login regenerando el session id.",
                "Añade SameSite=Strict a tu cookie y verifica con un form cross-site en una página local.",
                "Implementa el token anti-CSRF de doble envío solo para rutas con mutaciones.",
              ],
              summary: [
                "CSRF abusa de la cookie que viaja sola; SameSite, la verificación de origen y los tokens lo frenan.",
                "La fijación y el secuestro se neutralizan regenerando la sesión en cada login.",
                "Cuanto menos control regale el servidor a la cookie, más pequeña es la superficie de ataque.",
              ],
              lang: "javascript",
              exampleFile: "csrf-y-secuestro-de-sesion",
              desc: "Mitiga CSRF, session fixation y el secuestro de sesión en tu backend.",
            },
          },
          {
            id: "rate-limiting-y-brute-force",
            title: "Rate limiting y fuerza bruta",
            duration: "12 min",
            level: "avanzado",
            category: "seguridad",
            cardText: "Contra el ataque de credenciales: límites por IP y por cuenta con bloqueo y backoff.",
            desc: "Protege el login con rate limiting, bloqueo de cuenta y backoff exponencial.",
            body: {
              intro: [
                "La fuerza bruta convierte una contraseña débil en una puerta abierta: el atacante prueba miles de combinaciones por minuto contra tu login. Detrás de cada acierto real hay una secuencia de fallos que tu servidor puede y debe detectar.",
                "El rate limiting no solo protege contra fuerza bruta: también frena abuso de endpoints, scraping y ataques de denegación. Es la pieza que convierte el login en un objetivo caro.",
              ],
              def: {
                par: "El rate limiting limita el número de peticiones de un cliente en una ventana de tiempo. Para credenciales, el rate limiting por cuenta suma bloqueos tras N fallos y backoff exponencial entre reintentos.",
                porQue: "Sin límite, cada cuenta es un ensayo infinito para el atacante y cada endpoint es un recurso gratis para saturar el servidor.",
                cuando: "Usa límites estrictos en login, registro, restablecimiento de contraseña y OTP; usa límites más holgados (pero presentes) en endpoints de lectura.",
              },
              concepts: [
                "Rate limiting por IP: capa barata que frena a un solo atacante, pero débil detrás de redes compartidas.",
                "Rate limiting por cuenta: key por email o user id, la defensa real contra fuerza bruta de credenciales.",
                "Bloqueo tras N fallos con ventana de desbloqueo y backoff exponencial entre intentos.",
                "Límites distintos según la sensibilidad del endpoint: /login muy tajo; /public aleatorio más amplio.",
                "Los límites se aplican en producción y también en infraestructura (WAF, proxy) como borde.",
              ],
              basic: {
                p: "En Express, el middleware más usado es express-rate-limit. Un límite modesto para el login, con respuesta 429 clara.",
                code: [
                  "const rateLimit = require('express-rate-limit');",
                  "",
                  "const loginLimiter = rateLimit({",
                  "  windowMs: 15 * 60 * 1000,   // 15 minutos",
                  "  max: 10,                   // 10 intentos",
                  "  standardHeaders: true,",
                  "  message: { error: 'Demasiados intentos. Espera un poco.' },",
                  "});",
                  "",
                  "app.post('/login', loginLimiter, loginController);",
                ],
                out: "HTTP/1.1 429 Many Requests con body JSON al superar los 10 intentos.",
                lang: "javascript",
              },
              intermediate: {
                p: "El límite por cuenta se resuelve con Redis: almacenamos fallos por email y aplicamos backoff exponencial, independientemente de la IP.",
                caption: "Bloqueo por cuenta con backoff en Redis",
                code: [
                  'async function registrarFallido(email, redis) {',
                  "  const key = `auth:fail:${email}`;",
                  "  const n = await redis.incr(key);",
                  "  await redis.expire(key, 3600);           // la ventana se resetea cada hora",
                  '  const delay = Math.min(60, 5 * Math.pow(2, n - 1));  // 5s, 10s, 20s...',
                  "  await redis.setex(`auth:cooldown:${email}`, delay, 1);",
                  "  return n;",
                  "}",
                  "",
                  "async function puedeIntentar(email, redis) {",
                  '  return (await redis.get(`auth:cooldown:${email}`)) === null;',
                  "}",
                ],
              },
              real: {
                p: "En producción el rate limiting del login se despliega en dos frentes: el edge (nginx o WAF) frena el tráfico masivo por IP, y la capa de aplicación aplica la política fina por cuenta y por endpoint, con métricas y alertas.",
                ul: [
                  "Aplica límites en el edge para absorber el volumen y en la app para la lógica de negocio.",
                  "Combina con captcha o challenge en IPs que fallen repetido; el perjuicio a usuarios reales es mínimo.",
                  "Publica las métricas de rechazos y alerta cuando un endpoint empiece a generar 429.",
                ],
                code: [
                  "# nginx: límite bruto de 30 req/min por IP en /login",
                  "limit_req_zone $binary_remote_addr zone=login:10m rate=30r/m;",
                  "server {",
                  "  location = /login {",
                  "    limit_req zone=login burst=10 nodelay;",
                  "    proxy_pass http://api;",
                  "  }",
                  "}",
                ],
                nota: "Los bloqueos por cuenta no deben dejar la cuenta inaccesible para siempre: una ventana de 15-60 minutos con backoff es más operativo y evita el auto-DoS.",
              },
              expl: [
                "El límite por IP es barato pero impreciso: una oficina compartida comparte IP y sufre límites ajenos.",
                "El límite por cuenta ataca el verdadero objetivo (las credenciales) y tolera redes compartidas.",
                "El backoff exponencial encarece el ensayo masivo sin castigar al usuario que se equivoca una vez.",
                "La respuesta 429 debe ser idéntica a la de credenciales incorrectas para no favorecer la enumeración.",
                "Sin métricas, el rate limiting es ciego: los rechazos legítimos y los ataques se confunden.",
              ],
              errors: [
                "Diferenciar en la respuesta el 429 del 401, ayudando al atacante a distinguir umbrales.",
                "Cachear el límite en el propio proceso sin estado compartido: cada instancia deja pasar el triple.",
                "Meter en el mismo límite endpoints de lectura y escritura con necesidades totalmente distintas.",
              ],
              tips: [
                "Empieza generoso y ajusta con datos, no al revés: un límite demasiado estricto rompe usuarios reales.",
                "Usa Redis (o el gestor de caché) para que el estado del límite sobreviva a varias instancias.",
                "Rotula los 429 con el header Retry-After para que los clientes no reintenten a ciegas.",
                "Elimina el backoff tras un login correcto: el culpable humano no debe quedar castigado sin motivo.",
              ],
              exercise: [
                "Configura express-rate-limit en /login con 10 intentos por 15 minutos y comprueba el 429.",
                "Implementa el bloqueo por cuenta en Redis con backoff exponencial de 5s como base.",
                "Coloca un límite por IP en nginx sobre /login y valida con un ataque simple de curl.",
              ],
              summary: [
                "El rate limiting por cuenta protege las credenciales donde el límite por IP no llega.",
                "El bloqueo con backoff exponencial encarece la fuerza bruta sin romper al usuario.",
                "Límites en el edge y en la aplicación, con métricas, completan la defensa en producción.",
              ],
              lang: "javascript",
              exampleFile: "rate-limiting-y-brute-force",
              desc: "Protege el login con rate limiting, bloqueo de cuenta y backoff exponencial.",
            },
          },
          {
            id: "cabeceras-de-seguridad-http",
            title: "Cabeceras de seguridad HTTP",
            duration: "11 min",
            level: "avanzado",
            category: "seguridad",
            cardText: "HSTS, CSP, X-Content-Type-Options y más: el endurecimiento de cada respuesta.",
            desc: "Endurece las respuestas HTTP con las cabeceras de seguridad que exige producción.",
            body: {
              intro: [
                "Las cabeceras de seguridad son la carta de presentación de tu backend: le dicen al navegador qué puede y qué no puede hacer con tus respuestas. Muchas brechas (clickjacking, MIME sniffing, mezcla de contenido) se evitan solo con headers bien puestos.",
                "Son la pieza más barata del hardening: un bloque de configuración en el servidor web o el framework cubre todo el tráfico, sin tocar la lógica de negocio. Aun así, se suelen olvidar hasta que una auditoría o el propio navegador te avisan.",
              ],
              def: {
                par: "Las cabeceras de seguridad HTTP instruyen al navegador sobre cómo comportarse con la respuesta: forzar HTTPS (HSTS), restringir orígenes de contenido (CSP), anular el sniffing de tipo MIME o impedir el embedding en iframes ajenos.",
                porQue: "Reducen la superficie de ataque del lado del cliente sin esfuerzo por petición: cada respuesta viaja con su política embebida.",
                cuando: "Aplícalas siempre en producción, todas juntas. No cubren el servidor en sí, pero cierran vectores de cliente y elevan la calificación en cualquier scanner.",
              },
              concepts: [
                "HSTS obliga al navegador a usar solo HTTPS y evita el downgrade a HTTP.",
                "CSP (Content-Security-Policy) lista los orígenes de scripts, estilos e imágenes permitidos.",
                "X-Frame-Options (o frame-ancestors) impide que tu web se incruste en iframes de terceros.",
                "X-Content-Type-Options: nosniff evita que el navegador sniffee el MIME real de una respuesta.",
                "Referrer-Policy controla cuánta información de tu URL se filtra al navegar a otros sitios.",
              ],
              basic: {
                p: "Observa qué expone tu API hoy y qué debería responder. Las cabeceras se ven con una simple petición HEAD.",
                code: [
                  "curl -sI https://api.example.com | grep -iE '^(HTTP|strict-transport|content-security|x-frame|x-content-type|referrer-policy|set-cookie)'",
                  "# Correcto ✓",
                  "Strict-Transport-Security: max-age=31536000; includeSubDomains",
                  "Content-Security-Policy: default-src 'none'",
                  "X-Frame-Options: DENY",
                  "X-Content-Type-Options: nosniff",
                  "Referrer-Policy: no-referrer",
                  "Set-Cookie: ...; HttpOnly; Secure; SameSite=Strict",
                ],
                out: "Un paquete estándar de cabeceras de seguridad con sus valores recomendados.",
                lang: "bash",
              },
              intermediate: {
                p: "En la práctica se declaran una vez en el servidor web y aplican a todo el tráfico. Configuración mínima en Nginx.",
                caption: "Hardening de cabeceras en Nginx",
                code: [
                  "server {",
                  "  add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;",
                  "  add_header Content-Security-Policy \"default-src 'none'; frame-ancestors 'none'\" always;",
                  "  add_header X-Frame-Options \"DENY\" always;",
                  "  add_header X-Content-Type-Options \"nosniff\" always;",
                  "  add_header Referrer-Policy \"no-referrer\" always;",
                  "}",
                ],
              },
              real: {
                p: "Un scanner de seguridad penaliza a tu sitio por cada cabecera ausente. En CI/CD puedes comprobar que ninguna desaparezca con una prueba simple sobre el endpoint de salud, antes de llegar al navegador del cliente.",
                ul: [
                  "Aplica las cabeceras en el borde (Nginx/CDN) para que ninguna respuesta escape sin política.",
                  "Valida en CI con una prueba que falle si falta HSTS, nosniff o frame-ancestors.",
                  "Revisa CSP en cada cambio de front: un origin nuevo bloqueado rompe funcionalidad en producción.",
                ],
                code: [
                  "import httpx",
                  "SECURITY_HEADERS = [\"strict-transport-security\", \"content-security-policy\",",
                  "                    \"x-frame-options\", \"x-content-type-options\"]",
                  "r = httpx.get(\"https://staging.example.com/api/health\", follow_redirects=True)",
                  "missing = [h for h in SECURITY_HEADERS if h not in r.headers]",
                  "assert not missing, f\"Faltan cabeceras: {missing}\"",
                ],
                nota: "HSTS con includeSubDomains exige que TODO tu subdominio sirva HTTPS; actívalo solo cuando estés seguro de no tener islas en HTTP.",
              },
              expl: [
                "HSTS se memoriza en el navegador durante max-age: con ello tu sitio deja de intentar recursos por HTTP.",
                "CSP con default-src 'none' es la más restrictiva: añade solo los orígenes que realmente necesitas.",
                "frame-ancestors 'none' impide el clickjacking moderno y describe mejor la intención que X-Frame-Options.",
                "nosniff es vital en APIs que sirven JSON: impide que un navegador lo ejecute si alguien logra reflejar contenido.",
                "Las cabeceras se heredan en cadenas de proxy: revisa que tu CDN no las pise o las duplique.",
              ],
              errors: [
                "Empezar la puesta en producción por HSTS #3 con includeSubDomains y un subdominio aún en HTTP.",
                "Dejar CSP vacía y esperar que siga protegiendo: sin directiva real, el navegador habilita el default más laxo.",
                "Confiar en una cabecera doble (two headers con valores opuestos) y que el navegador elija la mala.",
              ],
              tips: [
                "Empieza por nosniff, frame-ancestors y HSTS: son de bajo riesgo y alto impacto inmediato.",
                "Itera CSP en modo report-only antes de hacerla obligatoria para no romper el front.",
                "Incluye el check de cabeceras en tu prueba de humo del despliegue.",
              ],
              exercise: [
                "Añade las cinco cabeceras a tu API y verifica con curl que llegan en cada respuesta.",
                "Escribe la prueba en Python que falle si falta HSTS, nosniff o x-frame-options.",
                "Prueba CSP en report-only durante una semana y aplica los orígenes que registran los informes.",
              ],
              summary: [
                "Las cabeceras de seguridad son el hardening más barato: una configuración, todo el tráfico.",
                "La combinación estándar cierra clickjacking, MIME sniffing, downgrade a HTTP y fuga de origin.",
                "Compruébalas en CI y aplica CSP en modo report-only antes de endurecerla.",
              ],
              lang: "python",
              exampleFile: "cabeceras-de-seguridad-http",
              desc: "Endurece las respuestas HTTP con las cabeceras de seguridad que exige producción.",
            },
          },
        ],
      },
    ],
  },
];