// _curriculum_programacion.mjs
// Currículum del curso de Programación para Backend.
// Exporta COURSES con todos los módulos y lecciones.
// Las lecciones existentes en disco se listan SIN body (no se regeneran);
// las nuevas (módulo 07) llevan body completo (11 secciones estándar + metadatos).

export const COURSES = [
  {
    slug: "programacion",
    title: "Programación para Backend",
    modules: [
      {
        id: "modulo-01",
        n: 1,
        t: "Fundamentos de programación",
        level: "basico",
        caption: "Variables, tipos y operadores: el idioma base del desarrollo.",
        desc: "Aprende los cimientos de la programación orientada al backend: variables, constantes, tipos de datos, operadores, conversión de tipos y la entrada y salida de datos con comentarios profesionales.",
        subtitle: "Todo algoritmo del backend empieza por dominar variables, tipos y operadores.",
        objectives: [
          "Declarar variables y constantes respetando las reglas del lenguaje",
          "Distinguir los tipos de datos y su comportamiento",
          "Componer expresiones con operadores",
          "Convertir tipos de forma explícita y segura",
          "Manejar entrada y salida de datos con comentarios claros",
        ],
        lessons: [
          {
            id: "variables-y-constantes",
            title: "Variables y constantes",
            duration: "10 min",
            level: "basico",
            category: "fundamentos",
            cardText: "Guarda y reutiliza valores con variables y constantes, y entiende por qué un buen nombre importa en el backend.",
            desc: "Aprende a declarar variables y constantes en PHP para guardar y reutilizar datos en tu backend.",
          },
          {
            id: "tipos-de-datos",
            title: "Tipos de datos",
            duration: "12 min",
            level: "basico",
            category: "fundamentos",
            cardText: "int, float, string y bool: el tipo de cada valor define qué puedes hacer con él.",
            desc: "Conoce los tipos de datos de PHP y cómo influyen en la lógica de tu backend.",
          },
          {
            id: "operadores",
            title: "Operadores y expresiones",
            duration: "12 min",
            level: "basico",
            category: "fundamentos",
            cardText: "Construye expresiones con operadores aritméticos, de comparación, lógicos y de asignación.",
            desc: "Compón expresiones con operadores aritméticos, de comparación y lógicos en PHP.",
          },
          {
            id: "conversion-de-tipos",
            title: "Conversión de tipos",
            duration: "10 min",
            level: "basico",
            category: "fundamentos",
            cardText: "Convierte entre tipos explícita e implícitamente para validar peticiones sin sorpresas.",
            desc: "Convierte entre tipos de datos en PHP para controlar la entrada que llega a tu API.",
          },
          {
            id: "entrada-salida",
            title: "Entrada, salida y comentarios",
            duration: "10 min",
            level: "basico",
            category: "fundamentos",
            cardText: "Recibe datos del exterior y muéstralos, documentando cada decisión con comentarios.",
            desc: "Maneja la entrada y salida de datos en PHP y documenta tu código con comentarios.",
          },
        ],
      },
{
        id: "modulo-02",
        n: 2,
        t: "Control de flujo",
        level: "basico",
        caption: "Condicionales y bucles: tu código decide y repite por ti.",
        desc: "Domina if, else, elseif, switch, while, do-while, for y foreach, además del control fino con break y continue, para escribir la lógica que decide y repite en un backend real.",
        subtitle: "La lógica que toma decisiones y repite trabajo: condicionales y bucles.",
        objectives: [
          "Tomar decisiones con if, else y elseif",
          "Elegir switch cuando hay muchas comparaciones",
          "Repetir procesos con while y do-while",
          "Recorrer colecciones con for y foreach",
          "Controlar la ejecución de los bucles con break y continue",
        ],
        lessons: [
          {
            id: "condicionales",
            title: "Condicionales: if, else y elseif",
            duration: "12 min",
            level: "basico",
            category: "control de flujo",
            cardText: "Toma decisiones en tu código con if, else y elseif según el estado de la petición.",
            desc: "Aprende if, else y elseif en PHP para decidir el flujo de tu backend.",
          },
          {
            id: "condicional-switch",
            title: "La estructura switch",
            duration: "10 min",
            level: "basico",
            category: "control de flujo",
            cardText: "Compara un único valor contra muchas opciones de forma legible con switch.",
            desc: "Usa la estructura switch en PHP para comparar un valor contra múltiples casos.",
          },
          {
            id: "bucles-while",
            title: "Bucles while y do-while",
            duration: "10 min",
            level: "basico",
            category: "control de flujo",
            cardText: "Repite trabajo mientras se cumpla una condición con while y do-while.",
            desc: "Repite procesos con los bucles while y do-while en PHP.",
          },
          {
            id: "bucles-for-foreach",
            title: "Bucles for y foreach",
            duration: "12 min",
            level: "basico",
            category: "control de flujo",
            cardText: "Itera con for por contador y con foreach sobre arrays en el día a día del backend.",
            desc: "Aprende los bucles for y foreach de PHP para recorrer datos.",
          },
          {
            id: "break-continue",
            title: "break y continue: control fino de bucles",
            duration: "8 min",
            level: "basico",
            category: "control de flujo",
            cardText: "Sal de un bucle o salta una iteración con break y continue cuando sea necesario.",
            desc: "Controla los bucles de PHP con break y continue.",
          },
        ],
      },
{
        id: "modulo-03",
        n: 3,
        t: "Funciones",
        level: "basico",
        caption: "Código reutilizable: parámetros, scope, callbacks y recursividad.",
        desc: "Aprende a definir funciones, manejar parámetros y argumentos, entender el ámbito de las variables, utilizar funciones anónimas y callbacks y resolver problemas con recursividad.",
        subtitle: "Divide y vencerás: funciones que encapsulan lógica y se reutilizan.",
        objectives: [
          "Definir funciones y retornar valores",
          "Diferenciar parámetros y argumentos",
          "Entender el ámbito (scope) de las variables",
          "Usar funciones anónimas y callbacks",
          "Resolver problemas con recursividad",
        ],
        lessons: [
          {
            id: "funciones",
            title: "Funciones: definir y retornar",
            duration: "12 min",
            level: "basico",
            category: "funciones",
            cardText: "Agrupa lógica en funciones reutilizables que reciben datos y devuelven resultados.",
            desc: "Define funciones en PHP y retorna valores para reutilizar tu lógica de backend.",
          },
          {
            id: "parametros-y-argumentos",
            title: "Parámetros y argumentos",
            duration: "12 min",
            level: "basico",
            category: "funciones",
            cardText: "Pasa datos a tus funciones con parámetros, valores por defecto y tipos declarados.",
            desc: "Maneja parámetros y argumentos de funciones en PHP con tipos y valores por defecto.",
          },
          {
            id: "ambito-de-variables",
            title: "Ámbito (scope) de las variables",
            duration: "10 min",
            level: "basico",
            category: "funciones",
            cardText: "Local vs global: entiende dónde vive cada variable para evitar bugs sutiles.",
            desc: "Comprende el ámbito (scope) de las variables en PHP.",
          },
          {
            id: "funciones-anonimas-callbacks",
            title: "Funciones anónimas y callbacks",
            duration: "12 min",
            level: "basico",
            category: "funciones",
            cardText: "Pasa funciones como datos con cierres (closures) y callbacks para un código más flexible.",
            desc: "Usa funciones anónimas y callbacks en PHP para lógica más flexible.",
          },
          {
            id: "recursividad",
            title: "Recursividad",
            duration: "12 min",
            level: "basico",
            category: "funciones",
            cardText: "Una función que se llama a sí misma para resolver problemas por partes.",
            desc: "Resuelve problemas con recursividad en PHP.",
          },
        ],
      },
{
        id: "modulo-04",
        n: 4,
        t: "Estructuras de datos",
        level: "intermedio",
        caption: "Arrays, mapas, conjuntos y objetos: cómo se modelan los datos.",
        desc: "Organiza la información de tu backend con arrays indexados, arrays asociativos, conjuntos, objetos y estructuras anidadas, las piezas con las que se modela cualquier API.",
        subtitle: "Los datos importan: modelos con arrays, mapas y objetos.",
        objectives: [
          "Manejar arrays indexados",
          "Modelar mapas con arrays asociativos",
          "Usar conjuntos y colecciones",
          "Trabajar con objetos y estructuras de datos",
          "Componer estructuras anidadas complejas",
        ],
        lessons: [
          {
            id: "arrays",
            title: "Arrays: la base de los datos",
            duration: "14 min",
            level: "intermedio",
            category: "estructuras de datos",
            cardText: "El array es la estructura de datos por defecto del backend: ordénalo, recórrelo y transfórmalo.",
            desc: "Maneja arrays en PHP como base de las estructuras de datos del backend.",
          },
          {
            id: "arrays-asociativos",
            title: "Arrays asociativos (mapas)",
            duration: "12 min",
            level: "intermedio",
            category: "estructuras de datos",
            cardText: "Relaciona claves y valores para modelar registros, configuraciones y respuestas JSON.",
            desc: "Modela mapas clave-valor con arrays asociativos en PHP.",
          },
          {
            id: "conjuntos",
            title: "Conjuntos y colecciones",
            duration: "10 min",
            level: "intermedio",
            category: "estructuras de datos",
            cardText: "Colecciones de elementos únicos para operaciones de pertenencia y filtrado.",
            desc: "Usa conjuntos y colecciones en PHP para manejar elementos únicos.",
          },
          {
            id: "objetos",
            title: "Objetos y estructuras de datos",
            duration: "14 min",
            level: "intermedio",
            category: "estructuras de datos",
            cardText: "Modela entidades del dominio con objetos tipados y conversión a arrays y JSON.",
            desc: "Trabaja con objetos y estructuras de datos en PHP para modelar entidades.",
          },
          {
            id: "estructuras-anidadas",
            title: "Estructuras anidadas",
            duration: "12 min",
            level: "intermedio",
            category: "estructuras de datos",
            cardText: "Combina arrays y objetos en profundidad para representar datos complejos de una API.",
            desc: "Compose estructuras anidadas en PHP para representar datos complejos.",
          },
        ],
      },
{
        id: "modulo-05",
        n: 5,
        t: "Programación Orientada a Objetos",
        level: "intermedio",
        caption: "Clases, herencia y polimorfismo: el backend se modela con objetos.",
        desc: "Construye sistemas mantenibles con POO: clases, objetos, atributos, métodos, constructores, encapsulamiento, herencia, polimorfismo, abstracción e interfaces.",
        subtitle: "Modela tu dominio con clases, herencia y polimorfismo.",
        objectives: [
          "Crear clases e instancias correctamente",
          "Diseñar atributos, métodos y constructores",
          "Proteger el estado interno con encapsulamiento",
          "Compartir comportamiento con herencia",
          "Aplicar polimorfismo, abstracción e interfaces",
        ],
        lessons: [
          {
            id: "clases-y-objetos",
            title: "Clases y objetos",
            duration: "14 min",
            level: "intermedio",
            category: "poo",
            cardText: "Define clases e instancia objetos para modelar entidades que viven en tu backend.",
            desc: "Aprende clases y objetos en PHP para modelar entidades del backend.",
          },
          {
            id: "atributos-metodos-constructores",
            title: "Atributos, métodos y constructores",
            duration: "14 min",
            level: "intermedio",
            category: "poo",
            cardText: "Dota a tus clases de estado con atributos y de comportamiento con métodos y constructores.",
            desc: "Diseña atributos, métodos y constructores en PHP dentro de tus clases.",
          },
          {
            id: "encapsulamiento",
            title: "Encapsulamiento: public, private y protected",
            duration: "12 min",
            level: "intermedio",
            category: "poo",
            cardText: "Controla el acceso al estado interno con modificadores de visibilidad.",
            desc: "Aplica encapsulamiento en PHP con public, private y protected.",
          },
          {
            id: "herencia",
            title: "Herencia",
            duration: "12 min",
            level: "intermedio",
            category: "poo",
            cardText: "Reutiliza y especializa comportamiento extendiendo clases base.",
            desc: "Comparte comportamiento en PHP usando herencia entre clases.",
          },
          {
            id: "polimorfismo-abstraccion-interfaces",
            title: "Polimorfismo, abstracción e interfaces",
            duration: "14 min",
            level: "intermedio",
            category: "poo",
            cardText: "Diseña para la abstracción: clases abstractas, interfaces y comportamiento polimórfico.",
            desc: "Aplica polimorfismo, abstracción e interfaces en PHP.",
          },
        ],
      },
{
        id: "modulo-06",
        n: 6,
        t: "Código profesional",
        level: "intermedio",
        caption: "Modularidad, Clean Code, SOLID y errores: escribir para humanos.",
        desc: "Eleva tu código al nivel profesional: modularización, Clean Code, principios SOLID, DRY y KISS, debugging y manejo de errores con excepciones.",
        subtitle: "El código se lee más veces de las que se escribe: hazlo profesional.",
        objectives: [
          "Organizar el código en módulos coherentes",
          "Escribir código legible y mantenible con Clean Code",
          "Diseñar con los principios SOLID",
          "Reducir duplicidad con DRY y mantenerlo simple con KISS",
          "Depurar y manejar errores con excepciones",
        ],
        lessons: [
          {
            id: "modularizacion",
            title: "Modularización",
            duration: "12 min",
            level: "intermedio",
            category: "code profesional",
            cardText: "Divide tu proyecto en módulos y archivos con responsabilidades claras.",
            desc: "Organiza tu código PHP en módulos con responsabilidades claras.",
          },
          {
            id: "clean-code",
            title: "Clean Code",
            duration: "10 min",
            level: "intermedio",
            category: "code profesional",
            cardText: "Nombres claros, funciones pequeñas y legibilidad: escribir para humanos.",
            desc: "Aplica principios de Clean Code a tu código PHP de backend.",
          },
          {
            id: "principios-solid",
            title: "Principios SOLID",
            duration: "14 min",
            level: "intermedio",
            category: "code profesional",
            cardText: "Los cinco principios que mantienen tu código flexible y fácil de mantener.",
            desc: "Diseña con los principios SOLID en PHP.",
          },
          {
            id: "dry-kiss",
            title: "DRY y KISS",
            duration: "8 min",
            level: "intermedio",
            category: "code profesional",
            cardText: "No repitas lógica y mantenlo simple: dos reglas que evitan deuda técnica.",
            desc: "Reduce duplicidad con DRY y mantén la simplicidad con KISS en PHP.",
          },
          {
            id: "debugging",
            title: "Debugging y herramientas",
            duration: "12 min",
            level: "intermedio",
            category: "code profesional",
            cardText: "Puntos de ruptura, inspección de variables y herramientas de depuración.",
            desc: "Depura tu código PHP con herramientas y técnicas eficaces.",
          },
          {
            id: "manejo-de-errores",
            title: "Manejo de errores y excepciones",
            duration: "12 min",
            level: "intermedio",
            category: "code profesional",
            cardText: "Captura y gestiona errores con excepciones para respuestas robustas.",
            desc: "Maneja errores y excepciones en PHP para un backend robusto.",
          },
        ],
      },
{
        id: "modulo-07",
        n: 7,
        t: "Trabajo en equipo y herramientas",
        level: "intermedio",
        caption: "Git, colaboración, entornos y despliegue: de tu editor a producción.",
        desc: "Cierra el curso trabajando como en un equipo real: control de versiones con Git, pull requests, entornos de configuración, herramientas esenciales del backend y el camino del código hasta producción.",
        subtitle: "El backend profesional se construye en equipo y llega a producción.",
        objectives: [
          "Controlar versiones de tu código con Git",
          "Colaborar mediante pull requests y revisiones",
          "Gestionar la configuración por entornos",
          "Dominar las herramientas esenciales del backend",
          "Llevar tu código del repositorio al despliegue",
        ],
        lessons: [
          {
            id: "git-para-programadores",
            title: "Git para programadores",
            duration: "12 min",
            level: "intermedio",
            category: "colaboración",
            cardText: "El control de versiones como herramienta diaria: commits útiles, ramas y flujo de trabajo.",
            desc: "Aplica Git al flujo diario de programación con commits, ramas y buenas prácticas.",
            body: {
              intro: [
                "Hasta ahora has escrito código solo en tu editor. En producción, sin embargo, el código vive en un repositorio que comparte todo el equipo: cada cambio tiene historia, autor y motivo. Git es el estándar para que eso sea posible.",
                "Esta lección no trata de memorizar comandos: trata del flujo mental de guardar trabajo en pequeñas instantáneas comprensibles que después puedas revisar, comparar y restaurar.",
              ],
              def: {
                par: "Git es un sistema de control de versiones que registra los cambios de tu proyecto en instantáneas llamadas commits. Cada commit guarda un estado del código con autor, fecha y mensaje.",
                porQue: "En un backend real necesitas saber qué cambió, quién lo cambió y por qué para colaborar sin pisarte y para poder revertir un fallo en producción en segundos.",
                cuando: "Úsalo siempre, incluso en proyectos de una sola persona: abre una rama por funcionalidad, haz commits pequeños y deja git add solo para los archivos que tocan el cambio.",
              },
              concepts: [
                "Commit: una instantánea atómica del código con un mensaje claro.",
                "Rama (branch): una línea de trabajo independiente que no rompe main.",
                "Working tree, stage y repositorio: los tres espacios donde vive cada cambio.",
                "git diff: la lectura obligada antes de cada commit para revisar qué vas a guardar.",
                "git log: el historial legible de todo lo que ha pasado en el proyecto.",
              ],
              basic: {
                p: "El ciclo básico de un cambio con PHP: añadir los archivos que tocan esa tarea, revisar el diff y crear un commit con mensaje descriptivo.",
                code: [
                  "git status",
                  "git diff src/Auth/LoginController.php",
                  "git add src/Auth/LoginController.php",
                  'git commit -m "feat(auth): valida intentos de login fallidos"',
                  "git log --oneline --graph -5",
                ],
                out: "* commit 8f3c9a2 (HEAD -> feature/login-intentos) feat(auth): valida intentos de login fallidos",
                lang: "bash",
              },
              intermediate: {
                p: "Cuando la funcionalidad viene de otra rama, la integramos y resolvemos los conflictos que Git no puede decidir por nosotros.",
                code: [
                  "git checkout main",
                  "git merge feature/login-intentos",
                  "# Se modifica la misma línea en las dos ramas:",
                  "<<<<<<< HEAD",
                  "return $this->login();",
                  "=======",
                  "return $this->login($this->limitarIntentos());",
                  ">>>>>>> feature/login-intentos",
                  "# Editamos el archivo, guardamos y terminamos",
                  "git add src/Auth/LoginController.php",
                  'git commit -m "merge: integra control de intentos de login"',
                ],
                caption: "Resolución manual de un conflicto de merge",
                lang: "bash",
              },
              real: {
                p: "En un equipo de backend la regla es una rama por tarea, con el id del ticket en el nombre, y ningún push directo a main. Así cada cambio es auditable y reversible.",
                ul: [
                  "Mensajes convencionales: feat, fix, refactor, docs, chore.",
                  "Commits atómicos: un cambio lógico por commit, no diez.",
                  "Nunca versiones archivos generados, .env ni credenciales.",
                ],
                code: [
                  "git switch -c feat/278-reset-password",
                  "git add src/Auth/ResetPasswordService.php tests/ResetPasswordServiceTest.php",
                  'git commit -m "feat(auth): servicio de restablecimiento de contraseña"',
                  "git push -u origin feat/278-reset-password",
                ],
                nota: "El servicio de reset y su test forman un solo commit: si algo falla, se revierte todo o nada.",
                lang: "bash",
              },
              expl: [
                "git add mueve cambios al stage; el commit los fija en el historial.",
                "Las ramas son punteros baratos: crea tantas como necesites.",
                "Un conflicto no es un error: es una decisión de negocio que debes tomar tú.",
                "Revisar git diff antes de commit evita commits sucios y secretos colados.",
                "Un historial limpio convierte git log en documentación del producto.",
              ],
              errors: [
                "Hacer git add . sin mirar el diff y versionar el .env con credenciales.",
                "Mensajes como \"cambios\" o \"fix\" que no explican el porqué.",
                "Commitear archivos generados (vendor, storage/cache) llenando el repo de ruido.",
              ],
              tips: [
                "Configura un .gitignore con vendor/, .env y los archivos de caché.",
                "Usa git diff --cached para revisar qué tienes en el stage.",
                "Haz git log --oneline --graph por la mañana para ver el estado del equipo.",
                "Revertir es mejor que borrar: git revert crea un commit que anula el problema.",
              ],
              exercise: [
                "Crea una rama por cada funcionalidad de tu proyecto PHP y haz un commit por tarea.",
                "Fuerza un conflicto modificando la misma línea en dos ramas y resuélvelo.",
                "Escribe cinco mensajes de commit con prefijos feat y fix para cambios reales.",
              ],
              summary: [
                "Git guarda instantáneas atómicas con historia y motivo de cada cambio.",
                "Las ramas aíslan el trabajo y los merges integran decisiones.",
                "El flujo profesional: una rama por tarea, commits pequeños y main protegido.",
              ],
              lang: "bash",
              exampleFile: "git-para-programadores",
              desc: "Aplica Git al flujo diario de programación con commits, ramas y buenas prácticas.",
            },
          },
{
            id: "colaboracion-con-pull-requests",
            title: "Colaboración con pull requests",
            duration: "11 min",
            level: "intermedio",
            category: "colaboración",
            cardText: "Revisa el código de tus compañeros y defiende el tuyo: el ritual diario del trabajo en equipo.",
            desc: "Colabora mediante pull requests y revisiones de código en un equipo backend.",
            body: {
              intro: [
                "El pull request (PR) es la puerta por la que cada cambio entra al código compartido. Más que una petición técnica, es una conversación: el autor explica qué hace y por qué, y los revisores señalan riesgos antes de que el código llegue a producción.",
                "Dominar este ritual cambia tu forma de programar: sabes que alguien leerá tu código, así que lo escribes pensando en que otro lo entienda, no solo en que funcione.",
              ],
              def: {
                par: "Un pull request es una propuesta de cambio sobre una rama que otro desarrollador o un bot deben revisar antes de integrarla. Encierra diff, comentarios, discusión y estado de las comprobaciones.",
                porQue: "La revisión por pares atrapa bugs, aclara decisiones y distribuye conocimiento: deja de existir el único que entiende cada parte del backend.",
                cuando: "Úsalo para todo cambio que toque lógica de negocio, modelos de datos o endpoints. Para cambios triviales de un archivo con tests verdes, un PR corto también vale.",
              },
              concepts: [
                "Diff: la vista de exactamente qué líneas cambian (o se borran).",
                "Revise/apprure: aprobar, pedir cambios o comentar sin bloquear.",
                "Review en sitio: comentar sobre la propia línea de código.",
                "Checks: tests, linters y compilaciones que corren sobre el PR.",
                "Merge, squash y rebase: las tres formas de integrar la rama.",
              ],
              basic: {
                p: "Creamos un PR desde la rama de una funcionalidad con una descripción que orienta al revisor.",
                code: [
                  "git push -u origin feature/278-reset-password",
                  "# En GitHub o GitLab: New pull request",
                  "base: main   <-   compare: feature/278-reset-password",
                  'Título: "feat(auth): servicio de restablecimiento de contraseña"',
                  'Cuerpo: "Implementa el flujo de reset con token expirado de 30 min.',
                  "Incluye tests del servicio y del controlador. Closes #278.\"",
                ],
                out: "PR #289 creado · checks en ejecución · 2 commits · +312 −14",
                lang: "bash",
              },
              intermediate: {
                p: "La revisión suele pedir cambios. El autor los aplica en la misma rama y el PR se actualiza solo; la conversación queda documentada.",
                code: [
                  "# Comentario del revisor sobre src/Auth/ResetPasswordService.php",
                  '# "token->expiresAt no se valida en la rama de expirado"',
                  "",
                  "switch ($resultado) {",
                  '    case "token_invalido":',
                  '        throw new InvalidTokenException();',
                  '    case "token_expirado":',
                  '        throw new ExpiredTokenException();',
                  "}",
                  "# El autor añade la validación y empuja la corrección",
                  'git add src/Auth/ResetPasswordService.php',
                  'git commit -m "fix(auth): valida expiración del token antes de reset"',
                  "git push",
                ],
                caption: "Ciclo de comentario, corrección y re-empuje del PR",
                lang: "php",
              },
              real: {
                p: "Un PR de backend profesional incluye tests, cambios de esquema y una descripción de impacto. El checklist de revisión fija el nivel de calidad.",
                ul: [
                  "¿La lógica está testeada y los tests pasan en CI?",
                  "¿Se respetan los contratos de la API y la versión del recurso?",
                  "¿No cuelga algún dataset o credencial de ejemplo?",
                ],
                code: [
                  "# PR de migración de BD",
                  "SELECT version FROM schema_migrations;   # 42 -> 43",
                  "php artisan migrate --pretend",
                  "php artisan test tests/Auth/ResetPasswordFlowTest.php",
                  "git push",
                ],
                nota: "Los PR grandes y de una sola pieza se revisan peor. Fracciona el trabajo y revisa bloques pequeños.",
                lang: "bash",
              },
              expl: [
                "El cuerpo del PR explica el porqué porque el diff solo muestra el qué.",
                "Los checks en CI corren los tests antes de que nadie revise a mano.",
                "Un comentario en la línea correcta ahorra explicar contextos enteros.",
                "Aprobación no es confianza ciega: es fecha límite para la corrección.",
                "El squash al merge limpia el historial: varios commits de trabajo pasan a ser uno.",
              ],
              errors: [
                "Crear PRs gigantes de cientos de archivos imposibles de revisar.",
                "Resolver comentarios en la cabeza sin subir los cambios.",
                "Aprobar sin ejecutar: \"parece bien\" no es una revisión.",
              ],
              tips: [
                "Escribe el PR como una mini especificación de lo que hace y cómo probarlo.",
                "Mantén la PR abierta poco tiempo; la revisión en caliente es mejor.",
                "Usa plantillas de PR con checklist para que nadie olvide tests.",
                "Revisa primero los archivos de pruebas: te cuentan la intención.",
              ],
              exercise: [
                "Abre un PR que combine una funcionalidad y sus tests en una sola rama.",
                "Revisa un PR de un compañero y pide un cambio justificado con un comentario.",
                "Configura una checklist de revisión en la plantilla de PR de tu proyecto.",
              ],
              summary: [
                "Un PR es una propuesta de cambio revisada por pares antes de integrarse.",
                "La revisión en línea y los checks automáticos elevan el nivel del código.",
                "El ritual completo: descripción clara, tests verdes y discusión resuelta.",
              ],
              lang: "bash",
              exampleFile: "colaboracion-con-pull-requests",
              desc: "Colabora mediante pull requests y revisiones de código en un equipo backend.",
            },
          },
          {
            id: "entornos-y-configuracion",
            title: "Entornos de desarrollo y configuración",
            duration: "12 min",
            level: "intermedio",
            category: "configuración",
            cardText: "Separa desarrollo, staging y producción con variables de entorno y configuraciones seguras.",
            desc: "Gestiona la configuración por entornos con variables de entorno y prácticas seguras.",
            body: {
              intro: [
                "A nadie le gusta que la base de datos de producción aparezca en un archivo que se sube al repositorio. Los entornos resuelven eso: el mismo código se comporta distinto según dónde se ejecute, sin cambiar una línea del programa.",
                "La clave es la separación entre código y configuración: los valores sensibles viven fuera del código, en variables de entorno que cada entorno define por su cuenta.",
              ],
              def: {
                par: "Un entorno es un conjunto de ajustes (base de datos, URLs, umbrales, credenciales) en el que se ejecuta el backend. Separar configuración del código permite usar el mismo repositorio en desarrollo, staging y producción.",
                porQue: "Mezclar configuración y código rompe despliegues: la prueba en local no predice producción, y cualquier secreto versionado es una fuga anunciada.",
                cuando: "Aplicálo siempre que el comportamiento dependa del lugar: conexiones, cache, logging, pagos y cualquier feature flag.",
              },
              concepts: [
                "Variables de entorno: valores externos que PHP lee con getenv().",
                "Código 12-factor: configuración en el entorno, nunca en el código.",
                "Archivos .env: conveniente en local, olvidados en producción.",
                "Entornos típicos: dev, test, staging y production.",
                "Banderas de característica (feature flags): activar sin desplegar.",
              ],
              basic: {
                p: "Leemos la configuración con getenv() y definimos un valor por defecto para desarrollo.",
                code: [
                  "// config.php",
                  "return [",
                  "    \"db_host\" => getenv(\"DB_HOST\") ?: \"127.0.0.1\",",
                  "    \"db_name\" => getenv(\"DB_NAME\") ?: \"app_dev\",",
                  "    \"app_debug\" => getenv(\"APP_DEBUG\") === \"true\",",
                  "    \"app_env\" => getenv(\"APP_ENV\") ?: \"production\",",
                  "];",
                ],
                out: "Propiedades de conexión y modo debug derivadas del entorno, nunca del código.",
                lang: "php",
              },
              intermediate: {
                p: "En producción el .env vive en el servidor (o en el gestor de secretos), no en el repo. El mismo código se despliega en los tres entornos sin tocarlo.",
                code: [
                  "# .env.dev        (versionado si es inocuo)",
                  "APP_ENV=local",
                  "APP_DEBUG=true",
                  "DB_HOST=127.0.0.1",
                  "DB_NAME=app_dev",
                  "",
                  "# .env.production (solo en el servidor, nunca en git)",
                  "APP_ENV=production",
                  "APP_DEBUG=false",
                  "DB_HOST=db-prod.internal",
                  "DB_NAME=app_prod",
                  "DB_PASSWORD=super-secreto",
                ],
                caption: "Configuración idéntica en código, valores distintos por entorno",
                lang: "bash",
              },
              real: {
                p: "En un deploy real las variables llegan del sistema o del orquestador. Nginx, Docker Compose o el panel del host inyectan el entorno y el código solo lee.",
                ul: [
                  "APP_DEBUG=false y log aggregation activa en producción.",
                  "Nunca credenciales reales en repositorios ni en errores.",
                  "Configuración centralizada y validada al arrancar la app.",
                ],
                code: [
                  "# Docker Compose (extracto)",
                  "services:",
                  "  app:",
                  "    build: .",
                  "    environment:",
                  "      APP_ENV: production",
                  "      APP_DEBUG: \"false\"",
                  "      DB_PASSWORD: \u003c?vault-secret?\u003e",
                ],
                nota: "Los secretos ideales viven en un gestor (Secrets Manager, vault) y se inyectan como variables, no escritos en archivos.",
                lang: "bash",
              },
              expl: [
                "getenv() devuelve el valor del entorno o false; el operador ?: aplica el valor por defecto.",
                "Separar entornos evita borrar datos reales probando en local.",
                "APP_DEBUG=false impide que la pila de errores cuelgue datos internos al cliente.",
                "Un .env versionado sirve de plantilla; añade .env al .gitignore.",
                "Valida la configuración al arrancar: falla rápido antes de servir tráfico con valores rotos.",
              ],
              errors: [
                "Versionar .env con credenciales reales de producción.",
                "Activar APP_DEBUG=true en producción mostrando trazas internas.",
                "Crear ramas de código por entorno; los entornos cambian valores, no código.",
              ],
              tips: [
                "Empieza por getenv() con valores por defecto y un archivo de configuración central.",
                "Añade .env.local y .env a .gitignore desde el primer día.",
                "Define APP_ENV y después condiciona el resto de la configuración.",
                "Repite el valor por defecto y comenta dónde se cambia cada variable.",
              ],
              exercise: [
                "Extrae la configuración de una conexión PDO del código a variables de entorno.",
                "Crea .env.dev y .env.production con valores distintos y prueba que el código no cambia.",
                "Añade una variable ENABLE_FEATURE_X que encienda una ruta solo en staging.",
              ],
              summary: [
                "Configuración y código viven separados: los entornos definen valores.",
                "Git debe ignorar .env y cualquier secreto.",
                "El mismo repositorio se ejecuta idéntico en dev, staging y producción.",
              ],
              lang: "php",
              exampleFile: "entornos-y-configuracion",
              desc: "Gestiona la configuración por entornos con variables de entorno y prácticas seguras.",
            },
          },
{
            id: "herramientas-esenciales-backend",
            title: "Herramientas esenciales del backend",
            duration: "11 min",
            level: "intermedio",
            category: "herramientas",
            cardText: "Composer, linters, análisis estático y Docker: el taller completo de un desarrollador backend.",
            desc: "Domina las herramientas esenciales del backend: Composer, linters, análisis estático y contenedores.",
            body: {
              intro: [
                "El código no viaja solo: lo acompañan el gestor de dependencias, el linter que vigila el estilo, el analizador estático que caza errores antes de ejecutar y el contenedor que lo empaqueta igual en todos los equipos.",
                "Estas herramientas hacen tu vida más fácil porque trasladan la disciplina del equipo al máquina: errores que antes saltaban en producción se detienen en el commit.",
              ],
              def: {
                par: "El taller del backend moderno incluye Composer (dependencias PHP), un linter de estilo (phpcs), un analizador estático (PHPStan/Psalm), pruebas con PHPUnit y contenedores con Docker.",
                porQue: "Dependencias repetibles, estilo consistente y verificación automática reducen la deuda técnica y los fallos de producción.",
                cuando: "Prepara el entorno la primera semana de cualquier proyecto; cuanto antes se integre el linter en tu editor, antes deja de ser una molestia.",
              },
              concepts: [
                "Composer: gestión de dependencias y autoload PSR-4.",
                "phpcs/php-cs-fixer: estilo de código unificado.",
                "PHPStan/Psalm: análisis estático que encuentra bugs sin ejecutar.",
                "PHPUnit: la suite de pruebas que ejecutas tras cada cambio.",
                "Docker: entornos reproducibles para toda la fase del pipeline.",
              ],
              basic: {
                p: "Arrancamos un proyecto moderno con Composer y veremos qué hace el autoload de PSR-4.",
                code: [
                  "composer init",
                  'composer require --dev phpunit/phpunit phpstan/phpstan squizlabs/php_codesniffer',
                  "# composer.json",
                  '"autoload": {',
                  '  "psr-4": { "App\\\\": "src/" }',
                  "},",
                  "php -l src/App/Auth/ResetPasswordService.php",
                  "vendor/bin/phpunit",
                ],
                out: "OK (1 test, 3 assertions) · No syntax errors detected in src/App/Auth/ResetPasswordService.php",
                lang: "bash",
              },
              intermediate: {
                p: "El análisis estático entiende tu intención y te avisa antes de que rompas producción. Veamos cómo PHPStan señala un error seguro.",
                code: [
                  "class ResetPasswordService {",
                  "    public function generarToken(): string {",
                  "        return $this->repo->nuevaEntrada(); // devuelve ?Entrada",
                  "    }",
                  "}",
                  "# vendor/bin/phpstan analyse src --level 6",
                  "ERROR: Cannot assign int to property $expiracion::int, got ?string",
                ],
                caption: "PHPStan señalando un tipo incierto al nivel 6",
                lang: "php",
              },
              real: {
                p: "Docker deja atrás el cliché de \"en mi máquina funciona\": la imagen de la app es igual para todo el equipo y para el servidor.",
                ul: [
                  "Dockerfile declarativo para la imagen de la app.",
                  "docker compose levanta app + base de datos en local.",
                  "El mismo Dockerfile en CI y en producción garantiza paridad.",
                ],
                code: [
                  "FROM php:8.3-fpm",
                  "RUN docker-php-ext-install pdo_mysql",
                  "COPY . /var/www/html",
                  "WORKDIR /var/www/html",
                  "RUN composer install --no-dev --optimize-autoloader",
                ],
                nota: "La cadena de herramientas convierte el \"en mi máquina funciona\" en \"funciona en cualquier máquina\".",
                lang: "dockerfile",
              },
              expl: [
                "Composer descarga, versiona y protege las dependencias de tu proyecto.",
                "El autoload PSR-4 evita cientos de require manuales.",
                "phpcs aplica el estilo del equipo sin discusiones entre desarrolladores.",
                "PHPStan nivela el análisis progresivamente, sin inundar de warnings.",
                "Docker encapsula PHP, extensiones y configuraciones en una imagen reproducible.",
              ],
              errors: [
                "Commitear vendor/ o las dependencias del sistema: el repo y la imagen Docker deben ser el contrato.",
                "Poner PHPStan al nivel máximo el primer día e ignorar los errores.",
                "Confundir el linter con el análisis estático: uno vigila estilo, el otro tipos y flujo.",
              ],
              tips: [
                "Añade los scripts de Composer: composer test, composer lint y composer analyse.",
                "Integra phpcs y PHPStan en tu editor para que corrijan al escribir.",
                "Saca a CI la ejecución de phpunit y phpstan para bloquear merges.",
                "Empieza PHPStan en nivel 3 y súbelo de a uno con cada refactor.",
              ],
              exercise: [
                "Inicializa Composer en un proyecto PHP y activa el autoload PSR-4 de src/.",
                "Ejecuta phpstan en un nivel bajo y corrige los tres primeros errores.",
                "Escribe un Dockerfile mínimo para tu app y levántala con docker compose.",
              ],
              summary: [
                "Composer gestiona dependencias y autoload de forma repetible.",
                "phpcs y PHPStan protegen el estilo y los tipos antes de ejecutar.",
                "Docker convierte el entorno en reproducible para todo el equipo.",
              ],
              lang: "bash",
              exampleFile: "herramientas-esenciales-backend",
              desc: "Domina las herramientas esenciales del backend: Composer, linters, análisis estático y contenedores.",
            },
          },
          {
            id: "del-codigo-al-despliegue",
            title: "Del código al despliegue",
            duration: "12 min",
            level: "intermedio",
            category: "despliegue",
            cardText: "Cierra el círculo: integra, prueba y despliega tu backend con seguridad y sin sustos.",
            desc: "Lleva tu código PHP del repositorio a producción con integración continua y despliegue seguro.",
            body: {
              intro: [
                "Escribir el código era la parte bonita; ahora toca que llegue a producción entero, probado y en el orden correcto. Ese camino se llama pipeline y se automatiza para que ningún humano olvide el paso de las migraciones o los tests.",
                "En esta lección conectamos todo lo aprendido: Git alimenta la integración continua, que ejecuta tests y análisis, y un artefacto empujable termina desplegado en el servidor.",
              ],
              def: {
                par: "El pipeline de CI/CD ejecuta automáticamente tests, análisis estático y build tras cada push, y despliega el resultado si todo fue verde. Sus dos fases son Continuous Integration (integrar y verificar) y Continuous Delivery/Deployment (publicar).",
                porQue: "Desplegar a mano a medianoche es la fuente del pánico. La automatización hace que cada release sea idéntica, reversible y con los tests ya corridos.",
                cuando: "Configúralo antes de que el proyecto tenga más de un colaborador. Para backend críticos, entrena el pipeline con releases pequeñas y frecuentes.",
              },
              concepts: [
                "Integración continua: tests y checks ejecutados en cada push.",
                "Artefacto: la salida lista para desplegar (imagen, zip, build).",
                "Migraciones de base de datos: los cambios de esquema versionados.",
                "Despliegue: publicar el artefacto en el entorno de destino.",
                "Rollback: la vía de escape rápida si algo sale mal.",
              ],
              basic: {
                p: "El flujo mínimo que todo backend debería automatizar: en cada push se ejecutan lint, tests de la API y despliegue condicional.",
                code: [
                  "on: push",
                  "jobs:",
                  "  test:",
                  "    runs-on: ubuntu-latest",
                  "    steps:",
                  "      - uses: actions/checkout@v4",
                  "      - uses: shivammathur/setup-php@v2",
                  "      - run: composer install --no-interaction",
                  "      - run: vendor/bin/phpunit",
                  "      - run: vendor/bin/phpstan analyse src --level 5",
                ],
                out: "All checks have passed · 24 tests · 1 deploy artifact",
                lang: "yaml",
              },
              intermediate: {
                p: "Antes de tocar producción revisamos el plan de las migraciones: ver qué hará sobre la base de datos evita sorpresas.",
                code: [
                  "php artisan migrate --pretend",
                  "CREATE TABLE password_resets;",
                  "ALTER TABLE users ADD COLUMN reset_token_expires_at;",
                  "",
                  "# Solo cuando el plan es correcto, se ejecuta",
                  "php artisan migrate --force",
                  "php artisan config:cache && php artisan route:cache",
                  "systemctl reload php8.3-fpm",
                ],
                caption: "Revisión y aplicación de migraciones en el despliegue",
                lang: "bash",
              },
              real: {
                p: "Un despliegue profesional delega las migraciones a un paso dedicado y mantiene el servidor arriba con un reload, no un reinicio.",
                ul: [
                  "Backup automático antes de migrar.",
                  "Health check post-despliegue: el endpoint responde 200.",
                  "Rollback documentado: revertir la migración o volver el artefacto.",
                ],
                code: [
                  "echo '== backup =='",
                  "mysqldump app_prod > backup_$(date +%Y%m%d).sql",
                  "echo '== deploy =='",
                  "rsync -avz --delete dist/ usuario@prod:/var/www/html/",
                  "php artisan migrate --force",
                  "systemctl reload php8.3-fpm",
                  "curl -f https://api.example.com/health",
                ],
                nota: "El health check falla el despliegue si la app no arranca: mejor un 500 detectado por la máquina que por un usuario.",
                lang: "bash",
              },
              expl: [
                "El pipeline acota el trabajo manual: el dev empuja, la máquina verifica.",
                "Los tests de integración corren sobre la base real para validar migraciones.",
                "El artefacto se construye una vez y se despliega igual en staging y producción.",
                "Los health checks verifican el resultado, no solo el comando.",
                "El rollback no es una vergüenza: es la red de seguridad diseñada a propósito.",
              ],
              errors: [
                "Migrar la base antes de que el código esté desplegado y romper la compatibilidad.",
                "Desplegar archivos sin eliminar los obsoletos (usa --delete con cautela).",
                "Omitir el health check y enterarte del fallo por los clientes.",
              ],
              tips: [
                "Despliega lo mismo que probaste: mismo artefacto en staging y producción.",
                "Haz releases pequeñas y frecuentes para reducir el área de blast de cada una.",
                "Documenta el rollback en el propio runbook del despliegue.",
                "Dispara el pipeline también para ramas de pruebas, no solo main.",
              ],
              exercise: [
                "Crea un flujo de GitHub Actions que ejecute tus pruebas en cada push.",
                "Redacta el plan de migraciones de una tabla nueva y aplícalo con --pretend.",
                "Escribe un script de despliegue con backup, health check y rollback.",
              ],
              summary: [
                "El pipeline automatiza la integración, los tests y el despliegue del backend.",
                "Migraciones verificadas y health checks hacen fiable cada release.",
                "Despliegues pequeños, frecuentes y reversibles definen el flujo profesional.",
              ],
              lang: "bash",
              exampleFile: "del-codigo-al-despliegue",
              desc: "Lleva tu código PHP del repositorio a producción con integración continua y despliegue seguro.",
            },
          },
        ],
      },
    ],
  },
];
