// _curriculum_apis-rest.mjs
// Currículum del curso de APIs REST.
// Exporta COURSES con todos los módulos y lecciones.
// Las lecciones existentes en disco se listan SIN body (no se regeneran);
// las nuevas (módulo 07) llevan body completo (11 secciones estándar + metadatos).

export const COURSES = [
  {
    slug: "apis-rest",
    title: "APIs REST",
    modules: [
      {
        id: "modulo-01",
        n: 1,
        t: "Fundamentos de APIs",
        level: "intermedio",
        caption: "Qué es una API, su anatomía y los recursos que la componen.",
        desc: "Comprende qué es una API real, quién la consume, la historia y el estilo REST, los recursos con sus representaciones JSON y la arquitectura que los sostiene.",
        subtitle: "Antes de diseñar una API, entiende qué es exactamente y quién la usará.",
        objectives: [
          "Reconocer la anatomía de una API real",
          "Identificar clientes y consumidores",
          "Entender el estilo REST y su origen",
          "Definir qué es una API y para qué sirve",
          "Modelar recursos con representaciones JSON",
        ],
        lessons: [
          {
            id: "anatomia-api-real",
            title: "La anatomía de una API real",
            duration: "8 min",
            level: "intermedio",
            category: "fundamentos",
            cardText: "Recorremos una API real por dentro: endpoints, contratos, transporte y datos.",
            desc: "Reconoce las partes que componen una API real y cómo encajan.",
          },
          {
            id: "clientes-consumidores-api",
            title: "Clientes y consumidores de una API",
            duration: "9 min",
            level: "intermedio",
            category: "fundamentos",
            cardText: "Apps, frontends e integraciones: cada consumidor impone sus reglas de diseño.",
            desc: "Identifica quién consume tu API y cómo condiciona su diseño.",
          },
          {
            id: "estilo-rest-historia",
            title: "El estilo REST y su historia",
            duration: "8 min",
            level: "intermedio",
            category: "fundamentos",
            cardText: "De la tesis de Roy Fielding al estándar de facto de las APIs web.",
            desc: "Entiende el origen y los principios del estilo REST.",
          },
          {
            id: "que-es-una-api",
            title: "¿Qué es una API y para qué sirve?",
            duration: "8 min",
            level: "intermedio",
            category: "fundamentos",
            cardText: "Una interfaz de programación que expone el backend de forma controlada.",
            desc: "Define qué es una API y para qué sirve en un backend.",
          },
          {
            id: "recursos-representaciones-json",
            title: "Recursos y representaciones con JSON",
            duration: "9 min",
            level: "intermedio",
            category: "fundamentos",
            cardText: "Los recursos son la unidad de la API y JSON es su lenguaje habitual.",
            desc: "Modela recursos y sus representaciones JSON en REST.",
          },
        ],
      },
{
        id: "modulo-02",
        n: 2,
        t: "HTTP aplicado a REST",
        level: "intermedio",
        caption: "Cabeceras, códigos, métodos y negociación: habla HTTP con fluidez.",
        desc: "Domina el protocolo que transporta tu API: cabeceras de petición y respuesta, códigos de estado del 1xx al 5xx, Content-Type, métodos HTTP y negociación de contenido.",
        subtitle: "REST vive en HTTP: cuanto mejor lo domines, mejores APIs diseñarás.",
        objectives: [
          "Entender las cabeceras de petición y respuesta",
          "Elegir el código de estado correcto en cada caso",
          "Usar Content-Type y Content-Disposition",
          "Aplicar correctamente los métodos HTTP",
          "Negociar contenido entre cliente y servidor",
        ],
        lessons: [
          {
            id: "cabeceras-peticion-respuesta",
            title: "Cabeceras de petición y de respuesta",
            duration: "10 min",
            level: "intermedio",
            category: "http",
            cardText: "Authorization, Accept, Cache-Control y más: el contexto que HTTP entrega en cada llamada.",
            desc: "Aprende las cabeceras de petición y respuesta que mueven tu API.",
          },
          {
            id: "codigos-estado",
            title: "Códigos de estado del 1xx al 5xx",
            duration: "9 min",
            level: "intermedio",
            category: "http",
            cardText: "200, 201, 204, 400, 404, 429 y 503: el vocabulario del éxito y del error.",
            desc: "Domin los códigos de estado HTTP y cuándo usarlos en tu API.",
          },
          {
            id: "content-type-content-disposition",
            title: "Content-Type y Content-Disposition",
            duration: "9 min",
            level: "intermedio",
            category: "http",
            cardText: "Declara el formato del cuerpo y cómo el cliente debe tratar la respuesta.",
            desc: "Usa Content-Type y Content-Disposition para respuestas con formato.",
          },
          {
            id: "metodos-http",
            title: "Métodos HTTP: GET, POST, PUT, PATCH y DELETE",
            duration: "10 min",
            level: "intermedio",
            category: "http",
            cardText: "El verbo de cada petición expresa la intención sobre el recurso.",
            desc: "Aplica GET, POST, PUT, PATCH y DELETE correctamente en REST.",
          },
          {
            id: "negociacion-contenido",
            title: "Negociación de contenido",
            duration: "10 min",
            level: "intermedio",
            category: "http",
            cardText: "Accept y Content-Type permiten que el cliente elija el formato de la respuesta.",
            desc: "Implementa la negociación de contenido (JSON, XML, versiones).",
          },
        ],
      },
{
        id: "modulo-03",
        n: 3,
        t: "Diseño REST",
        level: "intermedio",
        caption: "Recursos, caché, errores, paginación y versionado: el diseño que perdura.",
        desc: "Diseña APIs que aguantan años en producción: caché con ETag y Cache-Control, errores consistentes, recursos en plural, paginación por query y versionado de URLs o headers.",
        subtitle: "Un buen diseño REST se nota a los dos años de estar en producción.",
        objectives: [
          "Aplicar caché con ETag y Cache-Control",
          "Diseñar una estructura de errores consistente",
          "Nombrar los recursos correctamente en plural",
          "Paginación y filtros por query",
          "Elegir la estrategia de versionado adecuada",
        ],
        lessons: [
          {
            id: "cache-etag-cache-control",
            title: "Caché con ETag y Cache-Control",
            duration: "10 min",
            level: "intermedio",
            category: "diseño",
            cardText: "Los validadores y la directiva de caché ahorran tráfico y latencia.",
            desc: "Implementa caché con ETag y Cache-Control en tus respuestas.",
          },
          {
            id: "estructura-errores-consistente",
            title: "Estructura de errores consistente",
            duration: "10 min",
            level: "intermedio",
            category: "diseño",
            cardText: "Un contrato de error uniforme que los clientes puedan parsear sin sorpresas.",
            desc: "Diseña una estructura de errores consistente para tu API.",
          },
          {
            id: "nombrando-recursos-plural",
            title: "Nombrando recursos en plural",
            duration: "10 min",
            level: "intermedio",
            category: "diseño",
            cardText: "/users y /users/42: sustantivos plurales y jerarquía simple y predecible.",
            desc: "Nombra los recursos de tu API en plural y con jerarquía clara.",
          },
          {
            id: "paginacion-filtros-query",
            title: "Paginación y filtros por query",
            duration: "10 min",
            level: "intermedio",
            category: "diseño",
            cardText: "page, limit, cursor y filtros: colecciones grandes sin ahogar al servidor.",
            desc: "Implementa paginación y filtros por query en tus listados.",
          },
          {
            id: "versionado-url-headers",
            title: "Versionado: URL vs headers",
            duration: "10 min",
            level: "intermedio",
            category: "diseño",
            cardText: "/v1/users o Accept: application/vnd.api.v1: las dos escuelas del versionado.",
            desc: "Compara el versionado por URL y el versionado por headers.",
          },
        ],
      },
{
        id: "modulo-04",
        n: 4,
        t: "Implementación",
        level: "intermedio",
        caption: "CRUD, autenticación, errores y validación: pone tu API a correr.",
        desc: "Implementa una API de verdad: autenticación básica y API keys, un CRUD completo de recurso, manejo de errores centralizado, serialización consistente y validación de entrada.",
        subtitle: "Del diseño al código: implementa un CRUD sólido y validado.",
        objectives: [
          "Autenticar con básica y API keys",
          "Implementar un CRUD completo de recurso",
          "Centralizar el manejo de errores",
          "Serializar respuestas consistentes",
          "Validar la entrada con reglas claras",
        ],
        lessons: [
          {
            id: "autenticacion-basica-api-keys",
            title: "Autenticación básica y API keys",
            duration: "11 min",
            level: "intermedio",
            category: "implementación",
            cardText: "Identifica a quien llama: Basic Auth para servicios internos y API keys para integraciones.",
            desc: "Implementa autenticación básica y API keys en tu API.",
          },
          {
            id: "crud-recurso-completo",
            title: "CRUD de un recurso completo",
            duration: "10 min",
            level: "intermedio",
            category: "implementación",
            cardText: "Listar, crear, leer, actualizar y borrar: el flujo completo sobre un recurso.",
            desc: "Construye el CRUD completo de un recurso REST.",
          },
          {
            id: "manejo-errores-centralizado",
            title: "Manejo de errores centralizado",
            duration: "10 min",
            level: "intermedio",
            category: "implementación",
            cardText: "Un único punto que convierte cualquier excepción en una respuesta de error.",
            desc: "Centraliza el manejo de errores de tu API en un solo punto.",
          },
          {
            id: "serializacion-respuestas-consistentes",
            title: "Serialización y respuestas consistentes",
            duration: "10 min",
            level: "intermedio",
            category: "implementación",
            cardText: "El mismo molde para cada respuesta: datos, metadatos y errores uniformes.",
            desc: "Serializa respuestas consistentes en toda tu API.",
          },
          {
            id: "validacion-entrada-reglas",
            title: "Validación de entrada y reglas",
            duration: "11 min",
            level: "intermedio",
            category: "implementación",
            cardText: "Nunca confíes en el cliente: valida cada campo antes de tocar tu lógica.",
            desc: "Valida la entrada de tu API con reglas claras.",
          },
        ],
      },
{
        id: "modulo-05",
        n: 5,
        t: "Documentación",
        level: "intermedio",
        caption: "OpenAPI, contrato y Swagger UI: documenta lo que construyes.",
        desc: "Convierte tu API en documentada y explorable: define el contrato, describe OpenAPI, documenta ejemplos y errores, genera SDKs y explora la API con Swagger UI.",
        subtitle: "Una API sin documentación es una API que nadie sabe usar.",
        objectives: [
          "Definir el contrato de la API",
          "Documentar con OpenAPI",
          "Usar Swagger UI para explorar y probar",
          "Incluir ejemplos y errores documentados",
          "Generar SDKs a partir del contrato",
        ],
        lessons: [
          {
            id: "definiendo-contrato-api",
            title: "Definiendo el contrato de la API",
            duration: "11 min",
            level: "intermedio",
            category: "documentación",
            cardText: "El contrato es el acuerdo formal entre tu API y quien la consume.",
            desc: "Define el contrato formal de tu API antes de implementarla.",
          },
          {
            id: "ejemplos-errores-sdks-generados",
            title: "Ejemplos, errores y SDKs generados",
            duration: "10 min",
            level: "intermedio",
            category: "documentación",
            cardText: "Ejemplos reales, catálogo de errores y SDKs que nacen del contrato.",
            desc: "Documenta ejemplos y errores y genera SDKs con tu contrato.",
          },
          {
            id: "que-es-openapi",
            title: "¿Qué es OpenAPI?",
            duration: "10 min",
            level: "intermedio",
            category: "documentación",
            cardText: "El estándar para describir APIs: rutas, parámetros, esquemas y respuestas.",
            desc: "Aprende qué es OpenAPI y cómo describir una API declarativamente.",
          },
          {
            id: "swagger-ui-exploracion",
            title: "Swagger UI: exploración de la API",
            duration: "11 min",
            level: "intermedio",
            category: "documentación",
            cardText: "De la especificación a una consola interactiva lista para probar endpoints.",
            desc: "Explora y prueba tu API con Swagger UI.",
          },
        ],
      },
      {
        id: "modulo-06",
        n: 6,
        t: "Calidad y seguridad",
        level: "intermedio",
        caption: "CORS, monitoreo, rate limiting y tests: una API lista para producción.",
        desc: "Endurece tu API: CORS y seguridad, monitoreo y métricas, rate limiting contra abusos y testing de endpoints para que no se rompa en producción.",
        subtitle: "Calidad y seguridad son las que aguantan el tráfico real.",
        objectives: [
          "Configurar CORS y buenas prácticas de seguridad",
          "Monitorear la API con métricas básicas",
          "Proteger la API con rate limiting",
          "Testear los endpoints de la API",
        ],
        lessons: [
          {
            id: "cors-buenas-practicas-seguridad",
            title: "CORS y buenas prácticas de seguridad",
            duration: "12 min",
            level: "intermedio",
            category: "calidad y seguridad",
            cardText: "Solo quien debe: política CORS y el checklist de seguridad del backend.",
            desc: "Configura CORS y aplica buenas prácticas de seguridad en tu API.",
          },
          {
            id: "monitoreo-metricas-basicas",
            title: "Monitoreo y métricas básicas",
            duration: "11 min",
            level: "intermedio",
            category: "calidad y seguridad",
            cardText: "Latencia, tasa de error y saturación: saber cómo respira tu API.",
            desc: "Monitorea tu API con métricas básicas de latencia y errores.",
          },
          {
            id: "rate-limiting-abuso-api",
            title: "Rate limiting y abuso de la API",
            duration: "11 min",
            level: "intermedio",
            category: "calidad y seguridad",
            cardText: "429 Too Many Requests: protege el backend de clientes que se pasan.",
            desc: "Implementa rate limiting para proteger tu API del abuso.",
          },
          {
            id: "testing-endpoints",
            title: "Testing de endpoints",
            duration: "11 min",
            level: "intermedio",
            category: "calidad y seguridad",
            cardText: "Pruebas que golpean los endpoints de verdad y blindan el contrato.",
            desc: "Testea los endpoints de tu API de forma automatizada.",
          },
        ],
      },
{
        id: "modulo-07",
        n: 7,
        t: "APIs en producción",
        level: "avanzado",
        caption: "Versionado semántico, evolución, deprecación y gobierno: la API vive años.",
        desc: "Gestiona la vida de tu API: versionado semántico, evolución sin romper clientes, deprecación de endpoints, compatibilidad hacia atrás y gobierno con observabilidad.",
        subtitle: "Las mejores APIs se cuidan más allá del día del lanzamiento.",
        objectives: [
          "Versionar la API con SemVer y changelogs",
          "Evolucionar endpoints sin romper clientes",
          "Depreciar y retirar endpoints con un plan",
          "Mantener la compatibilidad hacia atrás",
          "Gobernar la API con observabilidad",
        ],
        lessons: [
          {
            id: "versionado-semantico-para-apis",
            title: "Versionado semántico para APIs",
            duration: "12 min",
            level: "avanzado",
            category: "producción",
            cardText: "MAJOR.MINOR.PATCH aplicado a contratos: cuándo romper y cuándo sumar.",
            desc: "Aplica el versionado semántico y los changelogs a tu API.",
            body: {
              intro: [
                "Tu API vivirá años y cambiará decenas de veces. Sin una forma de comunicar cuánto cambia cada release, los consumidores nunca sabrán si pueden actualizar con confianza o si se les romperá el contrato.",
                "El versionado semántico (SemVer) resuelve esto con tres números que declaran la intención: MAJOR rompe, MINOR suma sin romper y PATCH corrige sin cambiar el contrato.",
              ],
              def: {
                par: "El versionado semántico usa MAJOR.MINOR.PATCH para comunicar el impacto de cada release de una API: MAJOR introduce cambios incompatibles, MINOR añade funcionalidad compatible y PATCH corrige errores sin alterar el contrato.",
                porQue: "El consumidor necesita saber, con solo leer la versión, si puede actualizar en caliente o si debe planificar una migración.",
                cuando: "Aplícalo a partir de la primera versión estable de la API. Durante el desarrollo inicial, la convención 0.x ya avisa de inestabilidad.",
              },
              concepts: [
                "MAJOR: cambios incompatibles (romper contrato, borrar campos).",
                "MINOR: funciones nuevas retrocompatibles (añadir campos).",
                "PATCH: correcciones que no cambian el comportamiento público.",
                "Changelog: el registro legible de qué cambió en cada versión.",
                "Versión del contrato vs versión de la implementación.",
              ],
              basic: {
                p: "Diseñamos el contrato OpenAPI con su versión SemVer y el changelog que acompaña cada release.",
                code: [
                  "openapi: 3.1.0",
                  "info:",
                  "  title: Shop API",
                  "  version: \"2.3.0\"",
                  "  description: >",
                  "    v2.3.0 (MINOR): nuevo campo `currency` en el pedido.",
                  "    v2.2.1 (PATCH): corrige el código 204 al vaciar el carrito.",
                  "    v2.0.0 (MAJOR): `/orders` en plural, contrato renovado.",
                ],
                out: "La versión declara el historial y el contrato se mantiene legible solo con la cabecera.",
                lang: "yaml",
              },
              intermediate: {
                p: "El changelog estructurado en Keep a Changelog deja ver el impacto real de cada versión: qué se añadió, qué se corrigió y qué rompió.",
                code: [
                  "## [2.3.0] - 2026-08-12",
                  "### Añadido",
                  "- Campo `currency` en el recurso pedido (retrocompatible).",
                  "- Endpoint `GET /orders/{id}/tracking`.",
                  "### Corregido",
                  "- Se devuelve 204 en vez de 200 al vaciar el carrito.",
                  "",
                  "## [2.0.0] - 2026-03-01",
                  "### Cambiado (ruptura)",
                  "- Ruta `/order` renombrada a `/orders`.",
                  "- El campo `total` pasa de number a string decimal.",
                ],
                caption: "Changelog del contrato en formato Keep a Changelog",
                lang: "markdown",
              },
              real: {
                p: "En producción, la decisión de saltar a una MAJOR se planifica: se anuncia, se da un plazo y se ofrecen versiones superpuestas mientras migran los consumidores.",
                ul: [
                  "Anuncia la ruptura con antelación en el changelog y en las notas de release.",
                  "Superpón temporalmente la versión nueva y la anterior.",
                  "Mide qué consumidores aún llaman a la versión vieja antes de retirarla.",
                ],
                code: [
                  "curl -i https://api.shop.dev/v2/orders/42",
                  "HTTP/1.1 200 OK",
                  "Content-Type: application/json",
                  'X-API-Version: 2.3.0',
                  "",
                  "GET /v1/orders/42        -> migrar antes del 2026-12-01",
                  "GET /v2/orders/42        -> contrato actual",
                ],
                nota: "Exponer la versión en una cabecera de respuesta ayuda a operaciones a auditar qué contrato está usando cada cliente.",
                lang: "bash",
              },
              expl: [
                "MAJOR rompe el contrato: cualquier cambio que haga fallar a un cliente existente.",
                "MINOR añade sin romper: nuevos campos, nuevos endpoints opcionales.",
                "PATCH corrige sin cambiar el comportamiento público de la API.",
                "El changelog es parte del contrato: documenta el impacto de cada release.",
                "No confundas la versión del paquete que implementa con la del contrato de la API.",
              ],
              errors: [
                "Etiquetar como MINOR un cambio que elimina campos y rompe clientes.",
                "No publicar changelog que acompañe las versiones: el impacto se adivina.",
                "Bumpear versiones sin relación real con los cambios del contrato.",
              ],
              tips: [
                "Añade version a info de tu spec OpenAPI y mantenla al día.",
                "Escribe el changelog en cada PR: si no cambia, revisa si de verdad es un release.",
                "Empieza en 0.1.0 y pasa a 1.0.0 cuando el contrato se estabilice.",
                "Documenta las fechas de fin de soporte de cada MAJOR.",
              ],
              exercise: [
                "Escribe el changelog de una release 2.4.0 con dos añadidos y una corrección.",
                "Clasifica cinco cambios reales de tu API en MAJOR, MINOR o PATCH.",
                "Añade la versión SemVer a la cabecera info de tu spec OpenAPI.",
              ],
              summary: [
                "SemVer comunica el impacto de cada release con MAJOR.MINOR.PATCH.",
                "El changelog documenta qué cambió y por qué en cada versión.",
                "Las rupturas se planifican, se anuncian y se superponen con la versión anterior.",
              ],
              lang: "bash",
              exampleFile: "versionado-semantico-para-apis",
              desc: "Aplica el versionado semántico y los changelogs a tu API.",
            },
          },
{
            id: "evolucion-de-endpoints-sin-romper",
            title: "Evolucionar sin romper a los clientes",
            duration: "12 min",
            level: "avanzado",
            category: "producción",
            cardText: "Cambia tu API por dentro sin que sus consumidores se enteren de que algo cambió.",
            desc: "Evoluciona tus endpoints añadiendo capacidades sin romper a los consumidores.",
            body: {
              intro: [
                "El peor sonido para un equipo de API es el de una aplicación móvil que deja de funcionar después de un deploy. Esas rupturas casi nunca son accidentales: son el precio de cambiar contratos sin estrategia.",
                "La evolución compatible es la regla de oro: antes de eliminar o renombrar, pregúntate cómo añadir sin romper. Casi siempre hay un camino aditivo.",
              ],
              def: {
                par: "Evolucionar sin romper significa cambiar la API por dentro (también su lógica) manteniendo el contrato que los clientes ya usan: no borrar campos, no cambiar tipos, no exigir nuevos datos obligatorios.",
                porQue: "Cada cliente (apps, frontends, integraciones) asume tu contrato. Una ruptura no categórica se paga con incidentes, tickets y pérdida de confianza.",
                cuando: "Aplícalo a cualquier API con consumidores desconocidos. En APIs internas con un único consumidor sincronizado, el cambio directo puede negociarse.",
              },
              concepts: [
                "Compatibilidad hacia atrás: las respuestas viejas siguen siendo válidas.",
                "Campos opcionales con valor por defecto: añadir sin exigir.",
                "Convenciones de fecha y enumerados: solo ampliar, nunca reordenar.",
                "Filtros y query params como puerta de acceso a nueva funcionalidad.",
                "Códigos y mensajes de error: añadir nuevos casos, no reutilizar otros.",
              ],
              basic: {
                p: "Añadir un campo nuevo a la respuesta es retrocompatible: los clientes que no lo conocen simplemente lo ignoran.",
                code: [
                  "// v1.4.0: el pedido gana `currency` por defecto",
                  "{\"id\": 42, \"total\": \"199.90\", \"currency\": \"EUR\", \"status\": \"enviado\"}",
                  "",
                  "# Los clientes viejos siguen leyendo id, total y status",
                  "# Los nuevos ya pueden usar currency sin negociar nada",
                ],
                out: "MAYOR/MINOR: solo MINOR, sin tocar los campos existentes.",
                lang: "json",
              },
              intermediate: {
                p: "Cuando el cambio altera el formato de un campo existente, la negociación de contenido te deja servir el nuevo contrato sin migrar a nadie a la fuerza.",
                code: [
                  "# Petición de un cliente que quiere el contrato nuevo",
                  "curl -H \"Accept: application/vnd.shop.v3+json\" \\",
                  "     https://api.shop.dev/orders/42",
                  "",
                  "# Respuesta con el formato nuevo (total como string)",
                  '{"id": 42, "total": "199.90", "tax": "31.98", "status": "enviado"}',
                  "",
                  "# Otro cliente sin el header sigue recibiendo el contrato viejo",
                  '{"id": 42, "total": 199.9, "status": "enviado"}',
                ],
                caption: "Doble contrato servido por negociación de contenido",
                lang: "bash",
              },
              real: {
                p: "En APIs grandes, un nuevo campo suele proteger el despliegue de la implementación: lanzarlo como opcional, medir su uso y solo entonces hacerlo estándar.",
                ul: [
                  "Añade los nuevos campos al final de la respuesta, nunca en medio.",
                  "Da valores por defecto sensatos a todo campo nuevo.",
                  "Deprecia antes de romper: aviso, plazo y superposición.",
                ],
                code: [
                  "# OpenAPI: campo nuevo marcado deprecado y opcional",
                  "schemas:",
                  "  Order:",
                  "    properties:",
                  "      id: { type: integer }",
                  "      total: { type: number }",
                  "      currency:",
                  "        type: string",
                  "        deprecated: true",
                  "        description: Usar /orders resources v3",
                ],
                nota: "El atributo deprecated del campo avisa en la documentación sin romper a quien sigue usándolo.",
                lang: "yaml",
              },
              expl: [
                "Añadir es el movimiento preferido: obliga a los clientes a nada.",
                "Los campos nuevos deben tener valores por defecto sensatos.",
                "La negociación de contenido permite convivir dos contratos.",
                "Cambios de formato de campos existentes casi siempre son ruptura.",
                "Cada ruptura se evita con una estrategia aditiva o con sobreversión pactada.",
              ],
              errors: [
                "Añadir un campo nuevo obligatorio: los clientes viejos fallan al validar.",
                "Renombrar un campo y dejar el viejo abajo sin alias.",
                "Cambiar el tipo de total a string y declararlo MINOR.",
              ],
              tips: [
                "Revisa tu spec OpenAPI antes de cada deploy: ¿hay cambios no compatibles?",
                "Dibuja el dif del contrato en la revisión de código.",
                "Mide usos: telemetría que asocie endpoint a versión de contrato.",
                "Mantén un catálogo de consumidores de tu API como mapa de influencia.",
              ],
              exercise: [
                "Añade el campo currency a tu esquema Order como opcional con por defecto.",
                "Compara el diff OpenAPI entre dos versiones y clasifica cada cambio.",
                "Sirve dos contratos con el mismo endpoint usando negociación de contenido.",
              ],
              summary: [
                "La evolución compatible se basa en añadir sin romper el contrato.",
                "Campos opcionales, valores por defecto y nuevos querys son la vía aditiva.",
                "La negociación de contenido permite superponer contratos sin migración forzada.",
              ],
              lang: "bash",
              exampleFile: "evolucion-de-endpoints-sin-romper",
              desc: "Evoluciona tus endpoints añadiendo capacidades sin romper a los consumidores.",
            },
          },
{
            id: "deprecacion-y-ciclo-de-vida",
            title: "Deprecación y ciclo de vida de endpoints",
            duration: "11 min",
            level: "avanzado",
            category: "producción",
            cardText: "Retirar un endpoint también se diseña: aviso, Sunset y 410 Gone.",
            desc: "Planifica la deprecación y retirada de endpoints de tu API.",
            body: {
              intro: [
                "Todo endpoint tiene fecha de nacimiento y también debería tener plan de retirada. Un camino de deprecación bien diseñado permite modernizar la API sin sembrar incidentes ni clientes colgados.",
                "La deprecación es un proceso de comunicación, no un simple borrado: primero avisas, luego publicas la fecha de fin de soporte y al final respondes con 410 Gone en lugar de fallar con un error críptico.",
              ],
              def: {
                par: "Deprecar un endpoint es declararlo en desuso manteniéndolo operativo mientras los consumidores migran. El ciclo de vida típico pasa por deprecado (aviso), Sunet (fecha límite anunciada) y retirado (410 Gone).",
                porQue: "Un borrado sin aviso rompe clientes a oscuras; una deprecación comunicada convierte la migración en un plan con fecha.",
                cuando: "Deprecia todo recurso con alternativa mejor y avísalo en cada respuesta. Retira solo cuando los consumidores estén migrados o el plazo publicado se cumpla.",
              },
              concepts: [
                "Cabecera Deprecation: marca el endpoint como en desuso desde ahora.",
                "Cabecera Sunset: la fecha en que dejará de estar operativo.",
                "Enlace de sustitución en la respuesta: a dónde migrar.",
                "Código 410 Gone: el recurso ya no existe y nunca volverá (contenido eliminado).",
                "Plan de retirada: fechas, métricas de uso y responsables.",
              ],
              basic: {
                p: "Marcamos un endpoint como deprecado y anunciamos su fin de soporte con cabeceras estándar.",
                code: [
                  "curl -i https://api.shop.dev/v2/orders/summary",
                  "HTTP/1.1 200 OK",
                  "Content-Type: application/json",
                  "Deprecation: true",
                  "Sunset: Sat, 31 Dec 2026 23:59:59 GMT",
                  "Link: <https://api.shop.dev/v2/orders>; rel=\"successor-version\"",
                  "",
                  "[{\"id\": 1, \"total\": \"199.90\", \"productos\": 2}]",
                ],
                out: "El endpoint sigue respondiendo, pero declara su desuso y su fecha límite.",
                lang: "bash",
              },
              intermediate: {
                p: "Una vez pasado el Sunset y comunicada la retirada, el recurso muerto responde 410 Gone con instrucciones de migración.",
                code: [
                  "curl -i https://api.shop.dev/v2/orders/summary",
                  "HTTP/1.1 410 Gone",
                  "Content-Type: application/json",
                  "",
                  "{\"error\": \"recurso_retirado\",",
                  " \"message\": \"El resumen por endpoint se retiró. Usa GET /v2/orders.\",",
                  " \"retirado\": \"2027-01-15\"}",
                ],
                caption: "Respuesta 410 Gone con guía de migración",
                lang: "json",
              },
              real: {
                p: "En equipos maduros, la deprecación se gobierna como un backlog: cada endpoint deprecado tiene fecha, métricas de uso y propietario de la migración.",
                ul: [
                  "Registra en un tablero cada deprecación con responsable y fecha.",
                  "Mide el consumo del endpoint deprecado antes de retirarlo.",
                  "Retira solo cuando las métricas estén a cero o la fecha se cumpla.",
                ],
                code: [
                  "# Vista de seguimiento de deprecaciones",
                  "endpoint                 deprecated  sunset      uso/sem  estado",
                  "POST /v1/webhooks        2026-06      2026-12-31  0        por retirar",
                  "GET  /v2/orders/summary   2026-08      2027-01-15  320      migrando",
                ],
                nota: "Las métricas mandan: retirar un endpoint con uso real aunque haya cumplido la fecha provoca un incidente evitable.",
                lang: "text",
              },
              expl: [
                "La cabecera Deprecation informa sin romper nada: es el primer aviso.",
                "Sunset da fecha concreta y negociable para la migración.",
                "El enlace successor-version muestra el camino de sustitución.",
                "El 410 distingue contenido retirado de una ruta inexistente (404).",
                "La deprecación sin plan no es deprecación: es un borrado programado.",
              ],
              errors: [
                "Anunciar Sunset y luego retirar antes de tiempo por presión interna.",
                "Enviar 404 a quienes siguen usando el endpoint retirado.",
                "No medir el uso: retirar un endpoint que nadie migró.",
              ],
              tips: [
                "Logea las invocaciones a endpoints deprecados para medir la transición.",
                "Conecta Sunset con un recordatorio automático antes de la retirada.",
                "Documenta la migración del recurso en el Link rel=successor-version.",
                "Comunica las retiradas en changelog y en los canales de la plataforma.",
              ],
              exercise: [
                "Marca un endpoint deprecado con las tres cabeceras de aviso.",
                "Redacta un plan de retirada con fecha, responsables y métricas.",
                "Implementa la respuesta 410 Gone con guía de migración.",
              ],
              summary: [
                "La deprecación se comunica con las cabeceras Deprecation y Sunset.",
                "El 410 Gone distingue la retirada de la ausencia del recurso.",
                "Las métricas de uso y las fechas gobiernan el ciclo de vida.",
              ],
              lang: "bash",
              exampleFile: "deprecacion-y-ciclo-de-vida",
              desc: "Planifica la deprecación y retirada de endpoints de tu API.",
            },
          },
          {
            id: "compatibilidad-y-migraciones",
            title: "Compatibilidad hacia atrás y migraciones",
            duration: "12 min",
            level: "avanzado",
            category: "producción",
            cardText: "Mantén lo viejo funcionando mientras construyes lo nuevo con estrategia.",
            desc: "Mantén la compatibilidad hacia atrás y ejecuta migraciones graduales en tu API.",
            body: {
              intro: [
                "La compatibilidad hacia atrás no es un estado mágico que se logra de una vez: es una propiedad que se cuida en cada commit. Cada vez que tocas un esquema, una ruta o un error, decides si el consumidor existente sale indemne.",
                "Las migraciones graduales convierten los cambios de mayor riesgo (contratos, campos, versiones) en etapas pequeñas que se pueden retroceder, midiendo en cada paso.",
              ],
              def: {
                par: "La compatibilidad hacia atrás garantiza que el código que hoy consume tu API siga funcionando tras tu release. Una migración gradual transforma el contrato en pasos compatibles, superpuestos y reversibles.",
                porQue: "Los consumidores no se actualizan al día siguiente: tus cambios navegan por una cola de despliegues de otros equipos. La compatibilidad da tiempo y la estrategia da seguridad.",
                cuando: "Aplícalas a todo cambio de contrato con consumidores desconocidos. En API interna con un único consumidor y despliegue atómico, las etapas pueden ser mínimas.",
              },
              concepts: [
                "Contrato fuente de verdad: las especs evolucionan antes que el código.",
                "Estrategia de espejo (mirror): servir ambos formatos a la vez durante la migración.",
                "Feature flags: cambiar el comportamiento sin cambiar el deploy.",
                "Migración de datos: transformar viejos sin perder lecturas.",
                "Pruebas contractuales: detectar rupturas en el momento del cambio.",
              ],
              basic: {
                p: "La regla de la compatibilidad: un campo que se va nunca desaparece sin plan; se arrastra deprecado mientras exista consumo.",
                code: [
                  "// Contrato 2.0: `payment.card` se reemplaza por `payment.method`",
                  "{\"id\": 42, \"payment\": {",
                  "  \"method\": \"card\",",
                  "  \"card\": \"**** 4242\"    // deprecado, se mantiene durante la migración",
                  "}}",
                ],
                out: "El consumidor viejo sigue leyendo payment.card; el nuevo usa method.",
                lang: "json",
              },
              intermediate: {
                p: "Una migración con espejo sirve ambos contratos mientras los clientes migran y mide cuándo dejar de emitir el viejo.",
                code: [
                  "// Durante la transición, la respuesta emite ambos campos",
                  "{\"id\": 42, \"status\": \"enviado\", \"estado\": \"enviado\"}",
                  "",
                  "# Estrategia:",
                  "# 1. Emitir `estado` a la vez que `status` (aditivo).",
                  "# 2. Medir cuántos clientes siguen leyendo `status`.",
                  "# 3. Al cae el uso, deprecar `status` y planificar su retirada.",
                ],
                caption: "Espejo de un campo durante su migración",
                lang: "json",
              },
              real: {
                p: "Las pruebas contractuales cazán rupturas en el instante en que se introducen: el contrato viejo se prueba durante toda la transición.",
                ul: [
                  "Versiona los contratos como artefactos que los consumidores mantienen.",
                  "Ejecuta las pruebas de contrato en el pipeline del proveedor.",
                  "Revertir una migración debe ser tan sencillo como volver el flag.",
                ],
                code: [
                  "// ContractTest para el campo `status` durante la migración",
                  "test(\"el campo status sigue presente hasta su retirada\", () => {",
                  "  const res = await api.get(\"/orders/42\");",
                  "  expect(res.body.status).toBeDefined();   // viejo contrato",
                  "  expect(res.body.estado).toBeDefined();    // nuevo contrato",
                  "});",
                ],
                nota: "Cuando el contrato viejo deja de probarse es porque ya se retiró de verdad: la prueba es el espejo de la decisión.",
                lang: "js",
              },
              expl: [
                "Compatibilidad es una decisión por commit: cada campo tocado se evalúa.",
                "El espejo da tiempo de migración a los consumidores sin parar nada.",
                "Los feature flags desacoplan el despliegue de la decisión de negocio.",
                "Las pruebas contractuales vigilan el contrato viejo mientras existe.",
                "Toda migración debe tener un plan de reversión explícito.",
              ],
              errors: [
                "Mantener el campo deprecado sin medir su uso y alargar la deuda.",
                "Retirar el contrato viejo mientras las pruebas contractuales aún lo cubren.",
                "Cambiar datos en caliente sin snapshot de los valores afectados.",
              ],
              tips: [
                "Añade pruebas contractuales que fijen el comportamiento del contrato vigente.",
                "Deja cada migración con su flag y su fecha de revisión.",
                "Documenta la estrategia de migración en el changelog de la versión.",
                "Mide el consumo por campo, no solo por endpoint.",
              ],
              exercise: [
                "Migra un campo con espejo y un plan de retirada de tres meses.",
                "Escribe una prueba contractual que fije el campo viejo durante la transición.",
                "Revertir una migración con un flag y comprobar que nada cambia para el cliente.",
              ],
              summary: [
                "La compatibilidad hacia atrás se decide cambio a cambio, no de golpe.",
                "El espejo y los flags permiten migrar sin detener a ningún consumidor.",
                "Las pruebas contractuales convierten la estrategia en garantía.",
              ],
              lang: "js",
              exampleFile: "compatibilidad-y-migraciones",
              desc: "Mantén la compatibilidad hacia atrás y ejecuta migraciones graduales en tu API.",
            },
          },
{
            id: "gobierno-y-observabilidad-de-la-api",
            title: "Gobierno y observabilidad de la API",
            duration: "12 min",
            level: "avanzado",
            category: "producción",
            cardText: "Reglas compartidas, contrato vivo y telemetría: la API se gobierna, no solo se construye.",
            desc: "Gobierna tu API con reglas compartidas y telemetría para operarla con confianza.",
            body: {
              intro: [
                "Cuando una API crece, todos los equipos anteriores del curso se ponen a prueba: ¿quién decide que un endpoint nuevo respeta el estilo?, ¿cómo sabes que una versión se usa de verdad?, ¿dónde ves la latencia antes de que la vea el usuario?",
                "La respuesta es el gobierno: reglas pactadas y verificadas por máquinas, más la observabilidad que convierte los datos de cada petición en decisiones.",
              ],
              def: {
                par: "El gobierno de una API es el conjunto de reglas, responsables y herramientas que mantienen su diseño coherente a lo largo del tiempo. La observabilidad es la capacidad de conocer el estado interno a partir de logs, métricas y trazas.",
                porQue: "Sin gobierno, cada equipo añade su propio estilo y el contrato se degrada; sin observabilidad, despliegas a ciegas y las rupturas solo las descubre el cliente.",
                cuando: "Establécelo cuando más de un equipo publica o consume la API: estilo compartido, catálogo, versionado y dashboards entran en el mismo entregable.",
              },
              concepts: [
                "Especificaciones como fuente de verdad: OpenAPI versionada y revisada.",
                "Estilo compartido: convenciones de nombres, errores y versionado.",
                "Logs estructurados: cada petición deja un registro en JSON con metadatos.",
                "Métricas RED: Rate, Errors y Duration por endpoint.",
                "Trazas distribuidas: siguen la petición a través de tus servicios.",
              ],
              basic: {
                p: "La observabilidad básica empieza por el log estructurado: cada petición registra su endpoint, latencia, código y un identificador de correlación.",
                code: [
                  "{\"ts\": \"2026-09-24T10:31:02Z\", \"event\": \"request\",",
                  " \"method\": \"POST\", \"path\": \"/orders\", \"status\": 201,",
                  " \"duration_ms\": 214, \"user_id\": 8041, \"request_id\": \"req_ab7c\"}",
                  "",
                  "# Buscando por request_id puedes seguir la petición enlogs y trazas",
                  "grep 'req_ab7c' access.log /var/log/api/errors.json",
                ],
                out: "Un log estructurado permite filtrar, agregar y correlacionar sin esfuerzo.",
                lang: "json",
              },
              intermediate: {
                p: "Las métricas RED por endpoint contestan las tres preguntas vitales: cuánto tráfico (Rate), cuántos fallos (Errors) y cuánto tarda (Duration).",
                code: [
                  "# Métricas agregadas por endpoint (prometheus/grafana style)",
                  "http_requests_total{endpoint=\"/orders\", code=\"200\"} 15430",
                  "http_errors_total{endpoint=\"/orders\", code=\"500\"}    12",
                  "http_request_duration_seconds{endpoint=\"/orders\"}{quantile=\"0.95\"} 0.481",
                  "http_requests_total{endpoint=\"/v1/orders/summary\"}  320   <- deprecado en uso",
                ],
                caption: "Datos RED que alimentan los umbrales de alerta",
                lang: "text",
              },
              real: {
                p: "En producción, el health check público y el SLO interno trabajan juntos: el primero dice que el proceso está vivo y el segundo, que la experiencia pactada se cumple.",
                ul: [
                  "Un health check responde 200 con estado y versión en JSON.",
                  "SLO objetivos por endpoint y alertas cuando se degradan.",
                  "Catálogo de la API visible para consumidores y operaciones.",
                ],
                code: [
                  "curl https://api.shop.dev/health",
                  "{\"status\": \"ok\", \"version\": \"2.3.0\",",
                  " \"db\": \"up\", \"cache\": \"up\", \"uptime_s\": 3600}",
                  "",
                  "GET /v2/orders    200    p95 481ms   (SLO 500ms)   OK",
                  "POST /v2/orders   201    p95 690ms   (SLO 500ms)   RISK",
                ],
                nota: "El dato que más duele es el deprecado en uso: la telemetría que detecta que nadie migró a tiempo.",
                lang: "bash",
              },
              expl: [
                "Gobernar es pactar reglas y verificarlas con lint de especs y revisiones.",
                "La espec OpenAPI versionada es el contrato único que todos consultan.",
                "Los logs estructurados hacen posible el puzzle de un incidente.",
                "Las métricas RED transforman opiniones en umbrales y alertas.",
                "La observabilidad también alimenta al gobierno: deprecaciones, uso y SLOs.",
              ],
              errors: [
                "Logs de texto libre que nadie puede filtrar ni agregar.",
                "Contar todo menos lo que importa: sin dimensional por endpoint.",
                "Salir a producción sin health check y sin SLO definido.",
              ],
              tips: [
                "Normaliza el request_id y llévalo en cada traza y respuesta.",
                "Añade lints de specs OpenAPI que bloqueen rupturas no aprobadas.",
                "Define SLO por endpoint crítico y alerta por burn rate.",
                "Mide la difusión del contrato: catálogo con versión y estado de cada recurso.",
              ],
              exercise: [
                "Emite un log estructurado JSON por request de tu API (sin librería externa).",
                "Define métricas RED para el endpoint /orders y un umbral de alerta.",
                "Escribe un health check que devuelva estado, versión y dependencias en JSON.",
              ],
              summary: [
                "El gobierno fija reglas de diseño verificables por máquina.",
                "Los logs estructurados y las métricas RED hacen observable la API.",
                "El health check y los SLO convierten la operación en decisiones con datos.",
              ],
              lang: "bash",
              exampleFile: "gobierno-y-observabilidad-de-la-api",
              desc: "Gobierna tu API con reglas compartidas y telemetría para operarla con confianza.",
            },
          },
        ],
      },
    ],
  },
];
